#include "title/op_a.hpp"

INCLUDE_ASM("asm/nonmatchings/title/op_a", OpA_InitProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", LoadTexture__Fv__3);
INCLUDE_ASM("asm/nonmatchings/title/op_a", LoadData__Fv__2);
INCLUDE_ASM("asm/nonmatchings/title/op_a", SetDanceMotion__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", InitDancerPos__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", OpA_DrawProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", DrawCloud__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", SmokeProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", OpA_MotionProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", MoveDancers__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", ReaderShadow__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", DancerShadow__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", ShogunShadow__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", ShisaiShadow__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", DrawShadow__Ffff);
INCLUDE_ASM("asm/nonmatchings/title/op_a", OpA_SoundProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", setTexScroll__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_a", setCloudTexScroll__Fv);
