#include "title/op_c.hpp"

INCLUDE_ASM("asm/nonmatchings/title/op_c", FaceChange__Fi__2);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_LoadDataBG__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_LoadDataBG2__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_LoadDataBG3__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_LoadDataBG4__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_LoadDataBG5__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_InitProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_InitProcess2__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_InitProcess3__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_InitProcess4__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_InitProcess5__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", MapLoad__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", MapLoad2__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_MotionProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", LoadCharaMajin__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_SoundProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", OpC_DrawProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", DrawDancer__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", InchikiShadow__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", DrawShadow__Fifff);
INCLUDE_ASM("asm/nonmatchings/title/op_c", MajinBeemProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", SmokeProcess__Fv__2);
INCLUDE_ASM("asm/nonmatchings/title/op_c", WaterProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/op_c", KageCheck__Fi);
INCLUDE_ASM("asm/nonmatchings/title/op_c", LightSet__Ffffi);
INCLUDE_ASM("asm/nonmatchings/title/op_c", setTexScroll__Fv__2);
INCLUDE_ASM("asm/nonmatchings/title/op_c", setTexAnim__Fv__2);
