#include "title/op_c.hpp"

INCLUDE_ASM("title", FaceChange__Fi__2);
INCLUDE_ASM("title", OpC_LoadDataBG__Fv);
INCLUDE_ASM("title", OpC_LoadDataBG2__Fv);
INCLUDE_ASM("title", OpC_LoadDataBG3__Fv);
INCLUDE_ASM("title", OpC_LoadDataBG4__Fv);
INCLUDE_ASM("title", OpC_LoadDataBG5__Fv);
INCLUDE_ASM("title", OpC_InitProcess__Fv);
INCLUDE_ASM("title", OpC_InitProcess2__Fv);
INCLUDE_ASM("title", OpC_InitProcess3__Fv);
INCLUDE_ASM("title", OpC_InitProcess4__Fv);
INCLUDE_ASM("title", OpC_InitProcess5__Fv);
INCLUDE_ASM("title", MapLoad__Fv);
INCLUDE_ASM("title", MapLoad2__Fv);
INCLUDE_ASM("title", OpC_MotionProcess__Fv);
INCLUDE_ASM("title", LoadCharaMajin__Fv);
INCLUDE_ASM("title", OpC_SoundProcess__Fv);
INCLUDE_ASM("title", OpC_DrawProcess__Fv);
INCLUDE_ASM("title", DrawDancer__Fv);
INCLUDE_ASM("title", InchikiShadow__Fv);
INCLUDE_ASM("title", DrawShadow__Fifff);
INCLUDE_ASM("title", MajinBeemProcess__Fv);
INCLUDE_ASM("title", SmokeProcess__Fv__2);
INCLUDE_ASM("title", WaterProcess__Fv);
INCLUDE_ASM("title", KageCheck__Fi);
INCLUDE_ASM("title", LightSet__Ffffi);
INCLUDE_ASM("title", setTexScroll__Fv__2);
INCLUDE_ASM("title", setTexAnim__Fv__2);
