#include "title/opening.hpp"

INCLUDE_ASM("asm/nonmatchings/title/opening", OpeningInit__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", LoadMessage__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", LoadScene__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", LoadSceneBG__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", OpeningLoop__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", SceneChange__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", PauseProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", SoundStop__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", WaitKeyProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", MotionProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", SoundProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", DrawProcess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", DrawMess__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", OpBgmPlay__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", OpPlayVolPanSE__FPfffiii);
INCLUDE_ASM("asm/nonmatchings/title/opening", OpSetVolPanSE__FPfffiii);
INCLUDE_ASM("asm/nonmatchings/title/opening", OpPlayVolSE__Fiiif);
INCLUDE_ASM("asm/nonmatchings/title/opening", OpGetVolSQ__Fi);
INCLUDE_ASM("asm/nonmatchings/title/opening", FadeCansel__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", OPAnalyz__FPc);
INCLUDE_ASM("asm/nonmatchings/title/opening", OPMdsLoad__Fv);
INCLUDE_ASM("asm/nonmatchings/title/opening", skipSpace__FPci);
INCLUDE_ASM("asm/nonmatchings/title/opening", checkArg__FPciPi);
