#include "title/title.hpp"

INCLUDE_ASM("asm/nonmatchings/title/title", DataLoad__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcA__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcA__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcB__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcB__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", AtraLight__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcC__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcC__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcD__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcD__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcE__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcE__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcF__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcF__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcG__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcG__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcH__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcH__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcI__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcI__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", InitProcTitle__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", DrawProcTitle__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", TitleInit__Fi);
INCLUDE_ASM("asm/nonmatchings/title/title", TitleLoop__Fv);
INCLUDE_ASM("asm/nonmatchings/title/title", TitleDraw__Fv);
