#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _Balloc);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _Bfree);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _multadd);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _s2b);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _hi0bits);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _lo0bits);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _i2b);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _multiply);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _pow5mult);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _lshift);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", __mcmp);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", __mdiff);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _ulp);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _b2d);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _d2b);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _ratio);
INCLUDE_ASM("asm/nonmatchings/lib/libc/stdlib/mprec", _mprec_log10);
