.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
glabel DisableIntc
    /* 014EA0 00114DA0 E0FFBD27 */  addiu      $29, $29, -0x20
    /* 014EA4 00114DA4 1000BFFF */  sd         $31, 0x10($29)
    /* 014EA8 00114DA8 0000B0FF */  sd         $16, 0x0($29)
    /* 014EAC 00114DAC 00601040 */  mfc0       $16, $12 /* handwritten instruction */
    /* 014EB0 00114DB0 0100023C */  lui        $2, (0x10000 >> 16)
    /* 014EB4 00114DB4 24800202 */  and        $16, $16, $2
    /* 014EB8 00114DB8 08000012 */  beqz       $16, .L00114DDC
    /* 014EBC 00114DBC 0100033C */   lui       $3, (0x10000 >> 16)
  .L00114DC0:
    /* 014EC0 00114DC0 39000042 */  di /* handwritten instruction */
    /* 014EC4 00114DC4 0F040000 */  sync.p
    /* 014EC8 00114DC8 00600240 */  mfc0       $2, $12 /* handwritten instruction */
    /* 014ECC 00114DCC 24104300 */  and        $2, $2, $3
    /* 014ED0 00114DD0 00000000 */  nop
    /* 014ED4 00114DD4 FAFF4014 */  bnez       $2, .L00114DC0
    /* 014ED8 00114DD8 00000000 */   nop
  .L00114DDC:
    /* 014EDC 00114DDC 1C50040C */  jal        _DisableIntc
    /* 014EE0 00114DE0 00000000 */   nop
    /* 014EE4 00114DE4 0F000000 */  sync
    /* 014EE8 00114DE8 03000012 */  beqz       $16, .L00114DF8
    /* 014EEC 00114DEC 1000BFDF */   ld        $31, 0x10($29)
    /* 014EF0 00114DF0 38000042 */  ei /* handwritten instruction */
    /* 014EF4 00114DF4 1000BFDF */  ld         $31, 0x10($29)
  .L00114DF8:
    /* 014EF8 00114DF8 0000B0DF */  ld         $16, 0x0($29)
    /* 014EFC 00114DFC 0800E003 */  jr         $31
    /* 014F00 00114E00 2000BD27 */   addiu     $29, $29, 0x20
    /* 014F04 00114E04 00000000 */  nop

/* Handwritten function */
glabel EnableIntc
    /* 014F08 00114E08 E0FFBD27 */  addiu      $29, $29, -0x20
    /* 014F0C 00114E0C 1000BFFF */  sd         $31, 0x10($29)
    /* 014F10 00114E10 0000B0FF */  sd         $16, 0x0($29)
    /* 014F14 00114E14 00601040 */  mfc0       $16, $12 /* handwritten instruction */
    /* 014F18 00114E18 0100023C */  lui        $2, (0x10000 >> 16)
    /* 014F1C 00114E1C 24800202 */  and        $16, $16, $2
    /* 014F20 00114E20 08000012 */  beqz       $16, .L00114E44
    /* 014F24 00114E24 0100033C */   lui       $3, (0x10000 >> 16)
  .L00114E28:
    /* 014F28 00114E28 39000042 */  di /* handwritten instruction */
    /* 014F2C 00114E2C 0F040000 */  sync.p
    /* 014F30 00114E30 00600240 */  mfc0       $2, $12 /* handwritten instruction */
    /* 014F34 00114E34 24104300 */  and        $2, $2, $3
    /* 014F38 00114E38 00000000 */  nop
    /* 014F3C 00114E3C FAFF4014 */  bnez       $2, .L00114E28
    /* 014F40 00114E40 00000000 */   nop
  .L00114E44:
    /* 014F44 00114E44 1850040C */  jal        _EnableIntc
    /* 014F48 00114E48 00000000 */   nop
    /* 014F4C 00114E4C 0F000000 */  sync
    /* 014F50 00114E50 03000012 */  beqz       $16, .L00114E60
    /* 014F54 00114E54 1000BFDF */   ld        $31, 0x10($29)
    /* 014F58 00114E58 38000042 */  ei /* handwritten instruction */
    /* 014F5C 00114E5C 1000BFDF */  ld         $31, 0x10($29)
  .L00114E60:
    /* 014F60 00114E60 0000B0DF */  ld         $16, 0x0($29)
    /* 014F64 00114E64 0800E003 */  jr         $31
    /* 014F68 00114E68 2000BD27 */   addiu     $29, $29, 0x20
    /* 014F6C 00114E6C 00000000 */  nop

/* Handwritten function */
glabel DisableDmac
    /* 014F70 00114E70 E0FFBD27 */  addiu      $29, $29, -0x20
    /* 014F74 00114E74 1000BFFF */  sd         $31, 0x10($29)
    /* 014F78 00114E78 0000B0FF */  sd         $16, 0x0($29)
    /* 014F7C 00114E7C 00601040 */  mfc0       $16, $12 /* handwritten instruction */
    /* 014F80 00114E80 0100023C */  lui        $2, (0x10000 >> 16)
    /* 014F84 00114E84 24800202 */  and        $16, $16, $2
    /* 014F88 00114E88 08000012 */  beqz       $16, .L00114EAC
    /* 014F8C 00114E8C 0100033C */   lui       $3, (0x10000 >> 16)
  .L00114E90:
    /* 014F90 00114E90 39000042 */  di /* handwritten instruction */
    /* 014F94 00114E94 0F040000 */  sync.p
    /* 014F98 00114E98 00600240 */  mfc0       $2, $12 /* handwritten instruction */
    /* 014F9C 00114E9C 24104300 */  and        $2, $2, $3
    /* 014FA0 00114EA0 00000000 */  nop
    /* 014FA4 00114EA4 FAFF4014 */  bnez       $2, .L00114E90
    /* 014FA8 00114EA8 00000000 */   nop
  .L00114EAC:
    /* 014FAC 00114EAC 2450040C */  jal        _DisableDmac
    /* 014FB0 00114EB0 00000000 */   nop
    /* 014FB4 00114EB4 0F000000 */  sync
    /* 014FB8 00114EB8 03000012 */  beqz       $16, .L00114EC8
    /* 014FBC 00114EBC 1000BFDF */   ld        $31, 0x10($29)
    /* 014FC0 00114EC0 38000042 */  ei /* handwritten instruction */
    /* 014FC4 00114EC4 1000BFDF */  ld         $31, 0x10($29)
  .L00114EC8:
    /* 014FC8 00114EC8 0000B0DF */  ld         $16, 0x0($29)
    /* 014FCC 00114ECC 0800E003 */  jr         $31
    /* 014FD0 00114ED0 2000BD27 */   addiu     $29, $29, 0x20
    /* 014FD4 00114ED4 00000000 */  nop

/* Handwritten function */
glabel EnableDmac
    /* 014FD8 00114ED8 E0FFBD27 */  addiu      $29, $29, -0x20
    /* 014FDC 00114EDC 1000BFFF */  sd         $31, 0x10($29)
    /* 014FE0 00114EE0 0000B0FF */  sd         $16, 0x0($29)
    /* 014FE4 00114EE4 00601040 */  mfc0       $16, $12 /* handwritten instruction */
    /* 014FE8 00114EE8 0100023C */  lui        $2, (0x10000 >> 16)
    /* 014FEC 00114EEC 24800202 */  and        $16, $16, $2
    /* 014FF0 00114EF0 08000012 */  beqz       $16, .L00114F14
    /* 014FF4 00114EF4 0100033C */   lui       $3, (0x10000 >> 16)
  .L00114EF8:
    /* 014FF8 00114EF8 39000042 */  di /* handwritten instruction */
    /* 014FFC 00114EFC 0F040000 */  sync.p
    /* 015000 00114F00 00600240 */  mfc0       $2, $12 /* handwritten instruction */
    /* 015004 00114F04 24104300 */  and        $2, $2, $3
    /* 015008 00114F08 00000000 */  nop
    /* 01500C 00114F0C FAFF4014 */  bnez       $2, .L00114EF8
    /* 015010 00114F10 00000000 */   nop
  .L00114F14:
    /* 015014 00114F14 2050040C */  jal        _EnableDmac
    /* 015018 00114F18 00000000 */   nop
    /* 01501C 00114F1C 0F000000 */  sync
    /* 015020 00114F20 03000012 */  beqz       $16, .L00114F30
    /* 015024 00114F24 1000BFDF */   ld        $31, 0x10($29)
    /* 015028 00114F28 38000042 */  ei /* handwritten instruction */
    /* 01502C 00114F2C 1000BFDF */  ld         $31, 0x10($29)
  .L00114F30:
    /* 015030 00114F30 0000B0DF */  ld         $16, 0x0($29)
    /* 015034 00114F34 0800E003 */  jr         $31
    /* 015038 00114F38 2000BD27 */   addiu     $29, $29, 0x20
    /* 01503C 00114F3C 00000000 */  nop

/* Handwritten function */
glabel SetAlarm
    /* 015040 00114F40 E0FFBD27 */  addiu      $29, $29, -0x20
    /* 015044 00114F44 FFFF8430 */  andi       $4, $4, 0xFFFF
    /* 015048 00114F48 1000BFFF */  sd         $31, 0x10($29)
    /* 01504C 00114F4C 0000B0FF */  sd         $16, 0x0($29)
    /* 015050 00114F50 00601040 */  mfc0       $16, $12 /* handwritten instruction */
    /* 015054 00114F54 0100023C */  lui        $2, (0x10000 >> 16)
    /* 015058 00114F58 24800202 */  and        $16, $16, $2
    /* 01505C 00114F5C 09000012 */  beqz       $16, .L00114F84
    /* 015060 00114F60 0100033C */   lui       $3, (0x10000 >> 16)
    /* 015064 00114F64 00000000 */  nop
  .L00114F68:
    /* 015068 00114F68 39000042 */  di /* handwritten instruction */
    /* 01506C 00114F6C 0F040000 */  sync.p
    /* 015070 00114F70 00600240 */  mfc0       $2, $12 /* handwritten instruction */
    /* 015074 00114F74 24104300 */  and        $2, $2, $3
    /* 015078 00114F78 00000000 */  nop
    /* 01507C 00114F7C FAFF4014 */  bnez       $2, .L00114F68
    /* 015080 00114F80 00000000 */   nop
  .L00114F84:
    /* 015084 00114F84 2850040C */  jal        _SetAlarm
    /* 015088 00114F88 00000000 */   nop
    /* 01508C 00114F8C 0F000000 */  sync
    /* 015090 00114F90 03000012 */  beqz       $16, .L00114FA0
    /* 015094 00114F94 1000BFDF */   ld        $31, 0x10($29)
    /* 015098 00114F98 38000042 */  ei /* handwritten instruction */
    /* 01509C 00114F9C 1000BFDF */  ld         $31, 0x10($29)
  .L00114FA0:
    /* 0150A0 00114FA0 0000B0DF */  ld         $16, 0x0($29)
    /* 0150A4 00114FA4 0800E003 */  jr         $31
    /* 0150A8 00114FA8 2000BD27 */   addiu     $29, $29, 0x20
    /* 0150AC 00114FAC 00000000 */  nop

/* Handwritten function */
glabel ReleaseAlarm
    /* 0150B0 00114FB0 E0FFBD27 */  addiu      $29, $29, -0x20
    /* 0150B4 00114FB4 1000BFFF */  sd         $31, 0x10($29)
    /* 0150B8 00114FB8 0000B0FF */  sd         $16, 0x0($29)
    /* 0150BC 00114FBC 00601040 */  mfc0       $16, $12 /* handwritten instruction */
    /* 0150C0 00114FC0 0100023C */  lui        $2, (0x10000 >> 16)
    /* 0150C4 00114FC4 24800202 */  and        $16, $16, $2
    /* 0150C8 00114FC8 08000012 */  beqz       $16, .L00114FEC
    /* 0150CC 00114FCC 0100033C */   lui       $3, (0x10000 >> 16)
  .L00114FD0:
    /* 0150D0 00114FD0 39000042 */  di /* handwritten instruction */
    /* 0150D4 00114FD4 0F040000 */  sync.p
    /* 0150D8 00114FD8 00600240 */  mfc0       $2, $12 /* handwritten instruction */
    /* 0150DC 00114FDC 24104300 */  and        $2, $2, $3
    /* 0150E0 00114FE0 00000000 */  nop
    /* 0150E4 00114FE4 FAFF4014 */  bnez       $2, .L00114FD0
    /* 0150E8 00114FE8 00000000 */   nop
  .L00114FEC:
    /* 0150EC 00114FEC 2C50040C */  jal        _ReleaseAlarm
    /* 0150F0 00114FF0 00000000 */   nop
    /* 0150F4 00114FF4 0F000000 */  sync
    /* 0150F8 00114FF8 03000012 */  beqz       $16, .L00115008
    /* 0150FC 00114FFC 1000BFDF */   ld        $31, 0x10($29)
    /* 015100 00115000 38000042 */  ei /* handwritten instruction */
    /* 015104 00115004 1000BFDF */  ld         $31, 0x10($29)
  .L00115008:
    /* 015108 00115008 0000B0DF */  ld         $16, 0x0($29)
    /* 01510C 0011500C 0800E003 */  jr         $31
    /* 015110 00115010 2000BD27 */   addiu     $29, $29, 0x20
    /* 015114 00115014 00000000 */  nop

glabel iEnableIntc
    /* 015118 00115018 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 01511C 0011501C 0000BFFF */  sd         $31, 0x0($29)
    /* 015120 00115020 3050040C */  jal        _iEnableIntc
    /* 015124 00115024 00000000 */   nop
    /* 015128 00115028 0F000000 */  sync
    /* 01512C 0011502C 0000BFDF */  ld         $31, 0x0($29)
    /* 015130 00115030 0800E003 */  jr         $31
    /* 015134 00115034 1000BD27 */   addiu     $29, $29, 0x10

glabel iDisableIntc
    /* 015138 00115038 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 01513C 0011503C 0000BFFF */  sd         $31, 0x0($29)
    /* 015140 00115040 3450040C */  jal        _iDisableIntc
    /* 015144 00115044 00000000 */   nop
    /* 015148 00115048 0F000000 */  sync
    /* 01514C 0011504C 0000BFDF */  ld         $31, 0x0($29)
    /* 015150 00115050 0800E003 */  jr         $31
    /* 015154 00115054 1000BD27 */   addiu     $29, $29, 0x10

glabel iEnableDmac
    /* 015158 00115058 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 01515C 0011505C 0000BFFF */  sd         $31, 0x0($29)
    /* 015160 00115060 3850040C */  jal        _iEnableDmac
    /* 015164 00115064 00000000 */   nop
    /* 015168 00115068 0F000000 */  sync
    /* 01516C 0011506C 0000BFDF */  ld         $31, 0x0($29)
    /* 015170 00115070 0800E003 */  jr         $31
    /* 015174 00115074 1000BD27 */   addiu     $29, $29, 0x10

glabel iDisableDmac
    /* 015178 00115078 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 01517C 0011507C 0000BFFF */  sd         $31, 0x0($29)
    /* 015180 00115080 3C50040C */  jal        _iDisableDmac
    /* 015184 00115084 00000000 */   nop
    /* 015188 00115088 0F000000 */  sync
    /* 01518C 0011508C 0000BFDF */  ld         $31, 0x0($29)
    /* 015190 00115090 0800E003 */  jr         $31
    /* 015194 00115094 1000BD27 */   addiu     $29, $29, 0x10

glabel iSetAlarm
    /* 015198 00115098 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 01519C 0011509C 0000BFFF */  sd         $31, 0x0($29)
    /* 0151A0 001150A0 4050040C */  jal        _iSetAlarm
    /* 0151A4 001150A4 FFFF8430 */   andi      $4, $4, 0xFFFF
    /* 0151A8 001150A8 0F000000 */  sync
    /* 0151AC 001150AC 0000BFDF */  ld         $31, 0x0($29)
    /* 0151B0 001150B0 0800E003 */  jr         $31
    /* 0151B4 001150B4 1000BD27 */   addiu     $29, $29, 0x10

glabel iReleaseAlarm
    /* 0151B8 001150B8 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 0151BC 001150BC 0000BFFF */  sd         $31, 0x0($29)
    /* 0151C0 001150C0 4450040C */  jal        _iReleaseAlarm
    /* 0151C4 001150C4 00000000 */   nop
    /* 0151C8 001150C8 0F000000 */  sync
    /* 0151CC 001150CC 0000BFDF */  ld         $31, 0x0($29)
    /* 0151D0 001150D0 0800E003 */  jr         $31
    /* 0151D4 001150D4 1000BD27 */   addiu     $29, $29, 0x10
