.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
glabel RFU000_FullReset
    /* 014000 00113F00 00000324 */  addiu      $3, $0, 0x0
    /* 014004 00113F04 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014008 00113F08 0800E003 */  jr         $31
    /* 01400C 00113F0C 00000000 */   nop

/* Handwritten function */
glabel ResetEE
    /* 014010 00113F10 01000324 */  addiu      $3, $0, 0x1
    /* 014014 00113F14 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014018 00113F18 0800E003 */  jr         $31
    /* 01401C 00113F1C 00000000 */   nop

/* Handwritten function */
glabel SetGsCrt
    /* 014020 00113F20 02000324 */  addiu      $3, $0, 0x2
    /* 014024 00113F24 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014028 00113F28 0800E003 */  jr         $31
    /* 01402C 00113F2C 00000000 */   nop

/* Handwritten function */
glabel RFU003
    /* 014030 00113F30 03000324 */  addiu      $3, $0, 0x3
    /* 014034 00113F34 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014038 00113F38 0800E003 */  jr         $31
    /* 01403C 00113F3C 00000000 */   nop

/* Handwritten function */
glabel Exit
    /* 014040 00113F40 04000324 */  addiu      $3, $0, 0x4
    /* 014044 00113F44 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014048 00113F48 0800E003 */  jr         $31
    /* 01404C 00113F4C 00000000 */   nop

/* Handwritten function */
glabel RFU005
    /* 014050 00113F50 05000324 */  addiu      $3, $0, 0x5
    /* 014054 00113F54 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014058 00113F58 0800E003 */  jr         $31
    /* 01405C 00113F5C 00000000 */   nop

/* Handwritten function */
glabel LoadExecPS2
    /* 014060 00113F60 06000324 */  addiu      $3, $0, 0x6
    /* 014064 00113F64 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014068 00113F68 0800E003 */  jr         $31
    /* 01406C 00113F6C 00000000 */   nop

/* Handwritten function */
glabel ExecPS2
    /* 014070 00113F70 07000324 */  addiu      $3, $0, 0x7
    /* 014074 00113F74 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014078 00113F78 0800E003 */  jr         $31
    /* 01407C 00113F7C 00000000 */   nop

/* Handwritten function */
glabel RFU008
    /* 014080 00113F80 08000324 */  addiu      $3, $0, 0x8
    /* 014084 00113F84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014088 00113F88 0800E003 */  jr         $31
    /* 01408C 00113F8C 00000000 */   nop

/* Handwritten function */
glabel RFU009
    /* 014090 00113F90 09000324 */  addiu      $3, $0, 0x9
    /* 014094 00113F94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014098 00113F98 0800E003 */  jr         $31
    /* 01409C 00113F9C 00000000 */   nop

/* Handwritten function */
glabel AddSbusIntcHandler
    /* 0140A0 00113FA0 0A000324 */  addiu      $3, $0, 0xA
    /* 0140A4 00113FA4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0140A8 00113FA8 0800E003 */  jr         $31
    /* 0140AC 00113FAC 00000000 */   nop

/* Handwritten function */
glabel RemoveSbusIntcHandler
    /* 0140B0 00113FB0 0B000324 */  addiu      $3, $0, 0xB
    /* 0140B4 00113FB4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0140B8 00113FB8 0800E003 */  jr         $31
    /* 0140BC 00113FBC 00000000 */   nop

/* Handwritten function */
glabel Interrupt2Iop
    /* 0140C0 00113FC0 0C000324 */  addiu      $3, $0, 0xC
    /* 0140C4 00113FC4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0140C8 00113FC8 0800E003 */  jr         $31
    /* 0140CC 00113FCC 00000000 */   nop

/* Handwritten function */
glabel SetVTLBRefillHandler
    /* 0140D0 00113FD0 0D000324 */  addiu      $3, $0, 0xD
    /* 0140D4 00113FD4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0140D8 00113FD8 0800E003 */  jr         $31
    /* 0140DC 00113FDC 00000000 */   nop

/* Handwritten function */
glabel SetVCommonHandler
    /* 0140E0 00113FE0 0E000324 */  addiu      $3, $0, 0xE
    /* 0140E4 00113FE4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0140E8 00113FE8 0800E003 */  jr         $31
    /* 0140EC 00113FEC 00000000 */   nop

/* Handwritten function */
glabel SetVInterruptHandler
    /* 0140F0 00113FF0 0F000324 */  addiu      $3, $0, 0xF
    /* 0140F4 00113FF4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0140F8 00113FF8 0800E003 */  jr         $31
    /* 0140FC 00113FFC 00000000 */   nop

/* Handwritten function */
glabel AddIntcHandler
    /* 014100 00114000 10000324 */  addiu      $3, $0, 0x10
    /* 014104 00114004 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014108 00114008 0800E003 */  jr         $31
    /* 01410C 0011400C 00000000 */   nop

/* Handwritten function */
glabel AddIntcHandler2
    /* 014110 00114010 10000324 */  addiu      $3, $0, 0x10
    /* 014114 00114014 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014118 00114018 0800E003 */  jr         $31
    /* 01411C 0011401C 00000000 */   nop

/* Handwritten function */
glabel RemoveIntcHandler
    /* 014120 00114020 11000324 */  addiu      $3, $0, 0x11
    /* 014124 00114024 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014128 00114028 0800E003 */  jr         $31
    /* 01412C 0011402C 00000000 */   nop

/* Handwritten function */
glabel AddDmacHandler
    /* 014130 00114030 12000324 */  addiu      $3, $0, 0x12
    /* 014134 00114034 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014138 00114038 0800E003 */  jr         $31
    /* 01413C 0011403C 00000000 */   nop

/* Handwritten function */
glabel AddDmacHandler2
    /* 014140 00114040 12000324 */  addiu      $3, $0, 0x12
    /* 014144 00114044 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014148 00114048 0800E003 */  jr         $31
    /* 01414C 0011404C 00000000 */   nop

/* Handwritten function */
glabel RemoveDmacHandler
    /* 014150 00114050 13000324 */  addiu      $3, $0, 0x13
    /* 014154 00114054 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014158 00114058 0800E003 */  jr         $31
    /* 01415C 0011405C 00000000 */   nop

/* Handwritten function */
glabel _EnableIntc
    /* 014160 00114060 14000324 */  addiu      $3, $0, 0x14
    /* 014164 00114064 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014168 00114068 0800E003 */  jr         $31
    /* 01416C 0011406C 00000000 */   nop

/* Handwritten function */
glabel _DisableIntc
    /* 014170 00114070 15000324 */  addiu      $3, $0, 0x15
    /* 014174 00114074 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014178 00114078 0800E003 */  jr         $31
    /* 01417C 0011407C 00000000 */   nop

/* Handwritten function */
glabel _EnableDmac
    /* 014180 00114080 16000324 */  addiu      $3, $0, 0x16
    /* 014184 00114084 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014188 00114088 0800E003 */  jr         $31
    /* 01418C 0011408C 00000000 */   nop

/* Handwritten function */
glabel _DisableDmac
    /* 014190 00114090 17000324 */  addiu      $3, $0, 0x17
    /* 014194 00114094 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014198 00114098 0800E003 */  jr         $31
    /* 01419C 0011409C 00000000 */   nop

/* Handwritten function */
glabel _SetAlarm
    /* 0141A0 001140A0 18000324 */  addiu      $3, $0, 0x18
    /* 0141A4 001140A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0141A8 001140A8 0800E003 */  jr         $31
    /* 0141AC 001140AC 00000000 */   nop

/* Handwritten function */
glabel _ReleaseAlarm
    /* 0141B0 001140B0 19000324 */  addiu      $3, $0, 0x19
    /* 0141B4 001140B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0141B8 001140B8 0800E003 */  jr         $31
    /* 0141BC 001140BC 00000000 */   nop

/* Handwritten function */
glabel _iEnableIntc
    /* 0141C0 001140C0 E6FF0324 */  addiu      $3, $0, -0x1A
    /* 0141C4 001140C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0141C8 001140C8 0800E003 */  jr         $31
    /* 0141CC 001140CC 00000000 */   nop

/* Handwritten function */
glabel _iDisableIntc
    /* 0141D0 001140D0 E5FF0324 */  addiu      $3, $0, -0x1B
    /* 0141D4 001140D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0141D8 001140D8 0800E003 */  jr         $31
    /* 0141DC 001140DC 00000000 */   nop

/* Handwritten function */
glabel _iEnableDmac
    /* 0141E0 001140E0 E4FF0324 */  addiu      $3, $0, -0x1C
    /* 0141E4 001140E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0141E8 001140E8 0800E003 */  jr         $31
    /* 0141EC 001140EC 00000000 */   nop

/* Handwritten function */
glabel _iDisableDmac
    /* 0141F0 001140F0 E3FF0324 */  addiu      $3, $0, -0x1D
    /* 0141F4 001140F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0141F8 001140F8 0800E003 */  jr         $31
    /* 0141FC 001140FC 00000000 */   nop

/* Handwritten function */
glabel _iSetAlarm
    /* 014200 00114100 E2FF0324 */  addiu      $3, $0, -0x1E
    /* 014204 00114104 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014208 00114108 0800E003 */  jr         $31
    /* 01420C 0011410C 00000000 */   nop

/* Handwritten function */
glabel _iReleaseAlarm
    /* 014210 00114110 E1FF0324 */  addiu      $3, $0, -0x1F
    /* 014214 00114114 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014218 00114118 0800E003 */  jr         $31
    /* 01421C 0011411C 00000000 */   nop

/* Handwritten function */
glabel CreateThread
    /* 014220 00114120 20000324 */  addiu      $3, $0, 0x20
    /* 014224 00114124 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014228 00114128 0800E003 */  jr         $31
    /* 01422C 0011412C 00000000 */   nop

/* Handwritten function */
glabel DeleteThread
    /* 014230 00114130 21000324 */  addiu      $3, $0, 0x21
    /* 014234 00114134 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014238 00114138 0800E003 */  jr         $31
    /* 01423C 0011413C 00000000 */   nop

/* Handwritten function */
glabel StartThread
    /* 014240 00114140 22000324 */  addiu      $3, $0, 0x22
    /* 014244 00114144 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014248 00114148 0800E003 */  jr         $31
    /* 01424C 0011414C 00000000 */   nop

/* Handwritten function */
glabel ExitThread
    /* 014250 00114150 23000324 */  addiu      $3, $0, 0x23
    /* 014254 00114154 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014258 00114158 0800E003 */  jr         $31
    /* 01425C 0011415C 00000000 */   nop

/* Handwritten function */
glabel ExitDeleteThread
    /* 014260 00114160 24000324 */  addiu      $3, $0, 0x24
    /* 014264 00114164 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014268 00114168 0800E003 */  jr         $31
    /* 01426C 0011416C 00000000 */   nop

/* Handwritten function */
glabel TerminateThread
    /* 014270 00114170 25000324 */  addiu      $3, $0, 0x25
    /* 014274 00114174 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014278 00114178 0800E003 */  jr         $31
    /* 01427C 0011417C 00000000 */   nop

/* Handwritten function */
glabel iTerminateThread
    /* 014280 00114180 DAFF0324 */  addiu      $3, $0, -0x26
    /* 014284 00114184 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014288 00114188 0800E003 */  jr         $31
    /* 01428C 0011418C 00000000 */   nop

/* Handwritten function */
glabel DisableDispatchThread
    /* 014290 00114190 27000324 */  addiu      $3, $0, 0x27
    /* 014294 00114194 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014298 00114198 0800E003 */  jr         $31
    /* 01429C 0011419C 00000000 */   nop

/* Handwritten function */
glabel EnableDispatchThread
    /* 0142A0 001141A0 28000324 */  addiu      $3, $0, 0x28
    /* 0142A4 001141A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0142A8 001141A8 0800E003 */  jr         $31
    /* 0142AC 001141AC 00000000 */   nop

/* Handwritten function */
glabel ChangeThreadPriority
    /* 0142B0 001141B0 29000324 */  addiu      $3, $0, 0x29
    /* 0142B4 001141B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0142B8 001141B8 0800E003 */  jr         $31
    /* 0142BC 001141BC 00000000 */   nop

/* Handwritten function */
glabel iChangeThreadPriority
    /* 0142C0 001141C0 D6FF0324 */  addiu      $3, $0, -0x2A
    /* 0142C4 001141C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0142C8 001141C8 0800E003 */  jr         $31
    /* 0142CC 001141CC 00000000 */   nop

/* Handwritten function */
glabel RotateThreadReadyQueue
    /* 0142D0 001141D0 2B000324 */  addiu      $3, $0, 0x2B
    /* 0142D4 001141D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0142D8 001141D8 0800E003 */  jr         $31
    /* 0142DC 001141DC 00000000 */   nop

/* Handwritten function */
glabel _iRotateThreadReadyQueue
    /* 0142E0 001141E0 D4FF0324 */  addiu      $3, $0, -0x2C
    /* 0142E4 001141E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0142E8 001141E8 0800E003 */  jr         $31
    /* 0142EC 001141EC 00000000 */   nop

/* Handwritten function */
glabel ReleaseWaitThread
    /* 0142F0 001141F0 2D000324 */  addiu      $3, $0, 0x2D
    /* 0142F4 001141F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0142F8 001141F8 0800E003 */  jr         $31
    /* 0142FC 001141FC 00000000 */   nop

/* Handwritten function */
glabel iReleaseWaitThread
    /* 014300 00114200 D2FF0324 */  addiu      $3, $0, -0x2E
    /* 014304 00114204 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014308 00114208 0800E003 */  jr         $31
    /* 01430C 0011420C 00000000 */   nop

/* Handwritten function */
glabel GetThreadId
    /* 014310 00114210 2F000324 */  addiu      $3, $0, 0x2F
    /* 014314 00114214 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014318 00114218 0800E003 */  jr         $31
    /* 01431C 0011421C 00000000 */   nop

/* Handwritten function */
glabel ReferThreadStatus
    /* 014320 00114220 30000324 */  addiu      $3, $0, 0x30
    /* 014324 00114224 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014328 00114228 0800E003 */  jr         $31
    /* 01432C 0011422C 00000000 */   nop

/* Handwritten function */
glabel iReferThreadStatus
    /* 014330 00114230 CFFF0324 */  addiu      $3, $0, -0x31
    /* 014334 00114234 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014338 00114238 0800E003 */  jr         $31
    /* 01433C 0011423C 00000000 */   nop

/* Handwritten function */
glabel SleepThread
    /* 014340 00114240 32000324 */  addiu      $3, $0, 0x32
    /* 014344 00114244 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014348 00114248 0800E003 */  jr         $31
    /* 01434C 0011424C 00000000 */   nop

/* Handwritten function */
glabel WakeupThread
    /* 014350 00114250 33000324 */  addiu      $3, $0, 0x33
    /* 014354 00114254 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014358 00114258 0800E003 */  jr         $31
    /* 01435C 0011425C 00000000 */   nop

/* Handwritten function */
glabel _iWakeupThread
    /* 014360 00114260 CCFF0324 */  addiu      $3, $0, -0x34
    /* 014364 00114264 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014368 00114268 0800E003 */  jr         $31
    /* 01436C 0011426C 00000000 */   nop

/* Handwritten function */
glabel CancelWakeupThread
    /* 014370 00114270 35000324 */  addiu      $3, $0, 0x35
    /* 014374 00114274 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014378 00114278 0800E003 */  jr         $31
    /* 01437C 0011427C 00000000 */   nop

/* Handwritten function */
glabel iCancelWakeupThread
    /* 014380 00114280 CAFF0324 */  addiu      $3, $0, -0x36
    /* 014384 00114284 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014388 00114288 0800E003 */  jr         $31
    /* 01438C 0011428C 00000000 */   nop

/* Handwritten function */
glabel SuspendThread
    /* 014390 00114290 37000324 */  addiu      $3, $0, 0x37
    /* 014394 00114294 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014398 00114298 0800E003 */  jr         $31
    /* 01439C 0011429C 00000000 */   nop

/* Handwritten function */
glabel _iSuspendThread
    /* 0143A0 001142A0 C8FF0324 */  addiu      $3, $0, -0x38
    /* 0143A4 001142A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0143A8 001142A8 0800E003 */  jr         $31
    /* 0143AC 001142AC 00000000 */   nop

/* Handwritten function */
glabel ResumeThread
    /* 0143B0 001142B0 39000324 */  addiu      $3, $0, 0x39
    /* 0143B4 001142B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0143B8 001142B8 0800E003 */  jr         $31
    /* 0143BC 001142BC 00000000 */   nop

/* Handwritten function */
glabel iResumeThread
    /* 0143C0 001142C0 C6FF0324 */  addiu      $3, $0, -0x3A
    /* 0143C4 001142C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0143C8 001142C8 0800E003 */  jr         $31
    /* 0143CC 001142CC 00000000 */   nop

/* Handwritten function */
glabel JoinThread
    /* 0143D0 001142D0 3B000324 */  addiu      $3, $0, 0x3B
    /* 0143D4 001142D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0143D8 001142D8 0800E003 */  jr         $31
    /* 0143DC 001142DC 00000000 */   nop

/* Handwritten function */
glabel RFU060
    /* 0143E0 001142E0 3C000324 */  addiu      $3, $0, 0x3C
    /* 0143E4 001142E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0143E8 001142E8 0800E003 */  jr         $31
    /* 0143EC 001142EC 00000000 */   nop

/* Handwritten function */
glabel RFU061
    /* 0143F0 001142F0 3D000324 */  addiu      $3, $0, 0x3D
    /* 0143F4 001142F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0143F8 001142F8 0800E003 */  jr         $31
    /* 0143FC 001142FC 00000000 */   nop

/* Handwritten function */
glabel EndOfHeap
    /* 014400 00114300 3E000324 */  addiu      $3, $0, 0x3E
    /* 014404 00114304 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014408 00114308 0800E003 */  jr         $31
    /* 01440C 0011430C 00000000 */   nop

/* Handwritten function */
glabel RFU063
    /* 014410 00114310 3F000324 */  addiu      $3, $0, 0x3F
    /* 014414 00114314 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014418 00114318 0800E003 */  jr         $31
    /* 01441C 0011431C 00000000 */   nop

/* Handwritten function */
glabel CreateSema
    /* 014420 00114320 40000324 */  addiu      $3, $0, 0x40
    /* 014424 00114324 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014428 00114328 0800E003 */  jr         $31
    /* 01442C 0011432C 00000000 */   nop

/* Handwritten function */
glabel DeleteSema
    /* 014430 00114330 41000324 */  addiu      $3, $0, 0x41
    /* 014434 00114334 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014438 00114338 0800E003 */  jr         $31
    /* 01443C 0011433C 00000000 */   nop

/* Handwritten function */
glabel SignalSema
    /* 014440 00114340 42000324 */  addiu      $3, $0, 0x42
    /* 014444 00114344 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014448 00114348 0800E003 */  jr         $31
    /* 01444C 0011434C 00000000 */   nop

/* Handwritten function */
glabel iSignalSema
    /* 014450 00114350 BDFF0324 */  addiu      $3, $0, -0x43
    /* 014454 00114354 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014458 00114358 0800E003 */  jr         $31
    /* 01445C 0011435C 00000000 */   nop

/* Handwritten function */
glabel WaitSema
    /* 014460 00114360 44000324 */  addiu      $3, $0, 0x44
    /* 014464 00114364 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014468 00114368 0800E003 */  jr         $31
    /* 01446C 0011436C 00000000 */   nop

/* Handwritten function */
glabel PollSema
    /* 014470 00114370 45000324 */  addiu      $3, $0, 0x45
    /* 014474 00114374 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014478 00114378 0800E003 */  jr         $31
    /* 01447C 0011437C 00000000 */   nop

/* Handwritten function */
glabel iPollSema
    /* 014480 00114380 BAFF0324 */  addiu      $3, $0, -0x46
    /* 014484 00114384 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014488 00114388 0800E003 */  jr         $31
    /* 01448C 0011438C 00000000 */   nop

/* Handwritten function */
glabel ReferSemaStatus
    /* 014490 00114390 47000324 */  addiu      $3, $0, 0x47
    /* 014494 00114394 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014498 00114398 0800E003 */  jr         $31
    /* 01449C 0011439C 00000000 */   nop

/* Handwritten function */
glabel iReferSemaStatus
    /* 0144A0 001143A0 B8FF0324 */  addiu      $3, $0, -0x48
    /* 0144A4 001143A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0144A8 001143A8 0800E003 */  jr         $31
    /* 0144AC 001143AC 00000000 */   nop

/* Handwritten function */
glabel RFU073
    /* 0144B0 001143B0 49000324 */  addiu      $3, $0, 0x49
    /* 0144B4 001143B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0144B8 001143B8 0800E003 */  jr         $31
    /* 0144BC 001143BC 00000000 */   nop

/* Handwritten function */
glabel SetOsdConfigParam
    /* 0144C0 001143C0 4A000324 */  addiu      $3, $0, 0x4A
    /* 0144C4 001143C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0144C8 001143C8 0800E003 */  jr         $31
    /* 0144CC 001143CC 00000000 */   nop

/* Handwritten function */
glabel GetOsdConfigParam
    /* 0144D0 001143D0 4B000324 */  addiu      $3, $0, 0x4B
    /* 0144D4 001143D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0144D8 001143D8 0800E003 */  jr         $31
    /* 0144DC 001143DC 00000000 */   nop

/* Handwritten function */
glabel GetGsHParam
    /* 0144E0 001143E0 4C000324 */  addiu      $3, $0, 0x4C
    /* 0144E4 001143E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0144E8 001143E8 0800E003 */  jr         $31
    /* 0144EC 001143EC 00000000 */   nop

/* Handwritten function */
glabel GetGsVParam
    /* 0144F0 001143F0 4D000324 */  addiu      $3, $0, 0x4D
    /* 0144F4 001143F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0144F8 001143F8 0800E003 */  jr         $31
    /* 0144FC 001143FC 00000000 */   nop

/* Handwritten function */
glabel SetGsHParam
    /* 014500 00114400 4E000324 */  addiu      $3, $0, 0x4E
    /* 014504 00114404 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014508 00114408 0800E003 */  jr         $31
    /* 01450C 0011440C 00000000 */   nop

/* Handwritten function */
glabel SetGsVParam
    /* 014510 00114410 4F000324 */  addiu      $3, $0, 0x4F
    /* 014514 00114414 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014518 00114418 0800E003 */  jr         $31
    /* 01451C 0011441C 00000000 */   nop

/* Handwritten function */
glabel RFU080_CreateEventFlag
    /* 014520 00114420 50000324 */  addiu      $3, $0, 0x50
    /* 014524 00114424 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014528 00114428 0800E003 */  jr         $31
    /* 01452C 0011442C 00000000 */   nop

/* Handwritten function */
glabel RFU081_DeleteEventFlag
    /* 014530 00114430 51000324 */  addiu      $3, $0, 0x51
    /* 014534 00114434 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014538 00114438 0800E003 */  jr         $31
    /* 01453C 0011443C 00000000 */   nop

/* Handwritten function */
glabel RFU082_SetEventFlag
    /* 014540 00114440 52000324 */  addiu      $3, $0, 0x52
    /* 014544 00114444 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014548 00114448 0800E003 */  jr         $31
    /* 01454C 0011444C 00000000 */   nop

/* Handwritten function */
glabel RFU083_iSetEventFlag
    /* 014550 00114450 ADFF0324 */  addiu      $3, $0, -0x53
    /* 014554 00114454 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014558 00114458 0800E003 */  jr         $31
    /* 01455C 0011445C 00000000 */   nop

/* Handwritten function */
glabel RFU084_ClearEventFlag
    /* 014560 00114460 54000324 */  addiu      $3, $0, 0x54
    /* 014564 00114464 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014568 00114468 0800E003 */  jr         $31
    /* 01456C 0011446C 00000000 */   nop

/* Handwritten function */
glabel RFU085_iClearEventFlag
    /* 014570 00114470 ABFF0324 */  addiu      $3, $0, -0x55
    /* 014574 00114474 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014578 00114478 0800E003 */  jr         $31
    /* 01457C 0011447C 00000000 */   nop

/* Handwritten function */
glabel RFU086_WaitEvnetFlag
    /* 014580 00114480 56000324 */  addiu      $3, $0, 0x56
    /* 014584 00114484 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014588 00114488 0800E003 */  jr         $31
    /* 01458C 0011448C 00000000 */   nop

/* Handwritten function */
glabel RFU087_PollEvnetFlag
    /* 014590 00114490 57000324 */  addiu      $3, $0, 0x57
    /* 014594 00114494 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014598 00114498 0800E003 */  jr         $31
    /* 01459C 0011449C 00000000 */   nop

/* Handwritten function */
glabel RFU088_iPollEvnetFlag
    /* 0145A0 001144A0 A8FF0324 */  addiu      $3, $0, -0x58
    /* 0145A4 001144A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0145A8 001144A8 0800E003 */  jr         $31
    /* 0145AC 001144AC 00000000 */   nop

/* Handwritten function */
glabel RFU089_ReferEventFlagStatus
    /* 0145B0 001144B0 59000324 */  addiu      $3, $0, 0x59
    /* 0145B4 001144B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0145B8 001144B8 0800E003 */  jr         $31
    /* 0145BC 001144BC 00000000 */   nop

/* Handwritten function */
glabel RFU090_iReferEventFlagStatus
    /* 0145C0 001144C0 A6FF0324 */  addiu      $3, $0, -0x5A
    /* 0145C4 001144C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0145C8 001144C8 0800E003 */  jr         $31
    /* 0145CC 001144CC 00000000 */   nop

/* Handwritten function */
glabel RFU091
    /* 0145D0 001144D0 5B000324 */  addiu      $3, $0, 0x5B
    /* 0145D4 001144D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0145D8 001144D8 0800E003 */  jr         $31
    /* 0145DC 001144DC 00000000 */   nop

/* Handwritten function */
glabel EnableIntcHandler
    /* 0145E0 001144E0 5C000324 */  addiu      $3, $0, 0x5C
    /* 0145E4 001144E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0145E8 001144E8 0800E003 */  jr         $31
    /* 0145EC 001144EC 00000000 */   nop

/* Handwritten function */
glabel iEnableIntcHandler
    /* 0145F0 001144F0 A4FF0324 */  addiu      $3, $0, -0x5C
    /* 0145F4 001144F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0145F8 001144F8 0800E003 */  jr         $31
    /* 0145FC 001144FC 00000000 */   nop

/* Handwritten function */
glabel DisableIntcHandler
    /* 014600 00114500 5D000324 */  addiu      $3, $0, 0x5D
    /* 014604 00114504 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014608 00114508 0800E003 */  jr         $31
    /* 01460C 0011450C 00000000 */   nop

/* Handwritten function */
glabel iDisableIntcHandler
    /* 014610 00114510 A3FF0324 */  addiu      $3, $0, -0x5D
    /* 014614 00114514 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014618 00114518 0800E003 */  jr         $31
    /* 01461C 0011451C 00000000 */   nop

/* Handwritten function */
glabel EnableDmacHandler
    /* 014620 00114520 5E000324 */  addiu      $3, $0, 0x5E
    /* 014624 00114524 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014628 00114528 0800E003 */  jr         $31
    /* 01462C 0011452C 00000000 */   nop

/* Handwritten function */
glabel iEnableDmacHandler
    /* 014630 00114530 A2FF0324 */  addiu      $3, $0, -0x5E
    /* 014634 00114534 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014638 00114538 0800E003 */  jr         $31
    /* 01463C 0011453C 00000000 */   nop

/* Handwritten function */
glabel DisableDmacHandler
    /* 014640 00114540 5F000324 */  addiu      $3, $0, 0x5F
    /* 014644 00114544 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014648 00114548 0800E003 */  jr         $31
    /* 01464C 0011454C 00000000 */   nop

/* Handwritten function */
glabel iDisableDmacHandler
    /* 014650 00114550 A1FF0324 */  addiu      $3, $0, -0x5F
    /* 014654 00114554 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014658 00114558 0800E003 */  jr         $31
    /* 01465C 0011455C 00000000 */   nop

/* Handwritten function */
glabel KSeg0
    /* 014660 00114560 60000324 */  addiu      $3, $0, 0x60
    /* 014664 00114564 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014668 00114568 0800E003 */  jr         $31
    /* 01466C 0011456C 00000000 */   nop

/* Handwritten function */
glabel EnableCache
    /* 014670 00114570 61000324 */  addiu      $3, $0, 0x61
    /* 014674 00114574 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014678 00114578 0800E003 */  jr         $31
    /* 01467C 0011457C 00000000 */   nop

/* Handwritten function */
glabel DisableCache
    /* 014680 00114580 62000324 */  addiu      $3, $0, 0x62
    /* 014684 00114584 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014688 00114588 0800E003 */  jr         $31
    /* 01468C 0011458C 00000000 */   nop

/* Handwritten function */
glabel GetCop0
    /* 014690 00114590 63000324 */  addiu      $3, $0, 0x63
    /* 014694 00114594 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014698 00114598 0800E003 */  jr         $31
    /* 01469C 0011459C 00000000 */   nop

/* Handwritten function */
glabel FlushCache
    /* 0146A0 001145A0 64000324 */  addiu      $3, $0, 0x64
    /* 0146A4 001145A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0146A8 001145A8 0800E003 */  jr         $31
    /* 0146AC 001145AC 00000000 */   nop

/* Handwritten function */
glabel CpuConfig
    /* 0146B0 001145B0 66000324 */  addiu      $3, $0, 0x66
    /* 0146B4 001145B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0146B8 001145B8 0800E003 */  jr         $31
    /* 0146BC 001145BC 00000000 */   nop

/* Handwritten function */
glabel iGetCop0
    /* 0146C0 001145C0 99FF0324 */  addiu      $3, $0, -0x67
    /* 0146C4 001145C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0146C8 001145C8 0800E003 */  jr         $31
    /* 0146CC 001145CC 00000000 */   nop

/* Handwritten function */
glabel iFlushCache
    /* 0146D0 001145D0 98FF0324 */  addiu      $3, $0, -0x68
    /* 0146D4 001145D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0146D8 001145D8 0800E003 */  jr         $31
    /* 0146DC 001145DC 00000000 */   nop

/* Handwritten function */
glabel iCpuConfig
    /* 0146E0 001145E0 96FF0324 */  addiu      $3, $0, -0x6A
    /* 0146E4 001145E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0146E8 001145E8 0800E003 */  jr         $31
    /* 0146EC 001145EC 00000000 */   nop

/* Handwritten function */
glabel sceSifStopDma
    /* 0146F0 001145F0 6B000324 */  addiu      $3, $0, 0x6B
    /* 0146F4 001145F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0146F8 001145F8 0800E003 */  jr         $31
    /* 0146FC 001145FC 00000000 */   nop

/* Handwritten function */
glabel SetCPUTimerHandler
    /* 014700 00114600 6C000324 */  addiu      $3, $0, 0x6C
    /* 014704 00114604 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014708 00114608 0800E003 */  jr         $31
    /* 01470C 0011460C 00000000 */   nop

/* Handwritten function */
glabel SetCPUTimer
    /* 014710 00114610 6D000324 */  addiu      $3, $0, 0x6D
    /* 014714 00114614 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014718 00114618 0800E003 */  jr         $31
    /* 01471C 0011461C 00000000 */   nop

/* Handwritten function */
glabel SetOsdConfigParam2
    /* 014720 00114620 6E000324 */  addiu      $3, $0, 0x6E
    /* 014724 00114624 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014728 00114628 0800E003 */  jr         $31
    /* 01472C 0011462C 00000000 */   nop

/* Handwritten function */
glabel GetOsdConfigParam2
    /* 014730 00114630 6F000324 */  addiu      $3, $0, 0x6F
    /* 014734 00114634 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014738 00114638 0800E003 */  jr         $31
    /* 01473C 0011463C 00000000 */   nop

/* Handwritten function */
glabel GsGetIMR
    /* 014740 00114640 70000324 */  addiu      $3, $0, 0x70
    /* 014744 00114644 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014748 00114648 0800E003 */  jr         $31
    /* 01474C 0011464C 00000000 */   nop

/* Handwritten function */
glabel iGsGetIMR
    /* 014750 00114650 90FF0324 */  addiu      $3, $0, -0x70
    /* 014754 00114654 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014758 00114658 0800E003 */  jr         $31
    /* 01475C 0011465C 00000000 */   nop

/* Handwritten function */
glabel GsPutIMR
    /* 014760 00114660 71000324 */  addiu      $3, $0, 0x71
    /* 014764 00114664 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014768 00114668 0800E003 */  jr         $31
    /* 01476C 0011466C 00000000 */   nop

/* Handwritten function */
glabel iGsPutIMR
    /* 014770 00114670 8FFF0324 */  addiu      $3, $0, -0x71
    /* 014774 00114674 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014778 00114678 0800E003 */  jr         $31
    /* 01477C 0011467C 00000000 */   nop

/* Handwritten function */
glabel SetPgifHandler
    /* 014780 00114680 72000324 */  addiu      $3, $0, 0x72
    /* 014784 00114684 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014788 00114688 0800E003 */  jr         $31
    /* 01478C 0011468C 00000000 */   nop

/* Handwritten function */
glabel SetVSyncFlag
    /* 014790 00114690 73000324 */  addiu      $3, $0, 0x73
    /* 014794 00114694 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014798 00114698 0800E003 */  jr         $31
    /* 01479C 0011469C 00000000 */   nop

/* Handwritten function */
glabel RFU116
    /* 0147A0 001146A0 74000324 */  addiu      $3, $0, 0x74
    /* 0147A4 001146A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0147A8 001146A8 0800E003 */  jr         $31
    /* 0147AC 001146AC 00000000 */   nop

/* Handwritten function */
glabel print
    /* 0147B0 001146B0 75000324 */  addiu      $3, $0, 0x75
    /* 0147B4 001146B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0147B8 001146B8 0800E003 */  jr         $31
    /* 0147BC 001146BC 00000000 */   nop

/* Handwritten function */
glabel sceSifDmaStat
    /* 0147C0 001146C0 76000324 */  addiu      $3, $0, 0x76
    /* 0147C4 001146C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0147C8 001146C8 0800E003 */  jr         $31
    /* 0147CC 001146CC 00000000 */   nop

/* Handwritten function */
glabel isceSifDmaStat
    /* 0147D0 001146D0 8AFF0324 */  addiu      $3, $0, -0x76
    /* 0147D4 001146D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0147D8 001146D8 0800E003 */  jr         $31
    /* 0147DC 001146DC 00000000 */   nop

/* Handwritten function */
glabel sceSifSetDma
    /* 0147E0 001146E0 77000324 */  addiu      $3, $0, 0x77
    /* 0147E4 001146E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0147E8 001146E8 0800E003 */  jr         $31
    /* 0147EC 001146EC 00000000 */   nop

/* Handwritten function */
glabel isceSifSetDma
    /* 0147F0 001146F0 89FF0324 */  addiu      $3, $0, -0x77
    /* 0147F4 001146F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 0147F8 001146F8 0800E003 */  jr         $31
    /* 0147FC 001146FC 00000000 */   nop

/* Handwritten function */
glabel sceSifSetDChain
    /* 014800 00114700 78000324 */  addiu      $3, $0, 0x78
    /* 014804 00114704 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014808 00114708 0800E003 */  jr         $31
    /* 01480C 0011470C 00000000 */   nop

/* Handwritten function */
glabel isceSifSetDChain
    /* 014810 00114710 88FF0324 */  addiu      $3, $0, -0x78
    /* 014814 00114714 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014818 00114718 0800E003 */  jr         $31
    /* 01481C 0011471C 00000000 */   nop

/* Handwritten function */
glabel sceSifSetReg
    /* 014820 00114720 79000324 */  addiu      $3, $0, 0x79
    /* 014824 00114724 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014828 00114728 0800E003 */  jr         $31
    /* 01482C 0011472C 00000000 */   nop

/* Handwritten function */
glabel sceSifGetReg
    /* 014830 00114730 7A000324 */  addiu      $3, $0, 0x7A
    /* 014834 00114734 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014838 00114738 0800E003 */  jr         $31
    /* 01483C 0011473C 00000000 */   nop

/* Handwritten function */
glabel ExecOSD
    /* 014840 00114740 7B000324 */  addiu      $3, $0, 0x7B
    /* 014844 00114744 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014848 00114748 0800E003 */  jr         $31
    /* 01484C 0011474C 00000000 */   nop

/* Handwritten function */
glabel Deci2Call
    /* 014850 00114750 7C000324 */  addiu      $3, $0, 0x7C
    /* 014854 00114754 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014858 00114758 0800E003 */  jr         $31
    /* 01485C 0011475C 00000000 */   nop

/* Handwritten function */
glabel PSMode
    /* 014860 00114760 7D000324 */  addiu      $3, $0, 0x7D
    /* 014864 00114764 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014868 00114768 0800E003 */  jr         $31
    /* 01486C 0011476C 00000000 */   nop

/* Handwritten function */
glabel MachineType
    /* 014870 00114770 7E000324 */  addiu      $3, $0, 0x7E
    /* 014874 00114774 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014878 00114778 0800E003 */  jr         $31
    /* 01487C 0011477C 00000000 */   nop

/* Handwritten function */
glabel GetMemorySize
    /* 014880 00114780 7F000324 */  addiu      $3, $0, 0x7F
    /* 014884 00114784 0C000000 */  syscall    0 /* handwritten instruction */
    /* 014888 00114788 0800E003 */  jr         $31
    /* 01488C 0011478C 00000000 */   nop
