TITLE_O_FILES :=\
    $(BUILD_DIR)/ref/asm/split/title/_title_text_start.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScript__Load.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScript__Step.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScript__CheckScript.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScript__CheckArg.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScript__SkipSpace.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CDispFade__FadeOutStart.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CDispFade__FadeInStart.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CDispFade__FadeInit.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CDispFade__GetRate.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CDispFade__FadeOut.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CDispFade__FadeIn.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CBombEffect__Draw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CBombEffect__Step.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CMajinBeem__Draw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CMajinBeem__Draw2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CMajinBeem__Step.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSeireiKing__Draw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSeireiKing__Draw2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSeireiKing__Step.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpeningInit.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadMessage.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadScene.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadSceneBG.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpeningLoop.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SceneChange.s.o \
    $(BUILD_DIR)/ref/asm/split/title/PauseProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SoundStop.s.o \
    $(BUILD_DIR)/ref/asm/split/title/WaitKeyProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/MotionProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SoundProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawMess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpBgmPlay.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpPlayVolPanSE.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpSetVolPanSE.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpPlayVolSE.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpGetVolSQ.s.o \
    $(BUILD_DIR)/ref/asm/split/title/FadeCansel.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OPAnalyz.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OPMdsLoad.s.o \
    $(BUILD_DIR)/ref/asm/split/title/skipSpace.s.o \
    $(BUILD_DIR)/ref/asm/split/title/checkArg.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpA_InitProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadTexture__Fv__3.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadData__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SetDanceMotion.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitDancerPos.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpA_DrawProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawCloud.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SmokeProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpA_MotionProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/MoveDancers.s.o \
    $(BUILD_DIR)/ref/asm/split/title/ReaderShadow.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DancerShadow.s.o \
    $(BUILD_DIR)/ref/asm/split/title/ShogunShadow.s.o \
    $(BUILD_DIR)/ref/asm/split/title/ShisaiShadow.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawShadow.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpA_SoundProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/setTexScroll.s.o \
    $(BUILD_DIR)/ref/asm/split/title/setCloudTexScroll.s.o \
    $(BUILD_DIR)/ref/asm/split/title/FaceChange.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadCharaData.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadMotionData.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_LoadDataBG.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_LoadDataBG2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_InitProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_InitProcess2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_MotionProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_SoundProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpB_DrawProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/setTexAnime.s.o \
    $(BUILD_DIR)/ref/asm/split/title/FaceChange__Fi__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_LoadDataBG.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_LoadDataBG2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_LoadDataBG3.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_LoadDataBG4.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_LoadDataBG5.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_InitProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_InitProcess2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_InitProcess3.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_InitProcess4.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_InitProcess5.s.o \
    $(BUILD_DIR)/ref/asm/split/title/MapLoad.s.o \
    $(BUILD_DIR)/ref/asm/split/title/MapLoad2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_MotionProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LoadCharaMajin.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_SoundProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpC_DrawProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawDancer.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InchikiShadow.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawShadow_2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/MajinBeemProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SmokeProcess__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/WaterProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/KageCheck.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LightSet.s.o \
    $(BUILD_DIR)/ref/asm/split/title/setTexScroll__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/setTexAnim__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/FaceChange__Fi__3.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_LoadDataBG.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_LoadDataBG2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_InitProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_InitProcess2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SkyColor.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_MotionProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_SoundProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/OpD_DrawProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/EffectAtraPrizum.s.o \
    $(BUILD_DIR)/ref/asm/split/title/RollLight.s.o \
    $(BUILD_DIR)/ref/asm/split/title/EffectSeireiKing.s.o \
    $(BUILD_DIR)/ref/asm/split/title/LensFreaProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/Setsumei.s.o \
    $(BUILD_DIR)/ref/asm/split/title/HamonProcess.s.o \
    $(BUILD_DIR)/ref/asm/split/title/FaceChange__Fi__4.s.o \
    $(BUILD_DIR)/ref/asm/split/title/RushInit.s.o \
    $(BUILD_DIR)/ref/asm/split/title/RushLoop.s.o \
    $(BUILD_DIR)/ref/asm/split/title/MotionProcess__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcess__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SoundProcess__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/SetObjAnime.s.o \
    $(BUILD_DIR)/ref/asm/split/title/WaterProcess__Fv__2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DataLoad.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcA.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcA.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcB.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcB.s.o \
    $(BUILD_DIR)/ref/asm/split/title/AtraLight.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcC.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcC.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcD.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcD.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcE.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcE.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcF.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcF.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcG.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcG.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcH.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcH.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcI.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcI.s.o \
    $(BUILD_DIR)/ref/asm/split/title/InitProcTitle.s.o \
    $(BUILD_DIR)/ref/asm/split/title/DrawProcTitle.s.o \
    $(BUILD_DIR)/ref/asm/split/title/TitleInit.s.o \
    $(BUILD_DIR)/ref/asm/split/title/TitleLoop.s.o \
    $(BUILD_DIR)/ref/asm/split/title/TitleDraw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo____ct.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo__Init.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo__Fade.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo__FadeOut.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo__Sparkdraw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo__Draw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CLogo__Move.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSprite____ct.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSprite__Init.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSprite__Move.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSprite__Draw.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CSprite__Se.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CCursol____ct.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CCursol__Init.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CCursol__Move.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CCursol__Set.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CCursol__GetSelect.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CCursol__GetPos.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScFader__In.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScFader__In2.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScFader__Out.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScFader__Get.s.o \
    $(BUILD_DIR)/ref/asm/split/title/CScFader__Skip.s.o \
    $(BUILD_DIR)/ref/asm/split/title/TiPlayVolSE.s.o \
    $(BUILD_DIR)/ref/asm/sections/title/title.data.s.o \
    $(BUILD_DIR)/ref/asm/sections/title/title.bss.s.o \
