#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", memclr);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaGetChan);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaReset);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaDebug);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaPutEnv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaGetEnv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaPutStallAddr);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaSend);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaSendN);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaSendI);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaRecv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaRecvN);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaRecvI);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaSendM);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaSync);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaWatch);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaSyncN);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaLastSyncTime);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaPause);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaRestart);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libdma", sceDmaCallback);
