#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsResetGraph);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsGetGParam);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsResetPath);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetDefDispEnv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsPutDispEnv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGszbufaddr);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetDefDrawEnv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetDefClear);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsPutDrawEnv);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetDefDBuff);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSwapDBuff);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSyncV);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSyncPath);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetDefLoadImage);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetDefStoreImage);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsExecLoadImage);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsExecStoreImage);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSyncVCallback);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libgraph", sceGsSetHalfOffset);
