#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcInit);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", _lmcGetClientPtr);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcChangeThreadPriority);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcGetSlotMax);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcOpen);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcMkdir);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcClose);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcSeek);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", mceIntrReadFixAlign);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcRead);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcWrite);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcSync);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", mceGetInfoApdx);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcGetInfo);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcGetDir);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", mceStorePwd);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcChdir);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcFormat);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcDelete);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcFlush);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcSetFileInfo);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcRename);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcUnformat);
INCLUDE_ASM("asm/nonmatchings/lib/sce/libmc", sceMcGetEntSpace);
