.include "macro.inc"

.include "macro.inc"

.section .sdata, "wa"

/* Generated by spimdisasm 1.42.4 */

glabel sin_table_num
    /* 1A1F80 002A1E80 00008044 */ .word 0x44800000

glabel sin_table_unit_1
    /* 1A1F84 002A1E84 83F92243 */ .word 0x4322F983

glabel LanguageCode
    /* 1A1F88 002A1E88 01000000 */ .word 0x00000001

