.include "macro.inc"

.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.4 */

glabel __bss_start
    /* 002A3709 */ .space 0x77

glabel _args
    /* 002A3780 */ .space 0x180

glabel my_thid
    /* 002A3900 */ .space 0x08

glabel my_th_info
    /* 002A3908 */ .space 0x30

glabel cb_tp
    /* 002A3938 */ .space 0x48

glabel ncmdrdata
    /* 002A3980 */ .space 0x60

glabel icmdcd
    /* 002A39E0 */ .space 0x28

glabel func_num
    /* 002A3A08 */ .space 0x38

glabel icmdrdata
    /* 002A3A40 */ .space 0x40

glabel _sf_data
    /* 002A3A80 */ .space 0x140

glabel sfrdata
    /* 002A3BC0 */ .space 0x40

glabel cdrd
    /* 002A3C00 */ .space 0x28

glabel cdrdsf
    /* 002A3C28 */ .space 0x58

glabel _rd_intr_data
    /* 002A3C80 */ .space 0xC0

glabel _rd_data
    /* 002A3D40 */ .space 0x40

glabel _rdc_data
    /* 002A3D80 */ .space 0x340

glabel _Read_cur_pos
    /* 002A40C0 */ .space 0x10

glabel _gt_data
    /* 002A40D0 */ .space 0x30

glabel tocbf
    /* 002A4100 */ .space 0x810

glabel _lbn_prm
    /* 002A4910 */ .space 0x30

glabel scmdrdata
    /* 002A4940 */ .space 0x420

glabel cdrc
    /* 002A4D60 */ .space 0x28

glabel cdit
    /* 002A4D88 */ .space 0x28

glabel cddr
    /* 002A4DB0 */ .space 0x28

glabel cddr1
    /* 002A4DD8 */ .space 0x28

glabel cdbk
    /* 002A4E00 */ .space 0x28

glabel cddr2
    /* 002A4E28 */ .space 0x28

glabel _i_mode
    /* 002A4E50 */ .space 0x10

glabel _dr_mode
    /* 002A4E60 */ .space 0x10

glabel _mmode
    /* 002A4E70 */ .space 0x10

glabel _prio
    /* 002A4E80 */ .space 0x10

glabel _acn_data
    /* 002A4E90 */ .space 0x90

glabel TrayReq
    /* 002A4F20 */ .space 0x10

glabel _rs_data
    /* 002A4F30 */ .space 0x18

glabel eh_39
    /* 002A4F48 */ .space 0x10

glabel initialized_40
    /* 002A4F58 */ .space 0x08

glabel top_elt_41
    /* 002A4F60 */ .space 0x08

glabel thenan_3
    /* 002A4F68 */ .space 0x18

glabel thenan_3__2
    /* 002A4F80 */ .space 0x10

glabel objects
    /* 002A4F90 */ .space 0x10

glabel stack_6
    /* 002A4FA0 */ .space 0x400

glabel topArg
    /* 002A53A0 */ .space 0x08

glabel topSema
    /* 002A53A8 */ .space 0x08

glabel userarea
    /* 002A53B0 */ .space 0x50

glabel q_3
    /* 002A5400 */ .space 0x110

glabel tinfo
    /* 002A5510 */ .space 0x18

glabel D_002A5528
    /* 002A5528 */ .space 0x18

glabel wbuf
    /* 002A5540 */ .space 0x140

glabel rbuf
    /* 002A5680 */ .space 0x140

glabel linebuf
    /* 002A57C0 */ .space 0x80

glabel _pckt_buffer
    /* 002A5840 */ .space 0x80

glabel _send_buffer
    /* 002A58C0 */ .space 0x40

glabel _csdata
    /* 002A5900 */ .space 0x14

glabel sif0_handleid
    /* 002A5914 */ .space 0x04

glabel _data_table
    /* 002A5918 */ .space 0x08

glabel D_002A5920
    /* 002A5920 */ .space 0x04

glabel D_002A5924
    /* 002A5924 */ .space 0x08

glabel D_002A592C
    /* 002A592C */ .space 0x14

glabel _sys_buffer
    /* 002A5940 */ .space 0x100

glabel soft_reg
    /* 002A5A40 */ .space 0x80

glabel _packet_buffer
    /* 002A5AC0 */ .space 0x800

glabel _free_buffer
    /* 002A62C0 */ .space 0x800

glabel _free_buffer2
    /* 002A6AC0 */ .space 0x800

glabel _data_table__2
    /* 002A72C0 */ .space 0x40

glabel _send_data
    /* 002A7300 */ .space 0xC40

glabel _rcv_data
    /* 002A7F40 */ .space 0x40

glabel _intr_data
    /* 002A7F80 */ .space 0x90

glabel _iob
    /* 002A8010 */ .space 0x100

glabel _cd
    /* 002A8110 */ .space 0x28

glabel _fsversion
    /* 002A8138 */ .space 0x08

glabel _riu
    /* 002A8140 */ .space 0x40

glabel cd
    /* 002A8180 */ .space 0x40

glabel rdata
    /* 002A81C0 */ .space 0x40

glabel _aih_data
    /* 002A8200 */ .space 0x40

glabel _fih_data
    /* 002A8240 */ .space 0x40

glabel _lih_data
    /* 002A8280 */ .space 0x100

glabel _senddata
    /* 002A8380 */ .space 0x08

glabel D_002A8388
    /* 002A8388 */ .space 0x1F8

glabel cd__2
    /* 002A8580 */ .space 0x28

glabel _lfversion
    /* 002A85A8 */ .space 0x18

glabel rdata__2
    /* 002A85C0 */ .space 0x80

glabel mcClientID
    /* 002A8640 */ .space 0x28

glabel typeAddr
    /* 002A8668 */ .space 0x04

glabel freeAddr
    /* 002A866C */ .space 0x04

glabel formAddr
    /* 002A8670 */ .space 0x10

glabel buffFileInfo
    /* 002A8680 */ .space 0x20

glabel D_002A86A0
    /* 002A86A0 */ .space 0x20

glabel sifParamOrd
    /* 002A86C0 */ .space 0x30

glabel sifParamFname
    /* 002A86F0 */ .space 0x14

glabel D_002A8704
    /* 002A8704 */ .space 0x43C

glabel sifParamNext
    /* 002A8B40 */ .space 0xC0

glabel currentDir
    /* 002A8C00 */ .space 0xBF0

glabel _gp
    /* 002A97F0 */ .space 0x410

glabel retval
    /* 002A9C00 */ .space 0x40

glabel padsif
    /* 002A9C40 */ .space 0x50

glabel PadInfo
    /* 002A9C90 */ .space 0xF0

glabel dma_iop_data
    /* 002A9D80 */ .space 0x80

glabel buffer
    /* 002A9E00 */ .space 0x80

glabel transData_6
    /* 002A9E80 */ .space 0x10

glabel stack
    /* 002A9E90 */ .space 0x130

glabel sbuff
    /* 002A9FC0 */ .space 0x40

glabel __global_destructor_chain
    /* 002AA000 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel D_002AA004
    /* 002AA004 */ .space 0x0C

glabel SinTable
    /* 002AA010 */ .space 0x1000

glabel VisualData
    /* 002AB010 */ .space 0x10

glabel MotionData
    /* 002AB020 */ .space 0x10

