.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel LimmitZone__14CDngMessageManFv
    /* 0B5C90 001B5B90 789C838F */  lw         $3, -0x6388($28)
    /* 0B5C94 001B5B94 0100013C */  lui        $1, (0x10000 >> 16)
    /* 0B5C98 001B5B98 21086100 */  addu       $1, $3, $1
    /* 0B5C9C 001B5B9C 108B238C */  lw         $3, -0x74F0($1)
    /* 0B5CA0 001B5BA0 0A006004 */  bltz       $3, .L001B5BCC
    /* 0B5CA4 001B5BA4 00000000 */   nop
    /* 0B5CA8 001B5BA8 06006128 */  slti       $1, $3, 0x6
    /* 0B5CAC 001B5BAC 07002010 */  beqz       $1, .L001B5BCC
    /* 0B5CB0 001B5BB0 00000000 */   nop
    /* 0B5CB4 001B5BB4 0B000324 */  addiu      $3, $0, 0xB
    /* 0B5CB8 001B5BB8 240083AC */  sw         $3, 0x24($4)
    /* 0B5CBC 001B5BBC 789C838F */  lw         $3, -0x6388($28)
    /* 0B5CC0 001B5BC0 04006380 */  lb         $3, 0x4($3)
    /* 0B5CC4 001B5BC4 32006324 */  addiu      $3, $3, 0x32
    /* 0B5CC8 001B5BC8 0C0083AC */  sw         $3, 0xC($4)
  .L001B5BCC:
    /* 0B5CCC 001B5BCC 789C838F */  lw         $3, -0x6388($28)
    /* 0B5CD0 001B5BD0 0100013C */  lui        $1, (0x10000 >> 16)
    /* 0B5CD4 001B5BD4 21086100 */  addu       $1, $3, $1
    /* 0B5CD8 001B5BD8 108B258C */  lw         $5, -0x74F0($1)
    /* 0B5CDC 001B5BDC 0A000324 */  addiu      $3, $0, 0xA
    /* 0B5CE0 001B5BE0 0300A314 */  bne        $5, $3, .L001B5BF0
    /* 0B5CE4 001B5BE4 00000000 */   nop
    /* 0B5CE8 001B5BE8 0D000324 */  addiu      $3, $0, 0xD
    /* 0B5CEC 001B5BEC 240083AC */  sw         $3, 0x24($4)
  .L001B5BF0:
    /* 0B5CF0 001B5BF0 789C838F */  lw         $3, -0x6388($28)
    /* 0B5CF4 001B5BF4 0100013C */  lui        $1, (0x10000 >> 16)
    /* 0B5CF8 001B5BF8 21086100 */  addu       $1, $3, $1
    /* 0B5CFC 001B5BFC 108B258C */  lw         $5, -0x74F0($1)
    /* 0B5D00 001B5C00 0B000324 */  addiu      $3, $0, 0xB
    /* 0B5D04 001B5C04 0300A314 */  bne        $5, $3, .L001B5C14
    /* 0B5D08 001B5C08 00000000 */   nop
    /* 0B5D0C 001B5C0C 0E000324 */  addiu      $3, $0, 0xE
    /* 0B5D10 001B5C10 240083AC */  sw         $3, 0x24($4)
  .L001B5C14:
    /* 0B5D14 001B5C14 F0000324 */  addiu      $3, $0, 0xF0
    /* 0B5D18 001B5C18 040083AC */  sw         $3, 0x4($4)
    /* 0B5D1C 001B5C1C 1C0080AC */  sw         $0, 0x1C($4)
    /* 0B5D20 001B5C20 0800E003 */  jr         $31
    /* 0B5D24 001B5C24 00000000 */   nop
    /* 0B5D28 001B5C28 00000000 */  nop
    /* 0B5D2C 001B5C2C 00000000 */  nop

glabel SetStatus_Dry__14CDngMessageManFfff
    /* 0B5D30 001B5C30 808080C7 */  lwc1       $f0, -0x7F80($28)
    /* 0B5D34 001B5C34 82000C46 */  mul.s      $f2, $f0, $f12
    /* 0B5D38 001B5C38 34100E46 */  c.lt.s     $f2, $f14
    /* 0B5D3C 001B5C3C 00000000 */  nop
    /* 0B5D40 001B5C40 07000045 */  bc1f       .L001B5C60
    /* 0B5D44 001B5C44 00000000 */   nop
    /* 0B5D48 001B5C48 2400858C */  lw         $5, 0x24($4)
    /* 0B5D4C 001B5C4C AA000324 */  addiu      $3, $0, 0xAA
    /* 0B5D50 001B5C50 0300A314 */  bne        $5, $3, .L001B5C60
    /* 0B5D54 001B5C54 00000000 */   nop
    /* 0B5D58 001B5C58 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0B5D5C 001B5C5C 240083AC */  sw         $3, 0x24($4)
  .L001B5C60:
    /* 0B5D60 001B5C60 00008044 */  mtc1       $0, $f0
    /* 0B5D64 001B5C64 00000000 */  nop
    /* 0B5D68 001B5C68 34000E46 */  c.lt.s     $f0, $f14
    /* 0B5D6C 001B5C6C 00000000 */  nop
    /* 0B5D70 001B5C70 07000045 */  bc1f       .L001B5C90
    /* 0B5D74 001B5C74 00000000 */   nop
    /* 0B5D78 001B5C78 2400858C */  lw         $5, 0x24($4)
    /* 0B5D7C 001B5C7C AB000324 */  addiu      $3, $0, 0xAB
    /* 0B5D80 001B5C80 0300A314 */  bne        $5, $3, .L001B5C90
    /* 0B5D84 001B5C84 00000000 */   nop
    /* 0B5D88 001B5C88 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0B5D8C 001B5C8C 240083AC */  sw         $3, 0x24($4)
  .L001B5C90:
    /* 0B5D90 001B5C90 003F033C */  lui        $3, (0x3F000000 >> 16)
    /* 0B5D94 001B5C94 00088344 */  mtc1       $3, $f1
    /* 0B5D98 001B5C98 00000000 */  nop
    /* 0B5D9C 001B5C9C 00080D46 */  add.s      $f0, $f1, $f13
    /* 0B5DA0 001B5CA0 36100046 */  c.le.s     $f2, $f0
    /* 0B5DA4 001B5CA4 00000000 */  nop
    /* 0B5DA8 001B5CA8 0F000045 */  bc1f       .L001B5CE8
    /* 0B5DAC 001B5CAC 00000000 */   nop
    /* 0B5DB0 001B5CB0 01700146 */  sub.s      $f0, $f14, $f1
    /* 0B5DB4 001B5CB4 36100046 */  c.le.s     $f2, $f0
    /* 0B5DB8 001B5CB8 00000000 */  nop
    /* 0B5DBC 001B5CBC 0A000145 */  bc1t       .L001B5CE8
    /* 0B5DC0 001B5CC0 00000000 */   nop
    /* 0B5DC4 001B5CC4 2400858C */  lw         $5, 0x24($4)
    /* 0B5DC8 001B5CC8 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0B5DCC 001B5CCC 0600A314 */  bne        $5, $3, .L001B5CE8
    /* 0B5DD0 001B5CD0 00000000 */   nop
    /* 0B5DD4 001B5CD4 AA000324 */  addiu      $3, $0, 0xAA
    /* 0B5DD8 001B5CD8 240083AC */  sw         $3, 0x24($4)
    /* 0B5DDC 001B5CDC F0000324 */  addiu      $3, $0, 0xF0
    /* 0B5DE0 001B5CE0 040083AC */  sw         $3, 0x4($4)
    /* 0B5DE4 001B5CE4 1C0080AC */  sw         $0, 0x1C($4)
  .L001B5CE8:
    /* 0B5DE8 001B5CE8 00008044 */  mtc1       $0, $f0
    /* 0B5DEC 001B5CEC 00000000 */  nop
    /* 0B5DF0 001B5CF0 36700046 */  c.le.s     $f14, $f0
    /* 0B5DF4 001B5CF4 00000000 */  nop
    /* 0B5DF8 001B5CF8 0E000045 */  bc1f       .L001B5D34
    /* 0B5DFC 001B5CFC 00000000 */   nop
    /* 0B5E00 001B5D00 2400858C */  lw         $5, 0x24($4)
    /* 0B5E04 001B5D04 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0B5E08 001B5D08 0400A310 */  beq        $5, $3, .L001B5D1C
    /* 0B5E0C 001B5D0C 00000000 */   nop
    /* 0B5E10 001B5D10 AB000324 */  addiu      $3, $0, 0xAB
    /* 0B5E14 001B5D14 0700A314 */  bne        $5, $3, .L001B5D34
    /* 0B5E18 001B5D18 00000000 */   nop
  .L001B5D1C:
    /* 0B5E1C 001B5D1C AB000324 */  addiu      $3, $0, 0xAB
    /* 0B5E20 001B5D20 240083AC */  sw         $3, 0x24($4)
    /* 0B5E24 001B5D24 0900033C */  lui        $3, (0x9FFF6 >> 16)
    /* 0B5E28 001B5D28 F6FF6334 */  ori        $3, $3, (0x9FFF6 & 0xFFFF)
    /* 0B5E2C 001B5D2C 040083AC */  sw         $3, 0x4($4)
    /* 0B5E30 001B5D30 1C0080AC */  sw         $0, 0x1C($4)
  .L001B5D34:
    /* 0B5E34 001B5D34 0800E003 */  jr         $31
    /* 0B5E38 001B5D38 00000000 */   nop
    /* 0B5E3C 001B5D3C 00000000 */  nop

glabel SetSteevMes__14CDngMessageManFi
    /* 0B5E40 001B5D40 0400838C */  lw         $3, 0x4($4)
    /* 0B5E44 001B5D44 1000601C */  bgtz       $3, .L001B5D88
    /* 0B5E48 001B5D48 00000000 */   nop
    /* 0B5E4C 001B5D4C 2000838C */  lw         $3, 0x20($4)
    /* 0B5E50 001B5D50 2118A300 */  addu       $3, $5, $3
    /* 0B5E54 001B5D54 240083AC */  sw         $3, 0x24($4)
    /* 0B5E58 001B5D58 F0000324 */  addiu      $3, $0, 0xF0
    /* 0B5E5C 001B5D5C 040083AC */  sw         $3, 0x4($4)
    /* 0B5E60 001B5D60 01000324 */  addiu      $3, $0, 0x1
    /* 0B5E64 001B5D64 1C0083AC */  sw         $3, 0x1C($4)
    /* 0B5E68 001B5D68 2000838C */  lw         $3, 0x20($4)
    /* 0B5E6C 001B5D6C 01006324 */  addiu      $3, $3, 0x1
    /* 0B5E70 001B5D70 200083AC */  sw         $3, 0x20($4)
    /* 0B5E74 001B5D74 2000838C */  lw         $3, 0x20($4)
    /* 0B5E78 001B5D78 0A006128 */  slti       $1, $3, 0xA
    /* 0B5E7C 001B5D7C 02002014 */  bnez       $1, .L001B5D88
    /* 0B5E80 001B5D80 00000000 */   nop
    /* 0B5E84 001B5D84 200080AC */  sw         $0, 0x20($4)
  .L001B5D88:
    /* 0B5E88 001B5D88 0800E003 */  jr         $31
    /* 0B5E8C 001B5D8C 00000000 */   nop
