.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel Set__17CDungeonEventDataFP13CDungeonEvent
    /* 0CC920 001CC820 F0FFBD27 */  addiu      $29, $29, -0x10
    /* 0CC924 001CC824 0000BF7F */  sq         $31, 0x0($29)
    /* 0CC928 001CC828 0700A014 */  bnez       $5, .L001CC848
    /* 0CC92C 001CC82C 00000000 */   nop
    /* 0CC930 001CC830 2A00023C */  lui        $2, %hi("@3309")
    /* 0CC934 001CC834 90BF4424 */  addiu      $4, $2, %lo("@3309")
    /* 0CC938 001CC838 A611040C */  jal        printf
    /* 0CC93C 001CC83C 00000000 */   nop
  .L001CC840:
    /* 0CC940 001CC840 FFFF0010 */  b          .L001CC840
    /* 0CC944 001CC844 00000000 */   nop
  .L001CC848:
    /* 0CC948 001CC848 000085AC */  sw         $5, 0x0($4)
    /* 0CC94C 001CC84C 2800A38C */  lw         $3, 0x28($5)
    /* 0CC950 001CC850 300083AC */  sw         $3, 0x30($4)
    /* 0CC954 001CC854 3400A38C */  lw         $3, 0x34($5)
    /* 0CC958 001CC858 340083AC */  sw         $3, 0x34($4)
    /* 0CC95C 001CC85C 01000324 */  addiu      $3, $0, 0x1
    /* 0CC960 001CC860 380083AC */  sw         $3, 0x38($4)
    /* 0CC964 001CC864 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0CC968 001CC868 3C0083AC */  sw         $3, 0x3C($4)
    /* 0CC96C 001CC86C 0000BF7B */  lq         $31, 0x0($29)
    /* 0CC970 001CC870 1000BD27 */  addiu      $29, $29, 0x10
    /* 0CC974 001CC874 0800E003 */  jr         $31
    /* 0CC978 001CC878 00000000 */   nop
    /* 0CC97C 001CC87C 00000000 */  nop

glabel CheckSwitch__17CDungeonEventDataFv
    /* 0CC980 001CC880 0000828C */  lw         $2, 0x0($4)
    /* 0CC984 001CC884 04004014 */  bnez       $2, .L001CC898
    /* 0CC988 001CC888 00000000 */   nop
    /* 0CC98C 001CC88C 28160070 */  paddub     $2, $0, $0
    /* 0CC990 001CC890 0B000010 */  b          .L001CC8C0
    /* 0CC994 001CC894 00000000 */   nop
  .L001CC898:
    /* 0CC998 001CC898 3800828C */  lw         $2, 0x38($4)
    /* 0CC99C 001CC89C 07004010 */  beqz       $2, .L001CC8BC
    /* 0CC9A0 001CC8A0 00000000 */   nop
    /* 0CC9A4 001CC8A4 3400828C */  lw         $2, 0x34($4)
    /* 0CC9A8 001CC8A8 04004010 */  beqz       $2, .L001CC8BC
    /* 0CC9AC 001CC8AC 00000000 */   nop
    /* 0CC9B0 001CC8B0 01000224 */  addiu      $2, $0, 0x1
    /* 0CC9B4 001CC8B4 02000010 */  b          .L001CC8C0
    /* 0CC9B8 001CC8B8 00000000 */   nop
  .L001CC8BC:
    /* 0CC9BC 001CC8BC 28160070 */  paddub     $2, $0, $0
  .L001CC8C0:
    /* 0CC9C0 001CC8C0 0800E003 */  jr         $31
    /* 0CC9C4 001CC8C4 00000000 */   nop
    /* 0CC9C8 001CC8C8 00000000 */  nop
    /* 0CC9CC 001CC8CC 00000000 */  nop

glabel Stop__17CDungeonEventDataFv
    /* 0CC9D0 001CC8D0 340080AC */  sw         $0, 0x34($4)
    /* 0CC9D4 001CC8D4 0800E003 */  jr         $31
    /* 0CC9D8 001CC8D8 00000000 */   nop
    /* 0CC9DC 001CC8DC 00000000 */  nop

glabel Start__17CDungeonEventDataFv
    /* 0CC9E0 001CC8E0 01000324 */  addiu      $3, $0, 0x1
    /* 0CC9E4 001CC8E4 340083AC */  sw         $3, 0x34($4)
    /* 0CC9E8 001CC8E8 0800E003 */  jr         $31
    /* 0CC9EC 001CC8EC 00000000 */   nop

.section .rodata, "a"
.align 4

/* Generated by spimdisasm 1.42.4 */

glabel "@3309"
    /* 19C090 0029BF90 2A2A2A2A */ .word 0x2A2A2A2A
    /* 19C094 0029BF94 2A2A2A2A */ .word 0x2A2A2A2A
    /* 19C098 0029BF98 20657665 */ .word 0x65766520
    /* 19C09C 0029BF9C 6E74204E */ .word 0x4E20746E
    /* 19C0A0 0029BFA0 554C4C20 */ .word 0x204C4C55
    /* 19C0A4 0029BFA4 21210A00 */ .word 0x000A2121
    /* 19C0A8 0029BFA8 00000000 */ .word 0x00000000
    /* 19C0AC 0029BFAC 00000000 */ .word 0x00000000
