.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel SearchPartsID__16CDungeonEventManFii
    /* 0CC9F0 001CC8F0 80290500 */  sll        $5, $5, 6
    /* 0CC9F4 001CC8F4 2118A400 */  addu       $3, $5, $4
    /* 0CC9F8 001CC8F8 3C00628C */  lw         $2, 0x3C($3)
    /* 0CC9FC 001CC8FC 04004010 */  beqz       $2, .L001CC910
    /* 0CCA00 001CC900 00000000 */   nop
    /* 0CCA04 001CC904 1C00628C */  lw         $2, 0x1C($3)
    /* 0CCA08 001CC908 02000010 */  b          .L001CC914
    /* 0CCA0C 001CC90C 00000000 */   nop
  .L001CC910:
    /* 0CCA10 001CC910 FFFF0224 */  addiu      $2, $0, -0x1
  .L001CC914:
    /* 0CCA14 001CC914 0400C214 */  bne        $6, $2, .L001CC928
    /* 0CCA18 001CC918 00000000 */   nop
    /* 0CCA1C 001CC91C 21108500 */  addu       $2, $4, $5
    /* 0CCA20 001CC920 02000010 */  b          .L001CC92C
    /* 0CCA24 001CC924 00000000 */   nop
  .L001CC928:
    /* 0CCA28 001CC928 28160070 */  paddub     $2, $0, $0
  .L001CC92C:
    /* 0CCA2C 001CC92C 0800E003 */  jr         $31
    /* 0CCA30 001CC930 00000000 */   nop
    /* 0CCA34 001CC934 00000000 */  nop
    /* 0CCA38 001CC938 00000000 */  nop
    /* 0CCA3C 001CC93C 00000000 */  nop

glabel SearchSlot__16CDungeonEventManFv
    /* 0CCA40 001CC940 282E0070 */  paddub     $5, $0, $0
    /* 0CCA44 001CC944 09000010 */  b          .L001CC96C
    /* 0CCA48 001CC948 00000000 */   nop
  .L001CC94C:
    /* 0CCA4C 001CC94C 80110500 */  sll        $2, $5, 6
    /* 0CCA50 001CC950 21104400 */  addu       $2, $2, $4
    /* 0CCA54 001CC954 3C00438C */  lw         $3, 0x3C($2)
    /* 0CCA58 001CC958 03006014 */  bnez       $3, .L001CC968
    /* 0CCA5C 001CC95C 00000000 */   nop
    /* 0CCA60 001CC960 06000010 */  b          .L001CC97C
    /* 0CCA64 001CC964 00000000 */   nop
  .L001CC968:
    /* 0CCA68 001CC968 0100A524 */  addiu      $5, $5, 0x1
  .L001CC96C:
    /* 0CCA6C 001CC96C 4000A228 */  slti       $2, $5, 0x40
    /* 0CCA70 001CC970 F6FF4014 */  bnez       $2, .L001CC94C
    /* 0CCA74 001CC974 00000000 */   nop
    /* 0CCA78 001CC978 28160070 */  paddub     $2, $0, $0
  .L001CC97C:
    /* 0CCA7C 001CC97C 0800E003 */  jr         $31
    /* 0CCA80 001CC980 00000000 */   nop
    /* 0CCA84 001CC984 00000000 */  nop
    /* 0CCA88 001CC988 00000000 */  nop
    /* 0CCA8C 001CC98C 00000000 */  nop

glabel SearchDataSwitch__16CDungeonEventManFii
    /* 0CCA90 001CC990 A0FFBD27 */  addiu      $29, $29, -0x60
    /* 0CCA94 001CC994 5000BF7F */  sq         $31, 0x50($29)
    /* 0CCA98 001CC998 4000B47F */  sq         $20, 0x40($29)
    /* 0CCA9C 001CC99C 3000B37F */  sq         $19, 0x30($29)
    /* 0CCAA0 001CC9A0 2000B27F */  sq         $18, 0x20($29)
    /* 0CCAA4 001CC9A4 1000B17F */  sq         $17, 0x10($29)
    /* 0CCAA8 001CC9A8 0000B07F */  sq         $16, 0x0($29)
    /* 0CCAAC 001CC9AC 289E8070 */  paddub     $19, $4, $0
    /* 0CCAB0 001CC9B0 2896A070 */  paddub     $18, $5, $0
    /* 0CCAB4 001CC9B4 288EC070 */  paddub     $17, $6, $0
    /* 0CCAB8 001CC9B8 28860070 */  paddub     $16, $0, $0
    /* 0CCABC 001CC9BC 1C000010 */  b          .L001CCA30
    /* 0CCAC0 001CC9C0 00000000 */   nop
  .L001CC9C4:
    /* 0CCAC4 001CC9C4 80A11000 */  sll        $20, $16, 6
    /* 0CCAC8 001CC9C8 21189302 */  addu       $3, $20, $19
    /* 0CCACC 001CC9CC 0010648C */  lw         $4, 0x1000($3)
    /* 0CCAD0 001CC9D0 04008010 */  beqz       $4, .L001CC9E4
    /* 0CCAD4 001CC9D4 00000000 */   nop
    /* 0CCAD8 001CC9D8 3810638C */  lw         $3, 0x1038($3)
    /* 0CCADC 001CC9DC 02000010 */  b          .L001CC9E8
    /* 0CCAE0 001CC9E0 00000000 */   nop
  .L001CC9E4:
    /* 0CCAE4 001CC9E4 281E0070 */  paddub     $3, $0, $0
  .L001CC9E8:
    /* 0CCAE8 001CC9E8 10006010 */  beqz       $3, .L001CCA2C
    /* 0CCAEC 001CC9EC 00000000 */   nop
    /* 0CCAF0 001CC9F0 2000838C */  lw         $3, 0x20($4)
    /* 0CCAF4 001CC9F4 0D004316 */  bne        $18, $3, .L001CCA2C
    /* 0CCAF8 001CC9F8 00000000 */   nop
    /* 0CCAFC 001CC9FC 05002012 */  beqz       $17, .L001CCA14
    /* 0CCB00 001CCA00 00000000 */   nop
    /* 0CCB04 001CCA04 21107402 */  addu       $2, $19, $20
    /* 0CCB08 001CCA08 00104424 */  addiu      $4, $2, 0x1000
    /* 0CCB0C 001CCA0C 3832070C */  jal        Start__17CDungeonEventDataFv
    /* 0CCB10 001CCA10 00000000 */   nop
  .L001CCA14:
    /* 0CCB14 001CCA14 05002016 */  bnez       $17, .L001CCA2C
    /* 0CCB18 001CCA18 00000000 */   nop
    /* 0CCB1C 001CCA1C 21107402 */  addu       $2, $19, $20
    /* 0CCB20 001CCA20 00104424 */  addiu      $4, $2, 0x1000
    /* 0CCB24 001CCA24 3432070C */  jal        Stop__17CDungeonEventDataFv
    /* 0CCB28 001CCA28 00000000 */   nop
  .L001CCA2C:
    /* 0CCB2C 001CCA2C 01001026 */  addiu      $16, $16, 0x1
  .L001CCA30:
    /* 0CCB30 001CCA30 6000032A */  slti       $3, $16, 0x60
    /* 0CCB34 001CCA34 E3FF6014 */  bnez       $3, .L001CC9C4
    /* 0CCB38 001CCA38 00000000 */   nop
    /* 0CCB3C 001CCA3C 5000BF7B */  lq         $31, 0x50($29)
    /* 0CCB40 001CCA40 4000B47B */  lq         $20, 0x40($29)
    /* 0CCB44 001CCA44 3000B37B */  lq         $19, 0x30($29)
    /* 0CCB48 001CCA48 2000B27B */  lq         $18, 0x20($29)
    /* 0CCB4C 001CCA4C 1000B17B */  lq         $17, 0x10($29)
    /* 0CCB50 001CCA50 0000B07B */  lq         $16, 0x0($29)
    /* 0CCB54 001CCA54 6000BD27 */  addiu      $29, $29, 0x60
    /* 0CCB58 001CCA58 0800E003 */  jr         $31
    /* 0CCB5C 001CCA5C 00000000 */   nop

glabel SearchItemEventHold__16CDungeonEventManFi
    /* 0CCB60 001CCA60 28360070 */  paddub     $6, $0, $0
    /* 0CCB64 001CCA64 12000010 */  b          .L001CCAB0
    /* 0CCB68 001CCA68 00000000 */   nop
  .L001CCA6C:
    /* 0CCB6C 001CCA6C 80390600 */  sll        $7, $6, 6
    /* 0CCB70 001CCA70 2118E400 */  addu       $3, $7, $4
    /* 0CCB74 001CCA74 0010688C */  lw         $8, 0x1000($3)
    /* 0CCB78 001CCA78 04000011 */  beqz       $8, .L001CCA8C
    /* 0CCB7C 001CCA7C 00000000 */   nop
    /* 0CCB80 001CCA80 3810638C */  lw         $3, 0x1038($3)
    /* 0CCB84 001CCA84 02000010 */  b          .L001CCA90
    /* 0CCB88 001CCA88 00000000 */   nop
  .L001CCA8C:
    /* 0CCB8C 001CCA8C 281E0070 */  paddub     $3, $0, $0
  .L001CCA90:
    /* 0CCB90 001CCA90 06006010 */  beqz       $3, .L001CCAAC
    /* 0CCB94 001CCA94 00000000 */   nop
    /* 0CCB98 001CCA98 2000038D */  lw         $3, 0x20($8)
    /* 0CCB9C 001CCA9C 0300A314 */  bne        $5, $3, .L001CCAAC
    /* 0CCBA0 001CCAA0 00000000 */   nop
    /* 0CCBA4 001CCAA4 2118E400 */  addu       $3, $7, $4
    /* 0CCBA8 001CCAA8 301060AC */  sw         $0, 0x1030($3)
  .L001CCAAC:
    /* 0CCBAC 001CCAAC 0100C624 */  addiu      $6, $6, 0x1
  .L001CCAB0:
    /* 0CCBB0 001CCAB0 6000C328 */  slti       $3, $6, 0x60
    /* 0CCBB4 001CCAB4 EDFF6014 */  bnez       $3, .L001CCA6C
    /* 0CCBB8 001CCAB8 00000000 */   nop
    /* 0CCBBC 001CCABC 0800E003 */  jr         $31
    /* 0CCBC0 001CCAC0 00000000 */   nop
    /* 0CCBC4 001CCAC4 00000000 */  nop
    /* 0CCBC8 001CCAC8 00000000 */  nop
    /* 0CCBCC 001CCACC 00000000 */  nop

glabel GetDataNum__16CDungeonEventManFv
    /* 0CCBD0 001CCAD0 28160070 */  paddub     $2, $0, $0
    /* 0CCBD4 001CCAD4 28360070 */  paddub     $6, $0, $0
    /* 0CCBD8 001CCAD8 0E000010 */  b          .L001CCB14
    /* 0CCBDC 001CCADC 00000000 */   nop
  .L001CCAE0:
    /* 0CCBE0 001CCAE0 80190600 */  sll        $3, $6, 6
    /* 0CCBE4 001CCAE4 21286400 */  addu       $5, $3, $4
    /* 0CCBE8 001CCAE8 0010A38C */  lw         $3, 0x1000($5)
    /* 0CCBEC 001CCAEC 04006010 */  beqz       $3, .L001CCB00
    /* 0CCBF0 001CCAF0 00000000 */   nop
    /* 0CCBF4 001CCAF4 3810A38C */  lw         $3, 0x1038($5)
    /* 0CCBF8 001CCAF8 02000010 */  b          .L001CCB04
    /* 0CCBFC 001CCAFC 00000000 */   nop
  .L001CCB00:
    /* 0CCC00 001CCB00 281E0070 */  paddub     $3, $0, $0
  .L001CCB04:
    /* 0CCC04 001CCB04 02006014 */  bnez       $3, .L001CCB10
    /* 0CCC08 001CCB08 00000000 */   nop
    /* 0CCC0C 001CCB0C 01004224 */  addiu      $2, $2, 0x1
  .L001CCB10:
    /* 0CCC10 001CCB10 0100C624 */  addiu      $6, $6, 0x1
  .L001CCB14:
    /* 0CCC14 001CCB14 6000C328 */  slti       $3, $6, 0x60
    /* 0CCC18 001CCB18 F1FF6014 */  bnez       $3, .L001CCAE0
    /* 0CCC1C 001CCB1C 00000000 */   nop
    /* 0CCC20 001CCB20 0800E003 */  jr         $31
    /* 0CCC24 001CCB24 00000000 */   nop
    /* 0CCC28 001CCB28 00000000 */  nop
    /* 0CCC2C 001CCB2C 00000000 */  nop

glabel SearchDataSlot__16CDungeonEventManFv
    /* 0CCC30 001CCB30 282E0070 */  paddub     $5, $0, $0
    /* 0CCC34 001CCB34 11000010 */  b          .L001CCB7C
    /* 0CCC38 001CCB38 00000000 */   nop
  .L001CCB3C:
    /* 0CCC3C 001CCB3C 80310500 */  sll        $6, $5, 6
    /* 0CCC40 001CCB40 2118C400 */  addu       $3, $6, $4
    /* 0CCC44 001CCB44 0010628C */  lw         $2, 0x1000($3)
    /* 0CCC48 001CCB48 04004010 */  beqz       $2, .L001CCB5C
    /* 0CCC4C 001CCB4C 00000000 */   nop
    /* 0CCC50 001CCB50 3810628C */  lw         $2, 0x1038($3)
    /* 0CCC54 001CCB54 02000010 */  b          .L001CCB60
    /* 0CCC58 001CCB58 00000000 */   nop
  .L001CCB5C:
    /* 0CCC5C 001CCB5C 28160070 */  paddub     $2, $0, $0
  .L001CCB60:
    /* 0CCC60 001CCB60 05004014 */  bnez       $2, .L001CCB78
    /* 0CCC64 001CCB64 00000000 */   nop
    /* 0CCC68 001CCB68 21108600 */  addu       $2, $4, $6
    /* 0CCC6C 001CCB6C 00104224 */  addiu      $2, $2, 0x1000
    /* 0CCC70 001CCB70 06000010 */  b          .L001CCB8C
    /* 0CCC74 001CCB74 00000000 */   nop
  .L001CCB78:
    /* 0CCC78 001CCB78 0100A524 */  addiu      $5, $5, 0x1
  .L001CCB7C:
    /* 0CCC7C 001CCB7C 6000A228 */  slti       $2, $5, 0x60
    /* 0CCC80 001CCB80 EEFF4014 */  bnez       $2, .L001CCB3C
    /* 0CCC84 001CCB84 00000000 */   nop
    /* 0CCC88 001CCB88 28160070 */  paddub     $2, $0, $0
  .L001CCB8C:
    /* 0CCC8C 001CCB8C 0800E003 */  jr         $31
    /* 0CCC90 001CCB90 00000000 */   nop
    /* 0CCC94 001CCB94 00000000 */  nop
    /* 0CCC98 001CCB98 00000000 */  nop
    /* 0CCC9C 001CCB9C 00000000 */  nop

glabel CheckCollisionDataHit__16CDungeonEventManFi
    /* 0CCCA0 001CCBA0 60FFBD27 */  addiu      $29, $29, -0xA0
    /* 0CCCA4 001CCBA4 8000BF7F */  sq         $31, 0x80($29)
    /* 0CCCA8 001CCBA8 7000B67F */  sq         $22, 0x70($29)
    /* 0CCCAC 001CCBAC 6000B57F */  sq         $21, 0x60($29)
    /* 0CCCB0 001CCBB0 5000B47F */  sq         $20, 0x50($29)
    /* 0CCCB4 001CCBB4 4000B37F */  sq         $19, 0x40($29)
    /* 0CCCB8 001CCBB8 3000B27F */  sq         $18, 0x30($29)
    /* 0CCCBC 001CCBBC 2000B17F */  sq         $17, 0x20($29)
    /* 0CCCC0 001CCBC0 1000B07F */  sq         $16, 0x10($29)
    /* 0CCCC4 001CCBC4 0000B4E7 */  swc1       $f20, 0x0($29)
    /* 0CCCC8 001CCBC8 28AE8070 */  paddub     $21, $4, $0
    /* 0CCCCC 001CCBCC 80990500 */  sll        $19, $5, 6
    /* 0CCCD0 001CCBD0 21106402 */  addu       $2, $19, $4
    /* 0CCCD4 001CCBD4 00105624 */  addiu      $22, $2, 0x1000
    /* 0CCCD8 001CCBD8 0010428C */  lw         $2, 0x1000($2)
    /* 0CCCDC 001CCBDC 2C00518C */  lw         $17, 0x2C($2)
    /* 0CCCE0 001CCBE0 3000528C */  lw         $18, 0x30($2)
    /* 0CCCE4 001CCBE4 FFFF0224 */  addiu      $2, $0, -0x1
    /* 0CCCE8 001CCBE8 2C002212 */  beq        $17, $2, .L001CCC9C
    /* 0CCCEC 001CCBEC 00000000 */   nop
    /* 0CCCF0 001CCBF0 28860070 */  paddub     $16, $0, $0
    /* 0CCCF4 001CCBF4 26000010 */  b          .L001CCC90
    /* 0CCCF8 001CCBF8 00000000 */   nop
  .L001CCBFC:
    /* 0CCCFC 001CCBFC F09D848F */  lw         $4, -0x6210($28)
    /* 0CCD00 001CCC00 80181000 */  sll        $3, $16, 2
    /* 0CCD04 001CCC04 21106400 */  addu       $2, $3, $4
    /* 0CCD08 001CCC08 003C428C */  lw         $2, 0x3C00($2)
    /* 0CCD0C 001CCC0C 1F004010 */  beqz       $2, .L001CCC8C
    /* 0CCD10 001CCC10 00000000 */   nop
    /* 0CCD14 001CCC14 21107000 */  addu       $2, $3, $16
    /* 0CCD18 001CCC18 40290200 */  sll        $5, $2, 5
    /* 0CCD1C 001CCC1C 2118A400 */  addu       $3, $5, $4
    /* 0CCD20 001CCC20 5800628C */  lw         $2, 0x58($3)
    /* 0CCD24 001CCC24 19002216 */  bne        $17, $2, .L001CCC8C
    /* 0CCD28 001CCC28 00000000 */   nop
    /* 0CCD2C 001CCC2C FFFF0224 */  addiu      $2, $0, -0x1
    /* 0CCD30 001CCC30 04004212 */  beq        $18, $2, .L001CCC44
    /* 0CCD34 001CCC34 00000000 */   nop
    /* 0CCD38 001CCC38 6000628C */  lw         $2, 0x60($3)
    /* 0CCD3C 001CCC3C 13004216 */  bne        $18, $2, .L001CCC8C
    /* 0CCD40 001CCC40 00000000 */   nop
  .L001CCC44:
    /* 0CCD44 001CCC44 21288500 */  addu       $5, $4, $5
    /* 0CCD48 001CCC48 9000A427 */  addiu      $4, $29, 0x90
    /* 0CCD4C 001CCC4C 0C86040C */  jal        sceVu0CopyVector
    /* 0CCD50 001CCC50 00000000 */   nop
    /* 0CCD54 001CCC54 0000C28E */  lw         $2, 0x0($22)
    /* 0CCD58 001CCC58 180054C4 */  lwc1       $f20, 0x18($2)
    /* 0CCD5C 001CCC5C 21A0B302 */  addu       $20, $21, $19
    /* 0CCD60 001CCC60 9000A427 */  addiu      $4, $29, 0x90
    /* 0CCD64 001CCC64 10108526 */  addiu      $5, $20, 0x1010
    /* 0CCD68 001CCC68 648D040C */  jal        DistVector__FPfPf
    /* 0CCD6C 001CCC6C 00000000 */   nop
    /* 0CCD70 001CCC70 36001446 */  c.le.s     $f0, $f20
    /* 0CCD74 001CCC74 00000000 */  nop
    /* 0CCD78 001CCC78 04000045 */  bc1f       .L001CCC8C
    /* 0CCD7C 001CCC7C 00000000 */   nop
    /* 0CCD80 001CCC80 00108226 */  addiu      $2, $20, 0x1000
    /* 0CCD84 001CCC84 06000010 */  b          .L001CCCA0
    /* 0CCD88 001CCC88 00000000 */   nop
  .L001CCC8C:
    /* 0CCD8C 001CCC8C 01001026 */  addiu      $16, $16, 0x1
  .L001CCC90:
    /* 0CCD90 001CCC90 6000022A */  slti       $2, $16, 0x60
    /* 0CCD94 001CCC94 D9FF4014 */  bnez       $2, .L001CCBFC
    /* 0CCD98 001CCC98 00000000 */   nop
  .L001CCC9C:
    /* 0CCD9C 001CCC9C 28160070 */  paddub     $2, $0, $0
  .L001CCCA0:
    /* 0CCDA0 001CCCA0 8000BF7B */  lq         $31, 0x80($29)
    /* 0CCDA4 001CCCA4 7000B67B */  lq         $22, 0x70($29)
    /* 0CCDA8 001CCCA8 6000B57B */  lq         $21, 0x60($29)
    /* 0CCDAC 001CCCAC 5000B47B */  lq         $20, 0x50($29)
    /* 0CCDB0 001CCCB0 4000B37B */  lq         $19, 0x40($29)
    /* 0CCDB4 001CCCB4 3000B27B */  lq         $18, 0x30($29)
    /* 0CCDB8 001CCCB8 2000B17B */  lq         $17, 0x20($29)
    /* 0CCDBC 001CCCBC 1000B07B */  lq         $16, 0x10($29)
    /* 0CCDC0 001CCCC0 0000B4C7 */  lwc1       $f20, 0x0($29)
    /* 0CCDC4 001CCCC4 A000BD27 */  addiu      $29, $29, 0xA0
    /* 0CCDC8 001CCCC8 0800E003 */  jr         $31
    /* 0CCDCC 001CCCCC 00000000 */   nop

glabel SearchDataSlotPos__16CDungeonEventManFPf
    /* 0CCDD0 001CCCD0 80FFBD27 */  addiu      $29, $29, -0x80
    /* 0CCDD4 001CCCD4 7000BF7F */  sq         $31, 0x70($29)
    /* 0CCDD8 001CCCD8 6000B57F */  sq         $21, 0x60($29)
    /* 0CCDDC 001CCCDC 5000B47F */  sq         $20, 0x50($29)
    /* 0CCDE0 001CCCE0 4000B37F */  sq         $19, 0x40($29)
    /* 0CCDE4 001CCCE4 3000B27F */  sq         $18, 0x30($29)
    /* 0CCDE8 001CCCE8 2000B17F */  sq         $17, 0x20($29)
    /* 0CCDEC 001CCCEC 1000B07F */  sq         $16, 0x10($29)
    /* 0CCDF0 001CCCF0 0000B4E7 */  swc1       $f20, 0x0($29)
    /* 0CCDF4 001CCCF4 289E8070 */  paddub     $19, $4, $0
    /* 0CCDF8 001CCCF8 2896A070 */  paddub     $18, $5, $0
    /* 0CCDFC 001CCCFC 28860070 */  paddub     $16, $0, $0
    /* 0CCE00 001CCD00 26000010 */  b          .L001CCD9C
    /* 0CCE04 001CCD04 00000000 */   nop
  .L001CCD08:
    /* 0CCE08 001CCD08 80A11000 */  sll        $20, $16, 6
    /* 0CCE0C 001CCD0C 21A87402 */  addu       $21, $19, $20
    /* 0CCE10 001CCD10 0010B126 */  addiu      $17, $21, 0x1000
    /* 0CCE14 001CCD14 28262072 */  paddub     $4, $17, $0
    /* 0CCE18 001CCD18 2032070C */  jal        CheckSwitch__17CDungeonEventDataFv
    /* 0CCE1C 001CCD1C 00000000 */   nop
    /* 0CCE20 001CCD20 1D004010 */  beqz       $2, .L001CCD98
    /* 0CCE24 001CCD24 00000000 */   nop
    /* 0CCE28 001CCD28 2816A072 */  paddub     $2, $21, $0
    /* 0CCE2C 001CCD2C 28A62072 */  paddub     $20, $17, $0
    /* 0CCE30 001CCD30 0010428C */  lw         $2, 0x1000($2)
    /* 0CCE34 001CCD34 180054C4 */  lwc1       $f20, 0x18($2)
    /* 0CCE38 001CCD38 1010A426 */  addiu      $4, $21, 0x1010
    /* 0CCE3C 001CCD3C 282E4072 */  paddub     $5, $18, $0
    /* 0CCE40 001CCD40 648D040C */  jal        DistVector__FPfPf
    /* 0CCE44 001CCD44 00000000 */   nop
    /* 0CCE48 001CCD48 36001446 */  c.le.s     $f0, $f20
    /* 0CCE4C 001CCD4C 00000000 */  nop
    /* 0CCE50 001CCD50 09000045 */  bc1f       .L001CCD78
    /* 0CCE54 001CCD54 00000000 */   nop
    /* 0CCE58 001CCD58 0000828E */  lw         $2, 0x0($20)
    /* 0CCE5C 001CCD5C 2C00438C */  lw         $3, 0x2C($2)
    /* 0CCE60 001CCD60 FFFF0224 */  addiu      $2, $0, -0x1
    /* 0CCE64 001CCD64 04006214 */  bne        $3, $2, .L001CCD78
    /* 0CCE68 001CCD68 00000000 */   nop
    /* 0CCE6C 001CCD6C 28162072 */  paddub     $2, $17, $0
    /* 0CCE70 001CCD70 0E000010 */  b          .L001CCDAC
    /* 0CCE74 001CCD74 00000000 */   nop
  .L001CCD78:
    /* 0CCE78 001CCD78 28266072 */  paddub     $4, $19, $0
    /* 0CCE7C 001CCD7C 282E0072 */  paddub     $5, $16, $0
    /* 0CCE80 001CCD80 E832070C */  jal        CheckCollisionDataHit__16CDungeonEventManFi
    /* 0CCE84 001CCD84 00000000 */   nop
    /* 0CCE88 001CCD88 03004010 */  beqz       $2, .L001CCD98
    /* 0CCE8C 001CCD8C 00000000 */   nop
    /* 0CCE90 001CCD90 06000010 */  b          .L001CCDAC
    /* 0CCE94 001CCD94 00000000 */   nop
  .L001CCD98:
    /* 0CCE98 001CCD98 01001026 */  addiu      $16, $16, 0x1
  .L001CCD9C:
    /* 0CCE9C 001CCD9C 6000022A */  slti       $2, $16, 0x60
    /* 0CCEA0 001CCDA0 D9FF4014 */  bnez       $2, .L001CCD08
    /* 0CCEA4 001CCDA4 00000000 */   nop
    /* 0CCEA8 001CCDA8 28160070 */  paddub     $2, $0, $0
  .L001CCDAC:
    /* 0CCEAC 001CCDAC 7000BF7B */  lq         $31, 0x70($29)
    /* 0CCEB0 001CCDB0 6000B57B */  lq         $21, 0x60($29)
    /* 0CCEB4 001CCDB4 5000B47B */  lq         $20, 0x50($29)
    /* 0CCEB8 001CCDB8 4000B37B */  lq         $19, 0x40($29)
    /* 0CCEBC 001CCDBC 3000B27B */  lq         $18, 0x30($29)
    /* 0CCEC0 001CCDC0 2000B17B */  lq         $17, 0x20($29)
    /* 0CCEC4 001CCDC4 1000B07B */  lq         $16, 0x10($29)
    /* 0CCEC8 001CCDC8 0000B4C7 */  lwc1       $f20, 0x0($29)
    /* 0CCECC 001CCDCC 8000BD27 */  addiu      $29, $29, 0x80
    /* 0CCED0 001CCDD0 0800E003 */  jr         $31
    /* 0CCED4 001CCDD4 00000000 */   nop
    /* 0CCED8 001CCDD8 00000000 */  nop
    /* 0CCEDC 001CCDDC 00000000 */  nop

glabel SearchDataSlotPos2__16CDungeonEventManFPf
    /* 0CCEE0 001CCDE0 70FFBD27 */  addiu      $29, $29, -0x90
    /* 0CCEE4 001CCDE4 6000BF7F */  sq         $31, 0x60($29)
    /* 0CCEE8 001CCDE8 5000B47F */  sq         $20, 0x50($29)
    /* 0CCEEC 001CCDEC 4000B37F */  sq         $19, 0x40($29)
    /* 0CCEF0 001CCDF0 3000B27F */  sq         $18, 0x30($29)
    /* 0CCEF4 001CCDF4 2000B17F */  sq         $17, 0x20($29)
    /* 0CCEF8 001CCDF8 1000B07F */  sq         $16, 0x10($29)
    /* 0CCEFC 001CCDFC 0400B5E7 */  swc1       $f21, 0x4($29)
    /* 0CCF00 001CCE00 0000B4E7 */  swc1       $f20, 0x0($29)
    /* 0CCF04 001CCE04 28968070 */  paddub     $18, $4, $0
    /* 0CCF08 001CCE08 8000A427 */  addiu      $4, $29, 0x80
    /* 0CCF0C 001CCE0C 0C86040C */  jal        sceVu0CopyVector
    /* 0CCF10 001CCE10 00000000 */   nop
    /* 0CCF14 001CCE14 8400A227 */  addiu      $2, $29, 0x84
    /* 0CCF18 001CCE18 000054C4 */  lwc1       $f20, 0x0($2)
    /* 0CCF1C 001CCE1C 000040AC */  sw         $0, 0x0($2)
    /* 0CCF20 001CCE20 28860070 */  paddub     $16, $0, $0
    /* 0CCF24 001CCE24 34000010 */  b          .L001CCEF8
    /* 0CCF28 001CCE28 00000000 */   nop
  .L001CCE2C:
    /* 0CCF2C 001CCE2C 80A11000 */  sll        $20, $16, 6
    /* 0CCF30 001CCE30 21985402 */  addu       $19, $18, $20
    /* 0CCF34 001CCE34 00107126 */  addiu      $17, $19, 0x1000
    /* 0CCF38 001CCE38 28262072 */  paddub     $4, $17, $0
    /* 0CCF3C 001CCE3C 2032070C */  jal        CheckSwitch__17CDungeonEventDataFv
    /* 0CCF40 001CCE40 00000000 */   nop
    /* 0CCF44 001CCE44 2B004010 */  beqz       $2, .L001CCEF4
    /* 0CCF48 001CCE48 00000000 */   nop
    /* 0CCF4C 001CCE4C 7000A427 */  addiu      $4, $29, 0x70
    /* 0CCF50 001CCE50 10106526 */  addiu      $5, $19, 0x1010
    /* 0CCF54 001CCE54 0C86040C */  jal        sceVu0CopyVector
    /* 0CCF58 001CCE58 00000000 */   nop
    /* 0CCF5C 001CCE5C 7400A327 */  addiu      $3, $29, 0x74
    /* 0CCF60 001CCE60 000060C4 */  lwc1       $f0, 0x0($3)
    /* 0CCF64 001CCE64 41A00046 */  sub.s      $f1, $f20, $f0
    /* 0CCF68 001CCE68 00008044 */  mtc1       $0, $f0
    /* 0CCF6C 001CCE6C 00000000 */  nop
    /* 0CCF70 001CCE70 34080046 */  c.lt.s     $f1, $f0
    /* 0CCF74 001CCE74 00000000 */  nop
    /* 0CCF78 001CCE78 04000045 */  bc1f       .L001CCE8C
    /* 0CCF7C 001CCE7C 00000000 */   nop
    /* 0CCF80 001CCE80 47080046 */  neg.s      $f1, $f1
    /* 0CCF84 001CCE84 01000010 */  b          .L001CCE8C
    /* 0CCF88 001CCE88 00000000 */   nop
  .L001CCE8C:
    /* 0CCF8C 001CCE8C 2042023C */  lui        $2, (0x42200000 >> 16)
    /* 0CCF90 001CCE90 00008244 */  mtc1       $2, $f0
    /* 0CCF94 001CCE94 00000000 */  nop
    /* 0CCF98 001CCE98 34080046 */  c.lt.s     $f1, $f0
    /* 0CCF9C 001CCE9C 00000000 */  nop
    /* 0CCFA0 001CCEA0 14000045 */  bc1f       .L001CCEF4
    /* 0CCFA4 001CCEA4 00000000 */   nop
    /* 0CCFA8 001CCEA8 000060AC */  sw         $0, 0x0($3)
    /* 0CCFAC 001CCEAC 21109202 */  addu       $2, $20, $18
    /* 0CCFB0 001CCEB0 0010428C */  lw         $2, 0x1000($2)
    /* 0CCFB4 001CCEB4 180055C4 */  lwc1       $f21, 0x18($2)
    /* 0CCFB8 001CCEB8 7000A427 */  addiu      $4, $29, 0x70
    /* 0CCFBC 001CCEBC 8000A527 */  addiu      $5, $29, 0x80
    /* 0CCFC0 001CCEC0 648D040C */  jal        DistVector__FPfPf
    /* 0CCFC4 001CCEC4 00000000 */   nop
    /* 0CCFC8 001CCEC8 2041023C */  lui        $2, (0x41200000 >> 16)
    /* 0CCFCC 001CCECC 00088244 */  mtc1       $2, $f1
    /* 0CCFD0 001CCED0 00000000 */  nop
    /* 0CCFD4 001CCED4 40081546 */  add.s      $f1, $f1, $f21
    /* 0CCFD8 001CCED8 36000146 */  c.le.s     $f0, $f1
    /* 0CCFDC 001CCEDC 00000000 */  nop
    /* 0CCFE0 001CCEE0 04000045 */  bc1f       .L001CCEF4
    /* 0CCFE4 001CCEE4 00000000 */   nop
    /* 0CCFE8 001CCEE8 28162072 */  paddub     $2, $17, $0
    /* 0CCFEC 001CCEEC 06000010 */  b          .L001CCF08
    /* 0CCFF0 001CCEF0 00000000 */   nop
  .L001CCEF4:
    /* 0CCFF4 001CCEF4 01001026 */  addiu      $16, $16, 0x1
  .L001CCEF8:
    /* 0CCFF8 001CCEF8 6000022A */  slti       $2, $16, 0x60
    /* 0CCFFC 001CCEFC CBFF4014 */  bnez       $2, .L001CCE2C
    /* 0CD000 001CCF00 00000000 */   nop
    /* 0CD004 001CCF04 28160070 */  paddub     $2, $0, $0
  .L001CCF08:
    /* 0CD008 001CCF08 6000BF7B */  lq         $31, 0x60($29)
    /* 0CD00C 001CCF0C 5000B47B */  lq         $20, 0x50($29)
    /* 0CD010 001CCF10 4000B37B */  lq         $19, 0x40($29)
    /* 0CD014 001CCF14 3000B27B */  lq         $18, 0x30($29)
    /* 0CD018 001CCF18 2000B17B */  lq         $17, 0x20($29)
    /* 0CD01C 001CCF1C 1000B07B */  lq         $16, 0x10($29)
    /* 0CD020 001CCF20 0400B5C7 */  lwc1       $f21, 0x4($29)
    /* 0CD024 001CCF24 0000B4C7 */  lwc1       $f20, 0x0($29)
    /* 0CD028 001CCF28 9000BD27 */  addiu      $29, $29, 0x90
    /* 0CD02C 001CCF2C 0800E003 */  jr         $31
    /* 0CD030 001CCF30 00000000 */   nop
    /* 0CD034 001CCF34 00000000 */  nop
    /* 0CD038 001CCF38 00000000 */  nop
    /* 0CD03C 001CCF3C 00000000 */  nop

glabel SetupEvent__16CDungeonEventManFP11CDungeonMapi
    /* 0CD040 001CCF40 C0FEBD27 */  addiu      $29, $29, -0x140
    /* 0CD044 001CCF44 9000BF7F */  sq         $31, 0x90($29)
    /* 0CD048 001CCF48 8000BE7F */  sq         $30, 0x80($29)
    /* 0CD04C 001CCF4C 7000B77F */  sq         $23, 0x70($29)
    /* 0CD050 001CCF50 6000B67F */  sq         $22, 0x60($29)
    /* 0CD054 001CCF54 5000B57F */  sq         $21, 0x50($29)
    /* 0CD058 001CCF58 4000B47F */  sq         $20, 0x40($29)
    /* 0CD05C 001CCF5C 3000B37F */  sq         $19, 0x30($29)
    /* 0CD060 001CCF60 2000B27F */  sq         $18, 0x20($29)
    /* 0CD064 001CCF64 1000B17F */  sq         $17, 0x10($29)
    /* 0CD068 001CCF68 0000B07F */  sq         $16, 0x0($29)
    /* 0CD06C 001CCF6C 28AE8070 */  paddub     $21, $4, $0
    /* 0CD070 001CCF70 28A6A070 */  paddub     $20, $5, $0
    /* 0CD074 001CCF74 2800033C */  lui        $3, %hi(LIT_3530)
    /* 0CD078 001CCF78 A0A06324 */  addiu      $3, $3, %lo(LIT_3530)
    /* 0CD07C 001CCF7C B000A427 */  addiu      $4, $29, 0xB0
    /* 0CD080 001CCF80 00006378 */  lq         $3, 0x0($3)
    /* 0CD084 001CCF84 0000837C */  sq         $3, 0x0($4)
    /* 0CD088 001CCF88 01000324 */  addiu      $3, $0, 0x1
    /* 0CD08C 001CCF8C 9700C314 */  bne        $6, $3, .L001CD1EC
    /* 0CD090 001CCF90 00000000 */   nop
    /* 0CD094 001CCF94 289E0070 */  paddub     $19, $0, $0
    /* 0CD098 001CCF98 8F000010 */  b          .L001CD1D8
    /* 0CD09C 001CCF9C 00000000 */   nop
  .L001CCFA0:
    /* 0CD0A0 001CCFA0 28960070 */  paddub     $18, $0, $0
    /* 0CD0A4 001CCFA4 88000010 */  b          .L001CD1C8
    /* 0CD0A8 001CCFA8 00000000 */   nop
  .L001CCFAC:
    /* 0CD0AC 001CCFAC 80181300 */  sll        $3, $19, 2
    /* 0CD0B0 001CCFB0 21187300 */  addu       $3, $3, $19
    /* 0CD0B4 001CCFB4 80180300 */  sll        $3, $3, 2
    /* 0CD0B8 001CCFB8 21184302 */  addu       $3, $18, $3
    /* 0CD0BC 001CCFBC 00F10300 */  sll        $30, $3, 4
    /* 0CD0C0 001CCFC0 2118D403 */  addu       $3, $30, $20
    /* 0CD0C4 001CCFC4 581C7724 */  addiu      $23, $3, 0x1C58
    /* 0CD0C8 001CCFC8 F87FF726 */  addiu      $23, $23, 0x7FF8
    /* 0CD0CC 001CCFCC 0000E38E */  lw         $3, 0x0($23)
    /* 0CD0D0 001CCFD0 A000A3AF */  sw         $3, 0xA0($29)
    /* 0CD0D4 001CCFD4 FFFF0424 */  addiu      $4, $0, -0x1
    /* 0CD0D8 001CCFD8 A000A38F */  lw         $3, 0xA0($29)
    /* 0CD0DC 001CCFDC 79006410 */  beq        $3, $4, .L001CD1C4
    /* 0CD0E0 001CCFE0 00000000 */   nop
    /* 0CD0E4 001CCFE4 28B60070 */  paddub     $22, $0, $0
    /* 0CD0E8 001CCFE8 73000010 */  b          .L001CD1B8
    /* 0CD0EC 001CCFEC 00000000 */   nop
  .L001CCFF0:
    /* 0CD0F0 001CCFF0 2826A072 */  paddub     $4, $21, $0
    /* 0CD0F4 001CCFF4 282EC072 */  paddub     $5, $22, $0
    /* 0CD0F8 001CCFF8 A000A68F */  lw         $6, 0xA0($29)
    /* 0CD0FC 001CCFFC 3C32070C */  jal        SearchPartsID__16CDungeonEventManFii
    /* 0CD100 001CD000 00000000 */   nop
    /* 0CD104 001CD004 28864070 */  paddub     $16, $2, $0
    /* 0CD108 001CD008 6A004010 */  beqz       $2, .L001CD1B4
    /* 0CD10C 001CD00C 00000000 */   nop
    /* 0CD110 001CD010 2826A072 */  paddub     $4, $21, $0
    /* 0CD114 001CD014 CC32070C */  jal        SearchDataSlot__16CDungeonEventManFv
    /* 0CD118 001CD018 00000000 */   nop
    /* 0CD11C 001CD01C 288E4070 */  paddub     $17, $2, $0
    /* 0CD120 001CD020 07002016 */  bnez       $17, .L001CD040
    /* 0CD124 001CD024 00000000 */   nop
    /* 0CD128 001CD028 2A00023C */  lui        $2, %hi(LIT_3600)
    /* 0CD12C 001CD02C B0BF4424 */  addiu      $4, $2, %lo(LIT_3600)
    /* 0CD130 001CD030 A611040C */  jal        printf
    /* 0CD134 001CD034 00000000 */   nop
  .L001CD038:
    /* 0CD138 001CD038 FFFF0010 */  b          .L001CD038
    /* 0CD13C 001CD03C 00000000 */   nop
  .L001CD040:
    /* 0CD140 001CD040 28262072 */  paddub     $4, $17, $0
    /* 0CD144 001CD044 282E0072 */  paddub     $5, $16, $0
    /* 0CD148 001CD048 0832070C */  jal        Set__17CDungeonEventDataFP13CDungeonEvent
    /* 0CD14C 001CD04C 00000000 */   nop
    /* 0CD150 001CD050 2110D403 */  addu       $2, $30, $20
    /* 0CD154 001CD054 0100013C */  lui        $1, (0x10000 >> 16)
    /* 0CD158 001CD058 21084100 */  addu       $1, $2, $1
    /* 0CD15C 001CD05C 549C20C4 */  lwc1       $f0, -0x63AC($1)
    /* 0CD160 001CD060 60038046 */  cvt.s.w    $f13, $f0
    /* 0CD164 001CD064 0000E38E */  lw         $3, 0x0($23)
    /* 0CD168 001CD068 FFFF0224 */  addiu      $2, $0, -0x1
    /* 0CD16C 001CD06C 04006214 */  bne        $3, $2, .L001CD080
    /* 0CD170 001CD070 00000000 */   nop
    /* 0CD174 001CD074 28160070 */  paddub     $2, $0, $0
    /* 0CD178 001CD078 09000010 */  b          .L001CD0A0
    /* 0CD17C 001CD07C 00000000 */   nop
  .L001CD080:
    /* 0CD180 001CD080 C0100300 */  sll        $2, $3, 3
    /* 0CD184 001CD084 23104300 */  subu       $2, $2, $3
    /* 0CD188 001CD088 80100200 */  sll        $2, $2, 2
    /* 0CD18C 001CD08C 21104300 */  addu       $2, $2, $3
    /* 0CD190 001CD090 00110200 */  sll        $2, $2, 4
    /* 0CD194 001CD094 21105400 */  addu       $2, $2, $20
    /* 0CD198 001CD098 A0044284 */  lh         $2, 0x4A0($2)
    /* 0CD19C 001CD09C 00000000 */  nop
  .L001CD0A0:
    /* 0CD1A0 001CD0A0 00008244 */  mtc1       $2, $f0
    /* 0CD1A4 001CD0A4 00000000 */  nop
    /* 0CD1A8 001CD0A8 20008046 */  cvt.s.w    $f0, $f0
    /* 0CD1AC 001CD0AC 406B0046 */  add.s      $f13, $f13, $f0
    /* 0CD1B0 001CD0B0 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0CD1B4 001CD0B4 00008244 */  mtc1       $2, $f0
    /* 0CD1B8 001CD0B8 00000000 */  nop
    /* 0CD1BC 001CD0BC 36680046 */  c.le.s     $f13, $f0
    /* 0CD1C0 001CD0C0 00000000 */  nop
    /* 0CD1C4 001CD0C4 02000145 */  bc1t       .L001CD0D0
    /* 0CD1C8 001CD0C8 00000000 */   nop
    /* 0CD1CC 001CD0CC 416B0046 */  sub.s      $f13, $f13, $f0
  .L001CD0D0:
    /* 0CD1D0 001CD0D0 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0CD1D4 001CD0D4 00008244 */  mtc1       $2, $f0
    /* 0CD1D8 001CD0D8 00000000 */  nop
    /* 0CD1DC 001CD0DC 32000D46 */  c.eq.s     $f0, $f13
    /* 0CD1E0 001CD0E0 00000000 */  nop
    /* 0CD1E4 001CD0E4 03000045 */  bc1f       .L001CD0F4
    /* 0CD1E8 001CD0E8 00000000 */   nop
    /* 0CD1EC 001CD0EC 80BF023C */  lui        $2, (0xBF800000 >> 16)
    /* 0CD1F0 001CD0F0 00688244 */  mtc1       $2, $f13
  .L001CD0F4:
    /* 0CD1F4 001CD0F4 B4C2023C */  lui        $2, (0xC2B40000 >> 16)
    /* 0CD1F8 001CD0F8 00008244 */  mtc1       $2, $f0
    /* 0CD1FC 001CD0FC 00000000 */  nop
    /* 0CD200 001CD100 42000D46 */  mul.s      $f1, $f0, $f13
    /* 0CD204 001CD104 B08080C7 */  lwc1       $f0, -0x7F50($28)
    /* 0CD208 001CD108 42000146 */  mul.s      $f1, $f0, $f1
    /* 0CD20C 001CD10C 3443023C */  lui        $2, (0x43340000 >> 16)
    /* 0CD210 001CD110 00008244 */  mtc1       $2, $f0
    /* 0CD214 001CD114 00000000 */  nop
    /* 0CD218 001CD118 430B0046 */  div.s      $f13, $f1, $f0
    /* 0CD21C 001CD11C 00608044 */  mtc1       $0, $f12
    /* 0CD220 001CD120 00000000 */  nop
    /* 0CD224 001CD124 86630046 */  mov.s      $f14, $f12
    /* 0CD228 001CD128 1000048E */  lw         $4, 0x10($16)
    /* 0CD22C 001CD12C 70A3040C */  jal        SetRotation__6CFrameFfff
    /* 0CD230 001CD130 00000000 */   nop
    /* 0CD234 001CD134 1400048E */  lw         $4, 0x14($16)
    /* 0CD238 001CD138 C000A527 */  addiu      $5, $29, 0xC0
    /* 0CD23C 001CD13C 6CA0040C */  jal        GetLWMatrix__6CFrameFPA4_f
    /* 0CD240 001CD140 00000000 */   nop
    /* 0CD244 001CD144 200020AE */  sw         $0, 0x20($17)
    /* 0CD248 001CD148 E000ACC7 */  lwc1       $f12, 0xE0($29)
    /* 0CD24C 001CD14C E800ADC7 */  lwc1       $f13, 0xE8($29)
    /* 0CD250 001CD150 5077040C */  jal        atan2f
    /* 0CD254 001CD154 00000000 */   nop
    /* 0CD258 001CD158 240020E6 */  swc1       $f0, 0x24($17)
    /* 0CD25C 001CD15C 280020AE */  sw         $0, 0x28($17)
    /* 0CD260 001CD160 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 0CD264 001CD164 2C0022AE */  sw         $2, 0x2C($17)
    /* 0CD268 001CD168 2043023C */  lui        $2, (0x43200000 >> 16)
    /* 0CD26C 001CD16C 00088244 */  mtc1       $2, $f1
    /* 0CD270 001CD170 00009244 */  mtc1       $18, $f0
    /* 0CD274 001CD174 00000000 */  nop
    /* 0CD278 001CD178 20008046 */  cvt.s.w    $f0, $f0
    /* 0CD27C 001CD17C 020B0046 */  mul.s      $f12, $f1, $f0
    /* 0CD280 001CD180 00688044 */  mtc1       $0, $f13
    /* 0CD284 001CD184 00009344 */  mtc1       $19, $f0
    /* 0CD288 001CD188 00000000 */  nop
    /* 0CD28C 001CD18C 20008046 */  cvt.s.w    $f0, $f0
    /* 0CD290 001CD190 820B0046 */  mul.s      $f14, $f1, $f0
    /* 0CD294 001CD194 1000048E */  lw         $4, 0x10($16)
    /* 0CD298 001CD198 A09F040C */  jal        SetPosition__6CFrameFfff
    /* 0CD29C 001CD19C 00000000 */   nop
    /* 0CD2A0 001CD1A0 1400048E */  lw         $4, 0x14($16)
    /* 0CD2A4 001CD1A4 10002526 */  addiu      $5, $17, 0x10
    /* 0CD2A8 001CD1A8 B000A627 */  addiu      $6, $29, 0xB0
    /* 0CD2AC 001CD1AC 58A3040C */  jal        GetWorldPosition__6CFrameFPfPf
    /* 0CD2B0 001CD1B0 00000000 */   nop
  .L001CD1B4:
    /* 0CD2B4 001CD1B4 0100D626 */  addiu      $22, $22, 0x1
  .L001CD1B8:
    /* 0CD2B8 001CD1B8 4000C32A */  slti       $3, $22, 0x40
    /* 0CD2BC 001CD1BC 8CFF6014 */  bnez       $3, .L001CCFF0
    /* 0CD2C0 001CD1C0 00000000 */   nop
  .L001CD1C4:
    /* 0CD2C4 001CD1C4 01005226 */  addiu      $18, $18, 0x1
  .L001CD1C8:
    /* 0CD2C8 001CD1C8 1000432A */  slti       $3, $18, 0x10
    /* 0CD2CC 001CD1CC 77FF6014 */  bnez       $3, .L001CCFAC
    /* 0CD2D0 001CD1D0 00000000 */   nop
    /* 0CD2D4 001CD1D4 01007326 */  addiu      $19, $19, 0x1
  .L001CD1D8:
    /* 0CD2D8 001CD1D8 1000632A */  slti       $3, $19, 0x10
    /* 0CD2DC 001CD1DC 70FF6014 */  bnez       $3, .L001CCFA0
    /* 0CD2E0 001CD1E0 00000000 */   nop
    /* 0CD2E4 001CD1E4 66000010 */  b          .L001CD380
    /* 0CD2E8 001CD1E8 00000000 */   nop
  .L001CD1EC:
    /* 0CD2EC 001CD1EC 28960070 */  paddub     $18, $0, $0
    /* 0CD2F0 001CD1F0 5A000010 */  b          .L001CD35C
    /* 0CD2F4 001CD1F4 00000000 */   nop
  .L001CD1F8:
    /* 0CD2F8 001CD1F8 289E0070 */  paddub     $19, $0, $0
    /* 0CD2FC 001CD1FC 53000010 */  b          .L001CD34C
    /* 0CD300 001CD200 00000000 */   nop
  .L001CD204:
    /* 0CD304 001CD204 2826A072 */  paddub     $4, $21, $0
    /* 0CD308 001CD208 282E6072 */  paddub     $5, $19, $0
    /* 0CD30C 001CD20C 28364072 */  paddub     $6, $18, $0
    /* 0CD310 001CD210 3C32070C */  jal        SearchPartsID__16CDungeonEventManFii
    /* 0CD314 001CD214 00000000 */   nop
    /* 0CD318 001CD218 28864070 */  paddub     $16, $2, $0
    /* 0CD31C 001CD21C 4A004010 */  beqz       $2, .L001CD348
    /* 0CD320 001CD220 00000000 */   nop
    /* 0CD324 001CD224 2826A072 */  paddub     $4, $21, $0
    /* 0CD328 001CD228 CC32070C */  jal        SearchDataSlot__16CDungeonEventManFv
    /* 0CD32C 001CD22C 00000000 */   nop
    /* 0CD330 001CD230 288E4070 */  paddub     $17, $2, $0
    /* 0CD334 001CD234 28262072 */  paddub     $4, $17, $0
    /* 0CD338 001CD238 282E0072 */  paddub     $5, $16, $0
    /* 0CD33C 001CD23C 0832070C */  jal        Set__17CDungeonEventDataFP13CDungeonEvent
    /* 0CD340 001CD240 00000000 */   nop
    /* 0CD344 001CD244 2118D402 */  addu       $3, $22, $20
    /* 0CD348 001CD248 000661C4 */  lwc1       $f1, 0x600($3)
    /* 0CD34C 001CD24C FFFF0224 */  addiu      $2, $0, -0x1
    /* 0CD350 001CD250 04004216 */  bne        $18, $2, .L001CD264
    /* 0CD354 001CD254 00000000 */   nop
    /* 0CD358 001CD258 28160070 */  paddub     $2, $0, $0
    /* 0CD35C 001CD25C 03000010 */  b          .L001CD26C
    /* 0CD360 001CD260 00000000 */   nop
  .L001CD264:
    /* 0CD364 001CD264 A0046284 */  lh         $2, 0x4A0($3)
    /* 0CD368 001CD268 00000000 */  nop
  .L001CD26C:
    /* 0CD36C 001CD26C 00008244 */  mtc1       $2, $f0
    /* 0CD370 001CD270 00000000 */  nop
    /* 0CD374 001CD274 20008046 */  cvt.s.w    $f0, $f0
    /* 0CD378 001CD278 40080046 */  add.s      $f1, $f1, $f0
    /* 0CD37C 001CD27C 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0CD380 001CD280 00008244 */  mtc1       $2, $f0
    /* 0CD384 001CD284 00000000 */  nop
    /* 0CD388 001CD288 36080046 */  c.le.s     $f1, $f0
    /* 0CD38C 001CD28C 00000000 */  nop
    /* 0CD390 001CD290 02000145 */  bc1t       .L001CD29C
    /* 0CD394 001CD294 00000000 */   nop
    /* 0CD398 001CD298 41080046 */  sub.s      $f1, $f1, $f0
  .L001CD29C:
    /* 0CD39C 001CD29C 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0CD3A0 001CD2A0 00008244 */  mtc1       $2, $f0
    /* 0CD3A4 001CD2A4 00000000 */  nop
    /* 0CD3A8 001CD2A8 32000146 */  c.eq.s     $f0, $f1
    /* 0CD3AC 001CD2AC 00000000 */  nop
    /* 0CD3B0 001CD2B0 03000045 */  bc1f       .L001CD2C0
    /* 0CD3B4 001CD2B4 00000000 */   nop
    /* 0CD3B8 001CD2B8 80BF023C */  lui        $2, (0xBF800000 >> 16)
    /* 0CD3BC 001CD2BC 00088244 */  mtc1       $2, $f1
  .L001CD2C0:
    /* 0CD3C0 001CD2C0 B4C2023C */  lui        $2, (0xC2B40000 >> 16)
    /* 0CD3C4 001CD2C4 00008244 */  mtc1       $2, $f0
    /* 0CD3C8 001CD2C8 00000000 */  nop
    /* 0CD3CC 001CD2CC 42000146 */  mul.s      $f1, $f0, $f1
    /* 0CD3D0 001CD2D0 B08080C7 */  lwc1       $f0, -0x7F50($28)
    /* 0CD3D4 001CD2D4 42000146 */  mul.s      $f1, $f0, $f1
    /* 0CD3D8 001CD2D8 3443023C */  lui        $2, (0x43340000 >> 16)
    /* 0CD3DC 001CD2DC 00008244 */  mtc1       $2, $f0
    /* 0CD3E0 001CD2E0 00000000 */  nop
    /* 0CD3E4 001CD2E4 430B0046 */  div.s      $f13, $f1, $f0
    /* 0CD3E8 001CD2E8 00608044 */  mtc1       $0, $f12
    /* 0CD3EC 001CD2EC 00000000 */  nop
    /* 0CD3F0 001CD2F0 86630046 */  mov.s      $f14, $f12
    /* 0CD3F4 001CD2F4 1000048E */  lw         $4, 0x10($16)
    /* 0CD3F8 001CD2F8 70A3040C */  jal        SetRotation__6CFrameFfff
    /* 0CD3FC 001CD2FC 00000000 */   nop
    /* 0CD400 001CD300 1400048E */  lw         $4, 0x14($16)
    /* 0CD404 001CD304 0001A527 */  addiu      $5, $29, 0x100
    /* 0CD408 001CD308 6CA0040C */  jal        GetLWMatrix__6CFrameFPA4_f
    /* 0CD40C 001CD30C 00000000 */   nop
    /* 0CD410 001CD310 200020AE */  sw         $0, 0x20($17)
    /* 0CD414 001CD314 2001ACC7 */  lwc1       $f12, 0x120($29)
    /* 0CD418 001CD318 2801ADC7 */  lwc1       $f13, 0x128($29)
    /* 0CD41C 001CD31C 5077040C */  jal        atan2f
    /* 0CD420 001CD320 00000000 */   nop
    /* 0CD424 001CD324 240020E6 */  swc1       $f0, 0x24($17)
    /* 0CD428 001CD328 280020AE */  sw         $0, 0x28($17)
    /* 0CD42C 001CD32C 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 0CD430 001CD330 2C0022AE */  sw         $2, 0x2C($17)
    /* 0CD434 001CD334 1400048E */  lw         $4, 0x14($16)
    /* 0CD438 001CD338 10002526 */  addiu      $5, $17, 0x10
    /* 0CD43C 001CD33C B000A627 */  addiu      $6, $29, 0xB0
    /* 0CD440 001CD340 58A3040C */  jal        GetWorldPosition__6CFrameFPfPf
    /* 0CD444 001CD344 00000000 */   nop
  .L001CD348:
    /* 0CD448 001CD348 01007326 */  addiu      $19, $19, 0x1
  .L001CD34C:
    /* 0CD44C 001CD34C 4000632A */  slti       $3, $19, 0x40
    /* 0CD450 001CD350 ACFF6014 */  bnez       $3, .L001CD204
    /* 0CD454 001CD354 00000000 */   nop
    /* 0CD458 001CD358 01005226 */  addiu      $18, $18, 0x1
  .L001CD35C:
    /* 0CD45C 001CD35C C0181200 */  sll        $3, $18, 3
    /* 0CD460 001CD360 23187200 */  subu       $3, $3, $18
    /* 0CD464 001CD364 80180300 */  sll        $3, $3, 2
    /* 0CD468 001CD368 21187200 */  addu       $3, $3, $18
    /* 0CD46C 001CD36C 00B10300 */  sll        $22, $3, 4
    /* 0CD470 001CD370 2118D402 */  addu       $3, $22, $20
    /* 0CD474 001CD374 4006638C */  lw         $3, 0x640($3)
    /* 0CD478 001CD378 9FFF6014 */  bnez       $3, .L001CD1F8
    /* 0CD47C 001CD37C 00000000 */   nop
  .L001CD380:
    /* 0CD480 001CD380 9000BF7B */  lq         $31, 0x90($29)
    /* 0CD484 001CD384 8000BE7B */  lq         $30, 0x80($29)
    /* 0CD488 001CD388 7000B77B */  lq         $23, 0x70($29)
    /* 0CD48C 001CD38C 6000B67B */  lq         $22, 0x60($29)
    /* 0CD490 001CD390 5000B57B */  lq         $21, 0x50($29)
    /* 0CD494 001CD394 4000B47B */  lq         $20, 0x40($29)
    /* 0CD498 001CD398 3000B37B */  lq         $19, 0x30($29)
    /* 0CD49C 001CD39C 2000B27B */  lq         $18, 0x20($29)
    /* 0CD4A0 001CD3A0 1000B17B */  lq         $17, 0x10($29)
    /* 0CD4A4 001CD3A4 0000B07B */  lq         $16, 0x0($29)
    /* 0CD4A8 001CD3A8 4001BD27 */  addiu      $29, $29, 0x140
    /* 0CD4AC 001CD3AC 0800E003 */  jr         $31
    /* 0CD4B0 001CD3B0 00000000 */   nop
    /* 0CD4B4 001CD3B4 00000000 */  nop
    /* 0CD4B8 001CD3B8 00000000 */  nop
    /* 0CD4BC 001CD3BC 00000000 */  nop

.section .rodata, "a"
.align 4

/* Generated by spimdisasm 1.42.4 */

glabel LIT_3600
    /* 19C0B0 0029BFB0 2A2A2065 */ .word 0x65202A2A
    /* 19C0B4 0029BFB4 76656E74 */ .word 0x746E6576
    /* 19C0B8 0029BFB8 64617461 */ .word 0x61746164
    /* 19C0BC 0029BFBC 20657272 */ .word 0x72726520
    /* 19C0C0 0029BFC0 200A0000 */ .word 0x00000A20
    /* 19C0C4 0029BFC4 00000000 */ .word 0x00000000
    /* 19C0C8 0029BFC8 00000000 */ .word 0x00000000
    /* 19C0CC 0029BFCC 00000000 */ .word 0x00000000
