.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel Set__21CHIT_MACHINGUN_EFFECTFPf
    /* 0AEA80 001AE980 D0FFBD27 */  addiu      $29, $29, -0x30
    /* 0AEA84 001AE984 2000BF7F */  sq         $31, 0x20($29)
    /* 0AEA88 001AE988 1000B17F */  sq         $17, 0x10($29)
    /* 0AEA8C 001AE98C 0000B07F */  sq         $16, 0x0($29)
    /* 0AEA90 001AE990 288E8070 */  paddub     $17, $4, $0
    /* 0AEA94 001AE994 FFFF1024 */  addiu      $16, $0, -0x1
    /* 0AEA98 001AE998 28260070 */  paddub     $4, $0, $0
    /* 0AEA9C 001AE99C 0A000010 */  b          .L001AE9C8
    /* 0AEAA0 001AE9A0 00000000 */   nop
  .L001AE9A4:
    /* 0AEAA4 001AE9A4 80180400 */  sll        $3, $4, 2
    /* 0AEAA8 001AE9A8 21187100 */  addu       $3, $3, $17
    /* 0AEAAC 001AE9AC 0001638C */  lw         $3, 0x100($3)
    /* 0AEAB0 001AE9B0 04006104 */  bgez       $3, .L001AE9C4
    /* 0AEAB4 001AE9B4 00000000 */   nop
    /* 0AEAB8 001AE9B8 28868070 */  paddub     $16, $4, $0
    /* 0AEABC 001AE9BC 05000010 */  b          .L001AE9D4
    /* 0AEAC0 001AE9C0 00000000 */   nop
  .L001AE9C4:
    /* 0AEAC4 001AE9C4 01008424 */  addiu      $4, $4, 0x1
  .L001AE9C8:
    /* 0AEAC8 001AE9C8 10008328 */  slti       $3, $4, 0x10
    /* 0AEACC 001AE9CC F5FF6014 */  bnez       $3, .L001AE9A4
    /* 0AEAD0 001AE9D0 00000000 */   nop
  .L001AE9D4:
    /* 0AEAD4 001AE9D4 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0AEAD8 001AE9D8 09000312 */  beq        $16, $3, .L001AEA00
    /* 0AEADC 001AE9DC 00000000 */   nop
    /* 0AEAE0 001AE9E0 00111000 */  sll        $2, $16, 4
    /* 0AEAE4 001AE9E4 21202202 */  addu       $4, $17, $2
    /* 0AEAE8 001AE9E8 0C86040C */  jal        sceVu0CopyVector
    /* 0AEAEC 001AE9EC 00000000 */   nop
    /* 0AEAF0 001AE9F0 11000424 */  addiu      $4, $0, 0x11
    /* 0AEAF4 001AE9F4 80181000 */  sll        $3, $16, 2
    /* 0AEAF8 001AE9F8 21187100 */  addu       $3, $3, $17
    /* 0AEAFC 001AE9FC 000164AC */  sw         $4, 0x100($3)
  .L001AEA00:
    /* 0AEB00 001AEA00 2000BF7B */  lq         $31, 0x20($29)
    /* 0AEB04 001AEA04 1000B17B */  lq         $17, 0x10($29)
    /* 0AEB08 001AEA08 0000B07B */  lq         $16, 0x0($29)
    /* 0AEB0C 001AEA0C 3000BD27 */  addiu      $29, $29, 0x30
    /* 0AEB10 001AEA10 0800E003 */  jr         $31
    /* 0AEB14 001AEA14 00000000 */   nop
    /* 0AEB18 001AEA18 00000000 */  nop
    /* 0AEB1C 001AEA1C 00000000 */  nop

glabel Draw__21CHIT_MACHINGUN_EFFECTFv
    /* 0AEB20 001AEA20 D0FFBD27 */  addiu      $29, $29, -0x30
    /* 0AEB24 001AEA24 2000BF7F */  sq         $31, 0x20($29)
    /* 0AEB28 001AEA28 1000B17F */  sq         $17, 0x10($29)
    /* 0AEB2C 001AEA2C 0000B07F */  sq         $16, 0x0($29)
    /* 0AEB30 001AEA30 288E8070 */  paddub     $17, $4, $0
    /* 0AEB34 001AEA34 28860070 */  paddub     $16, $0, $0
    /* 0AEB38 001AEA38 1C000010 */  b          .L001AEAAC
    /* 0AEB3C 001AEA3C 00000000 */   nop
  .L001AEA40:
    /* 0AEB40 001AEA40 80181000 */  sll        $3, $16, 2
    /* 0AEB44 001AEA44 21187100 */  addu       $3, $3, $17
    /* 0AEB48 001AEA48 0001638C */  lw         $3, 0x100($3)
    /* 0AEB4C 001AEA4C 16006004 */  bltz       $3, .L001AEAA8
    /* 0AEB50 001AEA50 00000000 */   nop
    /* 0AEB54 001AEA54 06000224 */  addiu      $2, $0, 0x6
    /* 0AEB58 001AEA58 1A006200 */  div        $0, $3, $2
    /* 0AEB5C 001AEA5C 02004014 */  bnez       $2, .L001AEA68
    /* 0AEB60 001AEA60 00000000 */   nop
    /* 0AEB64 001AEA64 CD010000 */  break      0, 7
  .L001AEA68:
    /* 0AEB68 001AEA68 12180000 */  mflo       $3
    /* 0AEB6C 001AEA6C 02000224 */  addiu      $2, $0, 0x2
    /* 0AEB70 001AEA70 23184300 */  subu       $3, $2, $3
    /* 0AEB74 001AEA74 00111000 */  sll        $2, $16, 4
    /* 0AEB78 001AEA78 21202202 */  addu       $4, $17, $2
    /* 0AEB7C 001AEA7C A040023C */  lui        $2, (0x40A00000 >> 16)
    /* 0AEB80 001AEA80 00608244 */  mtc1       $2, $f12
    /* 0AEB84 001AEA84 00310300 */  sll        $6, $3, 4
    /* 0AEB88 001AEA88 2A00023C */  lui        $2, %hi("@1116")
    /* 0AEB8C 001AEA8C 20B54524 */  addiu      $5, $2, %lo("@1116")
    /* 0AEB90 001AEA90 70000724 */  addiu      $7, $0, 0x70
    /* 0AEB94 001AEA94 10000824 */  addiu      $8, $0, 0x10
    /* 0AEB98 001AEA98 284E0071 */  paddub     $9, $8, $0
    /* 0AEB9C 001AEA9C 80000A24 */  addiu      $10, $0, 0x80
    /* 0AEBA0 001AEAA0 C0AE060C */  jal        set3DCellModel__FPfPcfiiiiUc
    /* 0AEBA4 001AEAA4 00000000 */   nop
  .L001AEAA8:
    /* 0AEBA8 001AEAA8 01001026 */  addiu      $16, $16, 0x1
  .L001AEAAC:
    /* 0AEBAC 001AEAAC 1000032A */  slti       $3, $16, 0x10
    /* 0AEBB0 001AEAB0 E3FF6014 */  bnez       $3, .L001AEA40
    /* 0AEBB4 001AEAB4 00000000 */   nop
    /* 0AEBB8 001AEAB8 2000BF7B */  lq         $31, 0x20($29)
    /* 0AEBBC 001AEABC 1000B17B */  lq         $17, 0x10($29)
    /* 0AEBC0 001AEAC0 0000B07B */  lq         $16, 0x0($29)
    /* 0AEBC4 001AEAC4 3000BD27 */  addiu      $29, $29, 0x30
    /* 0AEBC8 001AEAC8 0800E003 */  jr         $31
    /* 0AEBCC 001AEACC 00000000 */   nop

glabel Step__21CHIT_MACHINGUN_EFFECTFv
    /* 0AEBD0 001AEAD0 282E0070 */  paddub     $5, $0, $0
    /* 0AEBD4 001AEAD4 0B000010 */  b          .L001AEB04
    /* 0AEBD8 001AEAD8 00000000 */   nop
  .L001AEADC:
    /* 0AEBDC 001AEADC 80180500 */  sll        $3, $5, 2
    /* 0AEBE0 001AEAE0 21186400 */  addu       $3, $3, $4
    /* 0AEBE4 001AEAE4 00016624 */  addiu      $6, $3, 0x100
    /* 0AEBE8 001AEAE8 0001638C */  lw         $3, 0x100($3)
    /* 0AEBEC 001AEAEC 04006004 */  bltz       $3, .L001AEB00
    /* 0AEBF0 001AEAF0 00000000 */   nop
    /* 0AEBF4 001AEAF4 0000C38C */  lw         $3, 0x0($6)
    /* 0AEBF8 001AEAF8 FFFF6324 */  addiu      $3, $3, -0x1
    /* 0AEBFC 001AEAFC 0000C3AC */  sw         $3, 0x0($6)
  .L001AEB00:
    /* 0AEC00 001AEB00 0100A524 */  addiu      $5, $5, 0x1
  .L001AEB04:
    /* 0AEC04 001AEB04 1000A328 */  slti       $3, $5, 0x10
    /* 0AEC08 001AEB08 F4FF6014 */  bnez       $3, .L001AEADC
    /* 0AEC0C 001AEB0C 00000000 */   nop
    /* 0AEC10 001AEB10 0800E003 */  jr         $31
    /* 0AEC14 001AEB14 00000000 */   nop
    /* 0AEC18 001AEB18 00000000 */  nop
    /* 0AEC1C 001AEB1C 00000000 */  nop

.section .rodata, "a"
.align 4

/* Generated by spimdisasm 1.42.4 */

glabel "@1116"
    /* 19B620 0029B520 62617365 */ .word 0x65736162
    /* 19B624 0029B524 66783030 */ .word 0x30307866
    /* 19B628 0029B528 00000000 */ .word 0x00000000
    /* 19B62C 0029B52C 00000000 */ .word 0x00000000
