.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel Init__13CSHOT_FIREBARFPfPfii
    /* 0AEC20 001AEB20 80FFBD27 */  addiu      $29, $29, -0x80
    /* 0AEC24 001AEB24 6000BF7F */  sq         $31, 0x60($29)
    /* 0AEC28 001AEB28 5000B57F */  sq         $21, 0x50($29)
    /* 0AEC2C 001AEB2C 4000B47F */  sq         $20, 0x40($29)
    /* 0AEC30 001AEB30 3000B37F */  sq         $19, 0x30($29)
    /* 0AEC34 001AEB34 2000B27F */  sq         $18, 0x20($29)
    /* 0AEC38 001AEB38 1000B17F */  sq         $17, 0x10($29)
    /* 0AEC3C 001AEB3C 0000B07F */  sq         $16, 0x0($29)
    /* 0AEC40 001AEB40 28AE8070 */  paddub     $21, $4, $0
    /* 0AEC44 001AEB44 28A6A070 */  paddub     $20, $5, $0
    /* 0AEC48 001AEB48 289EC070 */  paddub     $19, $6, $0
    /* 0AEC4C 001AEB4C 2896E070 */  paddub     $18, $7, $0
    /* 0AEC50 001AEB50 288E0071 */  paddub     $17, $8, $0
    /* 0AEC54 001AEB54 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 0AEC58 001AEB58 0C00C2AC */  sw         $2, 0xC($6)
    /* 0AEC5C 001AEB5C 28266072 */  paddub     $4, $19, $0
    /* 0AEC60 001AEB60 282E6072 */  paddub     $5, $19, $0
    /* 0AEC64 001AEB64 9285040C */  jal        sceVu0Normalize
    /* 0AEC68 001AEB68 00000000 */   nop
    /* 0AEC6C 001AEB6C 0040023C */  lui        $2, (0x40000000 >> 16)
    /* 0AEC70 001AEB70 00608244 */  mtc1       $2, $f12
    /* 0AEC74 001AEB74 7000A427 */  addiu      $4, $29, 0x70
    /* 0AEC78 001AEB78 282E6072 */  paddub     $5, $19, $0
    /* 0AEC7C 001AEB7C 4688040C */  jal        sceVu0ScaleVectorXYZ
    /* 0AEC80 001AEB80 00000000 */   nop
    /* 0AEC84 001AEB84 28860070 */  paddub     $16, $0, $0
    /* 0AEC88 001AEB88 5C000010 */  b          .L001AECFC
    /* 0AEC8C 001AEB8C 00000000 */   nop
  .L001AEB90:
    /* 0AEC90 001AEB90 000DA28E */  lw         $2, 0xD00($21)
    /* 0AEC94 001AEB94 21100202 */  addu       $2, $16, $2
    /* 0AEC98 001AEB98 00110200 */  sll        $2, $2, 4
    /* 0AEC9C 001AEB9C 2120A202 */  addu       $4, $21, $2
    /* 0AECA0 001AEBA0 282E8072 */  paddub     $5, $20, $0
    /* 0AECA4 001AEBA4 0C86040C */  jal        sceVu0CopyVector
    /* 0AECA8 001AEBA8 00000000 */   nop
    /* 0AECAC 001AEBAC 000081C6 */  lwc1       $f1, 0x0($20)
    /* 0AECB0 001AEBB0 00009044 */  mtc1       $16, $f0
    /* 0AECB4 001AEBB4 00000000 */  nop
    /* 0AECB8 001AEBB8 A0008046 */  cvt.s.w    $f2, $f0
    /* 0AECBC 001AEBBC 7000A0C7 */  lwc1       $f0, 0x70($29)
    /* 0AECC0 001AEBC0 02000246 */  mul.s      $f0, $f0, $f2
    /* 0AECC4 001AEBC4 00080046 */  add.s      $f0, $f1, $f0
    /* 0AECC8 001AEBC8 000DA28E */  lw         $2, 0xD00($21)
    /* 0AECCC 001AEBCC 21100202 */  addu       $2, $16, $2
    /* 0AECD0 001AEBD0 00110200 */  sll        $2, $2, 4
    /* 0AECD4 001AEBD4 2110A202 */  addu       $2, $21, $2
    /* 0AECD8 001AEBD8 000040E4 */  swc1       $f0, 0x0($2)
    /* 0AECDC 001AEBDC 040081C6 */  lwc1       $f1, 0x4($20)
    /* 0AECE0 001AEBE0 7400A0C7 */  lwc1       $f0, 0x74($29)
    /* 0AECE4 001AEBE4 02000246 */  mul.s      $f0, $f0, $f2
    /* 0AECE8 001AEBE8 00080046 */  add.s      $f0, $f1, $f0
    /* 0AECEC 001AEBEC 000DA28E */  lw         $2, 0xD00($21)
    /* 0AECF0 001AEBF0 21100202 */  addu       $2, $16, $2
    /* 0AECF4 001AEBF4 00110200 */  sll        $2, $2, 4
    /* 0AECF8 001AEBF8 21105500 */  addu       $2, $2, $21
    /* 0AECFC 001AEBFC 040040E4 */  swc1       $f0, 0x4($2)
    /* 0AED00 001AEC00 080081C6 */  lwc1       $f1, 0x8($20)
    /* 0AED04 001AEC04 7800A0C7 */  lwc1       $f0, 0x78($29)
    /* 0AED08 001AEC08 02000246 */  mul.s      $f0, $f0, $f2
    /* 0AED0C 001AEC0C 00080046 */  add.s      $f0, $f1, $f0
    /* 0AED10 001AEC10 000DA28E */  lw         $2, 0xD00($21)
    /* 0AED14 001AEC14 21100202 */  addu       $2, $16, $2
    /* 0AED18 001AEC18 00110200 */  sll        $2, $2, 4
    /* 0AED1C 001AEC1C 21105500 */  addu       $2, $2, $21
    /* 0AED20 001AEC20 080040E4 */  swc1       $f0, 0x8($2)
    /* 0AED24 001AEC24 148481C7 */  lwc1       $f1, -0x7BEC($28)
    /* 0AED28 001AEC28 000060C6 */  lwc1       $f0, 0x0($19)
    /* 0AED2C 001AEC2C 02080046 */  mul.s      $f0, $f1, $f0
    /* 0AED30 001AEC30 000DA28E */  lw         $2, 0xD00($21)
    /* 0AED34 001AEC34 21100202 */  addu       $2, $16, $2
    /* 0AED38 001AEC38 00110200 */  sll        $2, $2, 4
    /* 0AED3C 001AEC3C 21105500 */  addu       $2, $2, $21
    /* 0AED40 001AEC40 000440E4 */  swc1       $f0, 0x400($2)
    /* 0AED44 001AEC44 148481C7 */  lwc1       $f1, -0x7BEC($28)
    /* 0AED48 001AEC48 040060C6 */  lwc1       $f0, 0x4($19)
    /* 0AED4C 001AEC4C 02080046 */  mul.s      $f0, $f1, $f0
    /* 0AED50 001AEC50 000DA28E */  lw         $2, 0xD00($21)
    /* 0AED54 001AEC54 21100202 */  addu       $2, $16, $2
    /* 0AED58 001AEC58 00110200 */  sll        $2, $2, 4
    /* 0AED5C 001AEC5C 21105500 */  addu       $2, $2, $21
    /* 0AED60 001AEC60 040440E4 */  swc1       $f0, 0x404($2)
    /* 0AED64 001AEC64 148481C7 */  lwc1       $f1, -0x7BEC($28)
    /* 0AED68 001AEC68 080060C6 */  lwc1       $f0, 0x8($19)
    /* 0AED6C 001AEC6C 02080046 */  mul.s      $f0, $f1, $f0
    /* 0AED70 001AEC70 000DA28E */  lw         $2, 0xD00($21)
    /* 0AED74 001AEC74 21100202 */  addu       $2, $16, $2
    /* 0AED78 001AEC78 00110200 */  sll        $2, $2, 4
    /* 0AED7C 001AEC7C 21105500 */  addu       $2, $2, $21
    /* 0AED80 001AEC80 080440E4 */  swc1       $f0, 0x408($2)
    /* 0AED84 001AEC84 908280C7 */  lwc1       $f0, -0x7D70($28)
    /* 0AED88 001AEC88 42000246 */  mul.s      $f1, $f0, $f2
    /* 0AED8C 001AEC8C 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0AED90 001AEC90 00008244 */  mtc1       $2, $f0
    /* 0AED94 001AEC94 00000000 */  nop
    /* 0AED98 001AEC98 00000146 */  add.s      $f0, $f0, $f1
    /* 0AED9C 001AEC9C 000DA28E */  lw         $2, 0xD00($21)
    /* 0AEDA0 001AECA0 21100202 */  addu       $2, $16, $2
    /* 0AEDA4 001AECA4 80100200 */  sll        $2, $2, 2
    /* 0AEDA8 001AECA8 21105500 */  addu       $2, $2, $21
    /* 0AEDAC 001AECAC 000840E4 */  swc1       $f0, 0x800($2)
    /* 0AEDB0 001AECB0 0041023C */  lui        $2, (0x41000000 >> 16)
    /* 0AEDB4 001AECB4 00008244 */  mtc1       $2, $f0
    /* 0AEDB8 001AECB8 00000000 */  nop
    /* 0AEDBC 001AECBC 42000246 */  mul.s      $f1, $f0, $f2
    /* 0AEDC0 001AECC0 3443023C */  lui        $2, (0x43340000 >> 16)
    /* 0AEDC4 001AECC4 00008244 */  mtc1       $2, $f0
    /* 0AEDC8 001AECC8 00000000 */  nop
    /* 0AEDCC 001AECCC 01000146 */  sub.s      $f0, $f0, $f1
    /* 0AEDD0 001AECD0 000DA28E */  lw         $2, 0xD00($21)
    /* 0AEDD4 001AECD4 21100202 */  addu       $2, $16, $2
    /* 0AEDD8 001AECD8 80100200 */  sll        $2, $2, 2
    /* 0AEDDC 001AECDC 21105500 */  addu       $2, $2, $21
    /* 0AEDE0 001AECE0 000940E4 */  swc1       $f0, 0x900($2)
    /* 0AEDE4 001AECE4 000DA28E */  lw         $2, 0xD00($21)
    /* 0AEDE8 001AECE8 21100202 */  addu       $2, $16, $2
    /* 0AEDEC 001AECEC 80100200 */  sll        $2, $2, 2
    /* 0AEDF0 001AECF0 21105500 */  addu       $2, $2, $21
    /* 0AEDF4 001AECF4 000C40AC */  sw         $0, 0xC00($2)
    /* 0AEDF8 001AECF8 01001026 */  addiu      $16, $16, 0x1
  .L001AECFC:
    /* 0AEDFC 001AECFC 1800022A */  slti       $2, $16, 0x18
    /* 0AEE00 001AED00 A3FF4014 */  bnez       $2, .L001AEB90
    /* 0AEE04 001AED04 00000000 */   nop
    /* 0AEE08 001AED08 FC09B2AE */  sw         $18, 0x9FC($21)
    /* 0AEE0C 001AED0C FC0AB1AE */  sw         $17, 0xAFC($21)
    /* 0AEE10 001AED10 FFFF0224 */  addiu      $2, $0, -0x1
    /* 0AEE14 001AED14 6000BF7B */  lq         $31, 0x60($29)
    /* 0AEE18 001AED18 5000B57B */  lq         $21, 0x50($29)
    /* 0AEE1C 001AED1C 4000B47B */  lq         $20, 0x40($29)
    /* 0AEE20 001AED20 3000B37B */  lq         $19, 0x30($29)
    /* 0AEE24 001AED24 2000B27B */  lq         $18, 0x20($29)
    /* 0AEE28 001AED28 1000B17B */  lq         $17, 0x10($29)
    /* 0AEE2C 001AED2C 0000B07B */  lq         $16, 0x0($29)
    /* 0AEE30 001AED30 8000BD27 */  addiu      $29, $29, 0x80
    /* 0AEE34 001AED34 0800E003 */  jr         $31
    /* 0AEE38 001AED38 00000000 */   nop
    /* 0AEE3C 001AED3C 00000000 */  nop

glabel Set__13CSHOT_FIREBARFPfPfii
    /* 0AEE40 001AED40 90FFBD27 */  addiu      $29, $29, -0x70
    /* 0AEE44 001AED44 5000BF7F */  sq         $31, 0x50($29)
    /* 0AEE48 001AED48 4000B47F */  sq         $20, 0x40($29)
    /* 0AEE4C 001AED4C 3000B37F */  sq         $19, 0x30($29)
    /* 0AEE50 001AED50 2000B27F */  sq         $18, 0x20($29)
    /* 0AEE54 001AED54 1000B17F */  sq         $17, 0x10($29)
    /* 0AEE58 001AED58 0000B07F */  sq         $16, 0x0($29)
    /* 0AEE5C 001AED5C 28A68070 */  paddub     $20, $4, $0
    /* 0AEE60 001AED60 289EA070 */  paddub     $19, $5, $0
    /* 0AEE64 001AED64 2886C070 */  paddub     $16, $6, $0
    /* 0AEE68 001AED68 2896E070 */  paddub     $18, $7, $0
    /* 0AEE6C 001AED6C 288E0071 */  paddub     $17, $8, $0
    /* 0AEE70 001AED70 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 0AEE74 001AED74 0C00C2AC */  sw         $2, 0xC($6)
    /* 0AEE78 001AED78 28260072 */  paddub     $4, $16, $0
    /* 0AEE7C 001AED7C 282E0072 */  paddub     $5, $16, $0
    /* 0AEE80 001AED80 9285040C */  jal        sceVu0Normalize
    /* 0AEE84 001AED84 00000000 */   nop
    /* 0AEE88 001AED88 0040023C */  lui        $2, (0x40000000 >> 16)
    /* 0AEE8C 001AED8C 00608244 */  mtc1       $2, $f12
    /* 0AEE90 001AED90 6000A427 */  addiu      $4, $29, 0x60
    /* 0AEE94 001AED94 282E0072 */  paddub     $5, $16, $0
    /* 0AEE98 001AED98 4688040C */  jal        sceVu0ScaleVectorXYZ
    /* 0AEE9C 001AED9C 00000000 */   nop
    /* 0AEEA0 001AEDA0 28860070 */  paddub     $16, $0, $0
    /* 0AEEA4 001AEDA4 60000010 */  b          .L001AEF28
    /* 0AEEA8 001AEDA8 00000000 */   nop
  .L001AEDAC:
    /* 0AEEAC 001AEDAC 000D828E */  lw         $2, 0xD00($20)
    /* 0AEEB0 001AEDB0 21100202 */  addu       $2, $16, $2
    /* 0AEEB4 001AEDB4 00110200 */  sll        $2, $2, 4
    /* 0AEEB8 001AEDB8 000061C6 */  lwc1       $f1, 0x0($19)
    /* 0AEEBC 001AEDBC 00009044 */  mtc1       $16, $f0
    /* 0AEEC0 001AEDC0 00000000 */  nop
    /* 0AEEC4 001AEDC4 E0008046 */  cvt.s.w    $f3, $f0
    /* 0AEEC8 001AEDC8 6000A0C7 */  lwc1       $f0, 0x60($29)
    /* 0AEECC 001AEDCC 02000346 */  mul.s      $f0, $f0, $f3
    /* 0AEED0 001AEDD0 40080046 */  add.s      $f1, $f1, $f0
    /* 0AEED4 001AEDD4 21188202 */  addu       $3, $20, $2
    /* 0AEED8 001AEDD8 000060C4 */  lwc1       $f0, 0x0($3)
    /* 0AEEDC 001AEDDC 81080046 */  sub.s      $f2, $f1, $f0
    /* 0AEEE0 001AEDE0 003F023C */  lui        $2, (0x3F000000 >> 16)
    /* 0AEEE4 001AEDE4 00008244 */  mtc1       $2, $f0
    /* 0AEEE8 001AEDE8 00000000 */  nop
    /* 0AEEEC 001AEDEC 42000346 */  mul.s      $f1, $f0, $f3
    /* 0AEEF0 001AEDF0 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 0AEEF4 001AEDF4 00008244 */  mtc1       $2, $f0
    /* 0AEEF8 001AEDF8 00000000 */  nop
    /* 0AEEFC 001AEDFC 00010146 */  add.s      $f4, $f0, $f1
    /* 0AEF00 001AEE00 03100446 */  div.s      $f0, $f2, $f4
    /* 0AEF04 001AEE04 000460E4 */  swc1       $f0, 0x400($3)
    /* 0AEF08 001AEE08 000D828E */  lw         $2, 0xD00($20)
    /* 0AEF0C 001AEE0C 21100202 */  addu       $2, $16, $2
    /* 0AEF10 001AEE10 00110200 */  sll        $2, $2, 4
    /* 0AEF14 001AEE14 040061C6 */  lwc1       $f1, 0x4($19)
    /* 0AEF18 001AEE18 6400A0C7 */  lwc1       $f0, 0x64($29)
    /* 0AEF1C 001AEE1C 02000346 */  mul.s      $f0, $f0, $f3
    /* 0AEF20 001AEE20 40080046 */  add.s      $f1, $f1, $f0
    /* 0AEF24 001AEE24 21105400 */  addu       $2, $2, $20
    /* 0AEF28 001AEE28 040040C4 */  lwc1       $f0, 0x4($2)
    /* 0AEF2C 001AEE2C 01080046 */  sub.s      $f0, $f1, $f0
    /* 0AEF30 001AEE30 03000446 */  div.s      $f0, $f0, $f4
    /* 0AEF34 001AEE34 040440E4 */  swc1       $f0, 0x404($2)
    /* 0AEF38 001AEE38 000D828E */  lw         $2, 0xD00($20)
    /* 0AEF3C 001AEE3C 21100202 */  addu       $2, $16, $2
    /* 0AEF40 001AEE40 00110200 */  sll        $2, $2, 4
    /* 0AEF44 001AEE44 080061C6 */  lwc1       $f1, 0x8($19)
    /* 0AEF48 001AEE48 6800A0C7 */  lwc1       $f0, 0x68($29)
    /* 0AEF4C 001AEE4C 02000346 */  mul.s      $f0, $f0, $f3
    /* 0AEF50 001AEE50 40080046 */  add.s      $f1, $f1, $f0
    /* 0AEF54 001AEE54 21105400 */  addu       $2, $2, $20
    /* 0AEF58 001AEE58 080040C4 */  lwc1       $f0, 0x8($2)
    /* 0AEF5C 001AEE5C 01080046 */  sub.s      $f0, $f1, $f0
    /* 0AEF60 001AEE60 03000446 */  div.s      $f0, $f0, $f4
    /* 0AEF64 001AEE64 080440E4 */  swc1       $f0, 0x408($2)
    /* 0AEF68 001AEE68 000D828E */  lw         $2, 0xD00($20)
    /* 0AEF6C 001AEE6C 21100202 */  addu       $2, $16, $2
    /* 0AEF70 001AEE70 80100200 */  sll        $2, $2, 2
    /* 0AEF74 001AEE74 21105400 */  addu       $2, $2, $20
    /* 0AEF78 001AEE78 000C40AC */  sw         $0, 0xC00($2)
    /* 0AEF7C 001AEE7C BE11040C */  jal        rand
    /* 0AEF80 001AEE80 00000000 */   nop
    /* 0AEF84 001AEE84 00008244 */  mtc1       $2, $f0
    /* 0AEF88 001AEE88 00000000 */  nop
    /* 0AEF8C 001AEE8C 20008046 */  cvt.s.w    $f0, $f0
    /* 0AEF90 001AEE90 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0AEF94 001AEE94 00188244 */  mtc1       $2, $f3
    /* 0AEF98 001AEE98 00000000 */  nop
    /* 0AEF9C 001AEE9C 42180046 */  mul.s      $f1, $f3, $f0
    /* 0AEFA0 001AEEA0 004F023C */  lui        $2, (0x4F000000 >> 16)
    /* 0AEFA4 001AEEA4 00008244 */  mtc1       $2, $f0
    /* 0AEFA8 001AEEA8 00000000 */  nop
    /* 0AEFAC 001AEEAC 83080046 */  div.s      $f2, $f1, $f0
    /* 0AEFB0 001AEEB0 00009044 */  mtc1       $16, $f0
    /* 0AEFB4 001AEEB4 00000000 */  nop
    /* 0AEFB8 001AEEB8 60008046 */  cvt.s.w    $f1, $f0
    /* 0AEFBC 001AEEBC 908280C7 */  lwc1       $f0, -0x7D70($28)
    /* 0AEFC0 001AEEC0 02000146 */  mul.s      $f0, $f0, $f1
    /* 0AEFC4 001AEEC4 00180046 */  add.s      $f0, $f3, $f0
    /* 0AEFC8 001AEEC8 00000246 */  add.s      $f0, $f0, $f2
    /* 0AEFCC 001AEECC 000D828E */  lw         $2, 0xD00($20)
    /* 0AEFD0 001AEED0 21100202 */  addu       $2, $16, $2
    /* 0AEFD4 001AEED4 80100200 */  sll        $2, $2, 2
    /* 0AEFD8 001AEED8 21105400 */  addu       $2, $2, $20
    /* 0AEFDC 001AEEDC 000840E4 */  swc1       $f0, 0x800($2)
    /* 0AEFE0 001AEEE0 0041023C */  lui        $2, (0x41000000 >> 16)
    /* 0AEFE4 001AEEE4 00008244 */  mtc1       $2, $f0
    /* 0AEFE8 001AEEE8 00000000 */  nop
    /* 0AEFEC 001AEEEC 42000146 */  mul.s      $f1, $f0, $f1
    /* 0AEFF0 001AEEF0 3443023C */  lui        $2, (0x43340000 >> 16)
    /* 0AEFF4 001AEEF4 00008244 */  mtc1       $2, $f0
    /* 0AEFF8 001AEEF8 00000000 */  nop
    /* 0AEFFC 001AEEFC 01000146 */  sub.s      $f0, $f0, $f1
    /* 0AF000 001AEF00 000D828E */  lw         $2, 0xD00($20)
    /* 0AF004 001AEF04 21100202 */  addu       $2, $16, $2
    /* 0AF008 001AEF08 80100200 */  sll        $2, $2, 2
    /* 0AF00C 001AEF0C 21105400 */  addu       $2, $2, $20
    /* 0AF010 001AEF10 000940E4 */  swc1       $f0, 0x900($2)
    /* 0AF014 001AEF14 80101000 */  sll        $2, $16, 2
    /* 0AF018 001AEF18 21105400 */  addu       $2, $2, $20
    /* 0AF01C 001AEF1C 000A52AC */  sw         $18, 0xA00($2)
    /* 0AF020 001AEF20 000B51AC */  sw         $17, 0xB00($2)
    /* 0AF024 001AEF24 01001026 */  addiu      $16, $16, 0x1
  .L001AEF28:
    /* 0AF028 001AEF28 1800022A */  slti       $2, $16, 0x18
    /* 0AF02C 001AEF2C 9FFF4014 */  bnez       $2, .L001AEDAC
    /* 0AF030 001AEF30 00000000 */   nop
    /* 0AF034 001AEF34 FFFF0224 */  addiu      $2, $0, -0x1
    /* 0AF038 001AEF38 5000BF7B */  lq         $31, 0x50($29)
    /* 0AF03C 001AEF3C 4000B47B */  lq         $20, 0x40($29)
    /* 0AF040 001AEF40 3000B37B */  lq         $19, 0x30($29)
    /* 0AF044 001AEF44 2000B27B */  lq         $18, 0x20($29)
    /* 0AF048 001AEF48 1000B17B */  lq         $17, 0x10($29)
    /* 0AF04C 001AEF4C 0000B07B */  lq         $16, 0x0($29)
    /* 0AF050 001AEF50 7000BD27 */  addiu      $29, $29, 0x70
    /* 0AF054 001AEF54 0800E003 */  jr         $31
    /* 0AF058 001AEF58 00000000 */   nop
    /* 0AF05C 001AEF5C 00000000 */  nop

glabel Rset__13CSHOT_FIREBARFv
    /* 0AF060 001AEF60 28360070 */  paddub     $6, $0, $0
    /* 0AF064 001AEF64 06000010 */  b          .L001AEF80
    /* 0AF068 001AEF68 00000000 */   nop
  .L001AEF6C:
    /* 0AF06C 001AEF6C FFFF0524 */  addiu      $5, $0, -0x1
    /* 0AF070 001AEF70 80180600 */  sll        $3, $6, 2
    /* 0AF074 001AEF74 21186400 */  addu       $3, $3, $4
    /* 0AF078 001AEF78 000C65AC */  sw         $5, 0xC00($3)
    /* 0AF07C 001AEF7C 0100C624 */  addiu      $6, $6, 0x1
  .L001AEF80:
    /* 0AF080 001AEF80 1800C328 */  slti       $3, $6, 0x18
    /* 0AF084 001AEF84 F9FF6014 */  bnez       $3, .L001AEF6C
    /* 0AF088 001AEF88 00000000 */   nop
    /* 0AF08C 001AEF8C 0800E003 */  jr         $31
    /* 0AF090 001AEF90 00000000 */   nop
    /* 0AF094 001AEF94 00000000 */  nop
    /* 0AF098 001AEF98 00000000 */  nop
    /* 0AF09C 001AEF9C 00000000 */  nop

glabel Step__13CSHOT_FIREBARFv
    /* 0AF0A0 001AEFA0 A0FFBD27 */  addiu      $29, $29, -0x60
    /* 0AF0A4 001AEFA4 5000BF7F */  sq         $31, 0x50($29)
    /* 0AF0A8 001AEFA8 4000B47F */  sq         $20, 0x40($29)
    /* 0AF0AC 001AEFAC 3000B37F */  sq         $19, 0x30($29)
    /* 0AF0B0 001AEFB0 2000B27F */  sq         $18, 0x20($29)
    /* 0AF0B4 001AEFB4 1000B17F */  sq         $17, 0x10($29)
    /* 0AF0B8 001AEFB8 0000B07F */  sq         $16, 0x0($29)
    /* 0AF0BC 001AEFBC 28A68070 */  paddub     $20, $4, $0
    /* 0AF0C0 001AEFC0 90938383 */  lb         $3, %gp_rel(init$1152)($28)
    /* 0AF0C4 001AEFC4 04006014 */  bnez       $3, .L001AEFD8
    /* 0AF0C8 001AEFC8 00000000 */   nop
    /* 0AF0CC 001AEFCC 8C9380AF */  sw         $0, %gp_rel(msg_cnt$1151)($28)
    /* 0AF0D0 001AEFD0 01000324 */  addiu      $3, $0, 0x1
    /* 0AF0D4 001AEFD4 909383A3 */  sb         $3, %gp_rel(init$1152)($28)
  .L001AEFD8:
    /* 0AF0D8 001AEFD8 8C93838F */  lw         $3, %gp_rel(msg_cnt$1151)($28)
    /* 0AF0DC 001AEFDC 01006324 */  addiu      $3, $3, 0x1
    /* 0AF0E0 001AEFE0 8C9383AF */  sw         $3, %gp_rel(msg_cnt$1151)($28)
    /* 0AF0E4 001AEFE4 8C93838F */  lw         $3, %gp_rel(msg_cnt$1151)($28)
    /* 0AF0E8 001AEFE8 1E006328 */  slti       $3, $3, 0x1E
    /* 0AF0EC 001AEFEC 02006014 */  bnez       $3, .L001AEFF8
    /* 0AF0F0 001AEFF0 00000000 */   nop
    /* 0AF0F4 001AEFF4 8C9380AF */  sw         $0, %gp_rel(msg_cnt$1151)($28)
  .L001AEFF8:
    /* 0AF0F8 001AEFF8 28860070 */  paddub     $16, $0, $0
    /* 0AF0FC 001AEFFC 6A000010 */  b          .L001AF1A8
    /* 0AF100 001AF000 00000000 */   nop
  .L001AF004:
    /* 0AF104 001AF004 80181000 */  sll        $3, $16, 2
    /* 0AF108 001AF008 21307400 */  addu       $6, $3, $20
    /* 0AF10C 001AF00C 000CD324 */  addiu      $19, $6, 0xC00
    /* 0AF110 001AF010 000CC48C */  lw         $4, 0xC00($6)
    /* 0AF114 001AF014 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0AF118 001AF018 62008310 */  beq        $4, $3, .L001AF1A4
    /* 0AF11C 001AF01C 00000000 */   nop
    /* 0AF120 001AF020 60008014 */  bnez       $4, .L001AF1A4
    /* 0AF124 001AF024 00000000 */   nop
    /* 0AF128 001AF028 0009D224 */  addiu      $18, $6, 0x900
    /* 0AF12C 001AF02C 0009C0C4 */  lwc1       $f0, 0x900($6)
    /* 0AF130 001AF030 8040033C */  lui        $3, (0x40800000 >> 16)
    /* 0AF134 001AF034 00608344 */  mtc1       $3, $f12
    /* 0AF138 001AF038 00000000 */  nop
    /* 0AF13C 001AF03C 01000C46 */  sub.s      $f0, $f0, $f12
    /* 0AF140 001AF040 0009C0E4 */  swc1       $f0, 0x900($6)
    /* 0AF144 001AF044 0008C1C4 */  lwc1       $f1, 0x800($6)
    /* 0AF148 001AF048 C48580C7 */  lwc1       $f0, -0x7A3C($28)
    /* 0AF14C 001AF04C 00080046 */  add.s      $f0, $f1, $f0
    /* 0AF150 001AF050 0008C0E4 */  swc1       $f0, 0x800($6)
    /* 0AF154 001AF054 8C93838F */  lw         $3, %gp_rel(msg_cnt$1151)($28)
    /* 0AF158 001AF058 3A006014 */  bnez       $3, .L001AF144
    /* 0AF15C 001AF05C 00000000 */   nop
    /* 0AF160 001AF060 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 0AF164 001AF064 00688244 */  mtc1       $2, $f13
    /* 0AF168 001AF068 00111000 */  sll        $2, $16, 4
    /* 0AF16C 001AF06C 21288202 */  addu       $5, $20, $2
    /* 0AF170 001AF070 F09D848F */  lw         $4, -0x6210($28)
    /* 0AF174 001AF074 000AC68C */  lw         $6, 0xA00($6)
    /* 0AF178 001AF078 02000724 */  addiu      $7, $0, 0x2
    /* 0AF17C 001AF07C 2846E070 */  paddub     $8, $7, $0
    /* 0AF180 001AF080 284EE070 */  paddub     $9, $7, $0
    /* 0AF184 001AF084 28560070 */  paddub     $10, $0, $0
    /* 0AF188 001AF088 285E0070 */  paddub     $11, $0, $0
    /* 0AF18C 001AF08C E8D5060C */  jal        Set__14CCollisionDataFPfiiffiiii
    /* 0AF190 001AF090 00000000 */   nop
    /* 0AF194 001AF094 F09D858F */  lw         $5, -0x6210($28)
    /* 0AF198 001AF098 05000424 */  addiu      $4, $0, 0x5
    /* 0AF19C 001AF09C 803DA38C */  lw         $3, 0x3D80($5)
    /* 0AF1A0 001AF0A0 80100300 */  sll        $2, $3, 2
    /* 0AF1A4 001AF0A4 21104300 */  addu       $2, $2, $3
    /* 0AF1A8 001AF0A8 40110200 */  sll        $2, $2, 5
    /* 0AF1AC 001AF0AC 21104500 */  addu       $2, $2, $5
    /* 0AF1B0 001AF0B0 580044AC */  sw         $4, 0x58($2)
    /* 0AF1B4 001AF0B4 06000424 */  addiu      $4, $0, 0x6
    /* 0AF1B8 001AF0B8 803DA38C */  lw         $3, 0x3D80($5)
    /* 0AF1BC 001AF0BC 80100300 */  sll        $2, $3, 2
    /* 0AF1C0 001AF0C0 21104300 */  addu       $2, $2, $3
    /* 0AF1C4 001AF0C4 40110200 */  sll        $2, $2, 5
    /* 0AF1C8 001AF0C8 21104500 */  addu       $2, $2, $5
    /* 0AF1CC 001AF0CC 600044AC */  sw         $4, 0x60($2)
    /* 0AF1D0 001AF0D0 049D828F */  lw         $2, -0x62FC($28)
    /* 0AF1D4 001AF0D4 EE004484 */  lh         $4, 0xEE($2)
    /* 0AF1D8 001AF0D8 F09D858F */  lw         $5, -0x6210($28)
    /* 0AF1DC 001AF0DC 803DA38C */  lw         $3, 0x3D80($5)
    /* 0AF1E0 001AF0E0 80100300 */  sll        $2, $3, 2
    /* 0AF1E4 001AF0E4 21104300 */  addu       $2, $2, $3
    /* 0AF1E8 001AF0E8 40110200 */  sll        $2, $2, 5
    /* 0AF1EC 001AF0EC 21104500 */  addu       $2, $2, $5
    /* 0AF1F0 001AF0F0 6C0044AC */  sw         $4, 0x6C($2)
    /* 0AF1F4 001AF0F4 049D828F */  lw         $2, -0x62FC($28)
    /* 0AF1F8 001AF0F8 1C004424 */  addiu      $4, $2, 0x1C
    /* 0AF1FC 001AF0FC F09D858F */  lw         $5, -0x6210($28)
    /* 0AF200 001AF100 803DA38C */  lw         $3, 0x3D80($5)
    /* 0AF204 001AF104 80100300 */  sll        $2, $3, 2
    /* 0AF208 001AF108 21104300 */  addu       $2, $2, $3
    /* 0AF20C 001AF10C 40110200 */  sll        $2, $2, 5
    /* 0AF210 001AF110 21104500 */  addu       $2, $2, $5
    /* 0AF214 001AF114 640044AC */  sw         $4, 0x64($2)
    /* 0AF218 001AF118 049D828F */  lw         $2, -0x62FC($28)
    /* 0AF21C 001AF11C 16004480 */  lb         $4, 0x16($2)
    /* 0AF220 001AF120 F09D918F */  lw         $17, -0x6210($28)
    /* 0AF224 001AF124 7CDA060C */  jal        GetWeaponElementAttr__Fi
    /* 0AF228 001AF128 00000000 */   nop
    /* 0AF22C 001AF12C 803D248E */  lw         $4, 0x3D80($17)
    /* 0AF230 001AF130 80180400 */  sll        $3, $4, 2
    /* 0AF234 001AF134 21186400 */  addu       $3, $3, $4
    /* 0AF238 001AF138 40190300 */  sll        $3, $3, 5
    /* 0AF23C 001AF13C 21187100 */  addu       $3, $3, $17
    /* 0AF240 001AF140 500062AC */  sw         $2, 0x50($3)
  .L001AF144:
    /* 0AF244 001AF144 00191000 */  sll        $3, $16, 4
    /* 0AF248 001AF148 21187400 */  addu       $3, $3, $20
    /* 0AF24C 001AF14C 000461C4 */  lwc1       $f1, 0x400($3)
    /* 0AF250 001AF150 000060C4 */  lwc1       $f0, 0x0($3)
    /* 0AF254 001AF154 00000146 */  add.s      $f0, $f0, $f1
    /* 0AF258 001AF158 000060E4 */  swc1       $f0, 0x0($3)
    /* 0AF25C 001AF15C 040461C4 */  lwc1       $f1, 0x404($3)
    /* 0AF260 001AF160 040060C4 */  lwc1       $f0, 0x4($3)
    /* 0AF264 001AF164 00000146 */  add.s      $f0, $f0, $f1
    /* 0AF268 001AF168 040060E4 */  swc1       $f0, 0x4($3)
    /* 0AF26C 001AF16C 080461C4 */  lwc1       $f1, 0x408($3)
    /* 0AF270 001AF170 080060C4 */  lwc1       $f0, 0x8($3)
    /* 0AF274 001AF174 00000146 */  add.s      $f0, $f0, $f1
    /* 0AF278 001AF178 080060E4 */  swc1       $f0, 0x8($3)
    /* 0AF27C 001AF17C 000041C6 */  lwc1       $f1, 0x0($18)
    /* 0AF280 001AF180 0042033C */  lui        $3, (0x42000000 >> 16)
    /* 0AF284 001AF184 00008344 */  mtc1       $3, $f0
    /* 0AF288 001AF188 00000000 */  nop
    /* 0AF28C 001AF18C 36080046 */  c.le.s     $f1, $f0
    /* 0AF290 001AF190 00000000 */  nop
    /* 0AF294 001AF194 03000045 */  bc1f       .L001AF1A4
    /* 0AF298 001AF198 00000000 */   nop
    /* 0AF29C 001AF19C FFFF0324 */  addiu      $3, $0, -0x1
    /* 0AF2A0 001AF1A0 000063AE */  sw         $3, 0x0($19)
  .L001AF1A4:
    /* 0AF2A4 001AF1A4 01001026 */  addiu      $16, $16, 0x1
  .L001AF1A8:
    /* 0AF2A8 001AF1A8 1800032A */  slti       $3, $16, 0x18
    /* 0AF2AC 001AF1AC 95FF6014 */  bnez       $3, .L001AF004
    /* 0AF2B0 001AF1B0 00000000 */   nop
    /* 0AF2B4 001AF1B4 5000BF7B */  lq         $31, 0x50($29)
    /* 0AF2B8 001AF1B8 4000B47B */  lq         $20, 0x40($29)
    /* 0AF2BC 001AF1BC 3000B37B */  lq         $19, 0x30($29)
    /* 0AF2C0 001AF1C0 2000B27B */  lq         $18, 0x20($29)
    /* 0AF2C4 001AF1C4 1000B17B */  lq         $17, 0x10($29)
    /* 0AF2C8 001AF1C8 0000B07B */  lq         $16, 0x0($29)
    /* 0AF2CC 001AF1CC 6000BD27 */  addiu      $29, $29, 0x60
    /* 0AF2D0 001AF1D0 0800E003 */  jr         $31
    /* 0AF2D4 001AF1D4 00000000 */   nop
    /* 0AF2D8 001AF1D8 00000000 */  nop
    /* 0AF2DC 001AF1DC 00000000 */  nop

glabel Draw__13CSHOT_FIREBARFv
    /* 0AF2E0 001AF1E0 90FFBD27 */  addiu      $29, $29, -0x70
    /* 0AF2E4 001AF1E4 6000BF7F */  sq         $31, 0x60($29)
    /* 0AF2E8 001AF1E8 5000B57F */  sq         $21, 0x50($29)
    /* 0AF2EC 001AF1EC 4000B47F */  sq         $20, 0x40($29)
    /* 0AF2F0 001AF1F0 3000B37F */  sq         $19, 0x30($29)
    /* 0AF2F4 001AF1F4 2000B27F */  sq         $18, 0x20($29)
    /* 0AF2F8 001AF1F8 1000B17F */  sq         $17, 0x10($29)
    /* 0AF2FC 001AF1FC 0000B07F */  sq         $16, 0x0($29)
    /* 0AF300 001AF200 28AE8070 */  paddub     $21, $4, $0
    /* 0AF304 001AF204 28860070 */  paddub     $16, $0, $0
    /* 0AF308 001AF208 289E0070 */  paddub     $19, $0, $0
    /* 0AF30C 001AF20C 47000010 */  b          .L001AF32C
    /* 0AF310 001AF210 00000000 */   nop
  .L001AF214:
    /* 0AF314 001AF214 80A01300 */  sll        $20, $19, 2
    /* 0AF318 001AF218 21189502 */  addu       $3, $20, $21
    /* 0AF31C 001AF21C 000C668C */  lw         $6, 0xC00($3)
    /* 0AF320 001AF220 FFFF0324 */  addiu      $3, $0, -0x1
    /* 0AF324 001AF224 4000C310 */  beq        $6, $3, .L001AF328
    /* 0AF328 001AF228 00000000 */   nop
    /* 0AF32C 001AF22C 08000016 */  bnez       $16, .L001AF250
    /* 0AF330 001AF230 00000000 */   nop
    /* 0AF334 001AF234 C701023C */  lui        $2, %hi(TexManager)
    /* 0AF338 001AF238 70584424 */  addiu      $4, $2, %lo(TexManager)
    /* 0AF33C 001AF23C D48B858F */  lw         $5, -0x742C($28)
    /* 0AF340 001AF240 46000624 */  addiu      $6, $0, 0x46
    /* 0AF344 001AF244 1CCC040C */  jal        ReloadTexture__15CTextureManagerFP13sceVif1Packeti
    /* 0AF348 001AF248 00000000 */   nop
    /* 0AF34C 001AF24C 01001024 */  addiu      $16, $0, 0x1
  .L001AF250:
    /* 0AF350 001AF250 21109502 */  addu       $2, $20, $21
    /* 0AF354 001AF254 000B438C */  lw         $3, 0xB00($2)
    /* 0AF358 001AF258 04000224 */  addiu      $2, $0, 0x4
    /* 0AF35C 001AF25C 1C006210 */  beq        $3, $2, .L001AF2D0
    /* 0AF360 001AF260 00000000 */   nop
    /* 0AF364 001AF264 03000224 */  addiu      $2, $0, 0x3
    /* 0AF368 001AF268 15006210 */  beq        $3, $2, .L001AF2C0
    /* 0AF36C 001AF26C 00000000 */   nop
    /* 0AF370 001AF270 02000224 */  addiu      $2, $0, 0x2
    /* 0AF374 001AF274 0E006210 */  beq        $3, $2, .L001AF2B0
    /* 0AF378 001AF278 00000000 */   nop
    /* 0AF37C 001AF27C 01001224 */  addiu      $18, $0, 0x1
    /* 0AF380 001AF280 08007210 */  beq        $3, $18, .L001AF2A4
    /* 0AF384 001AF284 00000000 */   nop
    /* 0AF388 001AF288 03006010 */  beqz       $3, .L001AF298
    /* 0AF38C 001AF28C 00000000 */   nop
    /* 0AF390 001AF290 13000010 */  b          .L001AF2E0
    /* 0AF394 001AF294 00000000 */   nop
  .L001AF298:
    /* 0AF398 001AF298 288E0070 */  paddub     $17, $0, $0
    /* 0AF39C 001AF29C 11000010 */  b          .L001AF2E4
    /* 0AF3A0 001AF2A0 00000000 */   nop
  .L001AF2A4:
    /* 0AF3A4 001AF2A4 288E4072 */  paddub     $17, $18, $0
    /* 0AF3A8 001AF2A8 0E000010 */  b          .L001AF2E4
    /* 0AF3AC 001AF2AC 00000000 */   nop
  .L001AF2B0:
    /* 0AF3B0 001AF2B0 01001124 */  addiu      $17, $0, 0x1
    /* 0AF3B4 001AF2B4 28960070 */  paddub     $18, $0, $0
    /* 0AF3B8 001AF2B8 0A000010 */  b          .L001AF2E4
    /* 0AF3BC 001AF2BC 00000000 */   nop
  .L001AF2C0:
    /* 0AF3C0 001AF2C0 288E0070 */  paddub     $17, $0, $0
    /* 0AF3C4 001AF2C4 28960070 */  paddub     $18, $0, $0
    /* 0AF3C8 001AF2C8 06000010 */  b          .L001AF2E4
    /* 0AF3CC 001AF2CC 00000000 */   nop
  .L001AF2D0:
    /* 0AF3D0 001AF2D0 02001124 */  addiu      $17, $0, 0x2
    /* 0AF3D4 001AF2D4 01001224 */  addiu      $18, $0, 0x1
    /* 0AF3D8 001AF2D8 02000010 */  b          .L001AF2E4
    /* 0AF3DC 001AF2DC 00000000 */   nop
  .L001AF2E0:
    /* 0AF3E0 001AF2E0 288E0070 */  paddub     $17, $0, $0
  .L001AF2E4:
    /* 0AF3E4 001AF2E4 21109502 */  addu       $2, $20, $21
    /* 0AF3E8 001AF2E8 00094CC4 */  lwc1       $f12, 0x900($2)
    /* 0AF3EC 001AF2EC 2C44040C */  jal        fptosi
    /* 0AF3F0 001AF2F0 00000000 */   nop
    /* 0AF3F4 001AF2F4 FF004A30 */  andi       $10, $2, 0xFF
    /* 0AF3F8 001AF2F8 00111300 */  sll        $2, $19, 4
    /* 0AF3FC 001AF2FC 2120A202 */  addu       $4, $21, $2
    /* 0AF400 001AF300 21189502 */  addu       $3, $20, $21
    /* 0AF404 001AF304 C0311100 */  sll        $6, $17, 7
    /* 0AF408 001AF308 C0391200 */  sll        $7, $18, 7
    /* 0AF40C 001AF30C 2A00023C */  lui        $2, %hi("@1211")
    /* 0AF410 001AF310 30B54524 */  addiu      $5, $2, %lo("@1211")
    /* 0AF414 001AF314 00086CC4 */  lwc1       $f12, 0x800($3)
    /* 0AF418 001AF318 80000824 */  addiu      $8, $0, 0x80
    /* 0AF41C 001AF31C 284E0071 */  paddub     $9, $8, $0
    /* 0AF420 001AF320 C0AE060C */  jal        set3DCellModel__FPfPcfiiiiUc
    /* 0AF424 001AF324 00000000 */   nop
  .L001AF328:
    /* 0AF428 001AF328 01007326 */  addiu      $19, $19, 0x1
  .L001AF32C:
    /* 0AF42C 001AF32C 1800632A */  slti       $3, $19, 0x18
    /* 0AF430 001AF330 B8FF6014 */  bnez       $3, .L001AF214
    /* 0AF434 001AF334 00000000 */   nop
    /* 0AF438 001AF338 6000BF7B */  lq         $31, 0x60($29)
    /* 0AF43C 001AF33C 5000B57B */  lq         $21, 0x50($29)
    /* 0AF440 001AF340 4000B47B */  lq         $20, 0x40($29)
    /* 0AF444 001AF344 3000B37B */  lq         $19, 0x30($29)
    /* 0AF448 001AF348 2000B27B */  lq         $18, 0x20($29)
    /* 0AF44C 001AF34C 1000B17B */  lq         $17, 0x10($29)
    /* 0AF450 001AF350 0000B07B */  lq         $16, 0x0($29)
    /* 0AF454 001AF354 7000BD27 */  addiu      $29, $29, 0x70
    /* 0AF458 001AF358 0800E003 */  jr         $31
    /* 0AF45C 001AF35C 00000000 */   nop

.section .rodata, "a"
.align 4

/* Generated by spimdisasm 1.42.4 */

glabel "@1211"
    /* 19B630 0029B530 63303577 */ .word 0x77353063
    /* 19B634 0029B534 5F680000 */ .word 0x0000685F
