.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel Draw__11CBombEffectFP7CCamerai
    /* 001910 01DAD610 C0FEBD27 */  addiu      $29, $29, -0x140
    /* 001914 01DAD614 9000BF7F */  sq         $31, 0x90($29)
    /* 001918 01DAD618 8000BE7F */  sq         $30, 0x80($29)
    /* 00191C 01DAD61C 7000B77F */  sq         $23, 0x70($29)
    /* 001920 01DAD620 6000B67F */  sq         $22, 0x60($29)
    /* 001924 01DAD624 5000B57F */  sq         $21, 0x50($29)
    /* 001928 01DAD628 4000B47F */  sq         $20, 0x40($29)
    /* 00192C 01DAD62C 3000B37F */  sq         $19, 0x30($29)
    /* 001930 01DAD630 2000B27F */  sq         $18, 0x20($29)
    /* 001934 01DAD634 1000B17F */  sq         $17, 0x10($29)
    /* 001938 01DAD638 0000B07F */  sq         $16, 0x0($29)
    /* 00193C 01DAD63C 28AE8070 */  paddub     $21, $4, $0
    /* 001940 01DAD640 28B6C070 */  paddub     $22, $6, $0
    /* 001944 01DAD644 2826A070 */  paddub     $4, $5, $0
    /* 001948 01DAD648 A000A527 */  addiu      $5, $29, 0xA0
    /* 00194C 01DAD64C 9C91040C */  jal        GetPos__7CCameraFPf
    /* 001950 01DAD650 00000000 */   nop
    /* 001954 01DAD654 3001A427 */  addiu      $4, $29, 0x130
    /* 001958 01DAD658 F88B82DF */  ld         $2, -0x7408($28)
    /* 00195C 01DAD65C 000082FC */  sd         $2, 0x0($4)
    /* 001960 01DAD660 3001A393 */  lbu        $3, 0x130($29)
    /* 001964 01DAD664 03000630 */  andi       $6, $0, 0x3
    /* 001968 01DAD668 FCFF0224 */  addiu      $2, $0, -0x4
    /* 00196C 01DAD66C 24106200 */  and        $2, $3, $2
    /* 001970 01DAD670 25104600 */  or         $2, $2, $6
    /* 001974 01DAD674 3001A2A3 */  sb         $2, 0x130($29)
    /* 001978 01DAD678 3001A593 */  lbu        $5, 0x130($29)
    /* 00197C 01DAD67C 08000364 */  daddiu     $3, $0, 0x8
    /* 001980 01DAD680 F3FF0224 */  addiu      $2, $0, -0xD
    /* 001984 01DAD684 2410A200 */  and        $2, $5, $2
    /* 001988 01DAD688 25104300 */  or         $2, $2, $3
    /* 00198C 01DAD68C 3001A2A3 */  sb         $2, 0x130($29)
    /* 001990 01DAD690 3001A593 */  lbu        $5, 0x130($29)
    /* 001994 01DAD694 00190600 */  sll        $3, $6, 4
    /* 001998 01DAD698 CFFF0224 */  addiu      $2, $0, -0x31
    /* 00199C 01DAD69C 2410A200 */  and        $2, $5, $2
    /* 0019A0 01DAD6A0 25104300 */  or         $2, $2, $3
    /* 0019A4 01DAD6A4 3001A2A3 */  sb         $2, 0x130($29)
    /* 0019A8 01DAD6A8 3001A593 */  lbu        $5, 0x130($29)
    /* 0019AC 01DAD6AC 40000364 */  daddiu     $3, $0, 0x40
    /* 0019B0 01DAD6B0 3FFF0224 */  addiu      $2, $0, -0xC1
    /* 0019B4 01DAD6B4 2410A200 */  and        $2, $5, $2
    /* 0019B8 01DAD6B8 25104300 */  or         $2, $2, $3
    /* 0019BC 01DAD6BC 3001A2A3 */  sb         $2, 0x130($29)
    /* 0019C0 01DAD6C0 E4BB040C */  jal        MGSetGsALPHA__FP10sceGsAlpha
    /* 0019C4 01DAD6C4 00000000 */   nop
    /* 0019C8 01DAD6C8 3801A427 */  addiu      $4, $29, 0x138
    /* 0019CC 01DAD6CC F08B82DF */  ld         $2, -0x7410($28)
    /* 0019D0 01DAD6D0 000082FC */  sd         $2, 0x0($4)
    /* 0019D4 01DAD6D4 3C01A593 */  lbu        $5, 0x13C($29)
    /* 0019D8 01DAD6D8 01000364 */  daddiu     $3, $0, 0x1
    /* 0019DC 01DAD6DC FEFF0224 */  addiu      $2, $0, -0x2
    /* 0019E0 01DAD6E0 2410A200 */  and        $2, $5, $2
    /* 0019E4 01DAD6E4 25104300 */  or         $2, $2, $3
    /* 0019E8 01DAD6E8 3C01A2A3 */  sb         $2, 0x13C($29)
    /* 0019EC 01DAD6EC B0BB040C */  jal        MGSetGsZBUF__FP9sceGsZbuf
    /* 0019F0 01DAD6F0 00000000 */   nop
    /* 0019F4 01DAD6F4 28860070 */  paddub     $16, $0, $0
    /* 0019F8 01DAD6F8 9A000010 */  b          .L01DAD964
    /* 0019FC 01DAD6FC 00000000 */   nop
  .L01DAD700:
    /* 001A00 01DAD700 80881000 */  sll        $17, $16, 2
    /* 001A04 01DAD704 21203502 */  addu       $4, $17, $21
    /* 001A08 01DAD708 0001838C */  lw         $3, 0x100($4)
    /* 001A0C 01DAD70C 01000224 */  addiu      $2, $0, 0x1
    /* 001A10 01DAD710 93006214 */  bne        $3, $2, .L01DAD960
    /* 001A14 01DAD714 00000000 */   nop
    /* 001A18 01DAD718 A000828C */  lw         $2, 0xA0($4)
    /* 001A1C 01DAD71C 90004004 */  bltz       $2, .L01DAD960
    /* 001A20 01DAD720 00000000 */   nop
    /* 001A24 01DAD724 00911000 */  sll        $18, $16, 4
    /* 001A28 01DAD728 21A0B202 */  addu       $20, $21, $18
    /* 001A2C 01DAD72C 000081C6 */  lwc1       $f1, 0x0($20)
    /* 001A30 01DAD730 A000A0C7 */  lwc1       $f0, 0xA0($29)
    /* 001A34 01DAD734 01000146 */  sub.s      $f0, $f0, $f1
    /* 001A38 01DAD738 B000A0E7 */  swc1       $f0, 0xB0($29)
    /* 001A3C 01DAD73C B400BE27 */  addiu      $30, $29, 0xB4
    /* 001A40 01DAD740 0000C0AF */  sw         $0, 0x0($30)
    /* 001A44 01DAD744 08009726 */  addiu      $23, $20, 0x8
    /* 001A48 01DAD748 080081C6 */  lwc1       $f1, 0x8($20)
    /* 001A4C 01DAD74C A800A0C7 */  lwc1       $f0, 0xA8($29)
    /* 001A50 01DAD750 01000146 */  sub.s      $f0, $f0, $f1
    /* 001A54 01DAD754 B800B327 */  addiu      $19, $29, 0xB8
    /* 001A58 01DAD758 000060E6 */  swc1       $f0, 0x0($19)
    /* 001A5C 01DAD75C B000A427 */  addiu      $4, $29, 0xB0
    /* 001A60 01DAD760 282E8070 */  paddub     $5, $4, $0
    /* 001A64 01DAD764 9285040C */  jal        sceVu0Normalize
    /* 001A68 01DAD768 00000000 */   nop
    /* 001A6C 01DAD76C 21183502 */  addu       $3, $17, $21
    /* 001A70 01DAD770 800060C4 */  lwc1       $f0, 0x80($3)
    /* 001A74 01DAD774 A0008046 */  cvt.s.w    $f2, $f0
    /* 001A78 01DAD778 E040023C */  lui        $2, (0x40E00000 >> 16)
    /* 001A7C 01DAD77C 00088244 */  mtc1       $2, $f1
    /* 001A80 01DAD780 00009044 */  mtc1       $16, $f0
    /* 001A84 01DAD784 00000000 */  nop
    /* 001A88 01DAD788 20008046 */  cvt.s.w    $f0, $f0
    /* 001A8C 01DAD78C C2080046 */  mul.s      $f3, $f1, $f0
    /* 001A90 01DAD790 40180246 */  add.s      $f1, $f3, $f2
    /* 001A94 01DAD794 B000A0C7 */  lwc1       $f0, 0xB0($29)
    /* 001A98 01DAD798 02000146 */  mul.s      $f0, $f0, $f1
    /* 001A9C 01DAD79C B000A0E7 */  swc1       $f0, 0xB0($29)
    /* 001AA0 01DAD7A0 800060C4 */  lwc1       $f0, 0x80($3)
    /* 001AA4 01DAD7A4 20008046 */  cvt.s.w    $f0, $f0
    /* 001AA8 01DAD7A8 40180046 */  add.s      $f1, $f3, $f0
    /* 001AAC 01DAD7AC 000060C6 */  lwc1       $f0, 0x0($19)
    /* 001AB0 01DAD7B0 02000146 */  mul.s      $f0, $f0, $f1
    /* 001AB4 01DAD7B4 000060E6 */  swc1       $f0, 0x0($19)
    /* 001AB8 01DAD7B8 B000A1C7 */  lwc1       $f1, 0xB0($29)
    /* 001ABC 01DAD7BC 000080C6 */  lwc1       $f0, 0x0($20)
    /* 001AC0 01DAD7C0 00080046 */  add.s      $f0, $f1, $f0
    /* 001AC4 01DAD7C4 C000A0E7 */  swc1       $f0, 0xC0($29)
    /* 001AC8 01DAD7C8 28168072 */  paddub     $2, $20, $0
    /* 001ACC 01DAD7CC 040041C4 */  lwc1       $f1, 0x4($2)
    /* 001AD0 01DAD7D0 0000C0C7 */  lwc1       $f0, 0x0($30)
    /* 001AD4 01DAD7D4 00000146 */  add.s      $f0, $f0, $f1
    /* 001AD8 01DAD7D8 C400A0E7 */  swc1       $f0, 0xC4($29)
    /* 001ADC 01DAD7DC 000061C6 */  lwc1       $f1, 0x0($19)
    /* 001AE0 01DAD7E0 0000E0C6 */  lwc1       $f0, 0x0($23)
    /* 001AE4 01DAD7E4 00080046 */  add.s      $f0, $f1, $f0
    /* 001AE8 01DAD7E8 C800A0E7 */  swc1       $f0, 0xC8($29)
    /* 001AEC 01DAD7EC 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 001AF0 01DAD7F0 CC00A2AF */  sw         $2, 0xCC($29)
    /* 001AF4 01DAD7F4 C0006CC4 */  lwc1       $f12, 0xC0($3)
    /* 001AF8 01DAD7F8 0040023C */  lui        $2, (0x40000000 >> 16)
    /* 001AFC 01DAD7FC 00008244 */  mtc1       $2, $f0
    /* 001B00 01DAD800 00000000 */  nop
    /* 001B04 01DAD804 43630046 */  div.s      $f13, $f12, $f0
    /* 001B08 01DAD808 D000A427 */  addiu      $4, $29, 0xD0
    /* 001B0C 01DAD80C E000A527 */  addiu      $5, $29, 0xE0
    /* 001B10 01DAD810 C000A627 */  addiu      $6, $29, 0xC0
    /* 001B14 01DAD814 283E0070 */  paddub     $7, $0, $0
    /* 001B18 01DAD818 D0B9040C */  jal        MGRotTransPers3DSprite__FPiPiPfffi
    /* 001B1C 01DAD81C 00000000 */   nop
    /* 001B20 01DAD820 01000324 */  addiu      $3, $0, 0x1
    /* 001B24 01DAD824 4E004314 */  bne        $2, $3, .L01DAD960
    /* 001B28 01DAD828 00000000 */   nop
    /* 001B2C 01DAD82C E000A28F */  lw         $2, 0xE0($29)
    /* 001B30 01DAD830 F000A2AF */  sw         $2, 0xF0($29)
    /* 001B34 01DAD834 D400A28F */  lw         $2, 0xD4($29)
    /* 001B38 01DAD838 F400A2AF */  sw         $2, 0xF4($29)
    /* 001B3C 01DAD83C D800A28F */  lw         $2, 0xD8($29)
    /* 001B40 01DAD840 F800A2AF */  sw         $2, 0xF8($29)
    /* 001B44 01DAD844 DC00A28F */  lw         $2, 0xDC($29)
    /* 001B48 01DAD848 FC00A2AF */  sw         $2, 0xFC($29)
    /* 001B4C 01DAD84C D000A28F */  lw         $2, 0xD0($29)
    /* 001B50 01DAD850 0001A2AF */  sw         $2, 0x100($29)
    /* 001B54 01DAD854 E400A28F */  lw         $2, 0xE4($29)
    /* 001B58 01DAD858 0401A2AF */  sw         $2, 0x104($29)
    /* 001B5C 01DAD85C E800A28F */  lw         $2, 0xE8($29)
    /* 001B60 01DAD860 0801A2AF */  sw         $2, 0x108($29)
    /* 001B64 01DAD864 EC00A28F */  lw         $2, 0xEC($29)
    /* 001B68 01DAD868 0C01A2AF */  sw         $2, 0x10C($29)
    /* 001B6C 01DAD86C 0500012A */  slti       $1, $16, 0x5
    /* 001B70 01DAD870 20002010 */  beqz       $1, .L01DAD8F4
    /* 001B74 01DAD874 00000000 */   nop
    /* 001B78 01DAD878 3900C016 */  bnez       $22, .L01DAD960
    /* 001B7C 01DAD87C 00000000 */   nop
    /* 001B80 01DAD880 1001A0AF */  sw         $0, 0x110($29)
    /* 001B84 01DAD884 1401A0AF */  sw         $0, 0x114($29)
    /* 001B88 01DAD888 80000224 */  addiu      $2, $0, 0x80
    /* 001B8C 01DAD88C 1801A2AF */  sw         $2, 0x118($29)
    /* 001B90 01DAD890 1C01A2AF */  sw         $2, 0x11C($29)
    /* 001B94 01DAD894 C701023C */  lui        $2, %hi(TexManager)
    /* 001B98 01DAD898 70584424 */  addiu      $4, $2, %lo(TexManager)
    /* 001B9C 01DAD89C DE01023C */  lui        $2, %hi(LIT_359__3)
    /* 001BA0 01DAD8A0 48BF4524 */  addiu      $5, $2, %lo(LIT_359__3)
    /* 001BA4 01DAD8A4 FFFF0624 */  addiu      $6, $0, -0x1
    /* 001BA8 01DAD8A8 B4C4040C */  jal        GetTexture__15CTextureManagerFPci
    /* 001BAC 01DAD8AC 00000000 */   nop
    /* 001BB0 01DAD8B0 28964070 */  paddub     $18, $2, $0
    /* 001BB4 01DAD8B4 21103502 */  addu       $2, $17, $21
    /* 001BB8 01DAD8B8 E0004CC4 */  lwc1       $f12, 0xE0($2)
    /* 001BBC 01DAD8BC 5044040C */  jal        fptoui
    /* 001BC0 01DAD8C0 00000000 */   nop
    /* 001BC4 01DAD8C4 D48B848F */  lw         $4, -0x742C($28)
    /* 001BC8 01DAD8C8 282E4072 */  paddub     $5, $18, $0
    /* 001BCC 01DAD8CC 1001A627 */  addiu      $6, $29, 0x110
    /* 001BD0 01DAD8D0 D000A727 */  addiu      $7, $29, 0xD0
    /* 001BD4 01DAD8D4 F000A827 */  addiu      $8, $29, 0xF0
    /* 001BD8 01DAD8D8 0001A927 */  addiu      $9, $29, 0x100
    /* 001BDC 01DAD8DC E000AA27 */  addiu      $10, $29, 0xE0
    /* 001BE0 01DAD8E0 285E4070 */  paddub     $11, $2, $0
    /* 001BE4 01DAD8E4 1C75050C */  jal        set3DSprite__FP13sceVif1PacketP8CTextureRC8CRect_i_PiPiPiPiUc
    /* 001BE8 01DAD8E8 00000000 */   nop
    /* 001BEC 01DAD8EC 1C000010 */  b          .L01DAD960
    /* 001BF0 01DAD8F0 00000000 */   nop
  .L01DAD8F4:
    /* 001BF4 01DAD8F4 2001A0AF */  sw         $0, 0x120($29)
    /* 001BF8 01DAD8F8 2401A0AF */  sw         $0, 0x124($29)
    /* 001BFC 01DAD8FC 80000224 */  addiu      $2, $0, 0x80
    /* 001C00 01DAD900 2801A2AF */  sw         $2, 0x128($29)
    /* 001C04 01DAD904 2C01A2AF */  sw         $2, 0x12C($29)
    /* 001C08 01DAD908 C701023C */  lui        $2, %hi(TexManager)
    /* 001C0C 01DAD90C 70584424 */  addiu      $4, $2, %lo(TexManager)
    /* 001C10 01DAD910 DE01023C */  lui        $2, %hi(LIT_360__3)
    /* 001C14 01DAD914 50BF4524 */  addiu      $5, $2, %lo(LIT_360__3)
    /* 001C18 01DAD918 FFFF0624 */  addiu      $6, $0, -0x1
    /* 001C1C 01DAD91C B4C4040C */  jal        GetTexture__15CTextureManagerFPci
    /* 001C20 01DAD920 00000000 */   nop
    /* 001C24 01DAD924 28964070 */  paddub     $18, $2, $0
    /* 001C28 01DAD928 21103502 */  addu       $2, $17, $21
    /* 001C2C 01DAD92C E0004CC4 */  lwc1       $f12, 0xE0($2)
    /* 001C30 01DAD930 5044040C */  jal        fptoui
    /* 001C34 01DAD934 00000000 */   nop
    /* 001C38 01DAD938 D48B848F */  lw         $4, -0x742C($28)
    /* 001C3C 01DAD93C 282E4072 */  paddub     $5, $18, $0
    /* 001C40 01DAD940 2001A627 */  addiu      $6, $29, 0x120
    /* 001C44 01DAD944 D000A727 */  addiu      $7, $29, 0xD0
    /* 001C48 01DAD948 F000A827 */  addiu      $8, $29, 0xF0
    /* 001C4C 01DAD94C 0001A927 */  addiu      $9, $29, 0x100
    /* 001C50 01DAD950 E000AA27 */  addiu      $10, $29, 0xE0
    /* 001C54 01DAD954 285E4070 */  paddub     $11, $2, $0
    /* 001C58 01DAD958 1C75050C */  jal        set3DSprite__FP13sceVif1PacketP8CTextureRC8CRect_i_PiPiPiPiUc
    /* 001C5C 01DAD95C 00000000 */   nop
  .L01DAD960:
    /* 001C60 01DAD960 01001026 */  addiu      $16, $16, 0x1
  .L01DAD964:
    /* 001C64 01DAD964 0800022A */  slti       $2, $16, 0x8
    /* 001C68 01DAD968 65FF4014 */  bnez       $2, .L01DAD700
    /* 001C6C 01DAD96C 00000000 */   nop
    /* 001C70 01DAD970 28260070 */  paddub     $4, $0, $0
    /* 001C74 01DAD974 E4BB040C */  jal        MGSetGsALPHA__FP10sceGsAlpha
    /* 001C78 01DAD978 00000000 */   nop
    /* 001C7C 01DAD97C 28260070 */  paddub     $4, $0, $0
    /* 001C80 01DAD980 B0BB040C */  jal        MGSetGsZBUF__FP9sceGsZbuf
    /* 001C84 01DAD984 00000000 */   nop
    /* 001C88 01DAD988 9000BF7B */  lq         $31, 0x90($29)
    /* 001C8C 01DAD98C 8000BE7B */  lq         $30, 0x80($29)
    /* 001C90 01DAD990 7000B77B */  lq         $23, 0x70($29)
    /* 001C94 01DAD994 6000B67B */  lq         $22, 0x60($29)
    /* 001C98 01DAD998 5000B57B */  lq         $21, 0x50($29)
    /* 001C9C 01DAD99C 4000B47B */  lq         $20, 0x40($29)
    /* 001CA0 01DAD9A0 3000B37B */  lq         $19, 0x30($29)
    /* 001CA4 01DAD9A4 2000B27B */  lq         $18, 0x20($29)
    /* 001CA8 01DAD9A8 1000B17B */  lq         $17, 0x10($29)
    /* 001CAC 01DAD9AC 0000B07B */  lq         $16, 0x0($29)
    /* 001CB0 01DAD9B0 4001BD27 */  addiu      $29, $29, 0x140
    /* 001CB4 01DAD9B4 0800E003 */  jr         $31
    /* 001CB8 01DAD9B8 00000000 */   nop
    /* 001CBC 01DAD9BC 00000000 */  nop

glabel Step__11CBombEffectFv
    /* 001CC0 01DAD9C0 281E0070 */  paddub     $3, $0, $0
    /* 001CC4 01DAD9C4 75000010 */  b          .L01DADB9C
    /* 001CC8 01DAD9C8 00000000 */   nop
  .L01DAD9CC:
    /* 001CCC 01DAD9CC 80280300 */  sll        $5, $3, 2
    /* 001CD0 01DAD9D0 2148A400 */  addu       $9, $5, $4
    /* 001CD4 01DAD9D4 00012A25 */  addiu      $10, $9, 0x100
    /* 001CD8 01DAD9D8 0001258D */  lw         $5, 0x100($9)
    /* 001CDC 01DAD9DC 01000824 */  addiu      $8, $0, 0x1
    /* 001CE0 01DAD9E0 6D00A814 */  bne        $5, $8, .L01DADB98
    /* 001CE4 01DAD9E4 00000000 */   nop
    /* 001CE8 01DAD9E8 80002525 */  addiu      $5, $9, 0x80
    /* 001CEC 01DAD9EC 8000278D */  lw         $7, 0x80($9)
    /* 001CF0 01DAD9F0 03000624 */  addiu      $6, $0, 0x3
    /* 001CF4 01DAD9F4 5600E610 */  beq        $7, $6, .L01DADB50
    /* 001CF8 01DAD9F8 00000000 */   nop
    /* 001CFC 01DAD9FC 02000624 */  addiu      $6, $0, 0x2
    /* 001D00 01DADA00 3B00E610 */  beq        $7, $6, .L01DADAF0
    /* 001D04 01DADA04 00000000 */   nop
    /* 001D08 01DADA08 1F00E810 */  beq        $7, $8, .L01DADA88
    /* 001D0C 01DADA0C 00000000 */   nop
    /* 001D10 01DADA10 0300E010 */  beqz       $7, .L01DADA20
    /* 001D14 01DADA14 00000000 */   nop
    /* 001D18 01DADA18 5F000010 */  b          .L01DADB98
    /* 001D1C 01DADA1C 00000000 */   nop
  .L01DADA20:
    /* 001D20 01DADA20 A0002725 */  addiu      $7, $9, 0xA0
    /* 001D24 01DADA24 A000268D */  lw         $6, 0xA0($9)
    /* 001D28 01DADA28 0100C624 */  addiu      $6, $6, 0x1
    /* 001D2C 01DADA2C A00026AD */  sw         $6, 0xA0($9)
    /* 001D30 01DADA30 C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001D34 01DADA34 0041063C */  lui        $6, (0x41000000 >> 16)
    /* 001D38 01DADA38 00008644 */  mtc1       $6, $f0
    /* 001D3C 01DADA3C 00000000 */  nop
    /* 001D40 01DADA40 00080046 */  add.s      $f0, $f1, $f0
    /* 001D44 01DADA44 C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001D48 01DADA48 E00021C5 */  lwc1       $f1, 0xE0($9)
    /* 001D4C 01DADA4C 8040063C */  lui        $6, (0x40800000 >> 16)
    /* 001D50 01DADA50 00008644 */  mtc1       $6, $f0
    /* 001D54 01DADA54 00000000 */  nop
    /* 001D58 01DADA58 00080046 */  add.s      $f0, $f1, $f0
    /* 001D5C 01DADA5C E00020E5 */  swc1       $f0, 0xE0($9)
    /* 001D60 01DADA60 A000268D */  lw         $6, 0xA0($9)
    /* 001D64 01DADA64 0300C628 */  slti       $6, $6, 0x3
    /* 001D68 01DADA68 4B00C014 */  bnez       $6, .L01DADB98
    /* 001D6C 01DADA6C 00000000 */   nop
    /* 001D70 01DADA70 0000E0AC */  sw         $0, 0x0($7)
    /* 001D74 01DADA74 0000A68C */  lw         $6, 0x0($5)
    /* 001D78 01DADA78 0100C624 */  addiu      $6, $6, 0x1
    /* 001D7C 01DADA7C 0000A6AC */  sw         $6, 0x0($5)
    /* 001D80 01DADA80 45000010 */  b          .L01DADB98
    /* 001D84 01DADA84 00000000 */   nop
  .L01DADA88:
    /* 001D88 01DADA88 A0002725 */  addiu      $7, $9, 0xA0
    /* 001D8C 01DADA8C A000268D */  lw         $6, 0xA0($9)
    /* 001D90 01DADA90 0100C624 */  addiu      $6, $6, 0x1
    /* 001D94 01DADA94 A00026AD */  sw         $6, 0xA0($9)
    /* 001D98 01DADA98 C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001D9C 01DADA9C 803F063C */  lui        $6, (0x3F800000 >> 16)
    /* 001DA0 01DADAA0 00008644 */  mtc1       $6, $f0
    /* 001DA4 01DADAA4 00000000 */  nop
    /* 001DA8 01DADAA8 00080046 */  add.s      $f0, $f1, $f0
    /* 001DAC 01DADAAC C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001DB0 01DADAB0 E00021C5 */  lwc1       $f1, 0xE0($9)
    /* 001DB4 01DADAB4 0041063C */  lui        $6, (0x41000000 >> 16)
    /* 001DB8 01DADAB8 00008644 */  mtc1       $6, $f0
    /* 001DBC 01DADABC 00000000 */  nop
    /* 001DC0 01DADAC0 00080046 */  add.s      $f0, $f1, $f0
    /* 001DC4 01DADAC4 E00020E5 */  swc1       $f0, 0xE0($9)
    /* 001DC8 01DADAC8 A000268D */  lw         $6, 0xA0($9)
    /* 001DCC 01DADACC 0400C628 */  slti       $6, $6, 0x4
    /* 001DD0 01DADAD0 3100C014 */  bnez       $6, .L01DADB98
    /* 001DD4 01DADAD4 00000000 */   nop
    /* 001DD8 01DADAD8 0000E0AC */  sw         $0, 0x0($7)
    /* 001DDC 01DADADC 0000A68C */  lw         $6, 0x0($5)
    /* 001DE0 01DADAE0 0100C624 */  addiu      $6, $6, 0x1
    /* 001DE4 01DADAE4 0000A6AC */  sw         $6, 0x0($5)
    /* 001DE8 01DADAE8 2B000010 */  b          .L01DADB98
    /* 001DEC 01DADAEC 00000000 */   nop
  .L01DADAF0:
    /* 001DF0 01DADAF0 A0002725 */  addiu      $7, $9, 0xA0
    /* 001DF4 01DADAF4 A000268D */  lw         $6, 0xA0($9)
    /* 001DF8 01DADAF8 0100C624 */  addiu      $6, $6, 0x1
    /* 001DFC 01DADAFC A00026AD */  sw         $6, 0xA0($9)
    /* 001E00 01DADB00 C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001E04 01DADB04 908280C7 */  lwc1       $f0, -0x7D70($28)
    /* 001E08 01DADB08 00080046 */  add.s      $f0, $f1, $f0
    /* 001E0C 01DADB0C C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001E10 01DADB10 E00021C5 */  lwc1       $f1, 0xE0($9)
    /* 001E14 01DADB14 4040063C */  lui        $6, (0x40400000 >> 16)
    /* 001E18 01DADB18 00008644 */  mtc1       $6, $f0
    /* 001E1C 01DADB1C 00000000 */  nop
    /* 001E20 01DADB20 01080046 */  sub.s      $f0, $f1, $f0
    /* 001E24 01DADB24 E00020E5 */  swc1       $f0, 0xE0($9)
    /* 001E28 01DADB28 A000268D */  lw         $6, 0xA0($9)
    /* 001E2C 01DADB2C 1400C628 */  slti       $6, $6, 0x14
    /* 001E30 01DADB30 1900C014 */  bnez       $6, .L01DADB98
    /* 001E34 01DADB34 00000000 */   nop
    /* 001E38 01DADB38 0000E0AC */  sw         $0, 0x0($7)
    /* 001E3C 01DADB3C 0000A68C */  lw         $6, 0x0($5)
    /* 001E40 01DADB40 0100C624 */  addiu      $6, $6, 0x1
    /* 001E44 01DADB44 0000A6AC */  sw         $6, 0x0($5)
    /* 001E48 01DADB48 13000010 */  b          .L01DADB98
    /* 001E4C 01DADB4C 00000000 */   nop
  .L01DADB50:
    /* 001E50 01DADB50 A000258D */  lw         $5, 0xA0($9)
    /* 001E54 01DADB54 0100A524 */  addiu      $5, $5, 0x1
    /* 001E58 01DADB58 A00025AD */  sw         $5, 0xA0($9)
    /* 001E5C 01DADB5C C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001E60 01DADB60 808080C7 */  lwc1       $f0, -0x7F80($28)
    /* 001E64 01DADB64 01080046 */  sub.s      $f0, $f1, $f0
    /* 001E68 01DADB68 C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001E6C 01DADB6C E00021C5 */  lwc1       $f1, 0xE0($9)
    /* 001E70 01DADB70 0040053C */  lui        $5, (0x40000000 >> 16)
    /* 001E74 01DADB74 00008544 */  mtc1       $5, $f0
    /* 001E78 01DADB78 00000000 */  nop
    /* 001E7C 01DADB7C 01080046 */  sub.s      $f0, $f1, $f0
    /* 001E80 01DADB80 E00020E5 */  swc1       $f0, 0xE0($9)
    /* 001E84 01DADB84 A000258D */  lw         $5, 0xA0($9)
    /* 001E88 01DADB88 5000A528 */  slti       $5, $5, 0x50
    /* 001E8C 01DADB8C 0200A014 */  bnez       $5, .L01DADB98
    /* 001E90 01DADB90 00000000 */   nop
    /* 001E94 01DADB94 000040AD */  sw         $0, 0x0($10)
  .L01DADB98:
    /* 001E98 01DADB98 01006324 */  addiu      $3, $3, 0x1
  .L01DADB9C:
    /* 001E9C 01DADB9C 05006528 */  slti       $5, $3, 0x5
    /* 001EA0 01DADBA0 8AFFA014 */  bnez       $5, .L01DAD9CC
    /* 001EA4 01DADBA4 00000000 */   nop
    /* 001EA8 01DADBA8 05000324 */  addiu      $3, $0, 0x5
    /* 001EAC 01DADBAC 63000010 */  b          .L01DADD3C
    /* 001EB0 01DADBB0 00000000 */   nop
  .L01DADBB4:
    /* 001EB4 01DADBB4 80280300 */  sll        $5, $3, 2
    /* 001EB8 01DADBB8 2148A400 */  addu       $9, $5, $4
    /* 001EBC 01DADBBC 00012A25 */  addiu      $10, $9, 0x100
    /* 001EC0 01DADBC0 0001258D */  lw         $5, 0x100($9)
    /* 001EC4 01DADBC4 01000824 */  addiu      $8, $0, 0x1
    /* 001EC8 01DADBC8 5B00A814 */  bne        $5, $8, .L01DADD38
    /* 001ECC 01DADBCC 00000000 */   nop
    /* 001ED0 01DADBD0 80002525 */  addiu      $5, $9, 0x80
    /* 001ED4 01DADBD4 8000278D */  lw         $7, 0x80($9)
    /* 001ED8 01DADBD8 03000624 */  addiu      $6, $0, 0x3
    /* 001EDC 01DADBDC 4400E610 */  beq        $7, $6, .L01DADCF0
    /* 001EE0 01DADBE0 00000000 */   nop
    /* 001EE4 01DADBE4 02000624 */  addiu      $6, $0, 0x2
    /* 001EE8 01DADBE8 2F00E610 */  beq        $7, $6, .L01DADCA8
    /* 001EEC 01DADBEC 00000000 */   nop
    /* 001EF0 01DADBF0 1900E810 */  beq        $7, $8, .L01DADC58
    /* 001EF4 01DADBF4 00000000 */   nop
    /* 001EF8 01DADBF8 0300E010 */  beqz       $7, .L01DADC08
    /* 001EFC 01DADBFC 00000000 */   nop
    /* 001F00 01DADC00 4D000010 */  b          .L01DADD38
    /* 001F04 01DADC04 00000000 */   nop
  .L01DADC08:
    /* 001F08 01DADC08 A0002725 */  addiu      $7, $9, 0xA0
    /* 001F0C 01DADC0C A000268D */  lw         $6, 0xA0($9)
    /* 001F10 01DADC10 0100C624 */  addiu      $6, $6, 0x1
    /* 001F14 01DADC14 A00026AD */  sw         $6, 0xA0($9)
    /* 001F18 01DADC18 C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001F1C 01DADC1C 8041063C */  lui        $6, (0x41800000 >> 16)
    /* 001F20 01DADC20 00008644 */  mtc1       $6, $f0
    /* 001F24 01DADC24 00000000 */  nop
    /* 001F28 01DADC28 00080046 */  add.s      $f0, $f1, $f0
    /* 001F2C 01DADC2C C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001F30 01DADC30 A000268D */  lw         $6, 0xA0($9)
    /* 001F34 01DADC34 0300C628 */  slti       $6, $6, 0x3
    /* 001F38 01DADC38 3F00C014 */  bnez       $6, .L01DADD38
    /* 001F3C 01DADC3C 00000000 */   nop
    /* 001F40 01DADC40 0000E0AC */  sw         $0, 0x0($7)
    /* 001F44 01DADC44 0000A68C */  lw         $6, 0x0($5)
    /* 001F48 01DADC48 0100C624 */  addiu      $6, $6, 0x1
    /* 001F4C 01DADC4C 0000A6AC */  sw         $6, 0x0($5)
    /* 001F50 01DADC50 39000010 */  b          .L01DADD38
    /* 001F54 01DADC54 00000000 */   nop
  .L01DADC58:
    /* 001F58 01DADC58 A0002725 */  addiu      $7, $9, 0xA0
    /* 001F5C 01DADC5C A000268D */  lw         $6, 0xA0($9)
    /* 001F60 01DADC60 0100C624 */  addiu      $6, $6, 0x1
    /* 001F64 01DADC64 A00026AD */  sw         $6, 0xA0($9)
    /* 001F68 01DADC68 C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001F6C 01DADC6C 0041063C */  lui        $6, (0x41000000 >> 16)
    /* 001F70 01DADC70 00008644 */  mtc1       $6, $f0
    /* 001F74 01DADC74 00000000 */  nop
    /* 001F78 01DADC78 00080046 */  add.s      $f0, $f1, $f0
    /* 001F7C 01DADC7C C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001F80 01DADC80 A000268D */  lw         $6, 0xA0($9)
    /* 001F84 01DADC84 0400C628 */  slti       $6, $6, 0x4
    /* 001F88 01DADC88 2B00C014 */  bnez       $6, .L01DADD38
    /* 001F8C 01DADC8C 00000000 */   nop
    /* 001F90 01DADC90 0000E0AC */  sw         $0, 0x0($7)
    /* 001F94 01DADC94 0000A68C */  lw         $6, 0x0($5)
    /* 001F98 01DADC98 0100C624 */  addiu      $6, $6, 0x1
    /* 001F9C 01DADC9C 0000A6AC */  sw         $6, 0x0($5)
    /* 001FA0 01DADCA0 25000010 */  b          .L01DADD38
    /* 001FA4 01DADCA4 00000000 */   nop
  .L01DADCA8:
    /* 001FA8 01DADCA8 A0002725 */  addiu      $7, $9, 0xA0
    /* 001FAC 01DADCAC A000268D */  lw         $6, 0xA0($9)
    /* 001FB0 01DADCB0 0100C624 */  addiu      $6, $6, 0x1
    /* 001FB4 01DADCB4 A00026AD */  sw         $6, 0xA0($9)
    /* 001FB8 01DADCB8 C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 001FBC 01DADCBC 908280C7 */  lwc1       $f0, -0x7D70($28)
    /* 001FC0 01DADCC0 00080046 */  add.s      $f0, $f1, $f0
    /* 001FC4 01DADCC4 C00020E5 */  swc1       $f0, 0xC0($9)
    /* 001FC8 01DADCC8 A000268D */  lw         $6, 0xA0($9)
    /* 001FCC 01DADCCC 1400C628 */  slti       $6, $6, 0x14
    /* 001FD0 01DADCD0 1900C014 */  bnez       $6, .L01DADD38
    /* 001FD4 01DADCD4 00000000 */   nop
    /* 001FD8 01DADCD8 0000E0AC */  sw         $0, 0x0($7)
    /* 001FDC 01DADCDC 0000A68C */  lw         $6, 0x0($5)
    /* 001FE0 01DADCE0 0100C624 */  addiu      $6, $6, 0x1
    /* 001FE4 01DADCE4 0000A6AC */  sw         $6, 0x0($5)
    /* 001FE8 01DADCE8 13000010 */  b          .L01DADD38
    /* 001FEC 01DADCEC 00000000 */   nop
  .L01DADCF0:
    /* 001FF0 01DADCF0 A000258D */  lw         $5, 0xA0($9)
    /* 001FF4 01DADCF4 0100A524 */  addiu      $5, $5, 0x1
    /* 001FF8 01DADCF8 A00025AD */  sw         $5, 0xA0($9)
    /* 001FFC 01DADCFC C00021C5 */  lwc1       $f1, 0xC0($9)
    /* 002000 01DADD00 808080C7 */  lwc1       $f0, -0x7F80($28)
    /* 002004 01DADD04 01080046 */  sub.s      $f0, $f1, $f0
    /* 002008 01DADD08 C00020E5 */  swc1       $f0, 0xC0($9)
    /* 00200C 01DADD0C E00021C5 */  lwc1       $f1, 0xE0($9)
    /* 002010 01DADD10 0040053C */  lui        $5, (0x40000000 >> 16)
    /* 002014 01DADD14 00008544 */  mtc1       $5, $f0
    /* 002018 01DADD18 00000000 */  nop
    /* 00201C 01DADD1C 01080046 */  sub.s      $f0, $f1, $f0
    /* 002020 01DADD20 E00020E5 */  swc1       $f0, 0xE0($9)
    /* 002024 01DADD24 A000258D */  lw         $5, 0xA0($9)
    /* 002028 01DADD28 5000A528 */  slti       $5, $5, 0x50
    /* 00202C 01DADD2C 0200A014 */  bnez       $5, .L01DADD38
    /* 002030 01DADD30 00000000 */   nop
    /* 002034 01DADD34 000040AD */  sw         $0, 0x0($10)
  .L01DADD38:
    /* 002038 01DADD38 01006324 */  addiu      $3, $3, 0x1
  .L01DADD3C:
    /* 00203C 01DADD3C 08006528 */  slti       $5, $3, 0x8
    /* 002040 01DADD40 9CFFA014 */  bnez       $5, .L01DADBB4
    /* 002044 01DADD44 00000000 */   nop
    /* 002048 01DADD48 0800E003 */  jr         $31
    /* 00204C 01DADD4C 00000000 */   nop
