.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel Draw__10CMajinBeemFP7CCamera
    /* 002050 01DADD50 30FFBD27 */  addiu      $29, $29, -0xD0
    /* 002054 01DADD54 4000BF7F */  sq         $31, 0x40($29)
    /* 002058 01DADD58 3000B37F */  sq         $19, 0x30($29)
    /* 00205C 01DADD5C 2000B27F */  sq         $18, 0x20($29)
    /* 002060 01DADD60 1000B17F */  sq         $17, 0x10($29)
    /* 002064 01DADD64 0000B07F */  sq         $16, 0x0($29)
    /* 002068 01DADD68 28968070 */  paddub     $18, $4, $0
    /* 00206C 01DADD6C 2826A070 */  paddub     $4, $5, $0
    /* 002070 01DADD70 5000A527 */  addiu      $5, $29, 0x50
    /* 002074 01DADD74 9C91040C */  jal        GetPos__7CCameraFPf
    /* 002078 01DADD78 00000000 */   nop
    /* 00207C 01DADD7C C000A427 */  addiu      $4, $29, 0xC0
    /* 002080 01DADD80 F88B82DF */  ld         $2, -0x7408($28)
    /* 002084 01DADD84 000082FC */  sd         $2, 0x0($4)
    /* 002088 01DADD88 C000A393 */  lbu        $3, 0xC0($29)
    /* 00208C 01DADD8C 03000630 */  andi       $6, $0, 0x3
    /* 002090 01DADD90 FCFF0224 */  addiu      $2, $0, -0x4
    /* 002094 01DADD94 24106200 */  and        $2, $3, $2
    /* 002098 01DADD98 25104600 */  or         $2, $2, $6
    /* 00209C 01DADD9C C000A2A3 */  sb         $2, 0xC0($29)
    /* 0020A0 01DADDA0 C000A593 */  lbu        $5, 0xC0($29)
    /* 0020A4 01DADDA4 08000364 */  daddiu     $3, $0, 0x8
    /* 0020A8 01DADDA8 F3FF0224 */  addiu      $2, $0, -0xD
    /* 0020AC 01DADDAC 2410A200 */  and        $2, $5, $2
    /* 0020B0 01DADDB0 25104300 */  or         $2, $2, $3
    /* 0020B4 01DADDB4 C000A2A3 */  sb         $2, 0xC0($29)
    /* 0020B8 01DADDB8 C000A593 */  lbu        $5, 0xC0($29)
    /* 0020BC 01DADDBC 00190600 */  sll        $3, $6, 4
    /* 0020C0 01DADDC0 CFFF0224 */  addiu      $2, $0, -0x31
    /* 0020C4 01DADDC4 2410A200 */  and        $2, $5, $2
    /* 0020C8 01DADDC8 25104300 */  or         $2, $2, $3
    /* 0020CC 01DADDCC C000A2A3 */  sb         $2, 0xC0($29)
    /* 0020D0 01DADDD0 C000A593 */  lbu        $5, 0xC0($29)
    /* 0020D4 01DADDD4 40000364 */  daddiu     $3, $0, 0x40
    /* 0020D8 01DADDD8 3FFF0224 */  addiu      $2, $0, -0xC1
    /* 0020DC 01DADDDC 2410A200 */  and        $2, $5, $2
    /* 0020E0 01DADDE0 25104300 */  or         $2, $2, $3
    /* 0020E4 01DADDE4 C000A2A3 */  sb         $2, 0xC0($29)
    /* 0020E8 01DADDE8 E4BB040C */  jal        MGSetGsALPHA__FP10sceGsAlpha
    /* 0020EC 01DADDEC 00000000 */   nop
    /* 0020F0 01DADDF0 C800A427 */  addiu      $4, $29, 0xC8
    /* 0020F4 01DADDF4 F08B82DF */  ld         $2, -0x7410($28)
    /* 0020F8 01DADDF8 000082FC */  sd         $2, 0x0($4)
    /* 0020FC 01DADDFC CC00A593 */  lbu        $5, 0xCC($29)
    /* 002100 01DADE00 01000364 */  daddiu     $3, $0, 0x1
    /* 002104 01DADE04 FEFF0224 */  addiu      $2, $0, -0x2
    /* 002108 01DADE08 2410A200 */  and        $2, $5, $2
    /* 00210C 01DADE0C 25104300 */  or         $2, $2, $3
    /* 002110 01DADE10 CC00A2A3 */  sb         $2, 0xCC($29)
    /* 002114 01DADE14 B0BB040C */  jal        MGSetGsZBUF__FP9sceGsZbuf
    /* 002118 01DADE18 00000000 */   nop
    /* 00211C 01DADE1C 28860070 */  paddub     $16, $0, $0
    /* 002120 01DADE20 4E000010 */  b          .L01DADF5C
    /* 002124 01DADE24 00000000 */   nop
  .L01DADE28:
    /* 002128 01DADE28 A406438E */  lw         $3, 0x6A4($18)
    /* 00212C 01DADE2C 01000224 */  addiu      $2, $0, 0x1
    /* 002130 01DADE30 49006214 */  bne        $3, $2, .L01DADF58
    /* 002134 01DADE34 00000000 */   nop
    /* 002138 01DADE38 80881000 */  sll        $17, $16, 2
    /* 00213C 01DADE3C 21183202 */  addu       $3, $17, $18
    /* 002140 01DADE40 D403628C */  lw         $2, 0x3D4($3)
    /* 002144 01DADE44 44004004 */  bltz       $2, .L01DADF58
    /* 002148 01DADE48 00000000 */   nop
    /* 00214C 01DADE4C 00111000 */  sll        $2, $16, 4
    /* 002150 01DADE50 21104202 */  addu       $2, $18, $2
    /* 002154 01DADE54 000040C4 */  lwc1       $f0, 0x0($2)
    /* 002158 01DADE58 6000A0E7 */  swc1       $f0, 0x60($29)
    /* 00215C 01DADE5C 040040C4 */  lwc1       $f0, 0x4($2)
    /* 002160 01DADE60 6400A0E7 */  swc1       $f0, 0x64($29)
    /* 002164 01DADE64 080040C4 */  lwc1       $f0, 0x8($2)
    /* 002168 01DADE68 6800A0E7 */  swc1       $f0, 0x68($29)
    /* 00216C 01DADE6C 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 002170 01DADE70 6C00A2AF */  sw         $2, 0x6C($29)
    /* 002174 01DADE74 C4046CC4 */  lwc1       $f12, 0x4C4($3)
    /* 002178 01DADE78 0040023C */  lui        $2, (0x40000000 >> 16)
    /* 00217C 01DADE7C 00008244 */  mtc1       $2, $f0
    /* 002180 01DADE80 00000000 */  nop
    /* 002184 01DADE84 43630046 */  div.s      $f13, $f12, $f0
    /* 002188 01DADE88 7000A427 */  addiu      $4, $29, 0x70
    /* 00218C 01DADE8C 8000A527 */  addiu      $5, $29, 0x80
    /* 002190 01DADE90 6000A627 */  addiu      $6, $29, 0x60
    /* 002194 01DADE94 283E0070 */  paddub     $7, $0, $0
    /* 002198 01DADE98 D0B9040C */  jal        MGRotTransPers3DSprite__FPiPiPfffi
    /* 00219C 01DADE9C 00000000 */   nop
    /* 0021A0 01DADEA0 01000324 */  addiu      $3, $0, 0x1
    /* 0021A4 01DADEA4 2C004314 */  bne        $2, $3, .L01DADF58
    /* 0021A8 01DADEA8 00000000 */   nop
    /* 0021AC 01DADEAC 8000A28F */  lw         $2, 0x80($29)
    /* 0021B0 01DADEB0 9000A2AF */  sw         $2, 0x90($29)
    /* 0021B4 01DADEB4 7400A28F */  lw         $2, 0x74($29)
    /* 0021B8 01DADEB8 9400A2AF */  sw         $2, 0x94($29)
    /* 0021BC 01DADEBC 7800A28F */  lw         $2, 0x78($29)
    /* 0021C0 01DADEC0 9800A2AF */  sw         $2, 0x98($29)
    /* 0021C4 01DADEC4 7C00A28F */  lw         $2, 0x7C($29)
    /* 0021C8 01DADEC8 9C00A2AF */  sw         $2, 0x9C($29)
    /* 0021CC 01DADECC 7000A28F */  lw         $2, 0x70($29)
    /* 0021D0 01DADED0 A000A2AF */  sw         $2, 0xA0($29)
    /* 0021D4 01DADED4 8400A28F */  lw         $2, 0x84($29)
    /* 0021D8 01DADED8 A400A2AF */  sw         $2, 0xA4($29)
    /* 0021DC 01DADEDC 8800A28F */  lw         $2, 0x88($29)
    /* 0021E0 01DADEE0 A800A2AF */  sw         $2, 0xA8($29)
    /* 0021E4 01DADEE4 8C00A28F */  lw         $2, 0x8C($29)
    /* 0021E8 01DADEE8 AC00A2AF */  sw         $2, 0xAC($29)
    /* 0021EC 01DADEEC B000A0AF */  sw         $0, 0xB0($29)
    /* 0021F0 01DADEF0 B400A0AF */  sw         $0, 0xB4($29)
    /* 0021F4 01DADEF4 80000224 */  addiu      $2, $0, 0x80
    /* 0021F8 01DADEF8 B800A2AF */  sw         $2, 0xB8($29)
    /* 0021FC 01DADEFC BC00A2AF */  sw         $2, 0xBC($29)
    /* 002200 01DADF00 C701023C */  lui        $2, %hi(TexManager)
    /* 002204 01DADF04 70584424 */  addiu      $4, $2, %lo(TexManager)
    /* 002208 01DADF08 DE01023C */  lui        $2, %hi(LIT_435__3)
    /* 00220C 01DADF0C 60BF4524 */  addiu      $5, $2, %lo(LIT_435__3)
    /* 002210 01DADF10 FFFF0624 */  addiu      $6, $0, -0x1
    /* 002214 01DADF14 B4C4040C */  jal        GetTexture__15CTextureManagerFPci
    /* 002218 01DADF18 00000000 */   nop
    /* 00221C 01DADF1C 289E4070 */  paddub     $19, $2, $0
    /* 002220 01DADF20 21103202 */  addu       $2, $17, $18
    /* 002224 01DADF24 B4054CC4 */  lwc1       $f12, 0x5B4($2)
    /* 002228 01DADF28 5044040C */  jal        fptoui
    /* 00222C 01DADF2C 00000000 */   nop
    /* 002230 01DADF30 D48B848F */  lw         $4, -0x742C($28)
    /* 002234 01DADF34 282E6072 */  paddub     $5, $19, $0
    /* 002238 01DADF38 B000A627 */  addiu      $6, $29, 0xB0
    /* 00223C 01DADF3C 7000A727 */  addiu      $7, $29, 0x70
    /* 002240 01DADF40 9000A827 */  addiu      $8, $29, 0x90
    /* 002244 01DADF44 A000A927 */  addiu      $9, $29, 0xA0
    /* 002248 01DADF48 8000AA27 */  addiu      $10, $29, 0x80
    /* 00224C 01DADF4C 285E4070 */  paddub     $11, $2, $0
    /* 002250 01DADF50 1C75050C */  jal        set3DSprite__FP13sceVif1PacketP8CTextureRC8CRect_i_PiPiPiPiUc
    /* 002254 01DADF54 00000000 */   nop
  .L01DADF58:
    /* 002258 01DADF58 01001026 */  addiu      $16, $16, 0x1
  .L01DADF5C:
    /* 00225C 01DADF5C 3B00022A */  slti       $2, $16, 0x3B
    /* 002260 01DADF60 B1FF4014 */  bnez       $2, .L01DADE28
    /* 002264 01DADF64 00000000 */   nop
    /* 002268 01DADF68 28260070 */  paddub     $4, $0, $0
    /* 00226C 01DADF6C E4BB040C */  jal        MGSetGsALPHA__FP10sceGsAlpha
    /* 002270 01DADF70 00000000 */   nop
    /* 002274 01DADF74 28260070 */  paddub     $4, $0, $0
    /* 002278 01DADF78 B0BB040C */  jal        MGSetGsZBUF__FP9sceGsZbuf
    /* 00227C 01DADF7C 00000000 */   nop
    /* 002280 01DADF80 4000BF7B */  lq         $31, 0x40($29)
    /* 002284 01DADF84 3000B37B */  lq         $19, 0x30($29)
    /* 002288 01DADF88 2000B27B */  lq         $18, 0x20($29)
    /* 00228C 01DADF8C 1000B17B */  lq         $17, 0x10($29)
    /* 002290 01DADF90 0000B07B */  lq         $16, 0x0($29)
    /* 002294 01DADF94 D000BD27 */  addiu      $29, $29, 0xD0
    /* 002298 01DADF98 0800E003 */  jr         $31
    /* 00229C 01DADF9C 00000000 */   nop

glabel Draw2__10CMajinBeemFP7CCameraPfPf
    /* 0022A0 01DADFA0 C0FEBD27 */  addiu      $29, $29, -0x140
    /* 0022A4 01DADFA4 9000BF7F */  sq         $31, 0x90($29)
    /* 0022A8 01DADFA8 8000BE7F */  sq         $30, 0x80($29)
    /* 0022AC 01DADFAC 7000B77F */  sq         $23, 0x70($29)
    /* 0022B0 01DADFB0 6000B67F */  sq         $22, 0x60($29)
    /* 0022B4 01DADFB4 5000B57F */  sq         $21, 0x50($29)
    /* 0022B8 01DADFB8 4000B47F */  sq         $20, 0x40($29)
    /* 0022BC 01DADFBC 3000B37F */  sq         $19, 0x30($29)
    /* 0022C0 01DADFC0 2000B27F */  sq         $18, 0x20($29)
    /* 0022C4 01DADFC4 1000B17F */  sq         $17, 0x10($29)
    /* 0022C8 01DADFC8 0000B07F */  sq         $16, 0x0($29)
    /* 0022CC 01DADFCC 28AE8070 */  paddub     $21, $4, $0
    /* 0022D0 01DADFD0 2896C070 */  paddub     $18, $6, $0
    /* 0022D4 01DADFD4 288EE070 */  paddub     $17, $7, $0
    /* 0022D8 01DADFD8 2826A070 */  paddub     $4, $5, $0
    /* 0022DC 01DADFDC A000A527 */  addiu      $5, $29, 0xA0
    /* 0022E0 01DADFE0 9C91040C */  jal        GetPos__7CCameraFPf
    /* 0022E4 01DADFE4 00000000 */   nop
    /* 0022E8 01DADFE8 A000A1C7 */  lwc1       $f1, 0xA0($29)
    /* 0022EC 01DADFEC 000020C6 */  lwc1       $f0, 0x0($17)
    /* 0022F0 01DADFF0 01080046 */  sub.s      $f0, $f1, $f0
    /* 0022F4 01DADFF4 A000A0E7 */  swc1       $f0, 0xA0($29)
    /* 0022F8 01DADFF8 040021C6 */  lwc1       $f1, 0x4($17)
    /* 0022FC 01DADFFC A400B027 */  addiu      $16, $29, 0xA4
    /* 002300 01DAE000 000000C6 */  lwc1       $f0, 0x0($16)
    /* 002304 01DAE004 01000146 */  sub.s      $f0, $f0, $f1
    /* 002308 01DAE008 000000E6 */  swc1       $f0, 0x0($16)
    /* 00230C 01DAE00C 080021C6 */  lwc1       $f1, 0x8($17)
    /* 002310 01DAE010 A800B127 */  addiu      $17, $29, 0xA8
    /* 002314 01DAE014 000020C6 */  lwc1       $f0, 0x0($17)
    /* 002318 01DAE018 01000146 */  sub.s      $f0, $f0, $f1
    /* 00231C 01DAE01C 000020E6 */  swc1       $f0, 0x0($17)
    /* 002320 01DAE020 A000A427 */  addiu      $4, $29, 0xA0
    /* 002324 01DAE024 282E8070 */  paddub     $5, $4, $0
    /* 002328 01DAE028 9285040C */  jal        sceVu0Normalize
    /* 00232C 01DAE02C 00000000 */   nop
    /* 002330 01DAE030 7041023C */  lui        $2, (0x41700000 >> 16)
    /* 002334 01DAE034 00088244 */  mtc1       $2, $f1
    /* 002338 01DAE038 A000A0C7 */  lwc1       $f0, 0xA0($29)
    /* 00233C 01DAE03C 02000146 */  mul.s      $f0, $f0, $f1
    /* 002340 01DAE040 A000A0E7 */  swc1       $f0, 0xA0($29)
    /* 002344 01DAE044 000000C6 */  lwc1       $f0, 0x0($16)
    /* 002348 01DAE048 02000146 */  mul.s      $f0, $f0, $f1
    /* 00234C 01DAE04C 000000E6 */  swc1       $f0, 0x0($16)
    /* 002350 01DAE050 000020C6 */  lwc1       $f0, 0x0($17)
    /* 002354 01DAE054 02000146 */  mul.s      $f0, $f0, $f1
    /* 002358 01DAE058 000020E6 */  swc1       $f0, 0x0($17)
    /* 00235C 01DAE05C 3001A427 */  addiu      $4, $29, 0x130
    /* 002360 01DAE060 F88B82DF */  ld         $2, -0x7408($28)
    /* 002364 01DAE064 000082FC */  sd         $2, 0x0($4)
    /* 002368 01DAE068 3001A393 */  lbu        $3, 0x130($29)
    /* 00236C 01DAE06C 03000630 */  andi       $6, $0, 0x3
    /* 002370 01DAE070 FCFF0224 */  addiu      $2, $0, -0x4
    /* 002374 01DAE074 24106200 */  and        $2, $3, $2
    /* 002378 01DAE078 25104600 */  or         $2, $2, $6
    /* 00237C 01DAE07C 3001A2A3 */  sb         $2, 0x130($29)
    /* 002380 01DAE080 3001A593 */  lbu        $5, 0x130($29)
    /* 002384 01DAE084 08000364 */  daddiu     $3, $0, 0x8
    /* 002388 01DAE088 F3FF0224 */  addiu      $2, $0, -0xD
    /* 00238C 01DAE08C 2410A200 */  and        $2, $5, $2
    /* 002390 01DAE090 25104300 */  or         $2, $2, $3
    /* 002394 01DAE094 3001A2A3 */  sb         $2, 0x130($29)
    /* 002398 01DAE098 3001A593 */  lbu        $5, 0x130($29)
    /* 00239C 01DAE09C 00190600 */  sll        $3, $6, 4
    /* 0023A0 01DAE0A0 CFFF0224 */  addiu      $2, $0, -0x31
    /* 0023A4 01DAE0A4 2410A200 */  and        $2, $5, $2
    /* 0023A8 01DAE0A8 25104300 */  or         $2, $2, $3
    /* 0023AC 01DAE0AC 3001A2A3 */  sb         $2, 0x130($29)
    /* 0023B0 01DAE0B0 3001A593 */  lbu        $5, 0x130($29)
    /* 0023B4 01DAE0B4 40000364 */  daddiu     $3, $0, 0x40
    /* 0023B8 01DAE0B8 3FFF0224 */  addiu      $2, $0, -0xC1
    /* 0023BC 01DAE0BC 2410A200 */  and        $2, $5, $2
    /* 0023C0 01DAE0C0 25104300 */  or         $2, $2, $3
    /* 0023C4 01DAE0C4 3001A2A3 */  sb         $2, 0x130($29)
    /* 0023C8 01DAE0C8 E4BB040C */  jal        MGSetGsALPHA__FP10sceGsAlpha
    /* 0023CC 01DAE0CC 00000000 */   nop
    /* 0023D0 01DAE0D0 3801A427 */  addiu      $4, $29, 0x138
    /* 0023D4 01DAE0D4 F08B82DF */  ld         $2, -0x7410($28)
    /* 0023D8 01DAE0D8 000082FC */  sd         $2, 0x0($4)
    /* 0023DC 01DAE0DC 3C01A593 */  lbu        $5, 0x13C($29)
    /* 0023E0 01DAE0E0 01000364 */  daddiu     $3, $0, 0x1
    /* 0023E4 01DAE0E4 FEFF0224 */  addiu      $2, $0, -0x2
    /* 0023E8 01DAE0E8 2410A200 */  and        $2, $5, $2
    /* 0023EC 01DAE0EC 25104300 */  or         $2, $2, $3
    /* 0023F0 01DAE0F0 3C01A2A3 */  sb         $2, 0x13C($29)
    /* 0023F4 01DAE0F4 B0BB040C */  jal        MGSetGsZBUF__FP9sceGsZbuf
    /* 0023F8 01DAE0F8 00000000 */   nop
    /* 0023FC 01DAE0FC A006A1C6 */  lwc1       $f1, 0x6A0($21)
    /* 002400 01DAE100 00008044 */  mtc1       $0, $f0
    /* 002404 01DAE104 00000000 */  nop
    /* 002408 01DAE108 36080046 */  c.le.s     $f1, $f0
    /* 00240C 01DAE10C 00000000 */  nop
    /* 002410 01DAE110 75000145 */  bc1t       .L01DAE2E8
    /* 002414 01DAE114 00000000 */   nop
    /* 002418 01DAE118 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 00241C 01DAE11C 00008244 */  mtc1       $2, $f0
    /* 002420 01DAE120 00000000 */  nop
    /* 002424 01DAE124 01080046 */  sub.s      $f0, $f1, $f0
    /* 002428 01DAE128 A006A0E6 */  swc1       $f0, 0x6A0($21)
    /* 00242C 01DAE12C B005A1C6 */  lwc1       $f1, 0x5B0($21)
    /* 002430 01DAE130 803E023C */  lui        $2, (0x3E800000 >> 16)
    /* 002434 01DAE134 00008244 */  mtc1       $2, $f0
    /* 002438 01DAE138 00000000 */  nop
    /* 00243C 01DAE13C 01080046 */  sub.s      $f0, $f1, $f0
    /* 002440 01DAE140 B005A0E6 */  swc1       $f0, 0x5B0($21)
    /* 002444 01DAE144 B003A426 */  addiu      $4, $21, 0x3B0
    /* 002448 01DAE148 282E4072 */  paddub     $5, $18, $0
    /* 00244C 01DAE14C 0C86040C */  jal        sceVu0CopyVector
    /* 002450 01DAE150 00000000 */   nop
    /* 002454 01DAE154 B003A0C6 */  lwc1       $f0, 0x3B0($21)
    /* 002458 01DAE158 B000A0E7 */  swc1       $f0, 0xB0($29)
    /* 00245C 01DAE15C B403A0C6 */  lwc1       $f0, 0x3B4($21)
    /* 002460 01DAE160 B400B227 */  addiu      $18, $29, 0xB4
    /* 002464 01DAE164 000040E6 */  swc1       $f0, 0x0($18)
    /* 002468 01DAE168 B803A0C6 */  lwc1       $f0, 0x3B8($21)
    /* 00246C 01DAE16C B800B327 */  addiu      $19, $29, 0xB8
    /* 002470 01DAE170 000060E6 */  swc1       $f0, 0x0($19)
    /* 002474 01DAE174 803F023C */  lui        $2, (0x3F800000 >> 16)
    /* 002478 01DAE178 BC00A2AF */  sw         $2, 0xBC($29)
    /* 00247C 01DAE17C B005ACC6 */  lwc1       $f12, 0x5B0($21)
    /* 002480 01DAE180 0040023C */  lui        $2, (0x40000000 >> 16)
    /* 002484 01DAE184 00008244 */  mtc1       $2, $f0
    /* 002488 01DAE188 00000000 */  nop
    /* 00248C 01DAE18C 43630046 */  div.s      $f13, $f12, $f0
    /* 002490 01DAE190 C000A427 */  addiu      $4, $29, 0xC0
    /* 002494 01DAE194 D000A527 */  addiu      $5, $29, 0xD0
    /* 002498 01DAE198 B000A627 */  addiu      $6, $29, 0xB0
    /* 00249C 01DAE19C 283E0070 */  paddub     $7, $0, $0
    /* 0024A0 01DAE1A0 D0B9040C */  jal        MGRotTransPers3DSprite__FPiPiPfffi
    /* 0024A4 01DAE1A4 00000000 */   nop
    /* 0024A8 01DAE1A8 01000324 */  addiu      $3, $0, 0x1
    /* 0024AC 01DAE1AC 4E004314 */  bne        $2, $3, .L01DAE2E8
    /* 0024B0 01DAE1B0 00000000 */   nop
    /* 0024B4 01DAE1B4 D000A28F */  lw         $2, 0xD0($29)
    /* 0024B8 01DAE1B8 0001A2AF */  sw         $2, 0x100($29)
    /* 0024BC 01DAE1BC C400A28F */  lw         $2, 0xC4($29)
    /* 0024C0 01DAE1C0 0401A2AF */  sw         $2, 0x104($29)
    /* 0024C4 01DAE1C4 C800B627 */  addiu      $22, $29, 0xC8
    /* 0024C8 01DAE1C8 0000C28E */  lw         $2, 0x0($22)
    /* 0024CC 01DAE1CC 0801B427 */  addiu      $20, $29, 0x108
    /* 0024D0 01DAE1D0 000082AE */  sw         $2, 0x0($20)
    /* 0024D4 01DAE1D4 CC00A28F */  lw         $2, 0xCC($29)
    /* 0024D8 01DAE1D8 0C01A2AF */  sw         $2, 0x10C($29)
    /* 0024DC 01DAE1DC C000A28F */  lw         $2, 0xC0($29)
    /* 0024E0 01DAE1E0 1001A2AF */  sw         $2, 0x110($29)
    /* 0024E4 01DAE1E4 D400A28F */  lw         $2, 0xD4($29)
    /* 0024E8 01DAE1E8 1401A2AF */  sw         $2, 0x114($29)
    /* 0024EC 01DAE1EC D800BE27 */  addiu      $30, $29, 0xD8
    /* 0024F0 01DAE1F0 0000C28F */  lw         $2, 0x0($30)
    /* 0024F4 01DAE1F4 1801B727 */  addiu      $23, $29, 0x118
    /* 0024F8 01DAE1F8 0000E2AE */  sw         $2, 0x0($23)
    /* 0024FC 01DAE1FC DC00A28F */  lw         $2, 0xDC($29)
    /* 002500 01DAE200 1C01A2AF */  sw         $2, 0x11C($29)
    /* 002504 01DAE204 B000A1C7 */  lwc1       $f1, 0xB0($29)
    /* 002508 01DAE208 A000A0C7 */  lwc1       $f0, 0xA0($29)
    /* 00250C 01DAE20C 00080046 */  add.s      $f0, $f1, $f0
    /* 002510 01DAE210 B000A0E7 */  swc1       $f0, 0xB0($29)
    /* 002514 01DAE214 000041C6 */  lwc1       $f1, 0x0($18)
    /* 002518 01DAE218 000000C6 */  lwc1       $f0, 0x0($16)
    /* 00251C 01DAE21C 00080046 */  add.s      $f0, $f1, $f0
    /* 002520 01DAE220 000040E6 */  swc1       $f0, 0x0($18)
    /* 002524 01DAE224 000061C6 */  lwc1       $f1, 0x0($19)
    /* 002528 01DAE228 000020C6 */  lwc1       $f0, 0x0($17)
    /* 00252C 01DAE22C 00080046 */  add.s      $f0, $f1, $f0
    /* 002530 01DAE230 000060E6 */  swc1       $f0, 0x0($19)
    /* 002534 01DAE234 B005ACC6 */  lwc1       $f12, 0x5B0($21)
    /* 002538 01DAE238 0040023C */  lui        $2, (0x40000000 >> 16)
    /* 00253C 01DAE23C 00008244 */  mtc1       $2, $f0
    /* 002540 01DAE240 00000000 */  nop
    /* 002544 01DAE244 43630046 */  div.s      $f13, $f12, $f0
    /* 002548 01DAE248 E000A427 */  addiu      $4, $29, 0xE0
    /* 00254C 01DAE24C F000A527 */  addiu      $5, $29, 0xF0
    /* 002550 01DAE250 B000A627 */  addiu      $6, $29, 0xB0
    /* 002554 01DAE254 283E0070 */  paddub     $7, $0, $0
    /* 002558 01DAE258 D0B9040C */  jal        MGRotTransPers3DSprite__FPiPiPfffi
    /* 00255C 01DAE25C 00000000 */   nop
    /* 002560 01DAE260 01000324 */  addiu      $3, $0, 0x1
    /* 002564 01DAE264 06004314 */  bne        $2, $3, .L01DAE280
    /* 002568 01DAE268 00000000 */   nop
    /* 00256C 01DAE26C E800A28F */  lw         $2, 0xE8($29)
    /* 002570 01DAE270 0000C2AF */  sw         $2, 0x0($30)
    /* 002574 01DAE274 0000E2AE */  sw         $2, 0x0($23)
    /* 002578 01DAE278 0000C2AE */  sw         $2, 0x0($22)
    /* 00257C 01DAE27C 000082AE */  sw         $2, 0x0($20)
  .L01DAE280:
    /* 002580 01DAE280 2001A0AF */  sw         $0, 0x120($29)
    /* 002584 01DAE284 2401A0AF */  sw         $0, 0x124($29)
    /* 002588 01DAE288 80000224 */  addiu      $2, $0, 0x80
    /* 00258C 01DAE28C 2801A2AF */  sw         $2, 0x128($29)
    /* 002590 01DAE290 2C01A2AF */  sw         $2, 0x12C($29)
    /* 002594 01DAE294 C701023C */  lui        $2, %hi(TexManager)
    /* 002598 01DAE298 70584424 */  addiu      $4, $2, %lo(TexManager)
    /* 00259C 01DAE29C DE01023C */  lui        $2, %hi(LIT_435__3)
    /* 0025A0 01DAE2A0 60BF4524 */  addiu      $5, $2, %lo(LIT_435__3)
    /* 0025A4 01DAE2A4 FFFF0624 */  addiu      $6, $0, -0x1
    /* 0025A8 01DAE2A8 B4C4040C */  jal        GetTexture__15CTextureManagerFPci
    /* 0025AC 01DAE2AC 00000000 */   nop
    /* 0025B0 01DAE2B0 28864070 */  paddub     $16, $2, $0
    /* 0025B4 01DAE2B4 A006ACC6 */  lwc1       $f12, 0x6A0($21)
    /* 0025B8 01DAE2B8 5044040C */  jal        fptoui
    /* 0025BC 01DAE2BC 00000000 */   nop
    /* 0025C0 01DAE2C0 D48B848F */  lw         $4, -0x742C($28)
    /* 0025C4 01DAE2C4 282E0072 */  paddub     $5, $16, $0
    /* 0025C8 01DAE2C8 2001A627 */  addiu      $6, $29, 0x120
    /* 0025CC 01DAE2CC C000A727 */  addiu      $7, $29, 0xC0
    /* 0025D0 01DAE2D0 0001A827 */  addiu      $8, $29, 0x100
    /* 0025D4 01DAE2D4 1001A927 */  addiu      $9, $29, 0x110
    /* 0025D8 01DAE2D8 D000AA27 */  addiu      $10, $29, 0xD0
    /* 0025DC 01DAE2DC 285E4070 */  paddub     $11, $2, $0
    /* 0025E0 01DAE2E0 1C75050C */  jal        set3DSprite__FP13sceVif1PacketP8CTextureRC8CRect_i_PiPiPiPiUc
    /* 0025E4 01DAE2E4 00000000 */   nop
  .L01DAE2E8:
    /* 0025E8 01DAE2E8 28260070 */  paddub     $4, $0, $0
    /* 0025EC 01DAE2EC E4BB040C */  jal        MGSetGsALPHA__FP10sceGsAlpha
    /* 0025F0 01DAE2F0 00000000 */   nop
    /* 0025F4 01DAE2F4 28260070 */  paddub     $4, $0, $0
    /* 0025F8 01DAE2F8 B0BB040C */  jal        MGSetGsZBUF__FP9sceGsZbuf
    /* 0025FC 01DAE2FC 00000000 */   nop
    /* 002600 01DAE300 9000BF7B */  lq         $31, 0x90($29)
    /* 002604 01DAE304 8000BE7B */  lq         $30, 0x80($29)
    /* 002608 01DAE308 7000B77B */  lq         $23, 0x70($29)
    /* 00260C 01DAE30C 6000B67B */  lq         $22, 0x60($29)
    /* 002610 01DAE310 5000B57B */  lq         $21, 0x50($29)
    /* 002614 01DAE314 4000B47B */  lq         $20, 0x40($29)
    /* 002618 01DAE318 3000B37B */  lq         $19, 0x30($29)
    /* 00261C 01DAE31C 2000B27B */  lq         $18, 0x20($29)
    /* 002620 01DAE320 1000B17B */  lq         $17, 0x10($29)
    /* 002624 01DAE324 0000B07B */  lq         $16, 0x0($29)
    /* 002628 01DAE328 4001BD27 */  addiu      $29, $29, 0x140
    /* 00262C 01DAE32C 0800E003 */  jr         $31
    /* 002630 01DAE330 00000000 */   nop
    /* 002634 01DAE334 00000000 */  nop
    /* 002638 01DAE338 00000000 */  nop
    /* 00263C 01DAE33C 00000000 */  nop

glabel Step__10CMajinBeemFv
    /* 002640 01DAE340 C0FFBD27 */  addiu      $29, $29, -0x40
    /* 002644 01DAE344 3000BF7F */  sq         $31, 0x30($29)
    /* 002648 01DAE348 2000B27F */  sq         $18, 0x20($29)
    /* 00264C 01DAE34C 1000B17F */  sq         $17, 0x10($29)
    /* 002650 01DAE350 0000B07F */  sq         $16, 0x0($29)
    /* 002654 01DAE354 28968070 */  paddub     $18, $4, $0
    /* 002658 01DAE358 D003868C */  lw         $6, 0x3D0($4)
    /* 00265C 01DAE35C 01000324 */  addiu      $3, $0, 0x1
    /* 002660 01DAE360 1C00C310 */  beq        $6, $3, .L01DAE3D4
    /* 002664 01DAE364 00000000 */   nop
    /* 002668 01DAE368 0300C010 */  beqz       $6, .L01DAE378
    /* 00266C 01DAE36C 00000000 */   nop
    /* 002670 01DAE370 7F000010 */  b          .L01DAE570
    /* 002674 01DAE374 00000000 */   nop
  .L01DAE378:
    /* 002678 01DAE378 C00341C6 */  lwc1       $f1, 0x3C0($18)
    /* 00267C 01DAE37C 000040C6 */  lwc1       $f0, 0x0($18)
    /* 002680 01DAE380 010B0046 */  sub.s      $f12, $f1, $f0
    /* 002684 01DAE384 C40341C6 */  lwc1       $f1, 0x3C4($18)
    /* 002688 01DAE388 040040C6 */  lwc1       $f0, 0x4($18)
    /* 00268C 01DAE38C 410B0046 */  sub.s      $f13, $f1, $f0
    /* 002690 01DAE390 5077040C */  jal        atan2f
    /* 002694 01DAE394 00000000 */   nop
    /* 002698 01DAE398 A80640E6 */  swc1       $f0, 0x6A8($18)
    /* 00269C 01DAE39C C00341C6 */  lwc1       $f1, 0x3C0($18)
    /* 0026A0 01DAE3A0 000040C6 */  lwc1       $f0, 0x0($18)
    /* 0026A4 01DAE3A4 010B0046 */  sub.s      $f12, $f1, $f0
    /* 0026A8 01DAE3A8 C80341C6 */  lwc1       $f1, 0x3C8($18)
    /* 0026AC 01DAE3AC 080040C6 */  lwc1       $f0, 0x8($18)
    /* 0026B0 01DAE3B0 410B0046 */  sub.s      $f13, $f1, $f0
    /* 0026B4 01DAE3B4 5077040C */  jal        atan2f
    /* 0026B8 01DAE3B8 00000000 */   nop
    /* 0026BC 01DAE3BC AC0640E6 */  swc1       $f0, 0x6AC($18)
    /* 0026C0 01DAE3C0 D003438E */  lw         $3, 0x3D0($18)
    /* 0026C4 01DAE3C4 01006324 */  addiu      $3, $3, 0x1
    /* 0026C8 01DAE3C8 D00343AE */  sw         $3, 0x3D0($18)
    /* 0026CC 01DAE3CC 68000010 */  b          .L01DAE570
    /* 0026D0 01DAE3D0 00000000 */   nop
  .L01DAE3D4:
    /* 0026D4 01DAE3D4 28860070 */  paddub     $16, $0, $0
    /* 0026D8 01DAE3D8 5D000010 */  b          .L01DAE550
    /* 0026DC 01DAE3DC 00000000 */   nop
  .L01DAE3E0:
    /* 0026E0 01DAE3E0 288E0070 */  paddub     $17, $0, $0
    /* 0026E4 01DAE3E4 11000010 */  b          .L01DAE42C
    /* 0026E8 01DAE3E8 00000000 */   nop
  .L01DAE3EC:
    /* 0026EC 01DAE3EC 3A000224 */  addiu      $2, $0, 0x3A
    /* 0026F0 01DAE3F0 23105100 */  subu       $2, $2, $17
    /* 0026F4 01DAE3F4 00110200 */  sll        $2, $2, 4
    /* 0026F8 01DAE3F8 21204202 */  addu       $4, $18, $2
    /* 0026FC 01DAE3FC 39000224 */  addiu      $2, $0, 0x39
    /* 002700 01DAE400 23105100 */  subu       $2, $2, $17
    /* 002704 01DAE404 00110200 */  sll        $2, $2, 4
    /* 002708 01DAE408 21284202 */  addu       $5, $18, $2
    /* 00270C 01DAE40C 0C86040C */  jal        sceVu0CopyVector
    /* 002710 01DAE410 00000000 */   nop
    /* 002714 01DAE414 80101100 */  sll        $2, $17, 2
    /* 002718 01DAE418 21185200 */  addu       $3, $2, $18
    /* 00271C 01DAE41C D403628C */  lw         $2, 0x3D4($3)
    /* 002720 01DAE420 01004224 */  addiu      $2, $2, 0x1
    /* 002724 01DAE424 D40362AC */  sw         $2, 0x3D4($3)
    /* 002728 01DAE428 01003126 */  addiu      $17, $17, 0x1
  .L01DAE42C:
    /* 00272C 01DAE42C 3A00222A */  slti       $2, $17, 0x3A
    /* 002730 01DAE430 EEFF4014 */  bnez       $2, .L01DAE3EC
    /* 002734 01DAE434 00000000 */   nop
    /* 002738 01DAE438 A8064CC6 */  lwc1       $f12, 0x6A8($18)
    /* 00273C 01DAE43C 9044040C */  jal        fptodp
    /* 002740 01DAE440 00000000 */   nop
    /* 002744 01DAE444 28264070 */  paddub     $4, $2, $0
    /* 002748 01DAE448 F473040C */  jal        cos
    /* 00274C 01DAE44C 00000000 */   nop
    /* 002750 01DAE450 288E4070 */  paddub     $17, $2, $0
    /* 002754 01DAE454 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 002758 01DAE458 00088244 */  mtc1       $2, $f1
    /* 00275C 01DAE45C B00640C6 */  lwc1       $f0, 0x6B0($18)
    /* 002760 01DAE460 03030146 */  div.s      $f12, $f0, $f1
    /* 002764 01DAE464 9044040C */  jal        fptodp
    /* 002768 01DAE468 00000000 */   nop
    /* 00276C 01DAE46C 28264070 */  paddub     $4, $2, $0
    /* 002770 01DAE470 282E2072 */  paddub     $5, $17, $0
    /* 002774 01DAE474 9E3F040C */  jal        dpmul
    /* 002778 01DAE478 00000000 */   nop
    /* 00277C 01DAE47C 28264070 */  paddub     $4, $2, $0
    /* 002780 01DAE480 9241040C */  jal        dptofp
    /* 002784 01DAE484 00000000 */   nop
    /* 002788 01DAE488 040041C6 */  lwc1       $f1, 0x4($18)
    /* 00278C 01DAE48C 00080046 */  add.s      $f0, $f1, $f0
    /* 002790 01DAE490 040040E6 */  swc1       $f0, 0x4($18)
    /* 002794 01DAE494 AC064CC6 */  lwc1       $f12, 0x6AC($18)
    /* 002798 01DAE498 9044040C */  jal        fptodp
    /* 00279C 01DAE49C 00000000 */   nop
    /* 0027A0 01DAE4A0 28264070 */  paddub     $4, $2, $0
    /* 0027A4 01DAE4A4 C474040C */  jal        sin
    /* 0027A8 01DAE4A8 00000000 */   nop
    /* 0027AC 01DAE4AC 288E4070 */  paddub     $17, $2, $0
    /* 0027B0 01DAE4B0 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 0027B4 01DAE4B4 00088244 */  mtc1       $2, $f1
    /* 0027B8 01DAE4B8 B00640C6 */  lwc1       $f0, 0x6B0($18)
    /* 0027BC 01DAE4BC 03030146 */  div.s      $f12, $f0, $f1
    /* 0027C0 01DAE4C0 9044040C */  jal        fptodp
    /* 0027C4 01DAE4C4 00000000 */   nop
    /* 0027C8 01DAE4C8 28264070 */  paddub     $4, $2, $0
    /* 0027CC 01DAE4CC 282E2072 */  paddub     $5, $17, $0
    /* 0027D0 01DAE4D0 9E3F040C */  jal        dpmul
    /* 0027D4 01DAE4D4 00000000 */   nop
    /* 0027D8 01DAE4D8 28264070 */  paddub     $4, $2, $0
    /* 0027DC 01DAE4DC 9241040C */  jal        dptofp
    /* 0027E0 01DAE4E0 00000000 */   nop
    /* 0027E4 01DAE4E4 000041C6 */  lwc1       $f1, 0x0($18)
    /* 0027E8 01DAE4E8 00080046 */  add.s      $f0, $f1, $f0
    /* 0027EC 01DAE4EC 000040E6 */  swc1       $f0, 0x0($18)
    /* 0027F0 01DAE4F0 AC064CC6 */  lwc1       $f12, 0x6AC($18)
    /* 0027F4 01DAE4F4 9044040C */  jal        fptodp
    /* 0027F8 01DAE4F8 00000000 */   nop
    /* 0027FC 01DAE4FC 28264070 */  paddub     $4, $2, $0
    /* 002800 01DAE500 F473040C */  jal        cos
    /* 002804 01DAE504 00000000 */   nop
    /* 002808 01DAE508 288E4070 */  paddub     $17, $2, $0
    /* 00280C 01DAE50C 4040023C */  lui        $2, (0x40400000 >> 16)
    /* 002810 01DAE510 00088244 */  mtc1       $2, $f1
    /* 002814 01DAE514 B00640C6 */  lwc1       $f0, 0x6B0($18)
    /* 002818 01DAE518 03030146 */  div.s      $f12, $f0, $f1
    /* 00281C 01DAE51C 9044040C */  jal        fptodp
    /* 002820 01DAE520 00000000 */   nop
    /* 002824 01DAE524 28264070 */  paddub     $4, $2, $0
    /* 002828 01DAE528 282E2072 */  paddub     $5, $17, $0
    /* 00282C 01DAE52C 9E3F040C */  jal        dpmul
    /* 002830 01DAE530 00000000 */   nop
    /* 002834 01DAE534 28264070 */  paddub     $4, $2, $0
    /* 002838 01DAE538 9241040C */  jal        dptofp
    /* 00283C 01DAE53C 00000000 */   nop
    /* 002840 01DAE540 080041C6 */  lwc1       $f1, 0x8($18)
    /* 002844 01DAE544 00080046 */  add.s      $f0, $f1, $f0
    /* 002848 01DAE548 080040E6 */  swc1       $f0, 0x8($18)
    /* 00284C 01DAE54C 01001026 */  addiu      $16, $16, 0x1
  .L01DAE550:
    /* 002850 01DAE550 0300032A */  slti       $3, $16, 0x3
    /* 002854 01DAE554 A2FF6014 */  bnez       $3, .L01DAE3E0
    /* 002858 01DAE558 00000000 */   nop
    /* 00285C 01DAE55C BC04438E */  lw         $3, 0x4BC($18)
    /* 002860 01DAE560 C8006328 */  slti       $3, $3, 0xC8
    /* 002864 01DAE564 02006014 */  bnez       $3, .L01DAE570
    /* 002868 01DAE568 00000000 */   nop
    /* 00286C 01DAE56C A40640AE */  sw         $0, 0x6A4($18)
  .L01DAE570:
    /* 002870 01DAE570 3000BF7B */  lq         $31, 0x30($29)
    /* 002874 01DAE574 2000B27B */  lq         $18, 0x20($29)
    /* 002878 01DAE578 1000B17B */  lq         $17, 0x10($29)
    /* 00287C 01DAE57C 0000B07B */  lq         $16, 0x0($29)
    /* 002880 01DAE580 4000BD27 */  addiu      $29, $29, 0x40
    /* 002884 01DAE584 0800E003 */  jr         $31
    /* 002888 01DAE588 00000000 */   nop
    /* 00288C 01DAE58C 00000000 */  nop
