.include "macro.inc"

.set noat /* Allow manual use of $at. */
.set noreorder /* Don't insert nops after branches. */

.section .sbss
/* Generated by spimdisasm 1.42.3 */

glabel _fbss
/* 002A2380 */ .space 0x04

glabel read_buffer
/* 002A2384 */ .space 0x04

glabel WorkBuffer__2
/* 002A2388 */ .space 0x04

glabel ActiveData
/* 002A238C */ .space 0x04

glabel dset_mds_packet
/* 002A2390 */ .space 0x04

glabel dset_mds_objnum
/* 002A2394 */ .space 0x04

glabel flag$332
/* 002A2398 */ .space 0x04

glabel init$333
/* 002A239C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A239D
/* 002A239D */ .space 0x03

glabel rpad$180
/* 002A23A0 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A23A2
/* 002A23A2 */ .space 0x02

glabel init$181
/* 002A23A4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A23A5
/* 002A23A5 */ .space 0x03

glabel cnt$250
/* 002A23A8 */ .space 0x04

glabel init$251
/* 002A23AC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A23AD
/* 002A23AD */ .space 0x03

glabel DBuffID
/* 002A23B0 */ .space 0x04

glabel mgWaitVSync
/* 002A23B4 */ .space 0x04

glabel DmaCH1
/* 002A23B8 */ .space 0x04

glabel DmaCH2
/* 002A23BC */ .space 0x04

glabel DmaCH8
/* 002A23C0 */ .space 0x04

glabel Vif1Packet
/* 002A23C4 */ .space 0x04

glabel VSyncField__2
/* 002A23C8 */ .space 0x04

glabel mgClearBackFlag
/* 002A23CC */ .space 0x04

glabel mgTEX1Env
/* 002A23D0 */ .space 0x08

glabel mgPixelTest
/* 002A23D8 */ .space 0x08

glabel mgZBuffer
/* 002A23E0 */ .space 0x08

glabel mgAlpha
/* 002A23E8 */ .space 0x08

glabel mgTexa
/* 002A23F0 */ .space 0x08

glabel packetbuf
/* 002A23F8 */ .space 0x08

glabel vcount
/* 002A2400 */ .space 0x04

glabel over_vsync
/* 002A2404 */ .space 0x04

glabel VSyncCallBack2
/* 002A2408 */ .space 0x04

glabel call_back_active
/* 002A240C */ .space 0x04

glabel movie_count
/* 002A2410 */ .space 0x04

glabel image_num$208
/* 002A2414 */ .space 0x04

glabel init$209
/* 002A2418 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2419
/* 002A2419 */ .space 0x03

glabel h_count
/* 002A241C */ .space 0x04

glabel count$298
/* 002A2420 */ .space 0x04

glabel init$299
/* 002A2424 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2425
/* 002A2425 */ .space 0x03

glabel old_vcount$301
/* 002A2428 */ .space 0x08

glabel init$302
/* 002A2430 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2431
/* 002A2431 */ .space 0x03

glabel capture$334
/* 002A2434 */ .space 0x04

glabel init$335
/* 002A2438 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2439
/* 002A2439 */ .space 0x03

glabel capture_start$337
/* 002A243C */ .space 0x04

glabel init$338
/* 002A2440 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2441
/* 002A2441 */ .space 0x03

glabel f$347
/* 002A2444 */ .space 0x04

glabel init$348
/* 002A2448 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2449
/* 002A2449 */ .space 0x03

glabel dyy$683
/* 002A244C */ .space 0x04

glabel init$684
/* 002A2450 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2451
/* 002A2451 */ .space 0x03

glabel dx$686
/* 002A2454 */ .space 0x04

glabel init$687
/* 002A2458 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2459
/* 002A2459 */ .space 0x07

glabel Shadow_SaveFrameBuff
/* 002A2460 */ .space 0x08

glabel Shadow_WorkTex
/* 002A2468 */ .space 0x08

glabel clut_adr$343
/* 002A2470 */ .space 0x04

glabel init$344
/* 002A2474 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2475
/* 002A2475 */ .space 0x03

glabel MotionStopFlag__10CCharacter
/* 002A2478 */ .space 0x04

glabel mds_buffer
/* 002A247C */ .space 0x04

glabel buffer__2
/* 002A2480 */ .space 0x04

glabel exbuffer
/* 002A2484 */ .space 0x04

glabel img_buffer
/* 002A2488 */ .space 0x04

glabel texture_block
/* 002A248C */ .space 0x04

glabel character
/* 002A2490 */ .space 0x04

glabel vertex_anime
/* 002A2494 */ .space 0x04

glabel def_vtype
/* 002A2498 */ .space 0x04

glabel shadow_vertex_anime
/* 002A249C */ .space 0x04

glabel pack_data
/* 002A24A0 */ .space 0x04

glabel motion_info_num
/* 002A24A4 */ .space 0x04

glabel key_start
/* 002A24A8 */ .space 0x04

glabel key_no
/* 002A24AC */ .space 0x04

glabel motion_info
/* 002A24B0 */ .space 0x04

glabel cloth_cnt
/* 002A24B4 */ .space 0x04

glabel now_motion_data
/* 002A24B8 */ .space 0x04

glabel shadow_motion
/* 002A24BC */ .space 0x04

glabel dont_delete_texb
/* 002A24C0 */ .space 0x04

glabel alloc_mdt_list
/* 002A24C4 */ .space 0x04

glabel alloc_dbuff_list
/* 002A24C8 */ .space 0x04

glabel alloc_smdt_list
/* 002A24CC */ .space 0x04

glabel alloc_sdbuff_list
/* 002A24D0 */ .space 0x04

glabel fsound_num
/* 002A24D4 */ .space 0x04

glabel tex_anime_list
/* 002A24D8 */ .space 0x04

glabel config_file
/* 002A24DC */ .space 0x04

glabel config_file_size
/* 002A24E0 */ .space 0x04

glabel header_num
/* 002A24E4 */ .space 0x04

glabel packfile_buff
/* 002A24E8 */ .space 0x04

glabel tree
/* 002A24EC */ .space 0x04

glabel data_sector
/* 002A24F0 */ .space 0x04

glabel old_vsync
/* 002A24F4 */ .space 0x04

glabel start_vsync
/* 002A24F8 */ .space 0x04

glabel pCloth
/* 002A24FC */ .space 0x04

glabel pBound
/* 002A2500 */ .space 0x04

glabel ParentFrame
/* 002A2504 */ .space 0x04

glabel DataBuffer
/* 002A2508 */ .space 0x04

glabel SaveData
/* 002A250C */ .space 0x04

glabel GameClearFlag
/* 002A2510 */ .space 0x04

glabel main_select_menu_no
/* 002A2514 */ .space 0x04

glabel MapNo
/* 002A2518 */ .space 0x04

glabel OldMapNo
/* 002A251C */ .space 0x04

glabel LocalMapNo
/* 002A2520 */ .space 0x04

glabel StartEventNo
/* 002A2524 */ .space 0x04

glabel SystemMes
/* 002A2528 */ .space 0x04

glabel CSnd
/* 002A252C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A252D
/* 002A252D */ .space 0x03

glabel main_select_padrup
/* 002A2530 */ .space 0x04

glabel mode
/* 002A2534 */ .space 0x04

glabel d1
/* 002A2538 */ .space 0x04

glabel d2
/* 002A253C */ .space 0x04

glabel d8
/* 002A2540 */ .space 0x04

glabel mc_mode
/* 002A2544 */ .space 0x04

glabel PolyCount
/* 002A2548 */ .space 0x04

glabel depth$682
/* 002A254C */ .space 0x04

glabel init$683
/* 002A2550 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2551
/* 002A2551 */ .space 0x03

glabel wt$685
/* 002A2554 */ .space 0x04

glabel init$686
/* 002A2558 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2559
/* 002A2559 */ .space 0x03

glabel init_flag$704
/* 002A255C */ .space 0x04

glabel init$705
/* 002A2560 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2561
/* 002A2561 */ .space 0x03

glabel edit_map
/* 002A2564 */ .space 0x04

glabel sub_map
/* 002A2568 */ .space 0x04

glabel event_no
/* 002A256C */ .space 0x04

glabel select$896
/* 002A2570 */ .space 0x04

glabel init$897
/* 002A2574 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2575
/* 002A2575 */ .space 0x03

glabel mem_chk_mode
/* 002A2578 */ .space 0x04

glabel check_cancel
/* 002A257C */ .space 0x04

glabel taiken_cnt
/* 002A2580 */ .space 0x04

glabel taiken_start
/* 002A2584 */ .space 0x04

glabel iopMSINBuffAddr
/* 002A2588 */ .space 0x04

glabel bd_size_total
/* 002A258C */ .space 0x04

glabel load_m_flg$571
/* 002A2590 */ .space 0x04

glabel init$572
/* 002A2594 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2595
/* 002A2595 */ .space 0x0B

glabel vert$388
/* 002A25A0 */ .space 0x04

glabel MesAbsDrawOff
/* 002A25A4 */ .space 0x04

glabel linear
/* 002A25A8 */ .space 0x04

glabel data_top
/* 002A25AC */ .space 0x04

glabel pdata
/* 002A25B0 */ .space 0x04

glabel dma_cnt
/* 002A25B4 */ .space 0x04

glabel now_loding_flag
/* 002A25B8 */ .space 0x04

glabel nl_start_cnt
/* 002A25BC */ .space 0x04

glabel col_cnt
/* 002A25C0 */ .space 0x04

glabel col_add
/* 002A25C4 */ .space 0x04

glabel logo_count
/* 002A25C8 */ .space 0x04

glabel count__2
/* 002A25CC */ .space 0x04

glabel map_title_no
/* 002A25D0 */ .space 0x04

glabel now_loding_off
/* 002A25D4 */ .space 0x04

glabel now_loading_vsync_end
/* 002A25D8 */ .space 0x04

glabel VSyncField
/* 002A25DC */ .space 0x04

glabel snd_read_buf
/* 002A25E0 */ .space 0x04

glabel bgm_off
/* 002A25E4 */ .space 0x04

glabel snd_id
/* 002A25E8 */ .space 0x04

glabel now_sound_set
/* 002A25EC */ .space 0x04

glabel now_voice_set
/* 002A25F0 */ .space 0x04

glabel now_bgm_no
/* 002A25F4 */ .space 0x04

glabel now_bgm_play
/* 002A25F8 */ .space 0x04

glabel now_bgm_vol
/* 002A25FC */ .space 0x04

glabel bgm_fade
/* 002A2600 */ .space 0x04

glabel now_bgm_fade_vol
/* 002A2604 */ .space 0x04

glabel bgm_fade_step
/* 002A2608 */ .space 0x04

glabel bgm_fade_vol
/* 002A260C */ .space 0x04

glabel now_amb_no
/* 002A2610 */ .space 0x04

glabel now_amb_vol
/* 002A2614 */ .space 0x04

glabel now_amb_play
/* 002A2618 */ .space 0x04

glabel now_sp_no
/* 002A261C */ .space 0x04

glabel se_table_no
/* 002A2620 */ .space 0x04

glabel basic_se_table_no
/* 002A2624 */ .space 0x04

glabel load_bgm_no
/* 002A2628 */ .space 0x04

glabel load_bgm_adr
/* 002A262C */ .space 0x04

glabel load_snd_set
/* 002A2630 */ .space 0x04

glabel load_snd_adr
/* 002A2634 */ .space 0x04

glabel load_voice_set
/* 002A2638 */ .space 0x04

glabel load_voice_adr
/* 002A263C */ .space 0x04

glabel load_sp_no
/* 002A2640 */ .space 0x04

glabel load_sp_adr
/* 002A2644 */ .space 0x04

glabel init_snd
/* 002A2648 */ .space 0x04

glabel system_snd_id$551
/* 002A264C */ .space 0x04

glabel init$552
/* 002A2650 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2651
/* 002A2651 */ .space 0x03

glabel se_list
/* 002A2654 */ .space 0x04

glabel SoundInfo
/* 002A2658 */ .space 0x04

glabel SystemMesCount
/* 002A265C */ .space 0x04

glabel SystemMesWait
/* 002A2660 */ .space 0x04

glabel SystemMesInputKey
/* 002A2664 */ .space 0x04

glabel sw
/* 002A2668 */ .space 0x04

glabel effect_count
/* 002A266C */ .space 0x04

glabel smoke_tex
/* 002A2670 */ .space 0x04

glabel sibuki_tex
/* 002A2674 */ .space 0x04

glabel hamon_tex
/* 002A2678 */ .space 0x04

glabel all_stop
/* 002A267C */ .space 0x04

glabel stop_anime__13CTextureAnime
/* 002A2680 */ .space 0x04

glabel pTexAnime
/* 002A2684 */ .space 0x04

glabel now_group
/* 002A2688 */ .space 0x04

glabel ebattle_flag
/* 002A268C */ .space 0x04

glabel ebattle_intro_flag
/* 002A2690 */ .space 0x04

glabel eb_count
/* 002A2694 */ .space 0x04

glabel eb_intro_cnt
/* 002A2698 */ .space 0x04

glabel eb_finish_cnt
/* 002A269C */ .space 0x04

glabel eb_end_count
/* 002A26A0 */ .space 0x04

glabel eb_result
/* 002A26A4 */ .space 0x04

glabel eb_key_count
/* 002A26A8 */ .space 0x04

glabel now_button_no
/* 002A26AC */ .space 0x04

glabel eb_chara
/* 002A26B0 */ .space 0x04

glabel fade_bgm
/* 002A26B4 */ .space 0x04

glabel play_fanfare
/* 002A26B8 */ .space 0x04

glabel now_time
/* 002A26BC */ .space 0x04

glabel sound_cnt
/* 002A26C0 */ .space 0x04

glabel debug_mode
/* 002A26C4 */ .space 0x04

glabel tex
/* 002A26C8 */ .space 0x04

glabel tex2
/* 002A26CC */ .space 0x04

glabel eb_key_num
/* 002A26D0 */ .space 0x04

glabel ok_draw_cnt
/* 002A26D4 */ .space 0x04

glabel ok_type
/* 002A26D8 */ .space 0x04

glabel ok_effect_button
/* 002A26DC */ .space 0x04

glabel viewMode
/* 002A26E0 */ .space 0x04

glabel chara_mode
/* 002A26E4 */ .space 0x04

glabel chara_fishing
/* 002A26E8 */ .space 0x04

glabel fishing_mes
/* 002A26EC */ .space 0x04

glabel viewAngleH
/* 002A26F0 */ .space 0x04

glabel viewAngleV
/* 002A26F4 */ .space 0x04

glabel rot_count$769
/* 002A26F8 */ .space 0x04

glabel init$770
/* 002A26FC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A26FD
/* 002A26FD */ .space 0x03

glabel bgm_vol$845
/* 002A2700 */ .space 0x04

glabel init$846
/* 002A2704 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2705
/* 002A2705 */ .space 0x03

glabel load_file$848
/* 002A2708 */ .space 0x04

glabel init$849
/* 002A270C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A270D
/* 002A270D */ .space 0x03

glabel st_cnt$855
/* 002A2710 */ .space 0x04

glabel init$856
/* 002A2714 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2715
/* 002A2715 */ .space 0x03

glabel wait_cnt$858
/* 002A2718 */ .space 0x04

glabel init$859
/* 002A271C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A271D
/* 002A271D */ .space 0x03

glabel cnt$1010
/* 002A2720 */ .space 0x04

glabel init$1011
/* 002A2724 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2725
/* 002A2725 */ .space 0x03

glabel ext$839
/* 002A2728 */ .space 0x04

glabel init$840
/* 002A272C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A272D
/* 002A272D */ .space 0x03

glabel EdDebugCameraFlag
/* 002A2730 */ .space 0x04

glabel EdDebugParamDrawOff
/* 002A2734 */ .space 0x04

glabel EdDebugCharaDrawOff
/* 002A2738 */ .space 0x04

glabel EdDebugMoveFlag
/* 002A273C */ .space 0x04

glabel DebugFont__2
/* 002A2740 */ .space 0x04

glabel count$345
/* 002A2744 */ .space 0x04

glabel init$346
/* 002A2748 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2749
/* 002A2749 */ .space 0x03

glabel thunder_count
/* 002A274C */ .space 0x04

glabel start_thunder
/* 002A2750 */ .space 0x04

glabel next_thunder_cnt
/* 002A2754 */ .space 0x04

glabel init_menu_cnt
/* 002A2758 */ .space 0x04

glabel menu_mode
/* 002A275C */ .space 0x04

glabel use_item
/* 002A2760 */ .space 0x04

glabel shop_no
/* 002A2764 */ .space 0x04

glabel name_reg_chara
/* 002A2768 */ .space 0x04

glabel SystemMesCount__2
/* 002A276C */ .space 0x04

glabel SystemMesPosition__2
/* 002A2770 */ .space 0x04

glabel SystemMesW
/* 002A2774 */ .space 0x04

glabel SystemMesH
/* 002A2778 */ .space 0x04

glabel SystemMesX
/* 002A277C */ .space 0x04

glabel SystemMesY
/* 002A2780 */ .space 0x04

glabel SystemMesWait__2
/* 002A2784 */ .space 0x04

glabel SystemMesInputKey__2
/* 002A2788 */ .space 0x04

glabel HelpMesCount
/* 002A278C */ .space 0x04

glabel cnt1
/* 002A2790 */ .space 0x04

glabel cnt2
/* 002A2794 */ .space 0x04

glabel ibox_open_flag
/* 002A2798 */ .space 0x04

glabel ibox_open_close_flag
/* 002A279C */ .space 0x04

glabel ibox_open_cnt
/* 002A27A0 */ .space 0x04

glabel ibox_frame
/* 002A27A4 */ .space 0x04

glabel ibox_base_frame
/* 002A27A8 */ .space 0x04

glabel frame_image_flag
/* 002A27AC */ .space 0x04

glabel edit_info
/* 002A27B0 */ .space 0x04

glabel texture_list
/* 002A27B4 */ .space 0x04

glabel fobject_list
/* 002A27B8 */ .space 0x04

glabel mapobj_list
/* 002A27BC */ .space 0x04

glabel objanime_list
/* 002A27C0 */ .space 0x04

glabel light_no
/* 002A27C4 */ .space 0x04

glabel partseffect_list
/* 002A27C8 */ .space 0x04

glabel objeffect_list
/* 002A27CC */ .space 0x04

glabel objtimer_list
/* 002A27D0 */ .space 0x04

glabel event_list
/* 002A27D4 */ .space 0x04

glabel water_list
/* 002A27D8 */ .space 0x04

glabel mapjump_id
/* 002A27DC */ .space 0x04

glabel people_list
/* 002A27E0 */ .space 0x04

glabel week_no
/* 002A27E4 */ .space 0x04

glabel objframe
/* 002A27E8 */ .space 0x04

glabel mapobj
/* 002A27EC */ .space 0x04

glabel mapparts
/* 002A27F0 */ .space 0x04

glabel water_info
/* 002A27F4 */ .space 0x04

glabel now_villinfo
/* 002A27F8 */ .space 0x04

glabel now_parts_no
/* 002A27FC */ .space 0x04

glabel binary
/* 002A2800 */ .space 0x04

glabel edit_rect_list
/* 002A2804 */ .space 0x04

glabel motion_parts_list
/* 002A2808 */ .space 0x04

glabel StayTexture
/* 002A280C */ .space 0x04

glabel NowEditMap
/* 002A2810 */ .space 0x04

glabel EdNPCReadBuffer
/* 002A2814 */ .space 0x04

glabel EdStepTimeFlag
/* 002A2818 */ .space 0x04

glabel EdInteriorFlag
/* 002A281C */ .space 0x04

glabel EdInteriorPartsNo
/* 002A2820 */ .space 0x04

glabel EdInteriorJumpID
/* 002A2824 */ .space 0x04

glabel EdInteriorDoorSound
/* 002A2828 */ .space 0x04

glabel EdInteriorStartEvent
/* 002A282C */ .space 0x04

glabel EdBeforeInBgmNo
/* 002A2830 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002A2834
/* 002A2834 */ .space 0x04

glabel EdEffectGroup
/* 002A2838 */ .space 0x08

glabel EffectTable__3
/* 002A2840 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002A2844
/* 002A2844 */ .space 0x0C

glabel EditMapInfo
/* 002A2850 */ .space 0x04

glabel EdEventData
/* 002A2854 */ .space 0x04

glabel EdSystemEventData
/* 002A2858 */ .space 0x04

glabel EdDrawOffFlag
/* 002A285C */ .space 0x04

glabel EdDrawOffMap
/* 002A2860 */ .space 0x04

glabel EdDrawOffMapShadow
/* 002A2864 */ .space 0x04

glabel EdThunderEffectFlag
/* 002A2868 */ .space 0x04

glabel EdPauseFlag
/* 002A286C */ .space 0x04

glabel clear_screen
/* 002A2870 */ .space 0x04

glabel key_lock
/* 002A2874 */ .space 0x04

glabel goto_dungeon
/* 002A2878 */ .space 0x04

glabel exit_loop
/* 002A287C */ .space 0x04

glabel loop_counter
/* 002A2880 */ .space 0x04

glabel key_counter
/* 002A2884 */ .space 0x04

glabel goto_menu
/* 002A2888 */ .space 0x04

glabel goto_return_menu
/* 002A288C */ .space 0x04

glabel sound_off_cnt
/* 002A2890 */ .space 0x04

glabel debug_menu_mode
/* 002A2894 */ .space 0x04

glabel goto_cmp_event
/* 002A2898 */ .space 0x04

glabel goto_cmp_event_level
/* 002A289C */ .space 0x04

glabel change_time_event
/* 002A28A0 */ .space 0x04

glabel draw_npc_cursor
/* 002A28A4 */ .space 0x04

glabel draw_clock
/* 002A28A8 */ .space 0x04

glabel edit_mode_draw
/* 002A28AC */ .space 0x04

glabel edit_mode_grd_draw
/* 002A28B0 */ .space 0x04

glabel depth_of_field
/* 002A28B4 */ .space 0x04

glabel edit_mode_lighting
/* 002A28B8 */ .space 0x04

glabel draw_sky
/* 002A28BC */ .space 0x04

glabel start_event_no
/* 002A28C0 */ .space 0x04

glabel start_system_event
/* 002A28C4 */ .space 0x04

glabel move_count
/* 002A28C8 */ .space 0x04

glabel interior_test
/* 002A28CC */ .space 0x04

glabel interior_name
/* 002A28D0 */ .space 0x04

glabel oldGameMode
/* 002A28D4 */ .space 0x04

glabel pEditGround
/* 002A28D8 */ .space 0x04

glabel EditArea
/* 002A28DC */ .space 0x04

glabel ObjParts
/* 002A28E0 */ .space 0x04

glabel RiverParts
/* 002A28E4 */ .space 0x04

glabel RoadParts
/* 002A28E8 */ .space 0x04

glabel MotionParts
/* 002A28EC */ .space 0x04

glabel NowCamera
/* 002A28F0 */ .space 0x04

glabel NowTime
/* 002A28F4 */ .space 0x04

glabel SkyBackFrame
/* 002A28F8 */ .space 0x04

glabel CharaCursor0
/* 002A28FC */ .space 0x04

glabel CharaCursor1
/* 002A2900 */ .space 0x04

glabel CharaCursor2
/* 002A2904 */ .space 0x04

glabel TreasureCursor
/* 002A2908 */ .space 0x04

glabel TreasureCursorOpen
/* 002A290C */ .space 0x04

glabel end_counter
/* 002A2910 */ .space 0x04

glabel bgm_vol
/* 002A2914 */ .space 0x04

glabel bgm_play_flag
/* 002A2918 */ .space 0x04

glabel bgm_play_start
/* 002A291C */ .space 0x04

glabel door_open_cnt
/* 002A2920 */ .space 0x04

glabel door_open
/* 002A2924 */ .space 0x04

glabel fix_pos_enble
/* 002A2928 */ .space 0x04

glabel talk_villager
/* 002A292C */ .space 0x04

glabel chg_time_cnt
/* 002A2930 */ .space 0x04

glabel NowSelectAngle
/* 002A2934 */ .space 0x04

glabel OldSelectAngle
/* 002A2938 */ .space 0x04

glabel NowCursorRotY
/* 002A293C */ .space 0x04

glabel NowFocusParts
/* 002A2940 */ .space 0x04

glabel OldFocusParts
/* 002A2944 */ .space 0x04

glabel DrawPartsNameCount
/* 002A2948 */ .space 0x04

glabel init$654
/* 002A294C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A294D
/* 002A294D */ .space 0x03

glabel debug_flag_set$664
/* 002A2950 */ .space 0x04

glabel init$665
/* 002A2954 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2955
/* 002A2955 */ .space 0x03

glabel end_count$767
/* 002A2958 */ .space 0x04

glabel init$768
/* 002A295C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A295D
/* 002A295D */ .space 0x03

glabel top$798
/* 002A2960 */ .space 0x04

glabel init$799
/* 002A2964 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2965
/* 002A2965 */ .space 0x03

glabel select$801
/* 002A2968 */ .space 0x04

glabel init$802
/* 002A296C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A296D
/* 002A296D */ .space 0x03

glabel cur$804
/* 002A2970 */ .space 0x04

glabel init$805
/* 002A2974 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2975
/* 002A2975 */ .space 0x03

glabel debug_flag$1047
/* 002A2978 */ .space 0x04

glabel init$1048
/* 002A297C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A297D
/* 002A297D */ .space 0x03

glabel event_next$1100
/* 002A2980 */ .space 0x04

glabel init$1101
/* 002A2984 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2985
/* 002A2985 */ .space 0x03

glabel old_mode$1129
/* 002A2988 */ .space 0x04

glabel end_code$1144
/* 002A298C */ .space 0x04

glabel init$1145
/* 002A2990 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2991
/* 002A2991 */ .space 0x03

glabel offset$1876
/* 002A2994 */ .space 0x04

glabel init$1877
/* 002A2998 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2999
/* 002A2999 */ .space 0x03

glabel a$1906
/* 002A299C */ .space 0x04

glabel init$1907
/* 002A29A0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29A1
/* 002A29A1 */ .space 0x03

glabel draw_day_cnt
/* 002A29A4 */ .space 0x04

glabel draw_day_flag
/* 002A29A8 */ .space 0x04

glabel time_flag$2188
/* 002A29AC */ .space 0x04

glabel init$2189
/* 002A29B0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29B1
/* 002A29B1 */ .space 0x03

glabel parts$2227
/* 002A29B4 */ .space 0x04

glabel init$2228
/* 002A29B8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29B9
/* 002A29B9 */ .space 0x03

glabel now_obj$2241
/* 002A29BC */ .space 0x04

glabel init$2242
/* 002A29C0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29C1
/* 002A29C1 */ .space 0x03

glabel camera_dist_mode$2599
/* 002A29C4 */ .space 0x04

glabel init$2600
/* 002A29C8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29C9
/* 002A29C9 */ .space 0x03

glabel parts_no$2646
/* 002A29CC */ .space 0x04

glabel init$2647
/* 002A29D0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29D1
/* 002A29D1 */ .space 0x03

glabel scn_data
/* 002A29D4 */ .space 0x04

glabel parts_read_buffer
/* 002A29D8 */ .space 0x04

glabel roty$585
/* 002A29DC */ .space 0x04

glabel init$586
/* 002A29E0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29E1
/* 002A29E1 */ .space 0x03

glabel sys_eff_sc$590
/* 002A29E4 */ .space 0x04

glabel init$591
/* 002A29E8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29E9
/* 002A29E9 */ .space 0x03

glabel sys_eff_cnt$593
/* 002A29EC */ .space 0x04

glabel init$594
/* 002A29F0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29F1
/* 002A29F1 */ .space 0x03

glabel init$632
/* 002A29F4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A29F5
/* 002A29F5 */ .space 0x03

glabel fade_in_out
/* 002A29F8 */ .space 0x04

glabel fade_end
/* 002A29FC */ .space 0x04

glabel fade_step
/* 002A2A00 */ .space 0x04

glabel simple_event
/* 002A2A04 */ .space 0x04

glabel event_enable
/* 002A2A08 */ .space 0x04

glabel run_system_event
/* 002A2A0C */ .space 0x04

glabel not_wait_load
/* 002A2A10 */ .space 0x04

glabel motion_stop_flag
/* 002A2A14 */ .space 0x04

glabel menu_mode__2
/* 002A2A18 */ .space 0x04

glabel menu_mode_status
/* 002A2A1C */ .space 0x04

glabel p_use_item
/* 002A2A20 */ .space 0x04

glabel p_jump_map_no
/* 002A2A24 */ .space 0x04

glabel event_stop
/* 002A2A28 */ .space 0x04

glabel event_pause
/* 002A2A2C */ .space 0x04

glabel skip_enable
/* 002A2A30 */ .space 0x04

glabel set_wl_matrix
/* 002A2A34 */ .space 0x04

glabel follow_chara
/* 002A2A38 */ .space 0x04

glabel sync_camera_ref_chara
/* 002A2A3C */ .space 0x04

glabel sync_camera_ref_obj
/* 002A2A40 */ .space 0x04

glabel sync_camera_pos_obj
/* 002A2A44 */ .space 0x04

glabel BaseBuffer
/* 002A2A48 */ .space 0x04

glabel actv_file
/* 002A2A4C */ .space 0x04

glabel actv_buffer
/* 002A2A50 */ .space 0x04

glabel mode$2445
/* 002A2A54 */ .space 0x04

glabel init$2446
/* 002A2A58 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2A59
/* 002A2A59 */ .space 0x03

glabel select_chara$2452
/* 002A2A5C */ .space 0x04

glabel init$2453
/* 002A2A60 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2A61
/* 002A2A61 */ .space 0x03

glabel talk_villager__2
/* 002A2A64 */ .space 0x04

glabel talk_chara_info_id
/* 002A2A68 */ .space 0x04

glabel talk_camera
/* 002A2A6C */ .space 0x04

glabel talk_mode
/* 002A2A70 */ .space 0x04

glabel talk_select
/* 002A2A74 */ .space 0x04

glabel TalkMesMake
/* 002A2A78 */ .space 0x04

glabel TalkMesNo
/* 002A2A7C */ .space 0x04

glabel EdInInfo
/* 002A2A80 */ .space 0x04

glabel GameMode__2
/* 002A2A84 */ .space 0x04

glabel active_camera
/* 002A2A88 */ .space 0x04

glabel camera_change_count
/* 002A2A8C */ .space 0x04

glabel camera_num
/* 002A2A90 */ .space 0x04

glabel door_open_cnt__2
/* 002A2A94 */ .space 0x04

glabel NowCamera__2
/* 002A2A98 */ .space 0x04

glabel Chara__2
/* 002A2A9C */ .space 0x04

glabel NowTime__2
/* 002A2AA0 */ .space 0x04

glabel obj_anime_num
/* 002A2AA4 */ .space 0x04

glabel effect_num
/* 002A2AA8 */ .space 0x04

glabel parts_num
/* 002A2AAC */ .space 0x04

glabel func_point
/* 002A2AB0 */ .space 0x04

glabel func_num__2
/* 002A2AB4 */ .space 0x04

glabel start_event_no__2
/* 002A2AB8 */ .space 0x04

glabel start_system_event__2
/* 002A2ABC */ .space 0x04

glabel goto_menu__2
/* 002A2AC0 */ .space 0x04

glabel goto_return_menu__2
/* 002A2AC4 */ .space 0x04

glabel key_counter__2
/* 002A2AC8 */ .space 0x04

glabel loop_counter__2
/* 002A2ACC */ .space 0x04

glabel event_text$604
/* 002A2AD0 */ .space 0x04

glabel init$605
/* 002A2AD4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2AD5
/* 002A2AD5 */ .space 0x03

glabel old_mode$633
/* 002A2AD8 */ .space 0x04

glabel end_count$644
/* 002A2ADC */ .space 0x04

glabel init$645
/* 002A2AE0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2AE1
/* 002A2AE1 */ .space 0x03

glabel debug_flag$964
/* 002A2AE4 */ .space 0x04

glabel init$965
/* 002A2AE8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2AE9
/* 002A2AE9 */ .space 0x03

glabel debug_menu_mode$967
/* 002A2AEC */ .space 0x04

glabel init$968
/* 002A2AF0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2AF1
/* 002A2AF1 */ .space 0x03

glabel cnt$1223
/* 002A2AF4 */ .space 0x04

glabel init$1224
/* 002A2AF8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2AF9
/* 002A2AF9 */ .space 0x03

glabel setTexAnimCnt
/* 002A2AFC */ .space 0x04

glabel setTexAnimCntf
/* 002A2B00 */ .space 0x04

glabel npc_count
/* 002A2B04 */ .space 0x04

glabel objanime_list__2
/* 002A2B08 */ .space 0x04

glabel effect_list
/* 002A2B0C */ .space 0x04

glabel debug__2
/* 002A2B10 */ .space 0x04

glabel motion_parts_list__2
/* 002A2B14 */ .space 0x04

glabel water_list__2
/* 002A2B18 */ .space 0x04

glabel water_info__2
/* 002A2B1C */ .space 0x04

glabel old_parts$1125
/* 002A2B20 */ .space 0x04

glabel init$1126
/* 002A2B24 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2B25
/* 002A2B25 */ .space 0x03

glabel WaterLevel
/* 002A2B28 */ .space 0x04

glabel GroundLevel
/* 002A2B2C */ .space 0x04

glabel UkiGroundLevel
/* 002A2B30 */ .space 0x04

glabel HookGroundLevel
/* 002A2B34 */ .space 0x04

glabel LineGroundLevel
/* 002A2B38 */ .space 0x04

glabel EsaFrame
/* 002A2B3C */ .space 0x04

glabel esa_type
/* 002A2B40 */ .space 0x04

glabel HookFrame
/* 002A2B44 */ .space 0x04

glabel UkiFrame
/* 002A2B48 */ .space 0x04

glabel fishing_texb
/* 002A2B4C */ .space 0x04

glabel fish_texb
/* 002A2B50 */ .space 0x04

glabel esa_texb
/* 002A2B54 */ .space 0x04

glabel Fish
/* 002A2B58 */ .space 0x04

glabel AngleFish
/* 002A2B5C */ .space 0x04

glabel BattleFish
/* 002A2B60 */ .space 0x04

glabel FishNum
/* 002A2B64 */ .space 0x04

glabel cpoly
/* 002A2B68 */ .space 0x04

glabel cpoly_num
/* 002A2B6C */ .space 0x04

glabel set_hook_pos
/* 002A2B70 */ .space 0x04

glabel set_uki_pos
/* 002A2B74 */ .space 0x04

glabel pull_hook
/* 002A2B78 */ .space 0x04

glabel msg_cnt$1151
/* 002A2B7C */ .space 0x04

glabel init$1152
/* 002A2B80 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2B81
/* 002A2B81 */ .space 0x03

glabel WaterWaveLingWait
/* 002A2B84 */ .space 0x04

glabel healingSpeed
/* 002A2B88 */ .space 0x04

glabel healingSpeed_flg
/* 002A2B8C */ .space 0x04

glabel statusAlarmRate
/* 002A2B90 */ .space 0x04

glabel statusAlarmCounter
/* 002A2B94 */ .space 0x04

glabel statusRGBColor_life
/* 002A2B98 */ .space 0x04

glabel statusRGBColor_weapon
/* 002A2B9C */ .space 0x04

glabel statusRGBColor_30
/* 002A2BA0 */ .space 0x04

glabel statusRGBColor_15
/* 002A2BA4 */ .space 0x04

glabel statusRGBColor_life_2
/* 002A2BA8 */ .space 0x04

glabel statusRGBColor_weapon_2
/* 002A2BAC */ .space 0x04

glabel statusRGBColor_30_2
/* 002A2BB0 */ .space 0x04

glabel statusRGBColor_15_2
/* 002A2BB4 */ .space 0x04

glabel popupYRate$864
/* 002A2BB8 */ .space 0x04

glabel init$865
/* 002A2BBC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2BBD
/* 002A2BBD */ .space 0x03

glabel popupRGBRate$869
/* 002A2BC0 */ .space 0x04

glabel init$870
/* 002A2BC4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2BC5
/* 002A2BC5 */ .space 0x03

glabel poison_counter
/* 002A2BC8 */ .space 0x04

glabel BtCfgFlag
/* 002A2BCC */ .space 0x04

glabel BtSteebMsgNo
/* 002A2BD0 */ .space 0x04

glabel DebugInfoNowCursor
/* 002A2BD4 */ .space 0x04

glabel BtBattleMusic_Flag
/* 002A2BD8 */ .space 0x04

glabel BtBattleMusic_Wait
/* 002A2BDC */ .space 0x04

glabel BtBattleMusic_Vol
/* 002A2BE0 */ .space 0x04

glabel BtMapJumpFloor
/* 002A2BE4 */ .space 0x04

glabel BtLoadMapType
/* 002A2BE8 */ .space 0x04

glabel wait$1659
/* 002A2BEC */ .space 0x04

glabel init$1660
/* 002A2BF0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2BF1
/* 002A2BF1 */ .space 0x03

glabel roomStackCnt
/* 002A2BF4 */ .space 0x04

glabel errFlag2
/* 002A2BF8 */ .space 0x04

glabel argLevel__2
/* 002A2BFC */ .space 0x04

glabel teigiFileSize__2
/* 002A2C00 */ .space 0x04

glabel nowPartsCnt__2
/* 002A2C04 */ .space 0x04

glabel FrameObjAnimCnt
/* 002A2C08 */ .space 0x04

glabel filePathNum
/* 002A2C0C */ .space 0x04

glabel filePathColNum
/* 002A2C10 */ .space 0x04

glabel VERSION_VOL
/* 002A2C14 */ .space 0x04

glabel BtGetTreasurebox_Sled
/* 002A2C18 */ .space 0x04

glabel BtGetAtraBoll_Sled
/* 002A2C1C */ .space 0x04

glabel TreasureboxBig_itemNo
/* 002A2C20 */ .space 0x04

glabel TreasureboxBig_itemType
/* 002A2C24 */ .space 0x04

glabel TreasureboxBig_itemScale
/* 002A2C28 */ .space 0x04

glabel BtGetTreasureboxSmall_itemNo
/* 002A2C2C */ .space 0x04

glabel BtGetTreasureboxSmall_itemVolume
/* 002A2C30 */ .space 0x04

glabel BtAtraGetID
/* 002A2C34 */ .space 0x04

glabel BtAtraGetNo
/* 002A2C38 */ .space 0x04

glabel BtMiniChrSelecter_Sled
/* 002A2C3C */ .space 0x04

glabel BtMiniChrSel_Type
/* 002A2C40 */ .space 0x04

glabel BtMiniChrSelectNo
/* 002A2C44 */ .space 0x04

glabel frameWait$907
/* 002A2C48 */ .space 0x04

glabel BtMiniItemSelect_Sled
/* 002A2C4C */ .space 0x04

glabel GateKey_itemNo
/* 002A2C50 */ .space 0x04

glabel GateKey_Sled
/* 002A2C54 */ .space 0x04

glabel gateItemFlag
/* 002A2C58 */ .space 0x04

glabel escape_chr
/* 002A2C5C */ .space 0x04

glabel escape_sled
/* 002A2C60 */ .space 0x04

glabel hitCnt
/* 002A2C64 */ .space 0x04

glabel cnt$1192
/* 002A2C68 */ .space 0x04

glabel init$1193
/* 002A2C6C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2C6D
/* 002A2C6D */ .space 0x03

glabel bak_ColNo
/* 002A2C70 */ .space 0x04

glabel ShopUserStatusPt
/* 002A2C74 */ .space 0x04

glabel ShopBoard
/* 002A2C78 */ .space 0x04

glabel ShopStockPt
/* 002A2C7C */ .space 0x04

glabel ShopBoardInfo
/* 002A2C80 */ .space 0x04

glabel ItemBoardInfo
/* 002A2C84 */ .space 0x04

glabel WeaponBoardInfo
/* 002A2C88 */ .space 0x04

glabel AttachBoardInfo
/* 002A2C8C */ .space 0x04

glabel ShopListPt
/* 002A2C90 */ .space 0x04

glabel ShopWorkBuf
/* 002A2C94 */ .space 0x04

glabel ShopHelpWinPos
/* 002A2C98 */ .space 0x08

glabel ShopHelpWinH
/* 002A2CA0 */ .space 0x04

glabel ShopHelpWinW
/* 002A2CA4 */ .space 0x04

glabel ShopHaveItemPt
/* 002A2CA8 */ .space 0x04

glabel ShopHaveWepPt
/* 002A2CAC */ .space 0x04

glabel ShopHaveAttachPt
/* 002A2CB0 */ .space 0x04

glabel ChargeOrShopFlag
/* 002A2CB4 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2CB6
/* 002A2CB6 */ .space 0x02

glabel FishMenuTex
/* 002A2CB8 */ .space 0x04

glabel MenuMapJumpMode
/* 002A2CBC */ .space 0x04

glabel BtlMenuSaveDataPt
/* 002A2CC0 */ .space 0x04

glabel BtlMenuStatusPt
/* 002A2CC4 */ .space 0x04

glabel BtlMenuMode
/* 002A2CC8 */ .space 0x04

glabel BtlMenuBGMvol
/* 002A2CCC */ .space 0x04

glabel BtlMenuReadBlock
/* 002A2CD0 */ .space 0x04

glabel BtlMenuReadBuf
/* 002A2CD4 */ .space 0x04

glabel BtlMenuReadEndFlag
/* 002A2CD8 */ .space 0x04

glabel ItemMenuWeaponIconReadBlock
/* 002A2CDC */ .space 0x04

glabel ItemMenuAlreadyReadWepIconTexFlag
/* 002A2CE0 */ .space 0x04

glabel MenuShadowReadBlock
/* 002A2CE4 */ .space 0x04

glabel BtlMenuExReadBlock
/* 002A2CE8 */ .space 0x04

glabel BtlMenuExReadFlag
/* 002A2CEC */ .space 0x04

glabel MenuExtendReadBlock
/* 002A2CF0 */ .space 0x04

glabel MenuExTextureReadFlag
/* 002A2CF4 */ .space 0x04

glabel ItemMenuCharaReadBuf
/* 002A2CF8 */ .space 0x04

glabel BtlMDSBuildCnt
/* 002A2CFC */ .space 0x04

glabel BtlMenuManualReadBlock
/* 002A2D00 */ .space 0x04

glabel DngWepHavePt
/* 002A2D04 */ .space 0x04

glabel WepMenuEffectReadBuf
/* 002A2D08 */ .space 0x04

glabel CharaStatus
/* 002A2D0C */ .space 0x04

glabel MenuCharaFace
/* 002A2D10 */ .space 0x04

glabel NonCharaFace
/* 002A2D14 */ .space 0x04

glabel BtStatus
/* 002A2D18 */ .space 0x04

glabel WepStatus
/* 002A2D1C */ .space 0x04

glabel BtlAlpha
/* 002A2D20 */ .space 0x04

glabel BtlHira
/* 002A2D24 */ .space 0x04

glabel BtlKata
/* 002A2D28 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002A2D2C
/* 002A2D2C */ .space 0x04

glabel HelpWinHead
/* 002A2D30 */ .space 0x08

glabel BtlWakuMake2
/* 002A2D38 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2D39
/* 002A2D39 */ .space 0x03

glabel BtlHelpWinAlpha
/* 002A2D3C */ .space 0x04

glabel BtlHelpWinW
/* 002A2D40 */ .space 0x04

glabel BtlHelpWinH
/* 002A2D44 */ .space 0x04

glabel MenuSelect
/* 002A2D48 */ .space 0x08

glabel MenuItemPackPt
/* 002A2D50 */ .space 0x04

glabel EscapeDngFlg
/* 002A2D54 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2D56
/* 002A2D56 */ .space 0x02

glabel RoomOutFlag
/* 002A2D58 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2D5A
/* 002A2D5A */ .space 0x02

glabel MenuCharaMove
/* 002A2D5C */ .space 0x04

glabel PosAngle
/* 002A2D60 */ .space 0x04

glabel BtlHaveItemPt
/* 002A2D64 */ .space 0x04

glabel WepFrameRate
/* 002A2D68 */ .space 0x04

glabel WeaponPos
/* 002A2D6C */ .space 0x04

glabel WepPolyPos
/* 002A2D70 */ .space 0x04

glabel BtlEffectCt
/* 002A2D74 */ .space 0x04

glabel MenuWarningMsgFlag
/* 002A2D78 */ .space 0x04

glabel BtlMenuCharaChangeBuf
/* 002A2D7C */ .space 0x04

glabel warningcnt$1676
/* 002A2D80 */ .space 0x04

glabel init$1677
/* 002A2D84 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2D85
/* 002A2D85 */ .space 0x03

glabel warmcnt$2370
/* 002A2D88 */ .space 0x04

glabel init$2371
/* 002A2D8C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2D8D
/* 002A2D8D */ .space 0x03

glabel levelbrinkcnt$2379
/* 002A2D90 */ .space 0x04

glabel init$2380
/* 002A2D94 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2D95
/* 002A2D95 */ .space 0x03

glabel WeaponMenuSelectKeyLockFlag
/* 002A2D98 */ .space 0x04

glabel ct$4025
/* 002A2D9C */ .space 0x04

glabel init$4026
/* 002A2DA0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2DA1
/* 002A2DA1 */ .space 0x03

glabel ncnt$4292
/* 002A2DA4 */ .space 0x04

glabel init$4293
/* 002A2DA8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2DA9
/* 002A2DA9 */ .space 0x03

glabel ct$5739
/* 002A2DAC */ .space 0x04

glabel init$5740
/* 002A2DB0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2DB1
/* 002A2DB1 */ .space 0x03

glabel statusCnt$5776
/* 002A2DB4 */ .space 0x04

glabel init$5777
/* 002A2DB8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2DB9
/* 002A2DB9 */ .space 0x03

glabel NextWorldPos
/* 002A2DBC */ .space 0x04

glabel MapMoveCursor
/* 002A2DC0 */ .space 0x04

glabel MenuMoveTex
/* 002A2DC4 */ .space 0x04

glabel MenuItemUseVolume
/* 002A2DC8 */ .space 0x04

glabel WeaponRead_Buf
/* 002A2DCC */ .space 0x04

glabel MenuCharaEffectReadFlag
/* 002A2DD0 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2DD2
/* 002A2DD2 */ .space 0x02

glabel MenuCharaOldEffect
/* 002A2DD4 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2DD6
/* 002A2DD6 */ .space 0x02

glabel WepEffectMenuPt
/* 002A2DD8 */ .space 0x04

glabel WepEffectMenuReadBuf
/* 002A2DDC */ .space 0x04

glabel MenuWeaponModelBuildBuffer
/* 002A2DE0 */ .space 0x04

glabel CharaFileBGReadNo
/* 002A2DE4 */ .space 0x04

glabel charachangeid
/* 002A2DE8 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2DEA
/* 002A2DEA */ .space 0x02

glabel CharaChangeBaseBuf
/* 002A2DEC */ .space 0x04

glabel menucharReadbuf
/* 002A2DF0 */ .space 0x04

glabel menud0wepReadBuf
/* 002A2DF4 */ .space 0x04

glabel menud1wepReadBuf
/* 002A2DF8 */ .space 0x04

glabel menud2wepReadBuf
/* 002A2DFC */ .space 0x04

glabel MenuWepIconCharaChangePtr
/* 002A2E00 */ .space 0x04

glabel MenuVoiceLoadPtr
/* 002A2E04 */ .space 0x04

glabel CharaNameMes
/* 002A2E08 */ .space 0x04

glabel DngMenuMes
/* 002A2E0C */ .space 0x04

glabel CharaNameDrawFlag
/* 002A2E10 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E12
/* 002A2E12 */ .space 0x02

glabel CharaNameDrawCase
/* 002A2E14 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E16
/* 002A2E16 */ .space 0x02

glabel DngEscapeTex
/* 002A2E18 */ .space 0x04

glabel DngEscapeBlock
/* 002A2E1C */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E1E
/* 002A2E1E */ .space 0x02

glabel DngEscapeEndFlag
/* 002A2E20 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E22
/* 002A2E22 */ .space 0x02

glabel Analyze
/* 002A2E24 */ .space 0x04

glabel AnaBar
/* 002A2E28 */ .space 0x04

glabel EdMenuTextureReadEndFlag
/* 002A2E2C */ .space 0x04

glabel EdMenuTextureBlock
/* 002A2E30 */ .space 0x04

glabel EdMenuWorkBuf
/* 002A2E34 */ .space 0x04

glabel EdMenuExTextureBlock
/* 002A2E38 */ .space 0x04

glabel EdMenuExTextureBlock1
/* 002A2E3C */ .space 0x04

glabel EdMenuExTextureBlock2
/* 002A2E40 */ .space 0x04

glabel EditSwitch
/* 002A2E44 */ .space 0x04

glabel EdMenuRGB
/* 002A2E48 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E4A
/* 002A2E4A */ .space 0x02

glabel EdEffectCt
/* 002A2E4C */ .space 0x04

glabel EdMenuHelpWinAlpha
/* 002A2E50 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E52
/* 002A2E52 */ .space 0x02

glabel AnalyzeSelect
/* 002A2E54 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E56
/* 002A2E56 */ .space 0x02

glabel EdMenuMesNo2
/* 002A2E58 */ .space 0x04

glabel EdMenuMesMake2
/* 002A2E5C */ .space 0x04

glabel ButtonAdd
/* 002A2E60 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E62
/* 002A2E62 */ .space 0x02

glabel AnalyzeBackBlockCnt
/* 002A2E64 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E66
/* 002A2E66 */ .space 0x02

glabel EdMenuEffectFlag
/* 002A2E68 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E6A
/* 002A2E6A */ .space 0x02

glabel EdMenuEffectCt
/* 002A2E6C */ .space 0x04

glabel WindowPos
/* 002A2E70 */ .space 0x08

glabel EditMenuWinW
/* 002A2E78 */ .space 0x04

glabel EditMenuWinH
/* 002A2E7C */ .space 0x04

glabel MakeWin2Flag
/* 002A2E80 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2E82
/* 002A2E82 */ .space 0x02

glabel old_format$442
/* 002A2E84 */ .space 0x04

glabel iconNo$676
/* 002A2E88 */ .space 0x04

glabel init$677
/* 002A2E8C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2E8D
/* 002A2E8D */ .space 0x03

glabel StayTex
/* 002A2E90 */ .space 0x04

glabel AttachIcon
/* 002A2E94 */ .space 0x04

glabel ItemIcon
/* 002A2E98 */ .space 0x04

glabel ItemIcon2
/* 002A2E9C */ .space 0x04

glabel WepIcon
/* 002A2EA0 */ .space 0x04

glabel Sozai
/* 002A2EA4 */ .space 0x04

glabel HoleGray
/* 002A2EA8 */ .space 0x04

glabel HoleGold
/* 002A2EAC */ .space 0x04

glabel ObTip
/* 002A2EB0 */ .space 0x04

glabel ObPerson
/* 002A2EB4 */ .space 0x04

glabel CompleteTex
/* 002A2EB8 */ .space 0x04

glabel VillageBar
/* 002A2EBC */ .space 0x04

glabel VillageName
/* 002A2EC0 */ .space 0x04

glabel SaveBoard
/* 002A2EC4 */ .space 0x04

glabel MenuOption
/* 002A2EC8 */ .space 0x04

glabel CommonMenuAtoraInfo
/* 002A2ECC */ .space 0x04

glabel GetAtraMsgReadBuf
/* 002A2ED0 */ .space 0x04

glabel NowTipHavePt
/* 002A2ED4 */ .space 0x04

glabel AtoraTextureEnterFlag
/* 002A2ED8 */ .space 0x04

glabel AtoraTextureBaseBlock
/* 002A2EDC */ .space 0x04

glabel AtoraTextureReadBlock
/* 002A2EE0 */ .space 0x04

glabel AtoraOffsetBuf
/* 002A2EE4 */ .space 0x04

glabel CursorVibeCnt
/* 002A2EE8 */ .space 0x04

glabel MenuWakuCnt$723
/* 002A2EEC */ .space 0x04

glabel init$724
/* 002A2EF0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2EF1
/* 002A2EF1 */ .space 0x03

glabel tipcurCnt$998
/* 002A2EF4 */ .space 0x04

glabel init$999
/* 002A2EF8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2EF9
/* 002A2EF9 */ .space 0x03

glabel AtoraHeyCnt
/* 002A2EFC */ .space 0x04

glabel CompMsgCt
/* 002A2F00 */ .space 0x04

glabel OpConfigPt
/* 002A2F04 */ .space 0x04

glabel OpMenuWakuCnt$2385
/* 002A2F08 */ .space 0x04

glabel init$2386
/* 002A2F0C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2F0D
/* 002A2F0D */ .space 0x03

glabel OptionCurCnt$2388
/* 002A2F10 */ .space 0x04

glabel init$2389
/* 002A2F14 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2F15
/* 002A2F15 */ .space 0x03

glabel ct$2680
/* 002A2F18 */ .space 0x04

glabel init$2681
/* 002A2F1C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2F1D
/* 002A2F1D */ .space 0x03

glabel EventBoardPos
/* 002A2F20 */ .space 0x08

glabel EventItemMoveY
/* 002A2F28 */ .space 0x04

glabel EventBarY
/* 002A2F2C */ .space 0x04

glabel MiniEventBoard
/* 002A2F30 */ .space 0x04

glabel FishFoodBoard
/* 002A2F34 */ .space 0x04

glabel EventItemPackPt
/* 002A2F38 */ .space 0x04

glabel MiniEventTextureBlock
/* 002A2F3C */ .space 0x04

glabel MiniEventTexReadFlag
/* 002A2F40 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002A2F44
/* 002A2F44 */ .space 0x04

glabel MiniCur
/* 002A2F48 */ .space 0x08

glabel MenuEtcErrCnt
/* 002A2F50 */ .space 0x04

glabel DunLogBoard
/* 002A2F54 */ .space 0x04

glabel DunLogBoard2
/* 002A2F58 */ .space 0x04

glabel DEnterStatusPt
/* 002A2F5C */ .space 0x04

glabel DunWakuCnt$865
/* 002A2F60 */ .space 0x04

glabel init$866
/* 002A2F64 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2F65
/* 002A2F65 */ .space 0x03

glabel QuickCharaPos
/* 002A2F68 */ .space 0x08

glabel CharaChangeTexBlock
/* 002A2F70 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2F72
/* 002A2F72 */ .space 0x02

glabel CharaChangeReadFlag
/* 002A2F74 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2F76
/* 002A2F76 */ .space 0x02

glabel chara_change_buf
/* 002A2F78 */ .space 0x04

glabel QuickCharaTex
/* 002A2F7C */ .space 0x04

glabel ChangeStatusDataPt
/* 002A2F80 */ .space 0x04

glabel ItemPolyView
/* 002A2F84 */ .space 0x04

glabel MDebugItemPolyViewFlag
/* 002A2F88 */ .space 0x04

glabel polyreadflag
/* 002A2F8C */ .space 0x04

glabel PerBoardStatusPt
/* 002A2F90 */ .space 0x04

glabel PerBoardTex
/* 002A2F94 */ .space 0x04

glabel PerBoardPt
/* 002A2F98 */ .space 0x04

glabel ManualMsg
/* 002A2F9C */ .space 0x04

glabel PrevEastKingSndNo
/* 002A2FA0 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2FA2
/* 002A2FA2 */ .space 0x02

glabel PrevEastKingSndVol
/* 002A2FA4 */ .space 0x02

/* Automatically generated and unreferenced pad */
glabel B_002A2FA6
/* 002A2FA6 */ .space 0x02

glabel EastKingSndReadBuf
/* 002A2FA8 */ .space 0x04

glabel CharaName
/* 002A2FAC */ .space 0x04

glabel CharaFace
/* 002A2FB0 */ .space 0x04

glabel NameTemp
/* 002A2FB4 */ .space 0x04

glabel HiraTex
/* 002A2FB8 */ .space 0x04

glabel KataTex
/* 002A2FBC */ .space 0x04

glabel AlphaTex
/* 002A2FC0 */ .space 0x04

glabel up_or_down$942
/* 002A2FC4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2FC5
/* 002A2FC5 */ .space 0x03

glabel init$943
/* 002A2FC8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2FC9
/* 002A2FC9 */ .space 0x03

glabel OpeningReadBuf
/* 002A2FCC */ .space 0x04

glabel wait$915
/* 002A2FD0 */ .space 0x04

glabel init$916
/* 002A2FD4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A2FD5
/* 002A2FD5 */ .space 0x03

glabel Fade
/* 002A2FD8 */ .space 0x04

glabel Cursor
/* 002A2FDC */ .space 0x04

glabel Proc
/* 002A2FE0 */ .space 0x04

glabel PassReadBuffer
/* 002A2FE4 */ .space 0x04

glabel MesBuffer
/* 002A2FE8 */ .space 0x04

glabel OpBgmSqPort
/* 002A2FEC */ .space 0x04

glabel frame_info_cam
/* 002A2FF0 */ .space 0x04

glabel SceneNp__2
/* 002A2FF4 */ .space 0x04

glabel Pause
/* 002A2FF8 */ .space 0x04

glabel CameraMode
/* 002A2FFC */ .space 0x04

glabel SceneRp
/* 002A3000 */ .space 0x04

glabel SceneCnt
/* 002A3004 */ .space 0x04

glabel SceneFlg
/* 002A3008 */ .space 0x04

glabel SceneSw
/* 002A300C */ .space 0x04

glabel PauseFrame
/* 002A3010 */ .space 0x04

glabel End
/* 002A3014 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3015
/* 002A3015 */ .space 0x03

glabel EndCnt
/* 002A3018 */ .space 0x04

glabel BgmOff
/* 002A301C */ .space 0x04

glabel BgmVol
/* 002A3020 */ .space 0x04

glabel BgmNo
/* 002A3024 */ .space 0x04

glabel endflg$707
/* 002A3028 */ .space 0x04

glabel init$708
/* 002A302C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A302D
/* 002A302D */ .space 0x03

glabel flg$743
/* 002A3030 */ .space 0x04

glabel init$744
/* 002A3034 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3035
/* 002A3035 */ .space 0x03

glabel cnt$746
/* 002A3038 */ .space 0x04

glabel init$747
/* 002A303C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A303D
/* 002A303D */ .space 0x03

glabel no$920
/* 002A3040 */ .space 0x04

glabel init$921
/* 002A3044 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3045
/* 002A3045 */ .space 0x03

glabel cnt$937
/* 002A3048 */ .space 0x04

glabel init$938
/* 002A304C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A304D
/* 002A304D */ .space 0x03

glabel WaterR
/* 002A3050 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3051
/* 002A3051 */ .space 0x03

glabel WaterG
/* 002A3054 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3055
/* 002A3055 */ .space 0x03

glabel WaterB
/* 002A3058 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3059
/* 002A3059 */ .space 0x03

glabel WaterFlag
/* 002A305C */ .space 0x04

glabel WaterMeshW
/* 002A3060 */ .space 0x04

glabel WaterMeshH
/* 002A3064 */ .space 0x04

glabel WaterShake
/* 002A3068 */ .space 0x04

glabel WaterCourant
/* 002A306C */ .space 0x04

glabel WaterDecline
/* 002A3070 */ .space 0x04

glabel WaterAmplitude
/* 002A3074 */ .space 0x04

glabel WaterRefraction
/* 002A3078 */ .space 0x04

glabel ColModelCount
/* 002A307C */ .space 0x04

glabel shadowModelCount
/* 002A3080 */ .space 0x04

glabel animeSpeed1
/* 002A3084 */ .space 0x04

glabel animeSpeed2
/* 002A3088 */ .space 0x04

glabel pointLightStack
/* 002A308C */ .space 0x04

glabel argLevel
/* 002A3090 */ .space 0x04

glabel teigiFileSize
/* 002A3094 */ .space 0x04

glabel nowObjCnt
/* 002A3098 */ .space 0x04

glabel nowObjCnt2
/* 002A309C */ .space 0x04

glabel nowPartsCnt
/* 002A30A0 */ .space 0x04

glabel OP_AnimeSeqRot
/* 002A30A4 */ .space 0x04

glabel OP_FireList
/* 002A30A8 */ .space 0x04

glabel OP_GroundCol
/* 002A30AC */ .space 0x04

glabel OP_SkyFrame
/* 002A30B0 */ .space 0x04

glabel OP_CharaFrame__2
/* 002A30B4 */ .space 0x04

glabel CloudFlag
/* 002A30B8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A30B9
/* 002A30B9 */ .space 0x03

glabel Shadow
/* 002A30BC */ .space 0x04

glabel DancerAmb
/* 002A30C0 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002A30C4
/* 002A30C4 */ .space 0x04

glabel Smoke
/* 002A30C8 */ .space 0x08

glabel EffectTable
/* 002A30D0 */ .space 0x04

glabel DanceWait
/* 002A30D4 */ .space 0x04

glabel DanceCnt
/* 002A30D8 */ .space 0x04

glabel DanceStart
/* 002A30DC */ .space 0x04

glabel wait$360
/* 002A30E0 */ .space 0x04

glabel col$393
/* 002A30E4 */ .space 0x04

glabel init$394
/* 002A30E8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A30E9
/* 002A30E9 */ .space 0x03

glabel am$396
/* 002A30EC */ .space 0x04

glabel init$397
/* 002A30F0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A30F1
/* 002A30F1 */ .space 0x03

glabel wait$399
/* 002A30F4 */ .space 0x04

glabel init$400
/* 002A30F8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A30F9
/* 002A30F9 */ .space 0x03

glabel cnt$468
/* 002A30FC */ .space 0x04

glabel init$469
/* 002A3100 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3101
/* 002A3101 */ .space 0x03

glabel sw$471
/* 002A3104 */ .space 0x04

glabel init$472
/* 002A3108 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3109
/* 002A3109 */ .space 0x03

glabel sc$656
/* 002A310C */ .space 0x04

glabel init$657
/* 002A3110 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3111
/* 002A3111 */ .space 0x03

glabel cnt$681
/* 002A3114 */ .space 0x04

glabel init$682
/* 002A3118 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3119
/* 002A3119 */ .space 0x03

glabel d$717
/* 002A311C */ .space 0x04

glabel f$786
/* 002A3120 */ .space 0x04

glabel mus$915
/* 002A3124 */ .space 0x04

glabel init$916__2
/* 002A3128 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3129
/* 002A3129 */ .space 0x03

glabel wait$925
/* 002A312C */ .space 0x04

glabel init$926
/* 002A3130 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3131
/* 002A3131 */ .space 0x03

glabel wait$940
/* 002A3134 */ .space 0x04

glabel init$941
/* 002A3138 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3139
/* 002A3139 */ .space 0x03

glabel wait$955
/* 002A313C */ .space 0x04

glabel init$956
/* 002A3140 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3141
/* 002A3141 */ .space 0x03

glabel wait$970
/* 002A3144 */ .space 0x04

glabel init$971
/* 002A3148 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3149
/* 002A3149 */ .space 0x03

glabel seflg$988
/* 002A314C */ .space 0x04

glabel init$989
/* 002A3150 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3151
/* 002A3151 */ .space 0x03

glabel secnt$991
/* 002A3154 */ .space 0x04

glabel init$992
/* 002A3158 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3159
/* 002A3159 */ .space 0x03

glabel vol$994
/* 002A315C */ .space 0x04

glabel init$995
/* 002A3160 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3161
/* 002A3161 */ .space 0x03

glabel flg$1006
/* 002A3164 */ .space 0x04

glabel init$1007
/* 002A3168 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3169
/* 002A3169 */ .space 0x03

glabel flg$1019
/* 002A316C */ .space 0x04

glabel init$1020
/* 002A3170 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3171
/* 002A3171 */ .space 0x03

glabel setTexScrollCnt$1032
/* 002A3174 */ .space 0x04

glabel init$1033
/* 002A3178 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3179
/* 002A3179 */ .space 0x03

glabel setTexScrollCntf$1035
/* 002A317C */ .space 0x04

glabel init$1036
/* 002A3180 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3181
/* 002A3181 */ .space 0x03

glabel setTexScrollCnt$1062
/* 002A3184 */ .space 0x04

glabel init$1063
/* 002A3188 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3189
/* 002A3189 */ .space 0x03

glabel setTexScrollCntf$1065
/* 002A318C */ .space 0x04

glabel init$1066
/* 002A3190 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3191
/* 002A3191 */ .space 0x03

glabel ToansHouse
/* 002A3194 */ .space 0x04

glabel DoransFuusya
/* 002A3198 */ .space 0x08

glabel VolFade
/* 002A31A0 */ .space 0x04

glabel camera$589
/* 002A31A4 */ .space 0x04

glabel init$590
/* 002A31A8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A31A9
/* 002A31A9 */ .space 0x03

glabel wait$644
/* 002A31AC */ .space 0x04

glabel init$645__2
/* 002A31B0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A31B1
/* 002A31B1 */ .space 0x03

glabel wait$675
/* 002A31B4 */ .space 0x04

glabel init$676
/* 002A31B8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A31B9
/* 002A31B9 */ .space 0x03

glabel cnt$782
/* 002A31BC */ .space 0x04

glabel init$783
/* 002A31C0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A31C1
/* 002A31C1 */ .space 0x07

glabel DoransFuusya__2
/* 002A31C8 */ .space 0x08

glabel EffectTable__2
/* 002A31D0 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002A31D4
/* 002A31D4 */ .space 0x04

glabel Smoke__2
/* 002A31D8 */ .space 0x08

glabel MBeemCnt
/* 002A31E0 */ .space 0x04

glabel FireStep
/* 002A31E4 */ .space 0x04

glabel MajinBgmStart
/* 002A31E8 */ .space 0x04

glabel DanceBgmStart
/* 002A31EC */ .space 0x04

glabel DanceBgmCnt
/* 002A31F0 */ .space 0x04

glabel SndCnt
/* 002A31F4 */ .space 0x04

glabel camera$900
/* 002A31F8 */ .space 0x04

glabel init$901
/* 002A31FC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A31FD
/* 002A31FD */ .space 0x03

glabel step$938
/* 002A3200 */ .space 0x04

glabel init$939
/* 002A3204 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3205
/* 002A3205 */ .space 0x03

glabel d$941
/* 002A3208 */ .space 0x04

glabel init$942
/* 002A320C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A320D
/* 002A320D */ .space 0x03

glabel vol$992
/* 002A3210 */ .space 0x04

glabel init$993
/* 002A3214 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3215
/* 002A3215 */ .space 0x03

glabel cnt$995
/* 002A3218 */ .space 0x04

glabel init$996
/* 002A321C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A321D
/* 002A321D */ .space 0x03

glabel se$1004
/* 002A3220 */ .space 0x04

glabel init$1005
/* 002A3224 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3225
/* 002A3225 */ .space 0x03

glabel wait$1041
/* 002A3228 */ .space 0x04

glabel init$1042
/* 002A322C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A322D
/* 002A322D */ .space 0x03

glabel wait$1062
/* 002A3230 */ .space 0x04

glabel init$1063__2
/* 002A3234 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3235
/* 002A3235 */ .space 0x03

glabel wait$1077
/* 002A3238 */ .space 0x04

glabel init$1078
/* 002A323C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A323D
/* 002A323D */ .space 0x03

glabel wait$1094
/* 002A3240 */ .space 0x04

glabel init$1095
/* 002A3244 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3245
/* 002A3245 */ .space 0x03

glabel flg$1180
/* 002A3248 */ .space 0x04

glabel init$1181
/* 002A324C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A324D
/* 002A324D */ .space 0x03

glabel bright$1183
/* 002A3250 */ .space 0x04

glabel init$1184
/* 002A3254 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3255
/* 002A3255 */ .space 0x03

glabel cnt$1744
/* 002A3258 */ .space 0x04

glabel init$1745
/* 002A325C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A325D
/* 002A325D */ .space 0x03

glabel setTexScrollCnt
/* 002A3260 */ .space 0x04

glabel setTexScrollCntf
/* 002A3264 */ .space 0x04

glabel setTexAnimCnt__2
/* 002A3268 */ .space 0x04

glabel setTexAnimCntf__2
/* 002A326C */ .space 0x04

glabel amb3
/* 002A3270 */ .space 0x04

glabel SkyFrame__2
/* 002A3274 */ .space 0x04

glabel camera$574
/* 002A3278 */ .space 0x04

glabel init$575
/* 002A327C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A327D
/* 002A327D */ .space 0x03

glabel se$622
/* 002A3280 */ .space 0x04

glabel init$623
/* 002A3284 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3285
/* 002A3285 */ .space 0x03

glabel mus$630
/* 002A3288 */ .space 0x04

glabel init$631
/* 002A328C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A328D
/* 002A328D */ .space 0x03

glabel se$640
/* 002A3290 */ .space 0x04

glabel init$641
/* 002A3294 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3295
/* 002A3295 */ .space 0x03

glabel mus$648
/* 002A3298 */ .space 0x04

glabel init$649
/* 002A329C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A329D
/* 002A329D */ .space 0x03

glabel se$656
/* 002A32A0 */ .space 0x04

glabel init$657__2
/* 002A32A4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32A5
/* 002A32A5 */ .space 0x03

glabel mus$664
/* 002A32A8 */ .space 0x04

glabel init$665__2
/* 002A32AC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32AD
/* 002A32AD */ .space 0x03

glabel wait$678
/* 002A32B0 */ .space 0x04

glabel init$679
/* 002A32B4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32B5
/* 002A32B5 */ .space 0x03

glabel fade1$766
/* 002A32B8 */ .space 0x04

glabel init$767
/* 002A32BC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32BD
/* 002A32BD */ .space 0x03

glabel fade2$769
/* 002A32C0 */ .space 0x04

glabel init$770__2
/* 002A32C4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32C5
/* 002A32C5 */ .space 0x03

glabel fade3$772
/* 002A32C8 */ .space 0x04

glabel init$773
/* 002A32CC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32CD
/* 002A32CD */ .space 0x03

glabel rot1$932
/* 002A32D0 */ .space 0x04

glabel init$933
/* 002A32D4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32D5
/* 002A32D5 */ .space 0x03

glabel rot2$935
/* 002A32D8 */ .space 0x04

glabel init$936
/* 002A32DC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32DD
/* 002A32DD */ .space 0x03

glabel angle$975
/* 002A32E0 */ .space 0x04

glabel init$976
/* 002A32E4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32E5
/* 002A32E5 */ .space 0x03

glabel cnt$996
/* 002A32E8 */ .space 0x04

glabel init$997
/* 002A32EC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32ED
/* 002A32ED */ .space 0x03

glabel cnt1$1014
/* 002A32F0 */ .space 0x04

glabel init$1015
/* 002A32F4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32F5
/* 002A32F5 */ .space 0x03

glabel cntA$1017
/* 002A32F8 */ .space 0x04

glabel init$1018
/* 002A32FC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A32FD
/* 002A32FD */ .space 0x03

glabel cnt2$1024
/* 002A3300 */ .space 0x04

glabel init$1025
/* 002A3304 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3305
/* 002A3305 */ .space 0x03

glabel cntB$1027
/* 002A3308 */ .space 0x04

glabel init$1028
/* 002A330C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A330D
/* 002A330D */ .space 0x03

glabel fadeA1$1034
/* 002A3310 */ .space 0x04

glabel init$1035
/* 002A3314 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3315
/* 002A3315 */ .space 0x03

glabel fadeA2$1037
/* 002A3318 */ .space 0x04

glabel init$1038
/* 002A331C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A331D
/* 002A331D */ .space 0x03

glabel fadeB1$1047
/* 002A3320 */ .space 0x04

glabel init$1048__2
/* 002A3324 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3325
/* 002A3325 */ .space 0x03

glabel fadeB2$1050
/* 002A3328 */ .space 0x04

glabel init$1051
/* 002A332C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A332D
/* 002A332D */ .space 0x03

glabel fadeB3$1053
/* 002A3330 */ .space 0x04

glabel init$1054
/* 002A3334 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3335
/* 002A3335 */ .space 0x03

glabel x$1075
/* 002A3338 */ .space 0x04

glabel init$1076
/* 002A333C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A333D
/* 002A333D */ .space 0x03

glabel y$1078
/* 002A3340 */ .space 0x04

glabel init$1079
/* 002A3344 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3345
/* 002A3345 */ .space 0x03

glabel rot$1081
/* 002A3348 */ .space 0x04

glabel init$1082
/* 002A334C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A334D
/* 002A334D */ .space 0x03

glabel x2$1084
/* 002A3350 */ .space 0x04

glabel init$1085
/* 002A3354 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3355
/* 002A3355 */ .space 0x03

glabel y2$1087
/* 002A3358 */ .space 0x04

glabel init$1088
/* 002A335C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A335D
/* 002A335D */ .space 0x03

glabel rot2$1090
/* 002A3360 */ .space 0x04

glabel init$1091
/* 002A3364 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3365
/* 002A3365 */ .space 0x03

glabel x3$1093
/* 002A3368 */ .space 0x04

glabel init$1094
/* 002A336C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A336D
/* 002A336D */ .space 0x03

glabel y3$1096
/* 002A3370 */ .space 0x04

glabel init$1097
/* 002A3374 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3375
/* 002A3375 */ .space 0x03

glabel rot3$1099
/* 002A3378 */ .space 0x04

glabel init$1100
/* 002A337C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A337D
/* 002A337D */ .space 0x03

glabel x$1136
/* 002A3380 */ .space 0x04

glabel init$1137
/* 002A3384 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3385
/* 002A3385 */ .space 0x03

glabel y$1139
/* 002A3388 */ .space 0x04

glabel init$1140
/* 002A338C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A338D
/* 002A338D */ .space 0x03

glabel x2$1142
/* 002A3390 */ .space 0x04

glabel init$1143
/* 002A3394 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3395
/* 002A3395 */ .space 0x03

glabel y2$1145
/* 002A3398 */ .space 0x04

glabel init$1146
/* 002A339C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A339D
/* 002A339D */ .space 0x03

glabel OP_CharaFrame
/* 002A33A0 */ .space 0x04

glabel bEnd
/* 002A33A4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33A5
/* 002A33A5 */ .space 0x03

glabel EndCnt__2
/* 002A33A8 */ .space 0x04

glabel CameraMode__2
/* 002A33AC */ .space 0x04

glabel SceneNp
/* 002A33B0 */ .space 0x04

glabel TitleAngle
/* 002A33B4 */ .space 0x04

glabel StartDisp
/* 002A33B8 */ .space 0x04

glabel TitleFade
/* 002A33BC */ .space 0x04

glabel TitleFadeCnt
/* 002A33C0 */ .space 0x04

glabel StartLightning
/* 002A33C4 */ .space 0x04

glabel atraGetStatusRate
/* 002A33C8 */ .space 0x04

glabel old$498
/* 002A33CC */ .space 0x04

glabel init$499
/* 002A33D0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33D1
/* 002A33D1 */ .space 0x03

glabel iwacnt$512
/* 002A33D4 */ .space 0x04

glabel init$513
/* 002A33D8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33D9
/* 002A33D9 */ .space 0x03

glabel fade$599
/* 002A33DC */ .space 0x04

glabel init$600
/* 002A33E0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33E1
/* 002A33E1 */ .space 0x03

glabel mus$645
/* 002A33E4 */ .space 0x04

glabel init$646
/* 002A33E8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33E9
/* 002A33E9 */ .space 0x03

glabel ambi$653
/* 002A33EC */ .space 0x04

glabel init$654__2
/* 002A33F0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33F1
/* 002A33F1 */ .space 0x03

glabel bat$661
/* 002A33F4 */ .space 0x04

glabel init$662
/* 002A33F8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A33F9
/* 002A33F9 */ .space 0x03

glabel wait$679
/* 002A33FC */ .space 0x04

glabel init$680
/* 002A3400 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3401
/* 002A3401 */ .space 0x03

glabel wait$703
/* 002A3404 */ .space 0x04

glabel init$704
/* 002A3408 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3409
/* 002A3409 */ .space 0x03

glabel lightning$958
/* 002A340C */ .space 0x04

glabel init$959
/* 002A3410 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3411
/* 002A3411 */ .space 0x03

glabel col$961
/* 002A3414 */ .space 0x04

glabel init$962
/* 002A3418 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3419
/* 002A3419 */ .space 0x03

glabel ObjectFrame3
/* 002A341C */ .space 0x04

glabel CProcess
/* 002A3420 */ .space 0x08

glabel CFade
/* 002A3428 */ .space 0x04

glabel Fade1
/* 002A342C */ .space 0x04

glabel Fade2
/* 002A3430 */ .space 0x04

glabel Fade3
/* 002A3434 */ .space 0x04

glabel Fade4
/* 002A3438 */ .space 0x04

glabel Wait
/* 002A343C */ .space 0x04

glabel opcnt
/* 002A3440 */ .space 0x04

glabel keywait
/* 002A3444 */ .space 0x04

glabel brink
/* 002A3448 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3449
/* 002A3449 */ .space 0x03

glabel brinkcnt
/* 002A344C */ .space 0x04

glabel EffCnt
/* 002A3450 */ .space 0x04

glabel br$577
/* 002A3454 */ .space 0x04

glabel init$578
/* 002A3458 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3459
/* 002A3459 */ .space 0x07

glabel GameEnv
/* 002A3460 */ .space 0x08

glabel UserStatus
/* 002A3468 */ .space 0x04

glabel timeOutCount
/* 002A346C */ .space 0x04

glabel BtRubyDoorKey
/* 002A3470 */ .space 0x04

glabel BtDebugFlag
/* 002A3474 */ .space 0x04

glabel autoDemo
/* 002A3478 */ .space 0x04

glabel BtAllClear
/* 002A347C */ .space 0x04

glabel oldMsgNo
/* 002A3480 */ .space 0x04

glabel oldMsgNo2
/* 002A3484 */ .space 0x04

glabel colPolyNum
/* 002A3488 */ .space 0x04

glabel PadInput_OK
/* 002A348C */ .space 0x04

glabel PadInput_NO
/* 002A3490 */ .space 0x04

glabel ruby_effect_id
/* 002A3494 */ .space 0x04

glabel NowCamera__3
/* 002A3498 */ .space 0x04

glabel viewAngleH__2
/* 002A349C */ .space 0x04

glabel viewAngleV__2
/* 002A34A0 */ .space 0x04

glabel viewMode__2
/* 002A34A4 */ .space 0x04

glabel faceEyeCount
/* 002A34A8 */ .space 0x04

glabel cameraAuto
/* 002A34AC */ .space 0x04

glabel cameraAutoOld
/* 002A34B0 */ .space 0x04

glabel BtUraDongeon
/* 002A34B4 */ .space 0x04

glabel NowDngMap
/* 002A34B8 */ .space 0x04

glabel NowDranMapField
/* 002A34BC */ .space 0x04

glabel NowEventMan
/* 002A34C0 */ .space 0x04

glabel main_bgColor
/* 002A34C4 */ .space 0x03

/* Automatically generated and unreferenced pad */
glabel B_002A34C7
/* 002A34C7 */ .space 0x01

glabel sub_bgColor
/* 002A34C8 */ .space 0x03

/* Automatically generated and unreferenced pad */
glabel B_002A34CB
/* 002A34CB */ .space 0x01

glabel lightingMode
/* 002A34CC */ .space 0x04

glabel NowMonstorUnit
/* 002A34D0 */ .space 0x04

glabel CEffectHold
/* 002A34D4 */ .space 0x04

glabel CEffectHyde
/* 002A34D8 */ .space 0x04

glabel CMonUnitHold
/* 002A34DC */ .space 0x04

glabel CMonUnitHyde
/* 002A34E0 */ .space 0x04

glabel CharaMainHandViewFlag
/* 002A34E4 */ .space 0x04

glabel MonstorViewFlag
/* 002A34E8 */ .space 0x04

glabel NowMainEffect
/* 002A34EC */ .space 0x04

glabel NowWeapon
/* 002A34F0 */ .space 0x04

glabel NowWeaponHave
/* 002A34F4 */ .space 0x04

glabel RandomItem
/* 002A34F8 */ .space 0x04

glabel StealModel
/* 002A34FC */ .space 0x04

glabel CharaFrame
/* 002A3500 */ .space 0x04

glabel Water_Splash_actFlag
/* 002A3504 */ .space 0x04

glabel EscapeFlag
/* 002A3508 */ .space 0x04

glabel rogoSwitch2
/* 002A350C */ .space 0x04

glabel oldRogoY3
/* 002A3510 */ .space 0x04

glabel rogoY3
/* 002A3514 */ .space 0x04

glabel NewChangeFxFlag
/* 002A3518 */ .space 0x04

glabel atraShortGetType
/* 002A351C */ .space 0x04

glabel atraGetStatusRate__2
/* 002A3520 */ .space 0x04

glabel atraGetStatus
/* 002A3524 */ .space 0x04

glabel atraGetMsgBord
/* 002A3528 */ .space 0x04

glabel atraGetMsgBordRate
/* 002A352C */ .space 0x04

glabel shortAtraEffectPtr
/* 002A3530 */ .space 0x04

glabel itemNormalScale
/* 002A3534 */ .space 0x04

glabel itemOpenSmallFlag
/* 002A3538 */ .space 0x04

glabel itemOpenItemMds
/* 002A353C */ .space 0x04

glabel itemOpenItemImg
/* 002A3540 */ .space 0x04

glabel itemOpenItemChr
/* 002A3544 */ .space 0x04

glabel itemBoxModel
/* 002A3548 */ .space 0x04

glabel itemWeponScale
/* 002A354C */ .space 0x04

glabel itemOpenBigFlag
/* 002A3550 */ .space 0x04

glabel battleMenuWait
/* 002A3554 */ .space 0x04

glabel miniItemSelNo
/* 002A3558 */ .space 0x04

glabel BtGameModeFlag
/* 002A355C */ .space 0x04

glabel BtAllDrawFlag
/* 002A3560 */ .space 0x04

glabel driveStepHold
/* 002A3564 */ .space 0x04

glabel frameCaputer
/* 002A3568 */ .space 0x04

glabel driveNoInterpolate
/* 002A356C */ .space 0x04

glabel nowUnitNow
/* 002A3570 */ .space 0x04

glabel cursorFrame
/* 002A3574 */ .space 0x04

glabel bombCursorFrame
/* 002A3578 */ .space 0x04

glabel bicCursorFrame
/* 002A357C */ .space 0x04

glabel lockOnTargetDraw
/* 002A3580 */ .space 0x04

glabel lockOnTargetNo
/* 002A3584 */ .space 0x04

glabel lockOnTargetFlag
/* 002A3588 */ .space 0x04

glabel targetCursorShiftNo
/* 002A358C */ .space 0x04

glabel targetCursorShiftRot
/* 002A3590 */ .space 0x04

glabel selectMapNo
/* 002A3594 */ .space 0x04

glabel itemNowSel
/* 002A3598 */ .space 0x04

glabel BtEquipMap
/* 002A359C */ .space 0x04

glabel BtEquipMasuisyou
/* 002A35A0 */ .space 0x04

glabel iventInfo
/* 002A35A4 */ .space 0x04

glabel iventMarker
/* 002A35A8 */ .space 0x04

glabel iventActive
/* 002A35AC */ .space 0x04

glabel infoMap
/* 002A35B0 */ .space 0x04

glabel infoMapOld
/* 002A35B4 */ .space 0x04

glabel stickVector
/* 002A35B8 */ .space 0x04

glabel stickVector2
/* 002A35BC */ .space 0x04

glabel BtBySpeedFlag
/* 002A35C0 */ .space 0x04

glabel exitMenuFlag
/* 002A35C4 */ .space 0x04

glabel BtItemListCashFlag
/* 002A35C8 */ .space 0x04

glabel BtEventItemNo
/* 002A35CC */ .space 0x04

glabel NowHitValue
/* 002A35D0 */ .space 0x04

glabel NowShotData
/* 002A35D4 */ .space 0x04

glabel NowShotEffect
/* 002A35D8 */ .space 0x04

glabel ozumond_default_effect
/* 002A35DC */ .space 0x04

glabel NowColData
/* 002A35E0 */ .space 0x04

glabel NowBombEffect
/* 002A35E4 */ .space 0x04

glabel NowShockWave
/* 002A35E8 */ .space 0x04

glabel gameTask
/* 002A35EC */ .space 0x04

glabel existFlag
/* 002A35F0 */ .space 0x04

glabel tryalExit
/* 002A35F4 */ .space 0x04

glabel DeadKeyWait
/* 002A35F8 */ .space 0x04

glabel DeadKeyStartWait
/* 002A35FC */ .space 0x04

glabel BtEventData
/* 002A3600 */ .space 0x04

glabel old_read_buffer
/* 002A3604 */ .space 0x04

glabel BtEventMode
/* 002A3608 */ .space 0x04

glabel TEX_Floor1
/* 002A360C */ .space 0x04

glabel TEX_WepGage
/* 002A3610 */ .space 0x04

glabel TEX_Stayframe
/* 002A3614 */ .space 0x04

glabel TEX_Shadow
/* 002A3618 */ .space 0x04

glabel GoldTex
/* 002A361C */ .space 0x04

glabel defCameraWait
/* 002A3620 */ .space 0x04

glabel MonstorNameOff
/* 002A3624 */ .space 0x04

glabel rate$1031
/* 002A3628 */ .space 0x04

glabel init$1032
/* 002A362C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A362D
/* 002A362D */ .space 0x03

glabel itemposr$1146
/* 002A3630 */ .space 0x04

glabel init$1147
/* 002A3634 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3635
/* 002A3635 */ .space 0x03

glabel itemposr$1153
/* 002A3638 */ .space 0x04

glabel init$1154
/* 002A363C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A363D
/* 002A363D */ .space 0x03

glabel bic_posr$1167
/* 002A3640 */ .space 0x04

glabel init$1168
/* 002A3644 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3645
/* 002A3645 */ .space 0x03

glabel bic_posr$1183
/* 002A3648 */ .space 0x04

glabel init$1184__2
/* 002A364C */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A364D
/* 002A364D */ .space 0x03

glabel oldCameraHeight
/* 002A3650 */ .space 0x04

glabel oldCameraAngle
/* 002A3654 */ .space 0x04

glabel inputH1
/* 002A3658 */ .space 0x04

glabel cnt$1901
/* 002A365C */ .space 0x04

glabel init$1902
/* 002A3660 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3661
/* 002A3661 */ .space 0x03

glabel snd_cnt$2339
/* 002A3664 */ .space 0x04

glabel init$2340
/* 002A3668 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3669
/* 002A3669 */ .space 0x03

glabel id_cnt$2342
/* 002A366C */ .space 0x04

glabel init$2343
/* 002A3670 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3671
/* 002A3671 */ .space 0x03

glabel y$4444
/* 002A3674 */ .space 0x04

glabel init$4445
/* 002A3678 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3679
/* 002A3679 */ .space 0x03

glabel warning_cnt$4497
/* 002A367C */ .space 0x04

glabel init$4498
/* 002A3680 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3681
/* 002A3681 */ .space 0x03

glabel heal_counter$4569
/* 002A3684 */ .space 0x04

glabel init$4570
/* 002A3688 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3689
/* 002A3689 */ .space 0x03

glabel dmgSnd$5248
/* 002A368C */ .space 0x04

glabel init$5249
/* 002A3690 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3691
/* 002A3691 */ .space 0x03

glabel cnt$5345
/* 002A3694 */ .space 0x04

glabel init$5346
/* 002A3698 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A3699
/* 002A3699 */ .space 0x03

glabel ozumond_snd_cnt
/* 002A369C */ .space 0x04

glabel dmg_check_wait
/* 002A36A0 */ .space 0x04

glabel s_cnt$5881
/* 002A36A4 */ .space 0x04

glabel init$5882
/* 002A36A8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36A9
/* 002A36A9 */ .space 0x03

glabel msg_cnt$5888
/* 002A36AC */ .space 0x04

glabel init$5889
/* 002A36B0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36B1
/* 002A36B1 */ .space 0x03

glabel wait_cnt$5903
/* 002A36B4 */ .space 0x04

glabel wait_cnt$5931
/* 002A36B8 */ .space 0x04

glabel init$5932
/* 002A36BC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36BD
/* 002A36BD */ .space 0x03

glabel camera_far_dist_limmit
/* 002A36C0 */ .space 0x04

glabel cameraDilay$5984
/* 002A36C4 */ .space 0x04

glabel init$5985
/* 002A36C8 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36C9
/* 002A36C9 */ .space 0x03

glabel cnt$6019
/* 002A36CC */ .space 0x04

glabel init$6020
/* 002A36D0 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36D1
/* 002A36D1 */ .space 0x03

glabel targetCursorCnt
/* 002A36D4 */ .space 0x04

glabel rate$6337
/* 002A36D8 */ .space 0x04

glabel init$6338
/* 002A36DC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36DD
/* 002A36DD */ .space 0x03

glabel dmgColor$6719
/* 002A36E0 */ .space 0x04

glabel init$6720
/* 002A36E4 */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36E5
/* 002A36E5 */ .space 0x03

glabel dmgVec$6722
/* 002A36E8 */ .space 0x04

glabel init$6723
/* 002A36EC */ .space 0x01

/* Automatically generated and unreferenced pad */
glabel B_002A36ED
/* 002A36ED */ .space 0x03

glabel dmgFlag$6725
/* 002A36F0 */ .space 0x04

glabel unitAmbientAnime_Speed
/* 002A36F4 */ .space 0x04

glabel unitAmbientAnime_Count
/* 002A36F8 */ .space 0x04

glabel unitAmbientAnime_Timer
/* 002A36FC */ .space 0x04

glabel unitAmbientAnime_flag
/* 002A3700 */ .space 0x04

glabel nowCursor$6783
/* 002A3704 */ .space 0x04

glabel init$6784
/* 002A3708 */ .space 0x01
