.include "macro.inc"

.set noat /* Allow manual use of $at. */
.set noreorder /* Don't insert nops after branches. */

.section .bss
/* Generated by spimdisasm 1.42.3 */

glabel __bss_start
/* 002A3709 */ .space 0x77

glabel _args
/* 002A3780 */ .space 0x180

glabel my_thid
/* 002A3900 */ .space 0x08

glabel my_th_info
/* 002A3908 */ .space 0x30

glabel cb_tp
/* 002A3938 */ .space 0x48

glabel ncmdrdata
/* 002A3980 */ .space 0x60

glabel icmdcd
/* 002A39E0 */ .space 0x28

glabel func_num
/* 002A3A08 */ .space 0x38

glabel icmdrdata
/* 002A3A40 */ .space 0x40

glabel _sf_data
/* 002A3A80 */ .space 0x140

glabel sfrdata
/* 002A3BC0 */ .space 0x40

glabel cdrd
/* 002A3C00 */ .space 0x28

glabel cdrdsf
/* 002A3C28 */ .space 0x58

glabel _rd_intr_data
/* 002A3C80 */ .space 0xC0

glabel _rd_data
/* 002A3D40 */ .space 0x40

glabel _rdc_data
/* 002A3D80 */ .space 0x340

glabel _Read_cur_pos
/* 002A40C0 */ .space 0x10

glabel _gt_data
/* 002A40D0 */ .space 0x30

glabel tocbf
/* 002A4100 */ .space 0x810

glabel _lbn_prm
/* 002A4910 */ .space 0x30

glabel scmdrdata
/* 002A4940 */ .space 0x420

glabel cdrc
/* 002A4D60 */ .space 0x28

glabel cdit
/* 002A4D88 */ .space 0x28

glabel cddr
/* 002A4DB0 */ .space 0x28

glabel cddr1
/* 002A4DD8 */ .space 0x28

glabel cdbk
/* 002A4E00 */ .space 0x28

glabel cddr2
/* 002A4E28 */ .space 0x28

glabel _i_mode
/* 002A4E50 */ .space 0x10

glabel _dr_mode
/* 002A4E60 */ .space 0x10

glabel _mmode
/* 002A4E70 */ .space 0x10

glabel _prio
/* 002A4E80 */ .space 0x10

glabel _acn_data
/* 002A4E90 */ .space 0x90

glabel TrayReq
/* 002A4F20 */ .space 0x10

glabel _rs_data
/* 002A4F30 */ .space 0x18

glabel eh_39
/* 002A4F48 */ .space 0x10

glabel initialized_40
/* 002A4F58 */ .space 0x08

glabel top_elt_41
/* 002A4F60 */ .space 0x08

glabel thenan_3
/* 002A4F68 */ .space 0x18

glabel thenan_3__2
/* 002A4F80 */ .space 0x10

glabel objects
/* 002A4F90 */ .space 0x10

glabel stack_6
/* 002A4FA0 */ .space 0x400

glabel topArg
/* 002A53A0 */ .space 0x08

glabel topSema
/* 002A53A8 */ .space 0x08

glabel userarea
/* 002A53B0 */ .space 0x50

glabel q_3
/* 002A5400 */ .space 0x110

glabel tinfo
/* 002A5510 */ .space 0x18

glabel B_002A5528
/* 002A5528 */ .space 0x18

glabel wbuf
/* 002A5540 */ .space 0x140

glabel rbuf
/* 002A5680 */ .space 0x140

glabel linebuf
/* 002A57C0 */ .space 0x80

glabel _pckt_buffer
/* 002A5840 */ .space 0x80

glabel _send_buffer
/* 002A58C0 */ .space 0x40

glabel _csdata
/* 002A5900 */ .space 0x14

glabel sif0_handleid
/* 002A5914 */ .space 0x04

glabel _data_table
/* 002A5918 */ .space 0x08

glabel B_002A5920
/* 002A5920 */ .space 0x04

glabel B_002A5924
/* 002A5924 */ .space 0x08

glabel B_002A592C
/* 002A592C */ .space 0x14

glabel _sys_buffer
/* 002A5940 */ .space 0x100

glabel soft_reg
/* 002A5A40 */ .space 0x80

glabel _packet_buffer
/* 002A5AC0 */ .space 0x800

glabel _free_buffer
/* 002A62C0 */ .space 0x800

glabel _free_buffer2
/* 002A6AC0 */ .space 0x800

glabel _data_table__2
/* 002A72C0 */ .space 0x40

glabel _send_data
/* 002A7300 */ .space 0xC40

glabel _rcv_data
/* 002A7F40 */ .space 0x40

glabel _intr_data
/* 002A7F80 */ .space 0x90

glabel _iob
/* 002A8010 */ .space 0x100

glabel _cd
/* 002A8110 */ .space 0x28

glabel _fsversion
/* 002A8138 */ .space 0x08

glabel _riu
/* 002A8140 */ .space 0x40

glabel cd
/* 002A8180 */ .space 0x40

glabel rdata
/* 002A81C0 */ .space 0x40

glabel _aih_data
/* 002A8200 */ .space 0x40

glabel _fih_data
/* 002A8240 */ .space 0x40

glabel _lih_data
/* 002A8280 */ .space 0x100

glabel _senddata
/* 002A8380 */ .space 0x08

glabel B_002A8388
/* 002A8388 */ .space 0x1F8

glabel cd__2
/* 002A8580 */ .space 0x28

glabel _lfversion
/* 002A85A8 */ .space 0x18

glabel rdata__2
/* 002A85C0 */ .space 0x80

glabel mcClientID
/* 002A8640 */ .space 0x28

glabel typeAddr
/* 002A8668 */ .space 0x04

glabel freeAddr
/* 002A866C */ .space 0x04

glabel formAddr
/* 002A8670 */ .space 0x10

glabel buffFileInfo
/* 002A8680 */ .space 0x20

glabel B_002A86A0
/* 002A86A0 */ .space 0x20

glabel sifParamOrd
/* 002A86C0 */ .space 0x30

glabel sifParamFname
/* 002A86F0 */ .space 0x14

glabel B_002A8704
/* 002A8704 */ .space 0x43C

glabel sifParamNext
/* 002A8B40 */ .space 0xC0

glabel currentDir
/* 002A8C00 */ .space 0xBF0

glabel _gp
/* 002A97F0 */ .space 0x410

glabel retval
/* 002A9C00 */ .space 0x40

glabel padsif
/* 002A9C40 */ .space 0x50

glabel PadInfo
/* 002A9C90 */ .space 0xF0

glabel dma_iop_data
/* 002A9D80 */ .space 0x80

glabel buffer
/* 002A9E00 */ .space 0x80

glabel transData_6
/* 002A9E80 */ .space 0x10

glabel stack
/* 002A9E90 */ .space 0x130

glabel sbuff
/* 002A9FC0 */ .space 0x40

glabel __global_destructor_chain
/* 002AA000 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_002AA004
/* 002AA004 */ .space 0x0C

glabel SinTable
/* 002AA010 */ .space 0x1000

glabel VisualData
/* 002AB010 */ .space 0x10

glabel MotionData
/* 002AB020 */ .space 0x10

glabel TextureData
/* 002AB030 */ .space 0x10

glabel WaterData
/* 002AB040 */ .space 0x10

glabel VariousData
/* 002AB050 */ .space 0x10

glabel ActiveData0
/* 002AB060 */ .space 0x10

glabel ActiveData1
/* 002AB070 */ .space 0x10

glabel GlobalDataBuffer
/* 002AB080 */ .space 0x19C9910

glabel workbuffer
/* 01C74990 */ .space 0x10

/* Automatically generated and unreferenced pad */
glabel B_01C749A0
/* 01C749A0 */ .space 0x20

glabel pad_dma_buf
/* 01C749C0 */ .space 0x400

glabel pad_dma_buf2
/* 01C74DC0 */ .space 0x400

glabel mgPickZBuff
/* 01C751C0 */ .space 0x100

glabel GiftagAD
/* 01C752C0 */ .space 0x10

glabel mgDBuff
/* 01C752D0 */ .space 0x230

glabel mgBackColor
/* 01C75500 */ .space 0x10

glabel mgWindowRect
/* 01C75510 */ .space 0x10

glabel mgRenderInfo
/* 01C75520 */ .space 0x350

glabel TexManager
/* 01C75870 */ .space 0x4E48

/* Automatically generated and unreferenced pad */
glabel B_01C7A6B8
/* 01C7A6B8 */ .space 0x08

glabel mgZeroVector
/* 01C7A6C0 */ .space 0x10

glabel mgUnitVector
/* 01C7A6D0 */ .space 0x10

glabel mgUnitVector2
/* 01C7A6E0 */ .space 0x10

glabel mgZeroVector2
/* 01C7A6F0 */ .space 0x10

glabel mgUnitMatrix
/* 01C7A700 */ .space 0x40

glabel mgZeroMatrix
/* 01C7A740 */ .space 0x40

glabel vifpacket
/* 01C7A780 */ .space 0x40

glabel gs_simage
/* 01C7A7C0 */ .space 0x70

glabel texData
/* 01C7A830 */ .space 0x640

glabel alloc_mdt
/* 01C7AE70 */ .space 0x90

glabel alloc_dbuff
/* 01C7AF00 */ .space 0x90

glabel alloc_smdt
/* 01C7AF90 */ .space 0x90

glabel alloc_sdbuff
/* 01C7B020 */ .space 0x90

glabel load_img
/* 01C7B0B0 */ .space 0x10

glabel header_buff
/* 01C7B0C0 */ .space 0x40000

glabel bg_read_info
/* 01CBB0C0 */ .space 0x1380

glabel main_select_param
/* 01CBC440 */ .space 0x100

glabel GamePad
/* 01CBC540 */ .space 0x468

/* Automatically generated and unreferenced pad */
glabel B_01CBC9A8
/* 01CBC9A8 */ .space 0x08

glabel RunScript
/* 01CBC9B0 */ .space 0x48

/* Automatically generated and unreferenced pad */
glabel B_01CBC9F8
/* 01CBC9F8 */ .space 0x08

glabel SystemMesBuffer
/* 01CBCA00 */ .space 0x17710

/* Automatically generated and unreferenced pad */
glabel B_01CD4110
/* 01CD4110 */ .space 0x30

glabel save_data
/* 01CD4140 */ .space 0x131C0

glabel config_data
/* 01CE7300 */ .space 0x40

glabel DebugFont
/* 01CE7340 */ .space 0x21C

/* Automatically generated and unreferenced pad */
glabel B_01CE755C
/* 01CE755C */ .space 0x04

glabel mainCDataAlloc2
/* 01CE7560 */ .space 0x10

glabel msinCtx
/* 01CE7570 */ .space 0x14

/* Automatically generated and unreferenced pad */
glabel B_01CE7584
/* 01CE7584 */ .space 0x0C

glabel msinBfGrp
/* 01CE7590 */ .space 0x10

glabel msinBfCtx
/* 01CE75A0 */ .space 0x30

/* Automatically generated and unreferenced pad */
glabel B_01CE75D0
/* 01CE75D0 */ .space 0x30

glabel msinBf
/* 01CE7600 */ .space 0xC00

glabel gBank
/* 01CE8200 */ .space 0x40

glabel midi_state
/* 01CE8240 */ .space 0x400

glabel sq_inf_tbl
/* 01CE8640 */ .space 0x1904

/* Automatically generated and unreferenced pad */
glabel B_01CE9F44
/* 01CE9F44 */ .space 0x0C

glabel se_inf_tbl
/* 01CE9F50 */ .space 0x2EE4

/* Automatically generated and unreferenced pad */
glabel B_01CECE34
/* 01CECE34 */ .space 0x0C

glabel wk_name$396
/* 01CECE40 */ .space 0x14

/* Automatically generated and unreferenced pad */
glabel B_01CECE54
/* 01CECE54 */ .space 0x0C

glabel wk_name2$397
/* 01CECE60 */ .space 0x14

/* Automatically generated and unreferenced pad */
glabel B_01CECE74
/* 01CECE74 */ .space 0x0C

glabel sbuff__2
/* 01CECE80 */ .space 0x40

glabel gCd
/* 01CECEC0 */ .space 0x28

/* Automatically generated and unreferenced pad */
glabel B_01CECEE8
/* 01CECEE8 */ .space 0x08

glabel transData
/* 01CECEF0 */ .space 0x10

glabel def_vrtx
/* 01CECF00 */ .space 0xBB80

glabel Bone_Matrix$385
/* 01CF8A80 */ .space 0x40

glabel Bone_Matrix_inv$386
/* 01CF8AC0 */ .space 0x40

glabel Bone_Matrix_Base$387
/* 01CF8B00 */ .space 0x40

glabel MesWinTexBuff_01
/* 01CF8B40 */ .space 0x100

glabel MesWinTexBuff_02
/* 01CF8C40 */ .space 0x100

glabel MesWinTexBuff_11
/* 01CF8D40 */ .space 0x100

glabel MesWinTexBuff_12
/* 01CF8E40 */ .space 0x100

glabel NameRegistTbl
/* 01CF8F40 */ .space 0xB0

glabel RandTbl
/* 01CF8FF0 */ .space 0x100

glabel RandTbl2
/* 01CF90F0 */ .space 0x100

/* Automatically generated and unreferenced pad */
glabel B_01CF91F0
/* 01CF91F0 */ .space 0x10

glabel now_load
/* 01CF9200 */ .space 0x1F40

glabel nowloadDB
/* 01CFB140 */ .space 0x230

glabel nlPacket
/* 01CFB370 */ .space 0x20

glabel nl_tex
/* 01CFB390 */ .space 0x50

glabel nl_tex2
/* 01CFB3E0 */ .space 0x50

glabel FrameAttr
/* 01CFB430 */ .space 0x60

glabel bgm_cfg_file
/* 01CFB490 */ .space 0x20

glabel snd_cfg_file
/* 01CFB4B0 */ .space 0x20

glabel voice_cfg_file
/* 01CFB4D0 */ .space 0x20

glabel sp_cfg_file
/* 01CFB4F0 */ .space 0x20

glabel camera_pos
/* 01CFB510 */ .space 0x10

glabel camera_dir
/* 01CFB520 */ .space 0x10

glabel se_seq
/* 01CFB530 */ .space 0x100

glabel SystemMessage
/* 01CFB630 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01CFCDE8
/* 01CFCDE8 */ .space 0x18

glabel mes_data
/* 01CFCE00 */ .space 0xBB80

glabel mes_buff
/* 01D08980 */ .space 0x10000

glabel waveAnimeCnt
/* 01D18980 */ .space 0x80

glabel rd$690
/* 01D18A00 */ .space 0x4EC

/* Automatically generated and unreferenced pad */
glabel B_01D18EEC
/* 01D18EEC */ .space 0x04

glabel Fire
/* 01D18EF0 */ .space 0x40

glabel Candle
/* 01D18F30 */ .space 0x30

glabel draw_rect
/* 01D18F60 */ .space 0x10

glabel eb_key
/* 01D18F70 */ .space 0x700

glabel EdMoveCharaInfo
/* 01D19670 */ .space 0xB0

glabel sound_src
/* 01D19720 */ .space 0x220

glabel now_play_se
/* 01D19940 */ .space 0x10

glabel now_play_se_flag
/* 01D19950 */ .space 0x10

glabel dof
/* 01D19960 */ .space 0x1C

/* Automatically generated and unreferenced pad */
glabel B_01D1997C
/* 01D1997C */ .space 0x04

glabel thd_light
/* 01D19980 */ .space 0x40

glabel thd_color
/* 01D199C0 */ .space 0x40

glabel use_item_list
/* 01D19A00 */ .space 0x80

glabel ibox_pos
/* 01D19A80 */ .space 0x10

glabel ibox_rot
/* 01D19A90 */ .space 0x10

glabel frame_image_tex
/* 01D19AA0 */ .space 0x50

glabel CurrentDir__3
/* 01D19AF0 */ .space 0x40

glabel mapjump_name
/* 01D19B30 */ .space 0x80

glabel EdExchangeInfo
/* 01D19BB0 */ .space 0x1C

/* Automatically generated and unreferenced pad */
glabel B_01D19BCC
/* 01D19BCC */ .space 0x04

glabel EditMenuStatus
/* 01D19BD0 */ .space 0x1C

/* Automatically generated and unreferenced pad */
glabel B_01D19BEC
/* 01D19BEC */ .space 0x04

glabel EditPartsInfo
/* 01D19BF0 */ .space 0x1628

/* Automatically generated and unreferenced pad */
glabel B_01D1B218
/* 01D1B218 */ .space 0x08

glabel EditElementInfo
/* 01D1B220 */ .space 0x120

glabel EdInteriorBuffer
/* 01D1B340 */ .space 0x10

glabel EdNPCBuffer
/* 01D1B350 */ .space 0x10

glabel EdVillagerBuffer
/* 01D1B360 */ .space 0x10

glabel EdEventBuffer
/* 01D1B370 */ .space 0x10

glabel EdEventExBuffer
/* 01D1B380 */ .space 0x10

glabel EdMesBuffer
/* 01D1B390 */ .space 0x10

glabel EdScriptBuffer
/* 01D1B3A0 */ .space 0x10

glabel EdExtMessBuffer
/* 01D1B3B0 */ .space 0x10

glabel EdWorkBuffer
/* 01D1B3C0 */ .space 0x10

glabel EdMenuBuffer
/* 01D1B3D0 */ .space 0x10

glabel EditDataDir
/* 01D1B3E0 */ .space 0x100

glabel EditMapName
/* 01D1B4E0 */ .space 0x20

glabel EdInteriorName
/* 01D1B500 */ .space 0x20

glabel EdWind
/* 01D1B520 */ .space 0x30

glabel EditMes1
/* 01D1B550 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D1CD08
/* 01D1CD08 */ .space 0x08

glabel EditMes2
/* 01D1CD10 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D1E4C8
/* 01D1E4C8 */ .space 0x08

glabel EditEventMes1
/* 01D1E4D0 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D1FC88
/* 01D1FC88 */ .space 0x08

glabel EditEventMes2
/* 01D1FC90 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D21448
/* 01D21448 */ .space 0x08

glabel EditNameMes
/* 01D21450 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D22C08
/* 01D22C08 */ .space 0x08

glabel EditSystemMes
/* 01D22C10 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D243C8
/* 01D243C8 */ .space 0x08

glabel EditHelpMes
/* 01D243D0 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D25B88
/* 01D25B88 */ .space 0x08

glabel EdVillager
/* 01D25B90 */ .space 0xCE40

glabel EdVillagerInfo
/* 01D329D0 */ .space 0x5A0

glabel DebugFont__3
/* 01D32F70 */ .space 0x21C

/* Automatically generated and unreferenced pad */
glabel B_01D3318C
/* 01D3318C */ .space 0x04

glabel now_fog
/* 01D33190 */ .space 0x14

/* Automatically generated and unreferenced pad */
glabel B_01D331A4
/* 01D331A4 */ .space 0x0C

glabel EPartsInfoBuff
/* 01D331B0 */ .space 0x10

glabel MainChara
/* 01D331C0 */ .space 0x12A0

glabel RunEffect
/* 01D34460 */ .space 0xD0

glabel LIT_372__2
/* 01D34530 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D3453C
/* 01D3453C */ .space 0x04

glabel MainCamera
/* 01D34540 */ .space 0x2F0

glabel LIT_373__3
/* 01D34830 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D3483C
/* 01D3483C */ .space 0x04

glabel EditCamera
/* 01D34840 */ .space 0x2F0

glabel LIT_374__2
/* 01D34B30 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D34B3C
/* 01D34B3C */ .space 0x04

glabel IntroCamera
/* 01D34B40 */ .space 0x2F0

glabel LIT_375__2
/* 01D34E30 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D34E3C
/* 01D34E3C */ .space 0x04

glabel TalkCamera
/* 01D34E40 */ .space 0x2F0

glabel LIT_376__2
/* 01D35130 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D3513C
/* 01D3513C */ .space 0x04

glabel EventCamera
/* 01D35140 */ .space 0x2F0

glabel LIT_377__2
/* 01D35430 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D3543C
/* 01D3543C */ .space 0x04

glabel ViewCamera
/* 01D35440 */ .space 0x2F0

glabel SkyFrame
/* 01D35730 */ .space 0x10

glabel SunFrame
/* 01D35740 */ .space 0x10

glabel SystemEffect
/* 01D35750 */ .space 0x200

glabel fix_chara_pos
/* 01D35950 */ .space 0x10

glabel fix_chara_rot
/* 01D35960 */ .space 0x10

glabel fix_camera_pos
/* 01D35970 */ .space 0x10

glabel interior_map_name
/* 01D35980 */ .space 0x40

glabel NowPartsCursorPos
/* 01D359C0 */ .space 0x10

glabel ecursorframe__2
/* 01D359D0 */ .space 0x270

glabel NowCursorPos
/* 01D35C40 */ .space 0x10

glabel NextCursorPos
/* 01D35C50 */ .space 0x10

glabel TexAnime
/* 01D35C60 */ .space 0x1F0

glabel TexAnimeData
/* 01D35E50 */ .space 0x1600

glabel CharaTexAnimeData
/* 01D37450 */ .space 0x2C00

glabel DataBuffer__2
/* 01D3A050 */ .space 0x10

glabel CharaBuffer
/* 01D3A060 */ .space 0x10

glabel InteriorBuffer
/* 01D3A070 */ .space 0x10

glabel EtcDataBuffer
/* 01D3A080 */ .space 0x10

glabel name_mes$653
/* 01D3A090 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01D3B848
/* 01D3B848 */ .space 0x08

glabel menu$807
/* 01D3B850 */ .space 0x100

glabel chara$631
/* 01D3B950 */ .space 0x11B0

glabel appear_table
/* 01D3CB00 */ .space 0x28

/* Automatically generated and unreferenced pad */
glabel B_01D3CB28
/* 01D3CB28 */ .space 0x08

glabel select_table
/* 01D3CB30 */ .space 0x28

/* Automatically generated and unreferenced pad */
glabel B_01D3CB58
/* 01D3CB58 */ .space 0x08

glabel appear
/* 01D3CB60 */ .space 0xC0

glabel restore_info
/* 01D3CC20 */ .space 0x5A0

glabel fade_col
/* 01D3D1C0 */ .space 0x10

glabel EdEventInfo
/* 01D3D1D0 */ .space 0x450

glabel ObjHandle
/* 01D3D620 */ .space 0x700

glabel Sprite
/* 01D3DD20 */ .space 0x880

glabel obj_anime
/* 01D3E5A0 */ .space 0x900

glabel CurrentDir__4
/* 01D3EEA0 */ .space 0x40

glabel world_pos
/* 01D3EEE0 */ .space 0x10

glabel world_rot
/* 01D3EEF0 */ .space 0x10

glabel world_local
/* 01D3EF00 */ .space 0x40

glabel local_world
/* 01D3EF40 */ .space 0x40

glabel sync_camera_ref_offset
/* 01D3EF80 */ .space 0x10

glabel work_flag
/* 01D3EF90 */ .space 0x80

glabel asq_table
/* 01D3F010 */ .space 0x2140

glabel ActSeq
/* 01D41150 */ .space 0x820

glabel anime_data
/* 01D41970 */ .space 0x6E00

glabel sprite_table
/* 01D48770 */ .space 0x700

glabel SpriteTable
/* 01D48E70 */ .space 0x94

/* Automatically generated and unreferenced pad */
glabel B_01D48F04
/* 01D48F04 */ .space 0x0C

glabel SpriteTableBack
/* 01D48F10 */ .space 0x94

/* Automatically generated and unreferenced pad */
glabel B_01D48FA4
/* 01D48FA4 */ .space 0x0C

glabel SceneData
/* 01D48FB0 */ .space 0x11B0

glabel LIT_391__4
/* 01D4A160 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D4A16C
/* 01D4A16C */ .space 0x04

glabel DmmyCamera
/* 01D4A170 */ .space 0x2C0

glabel EdEventScript
/* 01D4A430 */ .space 0x48

/* Automatically generated and unreferenced pad */
glabel B_01D4A478
/* 01D4A478 */ .space 0x08

glabel SystemEventScript
/* 01D4A480 */ .space 0x48

/* Automatically generated and unreferenced pad */
glabel B_01D4A4C8
/* 01D4A4C8 */ .space 0x08

glabel chr_file
/* 01D4A4D0 */ .space 0x40

glabel save_l
/* 01D4A510 */ .space 0x80

glabel save_c
/* 01D4A590 */ .space 0x80

glabel save_a
/* 01D4A610 */ .space 0x20

glabel ext_func__2
/* 01D4A630 */ .space 0x1770

glabel TexAnime__2
/* 01D4BDA0 */ .space 0x1F0

glabel TexAnimeData__2
/* 01D4BF90 */ .space 0x1600

glabel Fire__2
/* 01D4D590 */ .space 0x40

glabel fix_chara_pos__2
/* 01D4D5D0 */ .space 0x10

glabel fix_chara_rot__2
/* 01D4D5E0 */ .space 0x10

glabel InteriorParts
/* 01D4D5F0 */ .space 0x1A40

glabel MotionParts__2
/* 01D4F030 */ .space 0x46C0

glabel Water__3
/* 01D536F0 */ .space 0x3B0

glabel LIT_347__2
/* 01D53AA0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D53AAC
/* 01D53AAC */ .space 0x04

glabel MainCamera__2
/* 01D53AB0 */ .space 0x2F0

glabel LIT_348__3
/* 01D53DA0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D53DAC
/* 01D53DAC */ .space 0x04

glabel TalkCamera__2
/* 01D53DB0 */ .space 0x2F0

glabel LIT_349__3
/* 01D540A0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D540AC
/* 01D540AC */ .space 0x04

glabel EventCamera__2
/* 01D540B0 */ .space 0x2F0

glabel LIT_350__3
/* 01D543A0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D543AC
/* 01D543AC */ .space 0x04

glabel ViewCamera__2
/* 01D543B0 */ .space 0x2C0

glabel LIT_351__2
/* 01D54670 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D5467C
/* 01D5467C */ .space 0x04

glabel ExitCamera
/* 01D54680 */ .space 0x2C0

glabel fix_pos$1123
/* 01D54940 */ .space 0x10

glabel CurrentDir__5
/* 01D54950 */ .space 0x80

glabel fishing_rect
/* 01D549D0 */ .space 0x20

glabel fish_rect
/* 01D549F0 */ .space 0x20

glabel UkiFrameTop
/* 01D54A10 */ .space 0x270

glabel Rod
/* 01D54C80 */ .space 0x11B0

glabel point
/* 01D55E30 */ .space 0x180

glabel old_p
/* 01D55FB0 */ .space 0x180

glabel velo
/* 01D56130 */ .space 0x180

glabel hookp
/* 01D562B0 */ .space 0x30

glabel hookop
/* 01D562E0 */ .space 0x30

glabel hookv
/* 01D56310 */ .space 0x30

glabel hook_dist
/* 01D56340 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D5634C
/* 01D5634C */ .space 0x04

glabel ukip
/* 01D56350 */ .space 0x40

glabel ukiop
/* 01D56390 */ .space 0x40

glabel ukiv
/* 01D563D0 */ .space 0x40

glabel uki_dist
/* 01D56410 */ .space 0x18

/* Automatically generated and unreferenced pad */
glabel B_01D56428
/* 01D56428 */ .space 0x08

glabel rod_top
/* 01D56430 */ .space 0x10

glabel fishhook
/* 01D56440 */ .space 0x10

glabel uki
/* 01D56450 */ .space 0x10

glabel DebugStatus
/* 01D56460 */ .space 0x54

/* Automatically generated and unreferenced pad */
glabel B_01D564B4
/* 01D564B4 */ .space 0x04

glabel StatusColor
/* 01D564B8 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D564C4
/* 01D564C4 */ .space 0x0C

glabel CheckWaterInfo
/* 01D564D0 */ .space 0x30

glabel WaterWaveLing
/* 01D56500 */ .space 0xC0

glabel BtCfgCash
/* 01D565C0 */ .space 0x40

glabel gateKeyStack
/* 01D56600 */ .space 0x80

glabel nameblock
/* 01D56680 */ .space 0x40

glabel nameWepBuff_mds
/* 01D566C0 */ .space 0x40

glabel nameWepBuff_img
/* 01D56700 */ .space 0x40

glabel BtEventInfo
/* 01D56740 */ .space 0xC0

glabel BtObjHdl
/* 01D56800 */ .space 0x180

glabel BtLoadMapFileName
/* 01D56980 */ .space 0x20

glabel scanRoomInfoWork
/* 01D569A0 */ .space 0x400

glabel buildMapDat
/* 01D56DA0 */ .space 0x76C0

glabel buildMapWork
/* 01D5E460 */ .space 0x76C0

glabel roomStack
/* 01D65B20 */ .space 0x100

glabel argStrBuff__2
/* 01D65C20 */ .space 0x5A00

glabel argValBuff__2
/* 01D6B620 */ .space 0x16800

glabel pathName
/* 01D81E20 */ .space 0x100

glabel FrameObjAnim
/* 01D81F20 */ .space 0x1B00

glabel filePathList
/* 01D83A20 */ .space 0x1200

glabel frameList
/* 01D84C20 */ .space 0x120

glabel filePathColList
/* 01D84D40 */ .space 0x2400

glabel frameListCol
/* 01D87140 */ .space 0x240

glabel BeeTbl
/* 01D87380 */ .space 0x1900

glabel MonsterTexAnim
/* 01D88C80 */ .space 0x6E00

glabel PUSH_INT_DATA
/* 01D8FA80 */ .space 0x200

glabel GL_INT
/* 01D8FC80 */ .space 0x28

/* Automatically generated and unreferenced pad */
glabel B_01D8FCA8
/* 01D8FCA8 */ .space 0x08

glabel ext_func
/* 01D8FCB0 */ .space 0x400

glabel ShopCashBuffer
/* 01D900B0 */ .space 0x10

glabel ShopCashBuffer2
/* 01D900C0 */ .space 0x10

glabel ShopMenu
/* 01D900D0 */ .space 0x1A8

/* Automatically generated and unreferenced pad */
glabel B_01D90278
/* 01D90278 */ .space 0x08

glabel ShopDataMove
/* 01D90280 */ .space 0x10C

/* Automatically generated and unreferenced pad */
glabel B_01D9038C
/* 01D9038C */ .space 0x04

glabel FishMenu
/* 01D90390 */ .space 0x28

/* Automatically generated and unreferenced pad */
glabel B_01D903B8
/* 01D903B8 */ .space 0x08

glabel FishRecordMenu
/* 01D903C0 */ .space 0x24

/* Automatically generated and unreferenced pad */
glabel B_01D903E4
/* 01D903E4 */ .space 0x0C

glabel MenuMes
/* 01D903F0 */ .space 0x20

glabel MenuExCashBuffer
/* 01D90410 */ .space 0x10

glabel NorMenuIcon
/* 01D90420 */ .space 0x40

glabel SysCur
/* 01D90460 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D9046C
/* 01D9046C */ .space 0x04

glabel MenuChara
/* 01D90470 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D9047C
/* 01D9047C */ .space 0x04

glabel MenuCharaFrame
/* 01D90480 */ .space 0x11B0

glabel DngWeaponFrm
/* 01D91630 */ .space 0xD440

glabel WepMenu
/* 01D9EA70 */ .space 0x17C

/* Automatically generated and unreferenced pad */
glabel B_01D9EBEC
/* 01D9EBEC */ .space 0x04

glabel ItemMenuMode
/* 01D9EBF0 */ .space 0x188

/* Automatically generated and unreferenced pad */
glabel B_01D9ED78
/* 01D9ED78 */ .space 0x08

glabel IconAutoGet
/* 01D9ED80 */ .space 0x30

glabel MenuMove
/* 01D9EDB0 */ .space 0x20

glabel MenuWeaponModelData
/* 01D9EDD0 */ .space 0xA8

/* Automatically generated and unreferenced pad */
glabel B_01D9EE78
/* 01D9EE78 */ .space 0x08

glabel MenuWeaponModelInfo
/* 01D9EE80 */ .space 0x50

glabel MenuCharaOldAmbient
/* 01D9EED0 */ .space 0x10

glabel MenureadFile
/* 01D9EEE0 */ .space 0x40

glabel MenuIconPos
/* 01D9EF20 */ .space 0x30

glabel EdCur
/* 01D9EF50 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D9EF5C
/* 01D9EF5C */ .space 0x04

glabel AnalyzeFill
/* 01D9EF60 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01D9EF6C
/* 01D9EF6C */ .space 0x14

glabel SaveFileInfo
/* 01D9EF80 */ .space 0x18C0

glabel mcdmybuf
/* 01DA0840 */ .space 0x40

glabel sys_config
/* 01DA0880 */ .space 0x40

glabel LIT_567__2
/* 01DA08C0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01DA08CC
/* 01DA08CC */ .space 0x04

glabel MenuCamera
/* 01DA08D0 */ .space 0x2C0

glabel CommonMenuMes1
/* 01DA0B90 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01DA2348
/* 01DA2348 */ .space 0x08

glabel CommonMenuMes2
/* 01DA2350 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01DA3B08
/* 01DA3B08 */ .space 0x08

glabel CommonMenuMes3
/* 01DA3B10 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01DA52C8
/* 01DA52C8 */ .space 0x08

glabel AtoraNameMes
/* 01DA52D0 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01DA6A88
/* 01DA6A88 */ .space 0x08

glabel MenuDispRc
/* 01DA6A90 */ .space 0x10

glabel BtEditPartsInfo
/* 01DA6AA0 */ .space 0x1628

/* Automatically generated and unreferenced pad */
glabel B_01DA80C8
/* 01DA80C8 */ .space 0x08

glabel MenuAtoraSel
/* 01DA80D0 */ .space 0x1AC

/* Automatically generated and unreferenced pad */
glabel B_01DA827C
/* 01DA827C */ .space 0x04

glabel McAccess
/* 01DA8280 */ .space 0x7C0

glabel OptionMenu
/* 01DA8A40 */ .space 0x88

/* Automatically generated and unreferenced pad */
glabel B_01DA8AC8
/* 01DA8AC8 */ .space 0x08

glabel SaveMenu
/* 01DA8AD0 */ .space 0x34

/* Automatically generated and unreferenced pad */
glabel B_01DA8B04
/* 01DA8B04 */ .space 0x0C

glabel SaveMenuMojiTextbl
/* 01DA8B10 */ .space 0x10

glabel MiniMenu
/* 01DA8B20 */ .space 0x54

/* Automatically generated and unreferenced pad */
glabel B_01DA8B74
/* 01DA8B74 */ .space 0x0C

glabel DEnterMenu
/* 01DA8B80 */ .space 0x1AC

/* Automatically generated and unreferenced pad */
glabel B_01DA8D2C
/* 01DA8D2C */ .space 0x04

glabel ChangeMenu
/* 01DA8D30 */ .space 0x60

glabel MenuItemCashBuffer
/* 01DA8D90 */ .space 0x10

glabel MenuDbgMsg
/* 01DA8DA0 */ .space 0x21C

/* Automatically generated and unreferenced pad */
glabel B_01DA8FBC
/* 01DA8FBC */ .space 0x04

glabel ItemAutoGet
/* 01DA8FC0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01DA8FCC
/* 01DA8FCC */ .space 0x04

glabel MenuGrobalDir
/* 01DA8FD0 */ .space 0x40

glabel MenuTrushMark
/* 01DA9010 */ .space 0x64

/* Automatically generated and unreferenced pad */
glabel B_01DA9074
/* 01DA9074 */ .space 0x0C

glabel EastKingMsgCls
/* 01DA9080 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01DAA838
/* 01DAA838 */ .space 0x08

glabel EastKing
/* 01DAA840 */ .space 0x1C

/* Automatically generated and unreferenced pad */
glabel B_01DAA85C
/* 01DAA85C */ .space 0x04

glabel EastKingMsg
/* 01DAA860 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01DAA86C
/* 01DAA86C */ .space 0x04

glabel ManualMenu
/* 01DAA870 */ .space 0x34

/* Automatically generated and unreferenced pad */
glabel B_01DAA8A4
/* 01DAA8A4 */ .space 0x0C

glabel ManualMenuTex
/* 01DAA8B0 */ .space 0x18

/* Automatically generated and unreferenced pad */
glabel B_01DAA8C8
/* 01DAA8C8 */ .space 0x08

glabel MenuEffectCashBuffer
/* 01DAA8D0 */ .space 0x10

glabel MenuWepLevelUp
/* 01DAA8E0 */ .space 0x1330

glabel ItemVolumeStep
/* 01DABC10 */ .space 0x2C

/* Automatically generated and unreferenced pad */
glabel B_01DABC3C
/* 01DABC3C */ .space 0x04

glabel NameSelect
/* 01DABC40 */ .space 0x2C

/* Automatically generated and unreferenced pad */
glabel B_01DABC6C
/* 01DABC6C */ .space 0x04

glabel OpenBook
/* 01DABC70 */ .space 0x0E

/* Automatically generated and unreferenced pad */
glabel B_01DABC7E
/* 01DABC7E */ .space 0x02

glabel Alpha
/* 01DABC80 */ .space 0x14

glabel errno
/* 01DABC94 */ .space 0x04

/* Automatically generated and unreferenced pad */
glabel B_01DABC98
/* 01DABC98 */ .space 0x68
