#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __default_terminate);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __terminate);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __throw_type_match);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __empty);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", new_eh_context);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __get_eh_context);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __get_eh_info);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", eh_context_initialize);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", eh_context_static);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __get_dynamic_handler_chain);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __sjthrow);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __sjpopnthrow);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __eh_rtime_match);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __get_eh_table_version);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __get_eh_table_language);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", old_find_exception_handler);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", find_exception_handler);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", get_reg_addr);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", copy_reg);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", next_stack_level);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __unwinding_cleanup);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", throw_helper);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __throw);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/_eh", __rethrow);
