#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", decode_uleb128);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", decode_sleb128);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", fde_merge);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", end_fde_sort);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", count_fdes);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", add_fdes);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", frame_init);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", find_fde);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", extract_cie_info);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", execute_cfa_insn);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __register_frame_info);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __register_frame);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __register_frame_info_table);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __register_frame_table);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __deregister_frame_info);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __deregister_frame);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", __frame_state_for);
INCLUDE_ASM("asm/nonmatchings/lib/libgcc/frame", fde_split);
