#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", new_iob);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", get_iob);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", _sceFsSemInit);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", _sceFsSemExit);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", _sceFsDbChk);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", _sceFsSigSema);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", _sceFsIntrSigSema);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceFsInit);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", _fs_version);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceFsReset);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceOpen);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceClose);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceLseek);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", fs_read_intr);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceRead);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceWrite);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/filestub", sceIoctl);
