#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", sceResetttyinit);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", VSync);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", VSync2);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", write);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", read);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", open);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", close);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", ioctl);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", lseek);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", sbrk);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", isatty);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", fstat);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", getpid);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", kill);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", stat);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", unlink);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", putnum);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/glue", get_mem_info);
