#include "common.h"

INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifInitRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifExitRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _sceRpcGetPacket);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _sceRpcFreePacket);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _sceRpcGetFPacket);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _sceRpcGetFPacket2);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _request_end);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _request_rdata);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifGetOtherData);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _search_svdata);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _request_bind);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifBindRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", _request_call);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifCallRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifCheckStatRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifSetRpcQueue);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifRegisterRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifRemoveRpc);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifRemoveRpcQueue);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifGetNextRequest);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifExecRequest);
INCLUDE_ASM("asm/nonmatchings/lib/sce/kernl/sifrpc", sceSifRpcLoop);
