.include "macro.inc"

.set noat /* Allow manual use of $at. */
.set noreorder /* Don't insert nops after branches. */

.section .bss
/* Generated by spimdisasm 1.42.3 */

glabel _dun_static_init_end
/* 01DC4414 */ .space 0x6C

glabel BtActStatus
/* 01DC4480 */ .space 0x150

glabel LIT_614__5
/* 01DC45D0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01DC45DC_2FFBDC
/* 01DC45DC */ .space 0x04

glabel MainCamera__4
/* 01DC45E0 */ .space 0x2F0

glabel LIT_615__6
/* 01DC48D0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01DC48DC_2FFEDC
/* 01DC48DC */ .space 0x04

glabel SubCamera
/* 01DC48E0 */ .space 0x2F0

glabel DispFade__3
/* 01DC4BD0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01DC4BDC_3001DC
/* 01DC4BDC */ .space 0x04

glabel MainDungeonMap
/* 01DC4BE0 */ .space 0x10B10

glabel UraDungeonMap
/* 01DD56F0 */ .space 0x10B10

glabel DranMapField
/* 01DE6200 */ .space 0xD4B0

glabel DngEventMan
/* 01DF36B0 */ .space 0x2800

glabel UraEventMan
/* 01DF5EB0 */ .space 0x2800

glabel main_light
/* 01DF86B0 */ .space 0x40

glabel main_lightcolor
/* 01DF86F0 */ .space 0x40

glabel main_ambientlight
/* 01DF8730 */ .space 0x10

glabel sub_light
/* 01DF8740 */ .space 0x40

glabel sub_lightcolor
/* 01DF8780 */ .space 0x40

glabel sub_ambientlight
/* 01DF87C0 */ .space 0x10

glabel MainMonstorUnit
/* 01DF87D0 */ .space 0x60750

glabel EnemyLifeGage
/* 01E58F20 */ .space 0x18

/* Automatically generated and unreferenced pad */
glabel B_01E58F38_394538
/* 01E58F38 */ .space 0x08

glabel CWeaponFx
/* 01E58F40 */ .space 0x540

glabel CWeaponElFx
/* 01E59480 */ .space 0x1F00

glabel MasekiEffect
/* 01E5B380 */ .space 0x326E0

glabel CharaMainEffect
/* 01E8DA60 */ .space 0xA160

glabel CharaMainEffectCrash
/* 01E97BC0 */ .space 0xA160

glabel CharaMain
/* 01EA1D20 */ .space 0x11B0

glabel CharaHand
/* 01EA2ED0 */ .space 0x11B0

glabel MainWeapon
/* 01EA4080 */ .space 0x11B0

glabel DefaultWeapon
/* 01EA5230 */ .space 0x11B0

glabel CrashWeapon
/* 01EA63E0 */ .space 0x11B0

glabel WeaponHave
/* 01EA7590 */ .space 0xF8

/* Automatically generated and unreferenced pad */
glabel B_01EA7688_3E2C88
/* 01EA7688 */ .space 0x08

glabel DngMessMan
/* 01EA7690 */ .space 0x28

/* Automatically generated and unreferenced pad */
glabel B_01EA76B8_3E2CB8
/* 01EA76B8 */ .space 0x08

glabel MainRandomItem
/* 01EA76C0 */ .space 0x620

glabel SubRandomItem
/* 01EA7CE0 */ .space 0x620

glabel StealItem
/* 01EA8300 */ .space 0x160

glabel NPCUnit
/* 01EA8460 */ .space 0x7BC0

glabel Water_Splash
/* 01EB0020 */ .space 0x11B0

glabel Trap_Circle
/* 01EB11D0 */ .space 0x11B0

glabel Trap_Circle_TexAnim
/* 01EB2380 */ .space 0x580

glabel EscapeEffect
/* 01EB2900 */ .space 0x11B0

glabel rogoAlphaA
/* 01EB3AB0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01EB3ABC_3EF0BC
/* 01EB3ABC */ .space 0x04

glabel rogoAlphaW
/* 01EB3AC0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01EB3ACC_3EF0CC
/* 01EB3ACC */ .space 0x04

glabel NewChangeFx
/* 01EB3AD0 */ .space 0x11B0

glabel atraGetPos
/* 01EB4C80 */ .space 0x10

glabel atraGetRot
/* 01EB4C90 */ .space 0x10

glabel shortAtraEffect
/* 01EB4CA0 */ .space 0x11B0

glabel itemOpenSmall
/* 01EB5E50 */ .space 0xA0

glabel itemOpenSmallFx
/* 01EB5EF0 */ .space 0xA0

glabel itemOpenBig
/* 01EB5F90 */ .space 0xA0

glabel itemOpenBigFx
/* 01EB6030 */ .space 0xA0

glabel DbgMsg
/* 01EB60D0 */ .space 0x21C

/* Automatically generated and unreferenced pad */
glabel B_01EB62EC_3F18EC
/* 01EB62EC */ .space 0x04

glabel BombInfo
/* 01EB62F0 */ .space 0x20

glabel CRunFx__2
/* 01EB6310 */ .space 0xD0

glabel kaze
/* 01EB63E0 */ .space 0x30

glabel iventPos
/* 01EB6410 */ .space 0x10

glabel DngMes1
/* 01EB6420 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01EB7BD8_3F31D8
/* 01EB7BD8 */ .space 0x08

glabel DngMes2
/* 01EB7BE0 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01EB9398_3F4998
/* 01EB9398 */ .space 0x08

glabel DngMesStb
/* 01EB93A0 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01EBAB58_3F6158
/* 01EBAB58 */ .space 0x08

glabel BtEventMes0
/* 01EBAB60 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01EBC318_3F7918
/* 01EBC318 */ .space 0x08

glabel BtEventMes1
/* 01EBC320 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01EBDAD8_3F90D8
/* 01EBDAD8 */ .space 0x08

glabel WeaponCrashEffect
/* 01EBDAE0 */ .space 0x660

glabel HitMark
/* 01EBE140 */ .space 0x6600

glabel HitPointMark
/* 01EC4740 */ .space 0x200

glabel MyHitPointMark
/* 01EC4940 */ .space 0x200

glabel HealEffect
/* 01EC4B40 */ .space 0x520

glabel mainItemModel
/* 01EC5060 */ .space 0x2810

glabel activeItem
/* 01EC7870 */ .space 0x3C

/* Automatically generated and unreferenced pad */
glabel B_01EC78AC_402EAC
/* 01EC78AC */ .space 0x04

glabel MonstorPicupInner
/* 01EC78B0 */ .space 0x90

glabel HitValue
/* 01EC7940 */ .space 0xC00

glabel ShotData
/* 01EC8540 */ .space 0x400

glabel ShotEffect
/* 01EC8940 */ .space 0x326F0

glabel OzumondShot
/* 01EFB030 */ .space 0x2C0

glabel OzumondFire
/* 01EFB2F0 */ .space 0xD10

glabel OzumondShotEffect
/* 01EFC000 */ .space 0x140

glabel CColData
/* 01EFC140 */ .space 0x3D90

glabel CBomb__2
/* 01EFFED0 */ .space 0x240

glabel ShockWave
/* 01F00110 */ .space 0x30

glabel veloOld
/* 01F00140 */ .space 0x10

glabel BtTexAnime
/* 01F00150 */ .space 0x1F0

glabel BtTexAnimeData
/* 01F00340 */ .space 0x2100

glabel BtNPCTexAnimeData
/* 01F02440 */ .space 0x2C00

glabel CharaMainTexAnim
/* 01F05040 */ .space 0x1600

glabel MainModelBuffer
/* 01F06640 */ .space 0x10

glabel MapModelBuffer
/* 01F06650 */ .space 0x10

glabel CharaModelBuffer
/* 01F06660 */ .space 0x10

glabel WeaponModelBuffer
/* 01F06670 */ .space 0x10

glabel WEffectModelBuffer
/* 01F06680 */ .space 0x10

glabel MasekiModelBuffer
/* 01F06690 */ .space 0x10

glabel BtMesBuffer
/* 01F066A0 */ .space 0x10

glabel BtSteebMesBuffer
/* 01F066B0 */ .space 0x10

glabel BtStartLogoBuffer
/* 01F066C0 */ .space 0x10

glabel MonstorModelBuffer
/* 01F066D0 */ .space 0x10

glabel MonstorScriptBuffer
/* 01F066E0 */ .space 0x100

glabel BtItemCashArea
/* 01F067E0 */ .space 0x60

glabel BtScriptWorkBuffer
/* 01F06840 */ .space 0x10

glabel BtCashBuffer
/* 01F06850 */ .space 0x10

glabel BtScriptBuffer
/* 01F06860 */ .space 0x10

glabel BtSystemScriptFileBuffer
/* 01F06870 */ .space 0x10

glabel floor_name
/* 01F06880 */ .space 0x20

glabel ref_off
/* 01F068A0 */ .space 0x10

glabel ruby_effect_pos
/* 01F068B0 */ .space 0x10

glabel ruby_effect_vec
/* 01F068C0 */ .space 0x10

glabel unitAmbientAnime_rgb
/* 01F068D0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01F068DC_441EDC
/* 01F068DC */ .space 0x04

glabel CDbgMsg
/* 01F068E0 */ .space 0x21C

/* Automatically generated and unreferenced pad */
glabel B_01F06AFC_4420FC
/* 01F06AFC */ .space 0x04
