name: Dark Cloud (North America)
sha1: D9965D6908A334A5DFC982F3384428AD42048D54
options:
  basename: SCUS_971.11
  target_path: rom/SCUS_971.11
  base_path: ..
  asm_path: asm
  asset_path: assets
  src_path: src
  build_path: build
  compiler: GCC
  ld_script_path: config/SCUS_971.11.auto.ld
  platform: ps2
  symbol_addrs_path: config/symbols.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  undefined_syms_auto_path: config/undefined_syms_auto.txt
  extensions_path: config/extensions
  find_file_boundaries: false # We can manually determine file boundaries ourselves later
  use_legacy_include_asm: false
  string_encoding: ascii

  # C file options
  # We cannot automatically create c files as mw does not allow inlining .s files as gcc does
  create_c_files: false 

  # Disassembly-related options
  asm_inc_header: ".include \"macro.inc\"\n\n.set noat      /* allow manual use of $at */\n.set noreorder /* don't insert nops after branches */\n\n"
segments:
  - [0x0] # Elf header
  - name: main
    type: code
    start: 0x100
    vram: 0x100000
    subalign: 4
    subsegments:
      - [0x100, hasm, crt0] # Sony SDK
      - [0x1C0, c, gcc_wrapper] # MW SDK

      # newlib - All of these files are compiled with GCC
      - [0x2A8, c, abort]
      - [0x2C8, c, abs]
      - [0x2E0, c, assert]
      - [0x318, c, atof]
      - [0x338, c]
      # atoi
      # _calloc_r
      # close_r
      # quorem
      - [0x1870, c, exit] # TODO: Check which module this is actually in
      - [0x1920, c]

      - name: texture
        type: cpp
        start: 0x30FF0
      - [0x31060, c]

      - name: ebattle
        type: cpp
        start: 0x68200
      - [0x68210, c]

      # SCE libs
      # - [0xC470, c, libdma] 
      # - [0xCF90, c]

      # Vu programs
      - [0x145400, bin, Vu_prog0]
      - [0x146200, bin, Vu_prog0f]
      - [0x148A00, bin, Vu_prog1]
      - [0x1498D0, bin, Vu_progg]
      - [0x149A00, bin, Vu_shadow]
      - [0x14B770, bin, Vu_shadow2]
      - [0x14DCF0, bin, Vu_shadow3]
      - [0x14FA60, bin, Vu_progmain]

      # __data_start
      - [0x14FBC0, rodata, data]
      # - [0x19FF80, c, sinit]
      # - [0x1A1110, rodata]
      - [0x1A1900, rodata, sdata]
      - [0x1A2480] # bss start

      # Manually define .sbss/.bss .s files
      - name: 1A2480.sbss
        type: hasm
        start: auto
      - name: 1A2790.sbss
        type: hasm
        start: auto
      - name: bss
        type: hasm
        start: auto

      # .sbss
      - name: sbss
        type: .sbss
        start: auto
        vram: 0x2A2380

      # .bss
      - name: bss
        type: .bss
        start: auto
        vram: 0x2A3709

      # Markers
      - name: __gp
        type: linker_offset
        start: auto
        vram: 0x2A97F0
      
      - name: __bss_end
        type: linker_offset
        start: auto
        vram: 0x1DABD00
  - name: mwcats.1
    type: bin
    start: 0x1FEBF0
  - name: mwcats.2
    type: bin
    start: 0x205060
  - name: mwcats.3
    type: bin
    start: 0x2055F0
  - [0x2057E0] # .relmain
  - name: comment
    type: bin
    start: 0x2B11C8 
  - name: reginfo
    type: bin
    start: 0x2B11F4 
  - [0x2B148C] # End of ROM
