.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel sceVu0ApplyMatrix
    /* 021688 00121588 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02168C 0012158C 1000A5D8 */  lqc2       $vf5, 0x10($5)
    /* 021690 00121590 2000A6D8 */  lqc2       $vf6, 0x20($5)
    /* 021694 00121594 3000A7D8 */  lqc2       $vf7, 0x30($5)
    /* 021698 00121598 0000C8D8 */  lqc2       $vf8, 0x0($6)
    /* 02169C 0012159C BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 0216A0 001215A0 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 0216A4 001215A4 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 0216A8 001215A8 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 0216AC 001215AC 0800E003 */  jr         $31
    /* 0216B0 001215B0 000089F8 */   sqc2      $vf9, 0x0($4)
    /* 0216B4 001215B4 00000000 */  nop

/* Handwritten function */
glabel sceVu0MulMatrix
    /* 0216B8 001215B8 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 0216BC 001215BC 1000A5D8 */  lqc2       $vf5, 0x10($5)
    /* 0216C0 001215C0 2000A6D8 */  lqc2       $vf6, 0x20($5)
    /* 0216C4 001215C4 3000A7D8 */  lqc2       $vf7, 0x30($5)
    /* 0216C8 001215C8 04000724 */  addiu      $7, $0, 0x4
  .L_loopMulMatrix:
    /* 0216CC 001215CC 0000C8D8 */  lqc2       $vf8, 0x0($6)
    /* 0216D0 001215D0 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 0216D4 001215D4 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 0216D8 001215D8 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 0216DC 001215DC 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 0216E0 001215E0 000089F8 */  sqc2       $vf9, 0x0($4)
    /* 0216E4 001215E4 FFFFE720 */  addi       $7, $7, -0x1 /* handwritten instruction */
    /* 0216E8 001215E8 1000C620 */  addi       $6, $6, 0x10 /* handwritten instruction */
    /* 0216EC 001215EC F7FF0714 */  bne        $0, $7, .L_loopMulMatrix
    /* 0216F0 001215F0 10008420 */   addi      $4, $4, 0x10 /* handwritten instruction */
    /* 0216F4 001215F4 0800E003 */  jr         $31
    /* 0216F8 001215F8 00000000 */   nop
    /* 0216FC 001215FC 00000000 */  nop

glabel sceVu0OuterProduct
    /* 021700 00121600 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 021704 00121604 0000C5D8 */  lqc2       $vf5, 0x0($6)
    /* 021708 00121608 FE22C54B */  vopmula.xyz $ACC, $vf4, $vf5
    /* 02170C 0012160C AE29C44B */  vopmsub.xyz $vf6, $vf5, $vf4
    /* 021710 00121610 AC31264A */  vsub.w     $vf6, $vf6, $vf6
    /* 021714 00121614 0800E003 */  jr         $31
    /* 021718 00121618 000086F8 */   sqc2      $vf6, 0x0($4)
    /* 02171C 0012161C 00000000 */  nop

glabel sceVu0InnerProduct
    /* 021720 00121620 000084D8 */  lqc2       $vf4, 0x0($4)
    /* 021724 00121624 0000A5D8 */  lqc2       $vf5, 0x0($5)
    /* 021728 00121628 6A21C54B */  vmul.xyz   $vf5, $vf4, $vf5
    /* 02172C 0012162C 4129054B */  vaddy.x    $vf5, $vf5, $vf5y
    /* 021730 00121630 4229054B */  vaddz.x    $vf5, $vf5, $vf5z
    /* 021734 00121634 00282248 */  qmfc2.ni   $2, $vf5
    /* 021738 00121638 00008244 */  mtc1       $2, $f0
    /* 02173C 0012163C 0800E003 */  jr         $31
    /* 021740 00121640 00000000 */   nop
    /* 021744 00121644 00000000 */  nop

glabel sceVu0Normalize
    /* 021748 00121648 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02174C 0012164C 6A21C44B */  vmul.xyz   $vf5, $vf4, $vf4
    /* 021750 00121650 4129054B */  vaddy.x    $vf5, $vf5, $vf5y
    /* 021754 00121654 4229054B */  vaddz.x    $vf5, $vf5, $vf5z
    /* 021758 00121658 BD03054A */  .word      0x4A0503BD                    # vsqrt      $Q, $vf5x # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 02175C 0012165C BF03004A */  vwaitq
    /* 021760 00121660 6001004B */  vaddq.x    $vf5, $vf0, $Q
    /* 021764 00121664 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 021768 00121668 AC01E04B */  vsub.xyzw  $vf6, $vf0, $vf0
    /* 02176C 0012166C BF03004A */  vwaitq
    /* 021770 00121670 9C21C04B */  vmulq.xyz  $vf6, $vf4, $Q
    /* 021774 00121674 0800E003 */  jr         $31
    /* 021778 00121678 000086F8 */   sqc2      $vf6, 0x0($4)
    /* 02177C 0012167C 00000000 */  nop

glabel sceVu0TransposeMatrix
    /* 021780 00121680 0000A878 */  lq         $8, 0x0($5)
    /* 021784 00121684 1000A978 */  lq         $9, 0x10($5)
    /* 021788 00121688 2000AA78 */  lq         $10, 0x20($5)
    /* 02178C 0012168C 3000AB78 */  lq         $11, 0x30($5)
    /* 021790 00121690 88642871 */  pextlw     $12, $9, $8
    /* 021794 00121694 A86C2871 */  pextuw     $13, $9, $8
    /* 021798 00121698 88746A71 */  pextlw     $14, $11, $10
    /* 02179C 0012169C A87C6A71 */  pextuw     $15, $11, $10
    /* 0217A0 001216A0 8943CC71 */  pcpyld     $8, $14, $12
    /* 0217A4 001216A4 A94B8E71 */  pcpyud     $9, $12, $14
    /* 0217A8 001216A8 8953ED71 */  pcpyld     $10, $15, $13
    /* 0217AC 001216AC A95BAF71 */  pcpyud     $11, $13, $15
    /* 0217B0 001216B0 0000887C */  sq         $8, 0x0($4)
    /* 0217B4 001216B4 1000897C */  sq         $9, 0x10($4)
    /* 0217B8 001216B8 20008A7C */  sq         $10, 0x20($4)
    /* 0217BC 001216BC 0800E003 */  jr         $31
    /* 0217C0 001216C0 30008B7C */   sq        $11, 0x30($4)
    /* 0217C4 001216C4 00000000 */  nop

glabel sceVu0InversMatrix
    /* 0217C8 001216C8 0000A878 */  lq         $8, 0x0($5)
    /* 0217CC 001216CC 1000A978 */  lq         $9, 0x10($5)
    /* 0217D0 001216D0 2000AA78 */  lq         $10, 0x20($5)
    /* 0217D4 001216D4 3000A4D8 */  lqc2       $vf4, 0x30($5)
    /* 0217D8 001216D8 3C23E54B */  vmove.xyzw $vf5, $vf4
    /* 0217DC 001216DC 2C21C44B */  vsub.xyz   $vf4, $vf4, $vf4
    /* 0217E0 001216E0 3C23E94B */  vmove.xyzw $vf9, $vf4
    /* 0217E4 001216E4 00202B48 */  qmfc2.ni   $11, $vf4
    /* 0217E8 001216E8 88642871 */  pextlw     $12, $9, $8
    /* 0217EC 001216EC A86C2871 */  pextuw     $13, $9, $8
    /* 0217F0 001216F0 88746A71 */  pextlw     $14, $11, $10
    /* 0217F4 001216F4 A87C6A71 */  pextuw     $15, $11, $10
    /* 0217F8 001216F8 8943CC71 */  pcpyld     $8, $14, $12
    /* 0217FC 001216FC A94B8E71 */  pcpyud     $9, $12, $14
    /* 021800 00121700 8953ED71 */  pcpyld     $10, $15, $13
    /* 021804 00121704 0030A848 */  qmtc2.ni   $8, $vf6
    /* 021808 00121708 0038A948 */  qmtc2.ni   $9, $vf7
    /* 02180C 0012170C 0040AA48 */  qmtc2.ni   $10, $vf8
    /* 021810 00121710 BC31C54B */  vmulax.xyz $ACC, $vf6, $vf5x
    /* 021814 00121714 BD38C54B */  vmadday.xyz $ACC, $vf7, $vf5y
    /* 021818 00121718 0A41C54B */  vmaddz.xyz $vf4, $vf8, $vf5z
    /* 02181C 0012171C 2C49C44B */  vsub.xyz   $vf4, $vf9, $vf4
    /* 021820 00121720 0000887C */  sq         $8, 0x0($4)
    /* 021824 00121724 1000897C */  sq         $9, 0x10($4)
    /* 021828 00121728 20008A7C */  sq         $10, 0x20($4)
    /* 02182C 0012172C 0800E003 */  jr         $31
    /* 021830 00121730 300084F8 */   sqc2      $vf4, 0x30($4)
    /* 021834 00121734 00000000 */  nop

glabel sceVu0DivVector
    /* 021838 00121738 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02183C 0012173C 00600844 */  mfc1       $8, $f12
    /* 021840 00121740 0028A848 */  qmtc2.ni   $8, $vf5
    /* 021844 00121744 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 021848 00121748 BF03004A */  vwaitq
    /* 02184C 0012174C 1C21E04B */  vmulq.xyzw $vf4, $vf4, $Q
    /* 021850 00121750 0800E003 */  jr         $31
    /* 021854 00121754 000084F8 */   sqc2      $vf4, 0x0($4)

glabel sceVu0DivVectorXYZ
    /* 021858 00121758 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02185C 0012175C 00600844 */  mfc1       $8, $f12
    /* 021860 00121760 0028A848 */  qmtc2.ni   $8, $vf5
    /* 021864 00121764 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 021868 00121768 BF03004A */  vwaitq
    /* 02186C 0012176C 1C21C04B */  vmulq.xyz  $vf4, $vf4, $Q
    /* 021870 00121770 0800E003 */  jr         $31
    /* 021874 00121774 000084F8 */   sqc2      $vf4, 0x0($4)

glabel sceVu0InterVector
    /* 021878 00121778 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02187C 0012177C 0000C5D8 */  lqc2       $vf5, 0x0($6)
    /* 021880 00121780 00600844 */  mfc1       $8, $f12
    /* 021884 00121784 0030A848 */  qmtc2.ni   $8, $vf6
    /* 021888 00121788 C301004B */  vaddw.x    $vf7, $vf0, $vf0w
    /* 02188C 0012178C 2C3A064B */  vsub.x     $vf8, $vf7, $vf6
    /* 021890 00121790 BC21E64B */  vmulax.xyzw $ACC, $vf4, $vf6x
    /* 021894 00121794 482AE84B */  vmaddx.xyzw $vf9, $vf5, $vf8x
    /* 021898 00121798 0800E003 */  jr         $31
    /* 02189C 0012179C 000089F8 */   sqc2      $vf9, 0x0($4)

glabel sceVu0AddVector
    /* 0218A0 001217A0 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 0218A4 001217A4 0000C5D8 */  lqc2       $vf5, 0x0($6)
    /* 0218A8 001217A8 A821E54B */  vadd.xyzw  $vf6, $vf4, $vf5
    /* 0218AC 001217AC 0800E003 */  jr         $31
    /* 0218B0 001217B0 000086F8 */   sqc2      $vf6, 0x0($4)
    /* 0218B4 001217B4 00000000 */  nop

glabel sceVu0SubVector
    /* 0218B8 001217B8 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 0218BC 001217BC 0000C5D8 */  lqc2       $vf5, 0x0($6)
    /* 0218C0 001217C0 AC21E54B */  vsub.xyzw  $vf6, $vf4, $vf5
    /* 0218C4 001217C4 0800E003 */  jr         $31
    /* 0218C8 001217C8 000086F8 */   sqc2      $vf6, 0x0($4)
    /* 0218CC 001217CC 00000000 */  nop

glabel sceVu0MulVector
    /* 0218D0 001217D0 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 0218D4 001217D4 0000C5D8 */  lqc2       $vf5, 0x0($6)
    /* 0218D8 001217D8 AA21E54B */  vmul.xyzw  $vf6, $vf4, $vf5
    /* 0218DC 001217DC 0800E003 */  jr         $31
    /* 0218E0 001217E0 000086F8 */   sqc2      $vf6, 0x0($4)
    /* 0218E4 001217E4 00000000 */  nop

glabel sceVu0ScaleVector
    /* 0218E8 001217E8 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 0218EC 001217EC 00600844 */  mfc1       $8, $f12
    /* 0218F0 001217F0 0028A848 */  qmtc2.ni   $8, $vf5
    /* 0218F4 001217F4 9821E54B */  vmulx.xyzw $vf6, $vf4, $vf5x
    /* 0218F8 001217F8 0800E003 */  jr         $31
    /* 0218FC 001217FC 000086F8 */   sqc2      $vf6, 0x0($4)

glabel sceVu0TransMatrix
    /* 021900 00121800 0000C4D8 */  lqc2       $vf4, 0x0($6)
    /* 021904 00121804 3000A5D8 */  lqc2       $vf5, 0x30($5)
    /* 021908 00121808 0000A778 */  lq         $7, 0x0($5)
    /* 02190C 0012180C 1000A878 */  lq         $8, 0x10($5)
    /* 021910 00121810 2000A978 */  lq         $9, 0x20($5)
    /* 021914 00121814 6829C44B */  vadd.xyz   $vf5, $vf5, $vf4
    /* 021918 00121818 0000877C */  sq         $7, 0x0($4)
    /* 02191C 0012181C 1000887C */  sq         $8, 0x10($4)
    /* 021920 00121820 2000897C */  sq         $9, 0x20($4)
    /* 021924 00121824 0800E003 */  jr         $31
    /* 021928 00121828 300085F8 */   sqc2      $vf5, 0x30($4)
    /* 02192C 0012182C 00000000 */  nop

glabel sceVu0CopyVector
    /* 021930 00121830 0000A678 */  lq         $6, 0x0($5)
    /* 021934 00121834 0800E003 */  jr         $31
    /* 021938 00121838 0000867C */   sq        $6, 0x0($4)
    /* 02193C 0012183C 00000000 */  nop

glabel sceVu0CopyMatrix
    /* 021940 00121840 0000A678 */  lq         $6, 0x0($5)
    /* 021944 00121844 1000A778 */  lq         $7, 0x10($5)
    /* 021948 00121848 2000A878 */  lq         $8, 0x20($5)
    /* 02194C 0012184C 3000A978 */  lq         $9, 0x30($5)
    /* 021950 00121850 0000867C */  sq         $6, 0x0($4)
    /* 021954 00121854 1000877C */  sq         $7, 0x10($4)
    /* 021958 00121858 2000887C */  sq         $8, 0x20($4)
    /* 02195C 0012185C 0800E003 */  jr         $31
    /* 021960 00121860 3000897C */   sq        $9, 0x30($4)
    /* 021964 00121864 00000000 */  nop

glabel sceVu0FTOI4Vector
    /* 021968 00121868 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02196C 0012186C 7D21E54B */  vftoi4.xyzw $vf5, $vf4
    /* 021970 00121870 0800E003 */  jr         $31
    /* 021974 00121874 000085F8 */   sqc2      $vf5, 0x0($4)

glabel sceVu0FTOI0Vector
    /* 021978 00121878 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02197C 0012187C 7C21E54B */  vftoi0.xyzw $vf5, $vf4
    /* 021980 00121880 0800E003 */  jr         $31
    /* 021984 00121884 000085F8 */   sqc2      $vf5, 0x0($4)

glabel sceVu0ITOF4Vector
    /* 021988 00121888 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02198C 0012188C 3D21E54B */  vitof4.xyzw $vf5, $vf4
    /* 021990 00121890 0800E003 */  jr         $31
    /* 021994 00121894 000085F8 */   sqc2      $vf5, 0x0($4)

glabel sceVu0ITOF0Vector
    /* 021998 00121898 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02199C 0012189C 3C21E54B */  vitof0.xyzw $vf5, $vf4
    /* 0219A0 001218A0 0800E003 */  jr         $31
    /* 0219A4 001218A4 000085F8 */   sqc2      $vf5, 0x0($4)

glabel sceVu0UnitMatrix
    /* 0219A8 001218A8 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 0219AC 001218AC 2821204A */  vadd.w     $vf4, $vf4, $vf0
    /* 0219B0 001218B0 3D23E54B */  vmr32.xyzw $vf5, $vf4
    /* 0219B4 001218B4 3D2BE64B */  vmr32.xyzw $vf6, $vf5
    /* 0219B8 001218B8 3D33E74B */  vmr32.xyzw $vf7, $vf6
    /* 0219BC 001218BC 300084F8 */  sqc2       $vf4, 0x30($4)
    /* 0219C0 001218C0 200085F8 */  sqc2       $vf5, 0x20($4)
    /* 0219C4 001218C4 100086F8 */  sqc2       $vf6, 0x10($4)
    /* 0219C8 001218C8 0800E003 */  jr         $31
    /* 0219CC 001218CC 000087F8 */   sqc2      $vf7, 0x0($4)

glabel _sceVu0ecossin
    /* 0219D0 001218D0 2500083C */  lui        $8, %hi(S5432)
    /* 0219D4 001218D4 F00A0825 */  addiu      $8, $8, %lo(S5432)
    /* 0219D8 001218D8 000005D9 */  lqc2       $vf5, 0x0($8)
    /* 0219DC 001218DC 3D33264A */  vmr32.w    $vf6, $vf6
    /* 0219E0 001218E0 0001064B */  vaddx.x    $vf4, $vf0, $vf6x
    /* 0219E4 001218E4 AA31064B */  vmul.x     $vf6, $vf6, $vf6
    /* 0219E8 001218E8 1821E04A */  vmulx.yzw  $vf4, $vf4, $vf0x
    /* 0219EC 001218EC 1B2AE64B */  vmulw.xyzw $vf8, $vf5, $vf6w
    /* 0219F0 001218F0 6C01E04B */  vsub.xyzw  $vf5, $vf0, $vf0
    /* 0219F4 001218F4 1842E64B */  vmulx.xyzw $vf8, $vf8, $vf6x
    /* 0219F8 001218F8 1842C64B */  vmulx.xyz  $vf8, $vf8, $vf6x
    /* 0219FC 001218FC 0321084B */  vaddw.x    $vf4, $vf4, $vf8w
    /* 021A00 00121900 1842864B */  vmulx.xy   $vf8, $vf8, $vf6x
    /* 021A04 00121904 0221084B */  vaddz.x    $vf4, $vf4, $vf8z
    /* 021A08 00121908 1842064B */  vmulx.x    $vf8, $vf8, $vf6x
    /* 021A0C 0012190C 0121084B */  vaddy.x    $vf4, $vf4, $vf8y
    /* 021A10 00121910 0021084B */  vaddx.x    $vf4, $vf4, $vf8x
    /* 021A14 00121914 0029844B */  vaddx.xy   $vf4, $vf5, $vf4x
    /* 021A18 00121918 EA21044B */  vmul.x     $vf7, $vf4, $vf4
    /* 021A1C 0012191C C401274A */  vsubx.w    $vf7, $vf0, $vf7x
    /* 021A20 00121920 BD03874B */  .word      0x4B8703BD                    # vsqrt      $Q, $vf7w # 00000000 <InstrIdType: R5900_COP2_SPECIAL2>
    /* 021A24 00121924 BF03004A */  vwaitq
    /* 021A28 00121928 0300E014 */  bnez       $7, .L_ecossin_01
    /* 021A2C 0012192C E001004B */   vaddq.x   $vf7, $vf0, $Q
    /* 021A30 00121930 02000010 */  b          .L_ecossin_02
    /* 021A34 00121934 0029074B */   vaddx.x   $vf4, $vf5, $vf7x
  .L_ecossin_01:
    /* 021A38 00121938 0429074B */  vsubx.x    $vf4, $vf5, $vf7x
  .L_ecossin_02:
    /* 021A3C 0012193C 0800E003 */  jr         $31
    /* 021A40 00121940 00000000 */   nop
    /* 021A44 00121944 00000000 */  nop

/* Handwritten function */
glabel sceVu0RotMatrixZ
    /* 021A48 00121948 00008044 */  mtc1       $0, $f0
    /* 021A4C 0012194C 34600046 */  c.lt.s     $f12, $f0
    /* 021A50 00121950 C93F013C */  lui        $1, (0x3FC90FDB >> 16)
    /* 021A54 00121954 DB0F2134 */  ori        $1, $1, (0x3FC90FDB & 0xFFFF)
    /* 021A58 00121958 00008144 */  mtc1       $1, $f0
    /* 021A5C 0012195C 04000045 */  bc1f       .L_RotMatrixZ_01
    /* 021A60 00121960 00000000 */   nop
    /* 021A64 00121964 00030C46 */  add.s      $f12, $f0, $f12
    /* 021A68 00121968 5E860408 */  j          _RotMatrixZ_02
    /* 021A6C 0012196C 01000724 */   addiu     $7, $0, 0x1
  .L_RotMatrixZ_01:
    /* 021A70 00121970 01030C46 */  sub.s      $f12, $f0, $f12
    /* 021A74 00121974 2D380000 */  daddu      $7, $0, $0
jlabel _RotMatrixZ_02
    /* 021A78 00121978 00600844 */  mfc1       $8, $f12
    /* 021A7C 0012197C 0030A848 */  qmtc2.ni   $8, $vf6
    /* 021A80 00121980 2D30E003 */  daddu      $6, $31, $0
    /* 021A84 00121984 3486040C */  jal        _sceVu0ecossin
    /* 021A88 00121988 00000000 */   nop
    /* 021A8C 0012198C 2DF8C000 */  daddu      $31, $6, $0
    /* 021A90 00121990 3C2BE64B */  vmove.xyzw $vf6, $vf5
    /* 021A94 00121994 3C2BE74B */  vmove.xyzw $vf7, $vf5
    /* 021A98 00121998 3C03E94B */  vmove.xyzw $vf9, $vf0
    /* 021A9C 0012199C 6C4AC94B */  vsub.xyz   $vf9, $vf9, $vf9
    /* 021AA0 001219A0 3D4BE84B */  vmr32.xyzw $vf8, $vf9
    /* 021AA4 001219A4 2C21644A */  vsub.zw    $vf4, $vf4, $vf4
    /* 021AA8 001219A8 8029844A */  vaddx.y    $vf6, $vf5, $vf4x
    /* 021AAC 001219AC 8129044B */  vaddy.x    $vf6, $vf5, $vf4y
    /* 021AB0 001219B0 C429044B */  vsubx.x    $vf7, $vf5, $vf4x
    /* 021AB4 001219B4 C129844A */  vaddy.y    $vf7, $vf5, $vf4y
    /* 021AB8 001219B8 04000724 */  addiu      $7, $0, 0x4
  .L_loopRotMatrixZ:
    /* 021ABC 001219BC 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 021AC0 001219C0 BC31E44B */  vmulax.xyzw $ACC, $vf6, $vf4x
    /* 021AC4 001219C4 BD38E44B */  vmadday.xyzw $ACC, $vf7, $vf4y
    /* 021AC8 001219C8 BE40E44B */  vmaddaz.xyzw $ACC, $vf8, $vf4z
    /* 021ACC 001219CC 4B49E44B */  vmaddw.xyzw $vf5, $vf9, $vf4w
    /* 021AD0 001219D0 000085F8 */  sqc2       $vf5, 0x0($4)
    /* 021AD4 001219D4 FFFFE720 */  addi       $7, $7, -0x1 /* handwritten instruction */
    /* 021AD8 001219D8 1000A520 */  addi       $5, $5, 0x10 /* handwritten instruction */
    /* 021ADC 001219DC F7FF0714 */  bne        $0, $7, .L_loopRotMatrixZ
    /* 021AE0 001219E0 10008420 */   addi      $4, $4, 0x10 /* handwritten instruction */
    /* 021AE4 001219E4 0800E003 */  jr         $31
    /* 021AE8 001219E8 00000000 */   nop
    /* 021AEC 001219EC 00000000 */  nop

/* Handwritten function */
glabel sceVu0RotMatrixX
    /* 021AF0 001219F0 00008044 */  mtc1       $0, $f0
    /* 021AF4 001219F4 34600046 */  c.lt.s     $f12, $f0
    /* 021AF8 001219F8 C93F013C */  lui        $1, (0x3FC90FDB >> 16)
    /* 021AFC 001219FC DB0F2134 */  ori        $1, $1, (0x3FC90FDB & 0xFFFF)
    /* 021B00 00121A00 00008144 */  mtc1       $1, $f0
    /* 021B04 00121A04 04000045 */  bc1f       .L_RotMatrixX_01
    /* 021B08 00121A08 00000000 */   nop
    /* 021B0C 00121A0C 00030C46 */  add.s      $f12, $f0, $f12
    /* 021B10 00121A10 88860408 */  j          _RotMatrixX_02
    /* 021B14 00121A14 01000724 */   addiu     $7, $0, 0x1
  .L_RotMatrixX_01:
    /* 021B18 00121A18 01030C46 */  sub.s      $f12, $f0, $f12
    /* 021B1C 00121A1C 2D380000 */  daddu      $7, $0, $0
jlabel _RotMatrixX_02
    /* 021B20 00121A20 00600844 */  mfc1       $8, $f12
    /* 021B24 00121A24 0030A848 */  qmtc2.ni   $8, $vf6
    /* 021B28 00121A28 2D30E003 */  daddu      $6, $31, $0
    /* 021B2C 00121A2C 3486040C */  jal        _sceVu0ecossin
    /* 021B30 00121A30 00000000 */   nop
    /* 021B34 00121A34 2DF8C000 */  daddu      $31, $6, $0
    /* 021B38 00121A38 3C2BE64B */  vmove.xyzw $vf6, $vf5
    /* 021B3C 00121A3C 3C2BE74B */  vmove.xyzw $vf7, $vf5
    /* 021B40 00121A40 3C2BE84B */  vmove.xyzw $vf8, $vf5
    /* 021B44 00121A44 3C2BE94B */  vmove.xyzw $vf9, $vf5
    /* 021B48 00121A48 8329004B */  vaddw.x    $vf6, $vf5, $vf0w
    /* 021B4C 00121A4C 432A204A */  vaddw.w    $vf9, $vf5, $vf0w
    /* 021B50 00121A50 2C21644A */  vsub.zw    $vf4, $vf4, $vf4
    /* 021B54 00121A54 C029444A */  vaddx.z    $vf7, $vf5, $vf4x
    /* 021B58 00121A58 C129844A */  vaddy.y    $vf7, $vf5, $vf4y
    /* 021B5C 00121A5C 042A844A */  vsubx.y    $vf8, $vf5, $vf4x
    /* 021B60 00121A60 012A444A */  vaddy.z    $vf8, $vf5, $vf4y
    /* 021B64 00121A64 04000724 */  addiu      $7, $0, 0x4
  .L_loopRotMatrixX:
    /* 021B68 00121A68 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 021B6C 00121A6C BC31E44B */  vmulax.xyzw $ACC, $vf6, $vf4x
    /* 021B70 00121A70 BD38E44B */  vmadday.xyzw $ACC, $vf7, $vf4y
    /* 021B74 00121A74 BE40E44B */  vmaddaz.xyzw $ACC, $vf8, $vf4z
    /* 021B78 00121A78 4B49E44B */  vmaddw.xyzw $vf5, $vf9, $vf4w
    /* 021B7C 00121A7C 000085F8 */  sqc2       $vf5, 0x0($4)
    /* 021B80 00121A80 FFFFE720 */  addi       $7, $7, -0x1 /* handwritten instruction */
    /* 021B84 00121A84 1000A520 */  addi       $5, $5, 0x10 /* handwritten instruction */
    /* 021B88 00121A88 F7FF0714 */  bne        $0, $7, .L_loopRotMatrixX
    /* 021B8C 00121A8C 10008420 */   addi      $4, $4, 0x10 /* handwritten instruction */
    /* 021B90 00121A90 0800E003 */  jr         $31
    /* 021B94 00121A94 00000000 */   nop

/* Handwritten function */
glabel sceVu0RotMatrixY
    /* 021B98 00121A98 00008044 */  mtc1       $0, $f0
    /* 021B9C 00121A9C 34600046 */  c.lt.s     $f12, $f0
    /* 021BA0 00121AA0 C93F013C */  lui        $1, (0x3FC90FDB >> 16)
    /* 021BA4 00121AA4 DB0F2134 */  ori        $1, $1, (0x3FC90FDB & 0xFFFF)
    /* 021BA8 00121AA8 00008144 */  mtc1       $1, $f0
    /* 021BAC 00121AAC 04000045 */  bc1f       .L_RotMatrixY_01
    /* 021BB0 00121AB0 00000000 */   nop
    /* 021BB4 00121AB4 00030C46 */  add.s      $f12, $f0, $f12
    /* 021BB8 00121AB8 B2860408 */  j          _RotMatrixY_02
    /* 021BBC 00121ABC 01000724 */   addiu     $7, $0, 0x1
  .L_RotMatrixY_01:
    /* 021BC0 00121AC0 01030C46 */  sub.s      $f12, $f0, $f12
    /* 021BC4 00121AC4 2D380000 */  daddu      $7, $0, $0
jlabel _RotMatrixY_02
    /* 021BC8 00121AC8 00600844 */  mfc1       $8, $f12
    /* 021BCC 00121ACC 0030A848 */  qmtc2.ni   $8, $vf6
    /* 021BD0 00121AD0 2D30E003 */  daddu      $6, $31, $0
    /* 021BD4 00121AD4 3486040C */  jal        _sceVu0ecossin
    /* 021BD8 00121AD8 00000000 */   nop
    /* 021BDC 00121ADC 2DF8C000 */  daddu      $31, $6, $0
    /* 021BE0 00121AE0 3C2BE64B */  vmove.xyzw $vf6, $vf5
    /* 021BE4 00121AE4 3C2BE74B */  vmove.xyzw $vf7, $vf5
    /* 021BE8 00121AE8 3C2BE84B */  vmove.xyzw $vf8, $vf5
    /* 021BEC 00121AEC 3C2BE94B */  vmove.xyzw $vf9, $vf5
    /* 021BF0 00121AF0 C329804A */  vaddw.y    $vf7, $vf5, $vf0w
    /* 021BF4 00121AF4 432A204A */  vaddw.w    $vf9, $vf5, $vf0w
    /* 021BF8 00121AF8 2C21644A */  vsub.zw    $vf4, $vf4, $vf4
    /* 021BFC 00121AFC 8429444A */  vsubx.z    $vf6, $vf5, $vf4x
    /* 021C00 00121B00 8129044B */  vaddy.x    $vf6, $vf5, $vf4y
    /* 021C04 00121B04 002A044B */  vaddx.x    $vf8, $vf5, $vf4x
    /* 021C08 00121B08 012A444A */  vaddy.z    $vf8, $vf5, $vf4y
    /* 021C0C 00121B0C 04000724 */  addiu      $7, $0, 0x4
  .L_loopRotMatrixY:
    /* 021C10 00121B10 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 021C14 00121B14 BC31E44B */  vmulax.xyzw $ACC, $vf6, $vf4x
    /* 021C18 00121B18 BD38E44B */  vmadday.xyzw $ACC, $vf7, $vf4y
    /* 021C1C 00121B1C BE40E44B */  vmaddaz.xyzw $ACC, $vf8, $vf4z
    /* 021C20 00121B20 4B49E44B */  vmaddw.xyzw $vf5, $vf9, $vf4w
    /* 021C24 00121B24 000085F8 */  sqc2       $vf5, 0x0($4)
    /* 021C28 00121B28 FFFFE720 */  addi       $7, $7, -0x1 /* handwritten instruction */
    /* 021C2C 00121B2C 1000A520 */  addi       $5, $5, 0x10 /* handwritten instruction */
    /* 021C30 00121B30 F7FF0714 */  bne        $0, $7, .L_loopRotMatrixY
    /* 021C34 00121B34 10008420 */   addi      $4, $4, 0x10 /* handwritten instruction */
    /* 021C38 00121B38 0800E003 */  jr         $31
    /* 021C3C 00121B3C 00000000 */   nop

glabel sceVu0RotMatrix
    /* 021C40 00121B40 D0FFBD27 */  addiu      $29, $29, -0x30
    /* 021C44 00121B44 1000B1FF */  sd         $17, 0x10($29)
    /* 021C48 00121B48 0000B0FF */  sd         $16, 0x0($29)
    /* 021C4C 00121B4C 2D88C000 */  daddu      $17, $6, $0
    /* 021C50 00121B50 2000BFFF */  sd         $31, 0x20($29)
    /* 021C54 00121B54 2D808000 */  daddu      $16, $4, $0
    /* 021C58 00121B58 5286040C */  jal        sceVu0RotMatrixZ
    /* 021C5C 00121B5C 08002CC6 */   lwc1      $f12, 0x8($17)
    /* 021C60 00121B60 04002CC6 */  lwc1       $f12, 0x4($17)
    /* 021C64 00121B64 2D200002 */  daddu      $4, $16, $0
    /* 021C68 00121B68 A686040C */  jal        sceVu0RotMatrixY
    /* 021C6C 00121B6C 2D280002 */   daddu     $5, $16, $0
    /* 021C70 00121B70 2D200002 */  daddu      $4, $16, $0
    /* 021C74 00121B74 00002CC6 */  lwc1       $f12, 0x0($17)
    /* 021C78 00121B78 2000BFDF */  ld         $31, 0x20($29)
    /* 021C7C 00121B7C 2D288000 */  daddu      $5, $4, $0
    /* 021C80 00121B80 1000B1DF */  ld         $17, 0x10($29)
    /* 021C84 00121B84 0000B0DF */  ld         $16, 0x0($29)
    /* 021C88 00121B88 7C860408 */  j          sceVu0RotMatrixX
    /* 021C8C 00121B8C 3000BD27 */   addiu     $29, $29, 0x30

glabel sceVu0ClampVector
    /* 021C90 00121B90 00600844 */  mfc1       $8, $f12
    /* 021C94 00121B94 00680944 */  mfc1       $9, $f13
    /* 021C98 00121B98 0000A6D8 */  lqc2       $vf6, 0x0($5)
    /* 021C9C 00121B9C 0020A848 */  qmtc2.ni   $8, $vf4
    /* 021CA0 00121BA0 0028A948 */  qmtc2.ni   $9, $vf5
    /* 021CA4 00121BA4 9031E44B */  vmaxx.xyzw $vf6, $vf6, $vf4x
    /* 021CA8 00121BA8 9431E54B */  vminix.xyzw $vf6, $vf6, $vf5x
    /* 021CAC 00121BAC 0800E003 */  jr         $31
    /* 021CB0 00121BB0 000086F8 */   sqc2      $vf6, 0x0($4)
    /* 021CB4 00121BB4 00000000 */  nop

glabel sceVu0CameraMatrix
    /* 021CB8 00121BB8 50FFBD27 */  addiu      $29, $29, -0xB0
    /* 021CBC 00121BBC 9000B4FF */  sd         $20, 0x90($29)
    /* 021CC0 00121BC0 2DA08000 */  daddu      $20, $4, $0
    /* 021CC4 00121BC4 8000B3FF */  sd         $19, 0x80($29)
    /* 021CC8 00121BC8 7000B2FF */  sd         $18, 0x70($29)
    /* 021CCC 00121BCC 2D98A000 */  daddu      $19, $5, $0
    /* 021CD0 00121BD0 6000B1FF */  sd         $17, 0x60($29)
    /* 021CD4 00121BD4 2D90C000 */  daddu      $18, $6, $0
    /* 021CD8 00121BD8 2D88E000 */  daddu      $17, $7, $0
    /* 021CDC 00121BDC 5000B0FF */  sd         $16, 0x50($29)
    /* 021CE0 00121BE0 A000BFFF */  sd         $31, 0xA0($29)
    /* 021CE4 00121BE4 2A86040C */  jal        sceVu0UnitMatrix
    /* 021CE8 00121BE8 2D20A003 */   daddu     $4, $29, $0
    /* 021CEC 00121BEC 4000B027 */  addiu      $16, $29, 0x40
    /* 021CF0 00121BF0 2D282002 */  daddu      $5, $17, $0
    /* 021CF4 00121BF4 2D200002 */  daddu      $4, $16, $0
    /* 021CF8 00121BF8 8085040C */  jal        sceVu0OuterProduct
    /* 021CFC 00121BFC 2D304002 */   daddu     $6, $18, $0
    /* 021D00 00121C00 2D280002 */  daddu      $5, $16, $0
    /* 021D04 00121C04 9285040C */  jal        sceVu0Normalize
    /* 021D08 00121C08 2D20A003 */   daddu     $4, $29, $0
    /* 021D0C 00121C0C 2000B027 */  addiu      $16, $29, 0x20
    /* 021D10 00121C10 2D284002 */  daddu      $5, $18, $0
    /* 021D14 00121C14 9285040C */  jal        sceVu0Normalize
    /* 021D18 00121C18 2D200002 */   daddu     $4, $16, $0
    /* 021D1C 00121C1C 2D280002 */  daddu      $5, $16, $0
    /* 021D20 00121C20 1000A427 */  addiu      $4, $29, 0x10
    /* 021D24 00121C24 8085040C */  jal        sceVu0OuterProduct
    /* 021D28 00121C28 2D30A003 */   daddu     $6, $29, $0
    /* 021D2C 00121C2C 2D306002 */  daddu      $6, $19, $0
    /* 021D30 00121C30 2D20A003 */  daddu      $4, $29, $0
    /* 021D34 00121C34 0086040C */  jal        sceVu0TransMatrix
    /* 021D38 00121C38 2D28A003 */   daddu     $5, $29, $0
    /* 021D3C 00121C3C 2D208002 */  daddu      $4, $20, $0
    /* 021D40 00121C40 B285040C */  jal        sceVu0InversMatrix
    /* 021D44 00121C44 2D28A003 */   daddu     $5, $29, $0
    /* 021D48 00121C48 A000BFDF */  ld         $31, 0xA0($29)
    /* 021D4C 00121C4C 9000B4DF */  ld         $20, 0x90($29)
    /* 021D50 00121C50 8000B3DF */  ld         $19, 0x80($29)
    /* 021D54 00121C54 7000B2DF */  ld         $18, 0x70($29)
    /* 021D58 00121C58 6000B1DF */  ld         $17, 0x60($29)
    /* 021D5C 00121C5C 5000B0DF */  ld         $16, 0x50($29)
    /* 021D60 00121C60 0800E003 */  jr         $31
    /* 021D64 00121C64 B000BD27 */   addiu     $29, $29, 0xB0

glabel sceVu0NormalLightMatrix
    /* 021D68 00121C68 A0FFBD27 */  addiu      $29, $29, -0x60
    /* 021D6C 00121C6C 5000B4E7 */  swc1       $f20, 0x50($29)
    /* 021D70 00121C70 80BF013C */  lui        $1, (0xBF800000 >> 16)
    /* 021D74 00121C74 00A08144 */  mtc1       $1, $f20
    /* 021D78 00121C78 1000B0FF */  sd         $16, 0x10($29)
    /* 021D7C 00121C7C 2D808000 */  daddu      $16, $4, $0
    /* 021D80 00121C80 3000B2FF */  sd         $18, 0x30($29)
    /* 021D84 00121C84 2000B1FF */  sd         $17, 0x20($29)
    /* 021D88 00121C88 2D90E000 */  daddu      $18, $7, $0
    /* 021D8C 00121C8C 2D88C000 */  daddu      $17, $6, $0
    /* 021D90 00121C90 06A30046 */  mov.s      $f12, $f20
    /* 021D94 00121C94 4000BFFF */  sd         $31, 0x40($29)
    /* 021D98 00121C98 FA85040C */  jal        sceVu0ScaleVector
    /* 021D9C 00121C9C 2D20A003 */   daddu     $4, $29, $0
    /* 021DA0 00121CA0 2D200002 */  daddu      $4, $16, $0
    /* 021DA4 00121CA4 9285040C */  jal        sceVu0Normalize
    /* 021DA8 00121CA8 2D28A003 */   daddu     $5, $29, $0
    /* 021DAC 00121CAC 2D282002 */  daddu      $5, $17, $0
    /* 021DB0 00121CB0 06A30046 */  mov.s      $f12, $f20
    /* 021DB4 00121CB4 FA85040C */  jal        sceVu0ScaleVector
    /* 021DB8 00121CB8 2D20A003 */   daddu     $4, $29, $0
    /* 021DBC 00121CBC 10000426 */  addiu      $4, $16, 0x10
    /* 021DC0 00121CC0 9285040C */  jal        sceVu0Normalize
    /* 021DC4 00121CC4 2D28A003 */   daddu     $5, $29, $0
    /* 021DC8 00121CC8 2D284002 */  daddu      $5, $18, $0
    /* 021DCC 00121CCC 06A30046 */  mov.s      $f12, $f20
    /* 021DD0 00121CD0 FA85040C */  jal        sceVu0ScaleVector
    /* 021DD4 00121CD4 2D20A003 */   daddu     $4, $29, $0
    /* 021DD8 00121CD8 20000426 */  addiu      $4, $16, 0x20
    /* 021DDC 00121CDC 9285040C */  jal        sceVu0Normalize
    /* 021DE0 00121CE0 2D28A003 */   daddu     $5, $29, $0
    /* 021DE4 00121CE4 00008044 */  mtc1       $0, $f0
    /* 021DE8 00121CE8 2D200002 */  daddu      $4, $16, $0
    /* 021DEC 00121CEC 803F013C */  lui        $1, (0x3F800000 >> 16)
    /* 021DF0 00121CF0 00088144 */  mtc1       $1, $f1
    /* 021DF4 00121CF4 2D288000 */  daddu      $5, $4, $0
    /* 021DF8 00121CF8 300000E6 */  swc1       $f0, 0x30($16)
    /* 021DFC 00121CFC 3C0001E6 */  swc1       $f1, 0x3C($16)
    /* 021E00 00121D00 380000E6 */  swc1       $f0, 0x38($16)
    /* 021E04 00121D04 A085040C */  jal        sceVu0TransposeMatrix
    /* 021E08 00121D08 340000E6 */   swc1      $f0, 0x34($16)
    /* 021E0C 00121D0C 4000BFDF */  ld         $31, 0x40($29)
    /* 021E10 00121D10 3000B2DF */  ld         $18, 0x30($29)
    /* 021E14 00121D14 2000B1DF */  ld         $17, 0x20($29)
    /* 021E18 00121D18 1000B0DF */  ld         $16, 0x10($29)
    /* 021E1C 00121D1C 5000B4C7 */  lwc1       $f20, 0x50($29)
    /* 021E20 00121D20 0800E003 */  jr         $31
    /* 021E24 00121D24 6000BD27 */   addiu     $29, $29, 0x60

glabel sceVu0LightColorMatrix
    /* 021E28 00121D28 B0FFBD27 */  addiu      $29, $29, -0x50
    /* 021E2C 00121D2C 0000B0FF */  sd         $16, 0x0($29)
    /* 021E30 00121D30 2D808000 */  daddu      $16, $4, $0
    /* 021E34 00121D34 3000B3FF */  sd         $19, 0x30($29)
    /* 021E38 00121D38 2000B2FF */  sd         $18, 0x20($29)
    /* 021E3C 00121D3C 2D980001 */  daddu      $19, $8, $0
    /* 021E40 00121D40 1000B1FF */  sd         $17, 0x10($29)
    /* 021E44 00121D44 2D90E000 */  daddu      $18, $7, $0
    /* 021E48 00121D48 4000BFFF */  sd         $31, 0x40($29)
    /* 021E4C 00121D4C 0C86040C */  jal        sceVu0CopyVector
    /* 021E50 00121D50 2D88C000 */   daddu     $17, $6, $0
    /* 021E54 00121D54 2D282002 */  daddu      $5, $17, $0
    /* 021E58 00121D58 0C86040C */  jal        sceVu0CopyVector
    /* 021E5C 00121D5C 10000426 */   addiu     $4, $16, 0x10
    /* 021E60 00121D60 2D284002 */  daddu      $5, $18, $0
    /* 021E64 00121D64 0C86040C */  jal        sceVu0CopyVector
    /* 021E68 00121D68 20000426 */   addiu     $4, $16, 0x20
    /* 021E6C 00121D6C 30000426 */  addiu      $4, $16, 0x30
    /* 021E70 00121D70 2D286002 */  daddu      $5, $19, $0
    /* 021E74 00121D74 4000BFDF */  ld         $31, 0x40($29)
    /* 021E78 00121D78 3000B3DF */  ld         $19, 0x30($29)
    /* 021E7C 00121D7C 2000B2DF */  ld         $18, 0x20($29)
    /* 021E80 00121D80 1000B1DF */  ld         $17, 0x10($29)
    /* 021E84 00121D84 0000B0DF */  ld         $16, 0x0($29)
    /* 021E88 00121D88 0C860408 */  j          sceVu0CopyVector
    /* 021E8C 00121D8C 5000BD27 */   addiu     $29, $29, 0x50

glabel sceVu0ViewScreenMatrix
    /* 021E90 00121D90 60FFBD27 */  addiu      $29, $29, -0xA0
    /* 021E94 00121D94 07880046 */  neg.s      $f0, $f17
    /* 021E98 00121D98 6000B4E7 */  swc1       $f20, 0x60($29)
    /* 021E9C 00121D9C 07950046 */  neg.s      $f20, $f18
    /* 021EA0 00121DA0 A000A1C7 */  lwc1       $f1, 0xA0($29)
    /* 021EA4 00121DA4 6800B5E7 */  swc1       $f21, 0x68($29)
    /* 021EA8 00121DA8 00001246 */  add.s      $f0, $f0, $f18
    /* 021EAC 00121DAC 420D1346 */  mul.s      $f21, $f1, $f19
    /* 021EB0 00121DB0 4000B0FF */  sd         $16, 0x40($29)
    /* 021EB4 00121DB4 02A51346 */  mul.s      $f20, $f20, $f19
    /* 021EB8 00121DB8 2D808000 */  daddu      $16, $4, $0
    /* 021EBC 00121DBC 428C0146 */  mul.s      $f17, $f17, $f1
    /* 021EC0 00121DC0 9000BAE7 */  swc1       $f26, 0x90($29)
    /* 021EC4 00121DC4 C79C0046 */  neg.s      $f19, $f19
    /* 021EC8 00121DC8 8800B9E7 */  swc1       $f25, 0x88($29)
    /* 021ECC 00121DCC 42AD0046 */  mul.s      $f21, $f21, $f0
    /* 021ED0 00121DD0 8000B8E7 */  swc1       $f24, 0x80($29)
    /* 021ED4 00121DD4 00A51146 */  add.s      $f20, $f20, $f17
    /* 021ED8 00121DD8 7800B7E7 */  swc1       $f23, 0x78($29)
    /* 021EDC 00121DDC C09C0146 */  add.s      $f19, $f19, $f1
    /* 021EE0 00121DE0 7000B6E7 */  swc1       $f22, 0x70($29)
    /* 021EE4 00121DE4 86650046 */  mov.s      $f22, $f12
    /* 021EE8 00121DE8 066E0046 */  mov.s      $f24, $f13
    /* 021EEC 00121DEC C6750046 */  mov.s      $f23, $f14
    /* 021EF0 00121DF0 867E0046 */  mov.s      $f26, $f15
    /* 021EF4 00121DF4 00000000 */  nop
    /* 021EF8 00121DF8 00000000 */  nop
    /* 021EFC 00121DFC 43AD1346 */  div.s      $f21, $f21, $f19
    /* 021F00 00121E00 00000000 */  nop
    /* 021F04 00121E04 00000000 */  nop
    /* 021F08 00121E08 03A51346 */  div.s      $f20, $f20, $f19
    /* 021F0C 00121E0C 5000BFFF */  sd         $31, 0x50($29)
    /* 021F10 00121E10 2A86040C */  jal        sceVu0UnitMatrix
    /* 021F14 00121E14 46860046 */   mov.s     $f25, $f16
    /* 021F18 00121E18 803F013C */  lui        $1, (0x3F800000 >> 16)
    /* 021F1C 00121E1C 00008144 */  mtc1       $1, $f0
    /* 021F20 00121E20 2D20A003 */  daddu      $4, $29, $0
    /* 021F24 00121E24 140016E6 */  swc1       $f22, 0x14($16)
    /* 021F28 00121E28 000016E6 */  swc1       $f22, 0x0($16)
    /* 021F2C 00121E2C 280000AE */  sw         $0, 0x28($16)
    /* 021F30 00121E30 3C0000AE */  sw         $0, 0x3C($16)
    /* 021F34 00121E34 2C0000E6 */  swc1       $f0, 0x2C($16)
    /* 021F38 00121E38 2A86040C */  jal        sceVu0UnitMatrix
    /* 021F3C 00121E3C 380000E6 */   swc1      $f0, 0x38($16)
    /* 021F40 00121E40 2D200002 */  daddu      $4, $16, $0
    /* 021F44 00121E44 0000B8E7 */  swc1       $f24, 0x0($29)
    /* 021F48 00121E48 1400B7E7 */  swc1       $f23, 0x14($29)
    /* 021F4C 00121E4C 2D28A003 */  daddu      $5, $29, $0
    /* 021F50 00121E50 2800B5E7 */  swc1       $f21, 0x28($29)
    /* 021F54 00121E54 2D308000 */  daddu      $6, $4, $0
    /* 021F58 00121E58 3000BAE7 */  swc1       $f26, 0x30($29)
    /* 021F5C 00121E5C 3400B9E7 */  swc1       $f25, 0x34($29)
    /* 021F60 00121E60 6E85040C */  jal        sceVu0MulMatrix
    /* 021F64 00121E64 3800B4E7 */   swc1      $f20, 0x38($29)
    /* 021F68 00121E68 5000BFDF */  ld         $31, 0x50($29)
    /* 021F6C 00121E6C 4000B0DF */  ld         $16, 0x40($29)
    /* 021F70 00121E70 9000BAC7 */  lwc1       $f26, 0x90($29)
    /* 021F74 00121E74 8800B9C7 */  lwc1       $f25, 0x88($29)
    /* 021F78 00121E78 8000B8C7 */  lwc1       $f24, 0x80($29)
    /* 021F7C 00121E7C 7800B7C7 */  lwc1       $f23, 0x78($29)
    /* 021F80 00121E80 7000B6C7 */  lwc1       $f22, 0x70($29)
    /* 021F84 00121E84 6800B5C7 */  lwc1       $f21, 0x68($29)
    /* 021F88 00121E88 6000B4C7 */  lwc1       $f20, 0x60($29)
    /* 021F8C 00121E8C 0800E003 */  jr         $31
    /* 021F90 00121E90 A000BD27 */   addiu     $29, $29, 0xA0
    /* 021F94 00121E94 00000000 */  nop

glabel sceVu0DropShadowMatrix
    /* 021F98 00121E98 06640046 */  mov.s      $f16, $f12
    /* 021F9C 00121E9C 2A00C010 */  beqz       $6, .L00121F48
    /* 021FA0 00121EA0 C66B0046 */   mov.s     $f15, $f13
    /* 021FA4 00121EA4 0000A1C4 */  lwc1       $f1, 0x0($5)
    /* 021FA8 00121EA8 0400A2C4 */  lwc1       $f2, 0x4($5)
    /* 021FAC 00121EAC 42820146 */  mul.s      $f9, $f16, $f1
    /* 021FB0 00121EB0 0800A3C4 */  lwc1       $f3, 0x8($5)
    /* 021FB4 00121EB4 827A0246 */  mul.s      $f10, $f15, $f2
    /* 021FB8 00121EB8 803F013C */  lui        $1, (0x3F800000 >> 16)
    /* 021FBC 00121EBC 00288144 */  mtc1       $1, $f5
    /* 021FC0 00121EC0 82710346 */  mul.s      $f6, $f14, $f3
    /* 021FC4 00121EC4 0C0090E4 */  swc1       $f16, 0xC($4)
    /* 021FC8 00121EC8 C7090046 */  neg.s      $f7, $f1
    /* 021FCC 00121ECC 1C008FE4 */  swc1       $f15, 0x1C($4)
    /* 021FD0 00121ED0 00480A46 */  add.s      $f0, $f9, $f10
    /* 021FD4 00121ED4 2C008EE4 */  swc1       $f14, 0x2C($4)
    /* 021FD8 00121ED8 07110046 */  neg.s      $f4, $f2
    /* 021FDC 00121EDC 300087E4 */  swc1       $f7, 0x30($4)
    /* 021FE0 00121EE0 071A0046 */  neg.s      $f8, $f3
    /* 021FE4 00121EE4 00000646 */  add.s      $f0, $f0, $f6
    /* 021FE8 00121EE8 340084E4 */  swc1       $f4, 0x34($4)
    /* 021FEC 00121EEC C2790146 */  mul.s      $f7, $f15, $f1
    /* 021FF0 00121EF0 02810246 */  mul.s      $f4, $f16, $f2
    /* 021FF4 00121EF4 380088E4 */  swc1       $f8, 0x38($4)
    /* 021FF8 00121EF8 01280046 */  sub.s      $f0, $f5, $f0
    /* 021FFC 00121EFC 42700146 */  mul.s      $f1, $f14, $f1
    /* 022000 00121F00 100087E4 */  swc1       $f7, 0x10($4)
    /* 022004 00121F04 82700246 */  mul.s      $f2, $f14, $f2
    /* 022008 00121F08 040084E4 */  swc1       $f4, 0x4($4)
    /* 02200C 00121F0C 41010546 */  sub.s      $f5, $f0, $f5
    /* 022010 00121F10 404A0046 */  add.s      $f9, $f9, $f0
    /* 022014 00121F14 200081E4 */  swc1       $f1, 0x20($4)
    /* 022018 00121F18 80520046 */  add.s      $f10, $f10, $f0
    /* 02201C 00121F1C 240082E4 */  swc1       $f2, 0x24($4)
    /* 022020 00121F20 80310046 */  add.s      $f6, $f6, $f0
    /* 022024 00121F24 3C0085E4 */  swc1       $f5, 0x3C($4)
    /* 022028 00121F28 02800346 */  mul.s      $f0, $f16, $f3
    /* 02202C 00121F2C 000089E4 */  swc1       $f9, 0x0($4)
    /* 022030 00121F30 C2780346 */  mul.s      $f3, $f15, $f3
    /* 022034 00121F34 14008AE4 */  swc1       $f10, 0x14($4)
    /* 022038 00121F38 280086E4 */  swc1       $f6, 0x28($4)
    /* 02203C 00121F3C 080080E4 */  swc1       $f0, 0x8($4)
    /* 022040 00121F40 0800E003 */  jr         $31
    /* 022044 00121F44 180083E4 */   swc1      $f3, 0x18($4)
  .L00121F48:
    /* 022048 00121F48 0000A2C4 */  lwc1       $f2, 0x0($5)
    /* 02204C 00121F4C 0400A4C4 */  lwc1       $f4, 0x4($5)
    /* 022050 00121F50 42810246 */  mul.s      $f5, $f16, $f2
    /* 022054 00121F54 0800A7C4 */  lwc1       $f7, 0x8($5)
    /* 022058 00121F58 82790446 */  mul.s      $f6, $f15, $f4
    /* 02205C 00121F5C 80BF013C */  lui        $1, (0xBF800000 >> 16)
    /* 022060 00121F60 00088144 */  mtc1       $1, $f1
    /* 022064 00121F64 02720746 */  mul.s      $f8, $f14, $f7
    /* 022068 00121F68 0C0080AC */  sw         $0, 0xC($4)
    /* 02206C 00121F6C 47120046 */  neg.s      $f9, $f2
    /* 022070 00121F70 1C0080AC */  sw         $0, 0x1C($4)
    /* 022074 00121F74 00280646 */  add.s      $f0, $f5, $f6
    /* 022078 00121F78 2C0080AC */  sw         $0, 0x2C($4)
    /* 02207C 00121F7C 82720446 */  mul.s      $f10, $f14, $f4
    /* 022080 00121F80 C7220046 */  neg.s      $f11, $f4
    /* 022084 00121F84 00000846 */  add.s      $f0, $f0, $f8
    /* 022088 00121F88 C2780246 */  mul.s      $f3, $f15, $f2
    /* 02208C 00121F8C 02830746 */  mul.s      $f12, $f16, $f7
    /* 022090 00121F90 00000000 */  nop
    /* 022094 00121F94 00000000 */  nop
    /* 022098 00121F98 43080046 */  div.s      $f1, $f1, $f0
    /* 02209C 00121F9C 41290046 */  sub.s      $f5, $f5, $f0
    /* 0220A0 00121FA0 81310046 */  sub.s      $f6, $f6, $f0
    /* 0220A4 00121FA4 01420046 */  sub.s      $f8, $f8, $f0
    /* 0220A8 00121FA8 427B0746 */  mul.s      $f13, $f15, $f7
    /* 0220AC 00121FAC 07000046 */  neg.s      $f0, $f0
    /* 0220B0 00121FB0 82700246 */  mul.s      $f2, $f14, $f2
    /* 0220B4 00121FB4 02810446 */  mul.s      $f4, $f16, $f4
    /* 0220B8 00121FB8 C7390046 */  neg.s      $f7, $f7
    /* 0220BC 00121FBC 02080046 */  mul.s      $f0, $f1, $f0
    /* 0220C0 00121FC0 42090546 */  mul.s      $f5, $f1, $f5
    /* 0220C4 00121FC4 C2080346 */  mul.s      $f3, $f1, $f3
    /* 0220C8 00121FC8 82080246 */  mul.s      $f2, $f1, $f2
    /* 0220CC 00121FCC 3C0080E4 */  swc1       $f0, 0x3C($4)
    /* 0220D0 00121FD0 420A0946 */  mul.s      $f9, $f1, $f9
    /* 0220D4 00121FD4 000085E4 */  swc1       $f5, 0x0($4)
    /* 0220D8 00121FD8 02090446 */  mul.s      $f4, $f1, $f4
    /* 0220DC 00121FDC 100083E4 */  swc1       $f3, 0x10($4)
    /* 0220E0 00121FE0 82090646 */  mul.s      $f6, $f1, $f6
    /* 0220E4 00121FE4 200082E4 */  swc1       $f2, 0x20($4)
    /* 0220E8 00121FE8 820A0A46 */  mul.s      $f10, $f1, $f10
    /* 0220EC 00121FEC 300089E4 */  swc1       $f9, 0x30($4)
    /* 0220F0 00121FF0 C20A0B46 */  mul.s      $f11, $f1, $f11
    /* 0220F4 00121FF4 040084E4 */  swc1       $f4, 0x4($4)
    /* 0220F8 00121FF8 020B0C46 */  mul.s      $f12, $f1, $f12
    /* 0220FC 00121FFC 140086E4 */  swc1       $f6, 0x14($4)
    /* 022100 00122000 420B0D46 */  mul.s      $f13, $f1, $f13
    /* 022104 00122004 24008AE4 */  swc1       $f10, 0x24($4)
    /* 022108 00122008 020A0846 */  mul.s      $f8, $f1, $f8
    /* 02210C 0012200C 34008BE4 */  swc1       $f11, 0x34($4)
    /* 022110 00122010 42080746 */  mul.s      $f1, $f1, $f7
    /* 022114 00122014 08008CE4 */  swc1       $f12, 0x8($4)
    /* 022118 00122018 18008DE4 */  swc1       $f13, 0x18($4)
    /* 02211C 0012201C 280088E4 */  swc1       $f8, 0x28($4)
    /* 022120 00122020 0800E003 */  jr         $31
    /* 022124 00122024 380081E4 */   swc1      $f1, 0x38($4)

/* Handwritten function */
glabel sceVu0RotTransPersN
    /* 022128 00122028 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02212C 0012202C 1000A5D8 */  lqc2       $vf5, 0x10($5)
    /* 022130 00122030 2000A6D8 */  lqc2       $vf6, 0x20($5)
    /* 022134 00122034 3000A7D8 */  lqc2       $vf7, 0x30($5)
  .L_rotTPN_loop:
    /* 022138 00122038 0000C8D8 */  lqc2       $vf8, 0x0($6)
    /* 02213C 0012203C BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 022140 00122040 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 022144 00122044 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 022148 00122048 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 02214C 0012204C BC03E94B */  vdiv       $Q, $vf0w, $vf9w
    /* 022150 00122050 BF03004A */  vwaitq
    /* 022154 00122054 5C4AC04B */  vmulq.xyz  $vf9, $vf9, $Q
    /* 022158 00122058 02000011 */  beqz       $8, .L_rotTPN
    /* 02215C 0012205C 7D49EA4B */   vftoi4.xyzw $vf10, $vf9
    /* 022160 00122060 7C496A4A */  vftoi0.zw  $vf10, $vf9
  .L_rotTPN:
    /* 022164 00122064 00008AF8 */  sqc2       $vf10, 0x0($4)
    /* 022168 00122068 FFFFE720 */  addi       $7, $7, -0x1 /* handwritten instruction */
    /* 02216C 0012206C 1000C620 */  addi       $6, $6, 0x10 /* handwritten instruction */
    /* 022170 00122070 F1FF0714 */  bne        $0, $7, .L_rotTPN_loop
    /* 022174 00122074 10008420 */   addi      $4, $4, 0x10 /* handwritten instruction */
    /* 022178 00122078 0800E003 */  jr         $31
    /* 02217C 0012207C 00000000 */   nop

glabel sceVu0RotTransPers
    /* 022180 00122080 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 022184 00122084 1000A5D8 */  lqc2       $vf5, 0x10($5)
    /* 022188 00122088 2000A6D8 */  lqc2       $vf6, 0x20($5)
    /* 02218C 0012208C 3000A7D8 */  lqc2       $vf7, 0x30($5)
    /* 022190 00122090 0000C8D8 */  lqc2       $vf8, 0x0($6)
    /* 022194 00122094 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 022198 00122098 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 02219C 0012209C BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 0221A0 001220A0 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 0221A4 001220A4 BC03E94B */  vdiv       $Q, $vf0w, $vf9w
    /* 0221A8 001220A8 BF03004A */  vwaitq
    /* 0221AC 001220AC 5C4AC04B */  vmulq.xyz  $vf9, $vf9, $Q
    /* 0221B0 001220B0 0200E010 */  beqz       $7, .L_rotTP
    /* 0221B4 001220B4 7D49EA4B */   vftoi4.xyzw $vf10, $vf9
    /* 0221B8 001220B8 7C496A4A */  vftoi0.zw  $vf10, $vf9
  .L_rotTP:
    /* 0221BC 001220BC 0800E003 */  jr         $31
    /* 0221C0 001220C0 00008AF8 */   sqc2      $vf10, 0x0($4)
    /* 0221C4 001220C4 00000000 */  nop

glabel sceVu0CopyVectorXYZ
    /* 0221C8 001220C8 0000A0C4 */  lwc1       $f0, 0x0($5)
    /* 0221CC 001220CC 000080E4 */  swc1       $f0, 0x0($4)
    /* 0221D0 001220D0 0400A1C4 */  lwc1       $f1, 0x4($5)
    /* 0221D4 001220D4 040081E4 */  swc1       $f1, 0x4($4)
    /* 0221D8 001220D8 0800A0C4 */  lwc1       $f0, 0x8($5)
    /* 0221DC 001220DC 0800E003 */  jr         $31
    /* 0221E0 001220E0 080080E4 */   swc1      $f0, 0x8($4)
    /* 0221E4 001220E4 00000000 */  nop

glabel sceVu0InterVectorXYZ
    /* 0221E8 001220E8 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 0221EC 001220EC 0000C5D8 */  lqc2       $vf5, 0x0($6)
    /* 0221F0 001220F0 00600844 */  mfc1       $8, $f12
    /* 0221F4 001220F4 0030A848 */  qmtc2.ni   $8, $vf6
    /* 0221F8 001220F8 3C23294A */  vmove.w    $vf9, $vf4
    /* 0221FC 001220FC C301004B */  vaddw.x    $vf7, $vf0, $vf0w
    /* 022200 00122100 2C3A064B */  vsub.x     $vf8, $vf7, $vf6
    /* 022204 00122104 BC21C64B */  vmulax.xyz $ACC, $vf4, $vf6x
    /* 022208 00122108 482AC84B */  vmaddx.xyz $vf9, $vf5, $vf8x
    /* 02220C 0012210C 0800E003 */  jr         $31
    /* 022210 00122110 000089F8 */   sqc2      $vf9, 0x0($4)
    /* 022214 00122114 00000000 */  nop

glabel sceVu0ScaleVectorXYZ
    /* 022218 00122118 0000A4D8 */  lqc2       $vf4, 0x0($5)
    /* 02221C 0012211C 00600844 */  mfc1       $8, $f12
    /* 022220 00122120 0028A848 */  qmtc2.ni   $8, $vf5
    /* 022224 00122124 1821C54B */  vmulx.xyz  $vf4, $vf4, $vf5x
    /* 022228 00122128 0800E003 */  jr         $31
    /* 02222C 0012212C 000084F8 */   sqc2      $vf4, 0x0($4)

glabel sceVu0ClipScreen
    /* 022230 00122130 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 022234 00122134 8045023C */  lui        $2, (0x45800000 >> 16)
    /* 022238 00122138 38140200 */  dsll       $2, $2, 16
    /* 02223C 0012213C 80454234 */  ori        $2, $2, 0x4580
    /* 022240 00122140 38140200 */  dsll       $2, $2, 16
    /* 022244 00122144 000087D8 */  lqc2       $vf7, 0x0($4)
    /* 022248 00122148 0030A248 */  qmtc2.ni   $2, $vf6
    /* 02224C 0012214C 0080C048 */  ctc2.ni    $0, $vi16
    /* 022250 00122150 6C39A44B */  vsub.xyw   $vf5, $vf7, $vf4
    /* 022254 00122154 6C31874B */  vsub.xy    $vf5, $vf6, $vf7
    /* 022258 00122158 FF02004A */  vnop
    /* 02225C 0012215C FF02004A */  vnop
    /* 022260 00122160 FF02004A */  vnop
    /* 022264 00122164 FF02004A */  vnop
    /* 022268 00122168 FF02004A */  vnop
    /* 02226C 0012216C 00804248 */  cfc2.ni    $2, $vi16
    /* 022270 00122170 0800E003 */  jr         $31
    /* 022274 00122174 C0004230 */   andi      $2, $2, 0xC0

glabel sceVu0ClipScreen3
    /* 022278 00122178 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 02227C 0012217C 8045023C */  lui        $2, (0x45800000 >> 16)
    /* 022280 00122180 38140200 */  dsll       $2, $2, 16
    /* 022284 00122184 80454234 */  ori        $2, $2, 0x4580
    /* 022288 00122188 38140200 */  dsll       $2, $2, 16
    /* 02228C 0012218C 000086D8 */  lqc2       $vf6, 0x0($4)
    /* 022290 00122190 0000A8D8 */  lqc2       $vf8, 0x0($5)
    /* 022294 00122194 0000C9D8 */  lqc2       $vf9, 0x0($6)
    /* 022298 00122198 0038A248 */  qmtc2.ni   $2, $vf7
    /* 02229C 0012219C 0080C048 */  ctc2.ni    $0, $vi16
    /* 0222A0 001221A0 6C31A44B */  vsub.xyw   $vf5, $vf6, $vf4
    /* 0222A4 001221A4 6C39864B */  vsub.xy    $vf5, $vf7, $vf6
    /* 0222A8 001221A8 6C41A44B */  vsub.xyw   $vf5, $vf8, $vf4
    /* 0222AC 001221AC 6C39884B */  vsub.xy    $vf5, $vf7, $vf8
    /* 0222B0 001221B0 6C49A44B */  vsub.xyw   $vf5, $vf9, $vf4
    /* 0222B4 001221B4 6C39894B */  vsub.xy    $vf5, $vf7, $vf9
    /* 0222B8 001221B8 FF02004A */  vnop
    /* 0222BC 001221BC FF02004A */  vnop
    /* 0222C0 001221C0 FF02004A */  vnop
    /* 0222C4 001221C4 FF02004A */  vnop
    /* 0222C8 001221C8 FF02004A */  vnop
    /* 0222CC 001221CC 00804248 */  cfc2.ni    $2, $vi16
    /* 0222D0 001221D0 0800E003 */  jr         $31
    /* 0222D4 001221D4 C0004230 */   andi      $2, $2, 0xC0

/* Handwritten function */
glabel sceVu0ClipAll
    /* 0222D8 001221D8 0000E8D8 */  lqc2       $vf8, 0x0($7)
    /* 0222DC 001221DC 0000C4D8 */  lqc2       $vf4, 0x0($6)
    /* 0222E0 001221E0 1000C5D8 */  lqc2       $vf5, 0x10($6)
    /* 0222E4 001221E4 2000C6D8 */  lqc2       $vf6, 0x20($6)
    /* 0222E8 001221E8 3000C7D8 */  lqc2       $vf7, 0x30($6)
    /* 0222EC 001221EC 000089D8 */  lqc2       $vf9, 0x0($4)
    /* 0222F0 001221F0 0000AAD8 */  lqc2       $vf10, 0x0($5)
    /* 0222F4 001221F4 00008BD8 */  lqc2       $vf11, 0x0($4)
    /* 0222F8 001221F8 0000ACD8 */  lqc2       $vf12, 0x0($5)
  .Lloop_clip_all:
    /* 0222FC 001221FC BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 022300 00122200 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 022304 00122204 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 022308 00122208 0B3AE84B */  vmaddw.xyzw $vf8, $vf7, $vf8w
    /* 02230C 0012220C DB4AC84B */  vmulw.xyz  $vf11, $vf9, $vf8w
    /* 022310 00122210 1B53C84B */  vmulw.xyz  $vf12, $vf10, $vf8w
    /* 022314 00122214 FF02004A */  vnop
    /* 022318 00122218 FF02004A */  vnop
    /* 02231C 0012221C 0080C048 */  ctc2.ni    $0, $vi16
    /* 022320 00122220 EC42AB4B */  vsub.xyw   $vf11, $vf8, $vf11
    /* 022324 00122224 2C63A84B */  vsub.xyw   $vf12, $vf12, $vf8
    /* 022328 00122228 3C4B2B4A */  vmove.w    $vf11, $vf9
    /* 02232C 0012222C 3C532C4A */  vmove.w    $vf12, $vf10
    /* 022330 00122230 FF02004A */  vnop
    /* 022334 00122234 1000E720 */  addi       $7, $7, 0x10 /* handwritten instruction */
    /* 022338 00122238 0000E8D8 */  lqc2       $vf8, 0x0($7)
    /* 02233C 0012223C FFFF0821 */  addi       $8, $8, -0x1 /* handwritten instruction */
    /* 022340 00122240 00804248 */  cfc2.ni    $2, $vi16
    /* 022344 00122244 C0004230 */  andi       $2, $2, 0xC0
    /* 022348 00122248 04004010 */  beqz       $2, .Lend_clip_all
    /* 02234C 0012224C 00000000 */   nop
    /* 022350 00122250 EAFF0814 */  bne        $0, $8, .Lloop_clip_all
    /* 022354 00122254 00000000 */   nop
    /* 022358 00122258 01000220 */  addi       $2, $0, 0x1 /* handwritten instruction */
  .Lend_clip_all:
    /* 02235C 0012225C 0800E003 */  jr         $31
    /* 022360 00122260 00000000 */   nop
    /* 022364 00122264 00000000 */  nop

glabel sceVpu0Reset
    /* 022368 00122268 0010023C */  lui        $2, (0x10003830 >> 16)
    /* 02236C 0012226C 0010043C */  lui        $4, (0x10003820 >> 16)
    /* 022370 00122270 30384234 */  ori        $2, $2, (0x10003830 & 0xFFFF)
    /* 022374 00122274 20388434 */  ori        $4, $4, (0x10003820 & 0xFFFF)
    /* 022378 00122278 000040AC */  sw         $0, 0x0($2)
    /* 02237C 0012227C 0010033C */  lui        $3, (0x10003810 >> 16)
    /* 022380 00122280 000080AC */  sw         $0, 0x0($4)
    /* 022384 00122284 10386334 */  ori        $3, $3, (0x10003810 & 0xFFFF)
    /* 022388 00122288 01000224 */  addiu      $2, $0, 0x1
    /* 02238C 0012228C 000062AC */  sw         $2, 0x0($3)
    /* 022390 00122290 00E04848 */  cfc2.ni    $8, $vi28
    /* 022394 00122294 02000835 */  ori        $8, $8, 0x2
    /* 022398 00122298 00E0C848 */  ctc2.ni    $8, $vi28
    /* 02239C 0012229C 0F040000 */  sync.p
    /* 0223A0 001222A0 2500043C */  lui        $4, %hi(init_vif_regs_126)
    /* 0223A4 001222A4 0010053C */  lui        $5, (0x10004000 >> 16)
    /* 0223A8 001222A8 000B8424 */  addiu      $4, $4, %lo(init_vif_regs_126)
    /* 0223AC 001222AC 0040A534 */  ori        $5, $5, (0x10004000 & 0xFFFF)
    /* 0223B0 001222B0 00008278 */  lq         $2, 0x0($4)
    /* 0223B4 001222B4 0000A27C */  sq         $2, 0x0($5)
    /* 0223B8 001222B8 10008378 */  lq         $3, 0x10($4)
    /* 0223BC 001222BC 0800E003 */  jr         $31
    /* 0223C0 001222C0 0000A37C */   sq        $3, 0x0($5)
    /* 0223C4 001222C4 00000000 */  nop
    /* 0223C8 001222C8 00000000 */  nop
    /* 0223CC 001222CC 00000000 */  nop
