.include "macro.inc"

.set noat /* Allow manual use of $at. */
.set noreorder /* Don't insert nops after branches. */

.section .bss
/* Generated by spimdisasm 1.42.3 */

glabel _title_static_init_end
/* 01DE1AFC */ .space 0x04

glabel CScript__2
/* 01DE1B00 */ .space 0xE300

glabel CharaDataBuffer__2
/* 01DEFE00 */ .space 0x70

glabel DummyBuffer
/* 01DEFE70 */ .space 0x10

glabel PassDataBuffer
/* 01DEFE80 */ .space 0x30

glabel MapDataBuffer
/* 01DEFEB0 */ .space 0x10

glabel WaterBuffer__2
/* 01DEFEC0 */ .space 0x10

glabel testBuffer
/* 01DEFED0 */ .space 0x10

glabel Chara__3
/* 01DEFEE0 */ .space 0x196D0

glabel CharaTex__2
/* 01E095B0 */ .space 0x17

/* Automatically generated and unreferenced pad */
glabel B_01E095C7_30EDC7
/* 01E095C7 */ .space 0x01

glabel LIT_363__5
/* 01E095C8 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01E095D4_30EDD4
/* 01E095D4 */ .space 0x0C

glabel OP_MainCamera
/* 01E095E0 */ .space 0x2F0

glabel Cam__2
/* 01E098D0 */ .space 0x3510

glabel Op_MotionInfo
/* 01E0CDE0 */ .space 0x10

glabel Mes1
/* 01E0CDF0 */ .space 0x17B8

/* Automatically generated and unreferenced pad */
glabel B_01E0E5A8_313DA8
/* 01E0E5A8 */ .space 0x08

glabel DispFade
/* 01E0E5B0 */ .space 0x10

glabel WaterV1
/* 01E0E5C0 */ .space 0x10

glabel WaterV2
/* 01E0E5D0 */ .space 0x10

glabel WaterV3
/* 01E0E5E0 */ .space 0x10

glabel WaterV4
/* 01E0E5F0 */ .space 0x10

glabel WaterPos
/* 01E0E600 */ .space 0x10

glabel ColModel
/* 01E0E610 */ .space 0x100

glabel ShadowModel
/* 01E0E710 */ .space 0x100

glabel pointLight
/* 01E0E810 */ .space 0xC00

/* Automatically generated and unreferenced pad */
glabel B_01E0F410_314C10
/* 01E0F410 */ .space 0x30

glabel teigiBuff
/* 01E0F440 */ .space 0x1000

glabel argStrBuff
/* 01E10440 */ .space 0x2000

glabel argValBuff
/* 01E12440 */ .space 0x8000

glabel LODNameBuff
/* 01E1A440 */ .space 0x10

glabel OP_BuildingMap
/* 01E1A450 */ .space 0xAF0

glabel OP_BuildingMap2
/* 01E1AF40 */ .space 0xAF0

glabel OP_GroundMap
/* 01E1BA30 */ .space 0xAF0

glabel OP_AnimeSeq
/* 01E1C520 */ .space 0x1200

glabel OP_FirePosition
/* 01E1D720 */ .space 0x600

glabel OP_FireScale
/* 01E1DD20 */ .space 0x180

glabel OP_FireFlg
/* 01E1DEA0 */ .space 0x180

glabel CFire
/* 01E1E020 */ .space 0x40

glabel DancerPos
/* 01E1E060 */ .space 0x230

glabel DancerRot
/* 01E1E290 */ .space 0x230

glabel Cloud
/* 01E1E4C0 */ .space 0x11B0

glabel lcolor$404
/* 01E1F670 */ .space 0x40

glabel OP_NornMapObj
/* 01E1F6B0 */ .space 0x4740

glabel OP_NornMapObj2
/* 01E23DF0 */ .space 0x5190

glabel CFire__2
/* 01E28F80 */ .space 0x40

glabel Komono
/* 01E28FC0 */ .space 0x11B0

glabel Door
/* 01E2A170 */ .space 0x90

glabel Fuusya
/* 01E2A200 */ .space 0x120

glabel Wind
/* 01E2A320 */ .space 0x30

glabel TaimatsuFrame
/* 01E2A350 */ .space 0x30

glabel Taimatsu
/* 01E2A380 */ .space 0x6C0

glabel OP_ToanMapObj
/* 01E2AA40 */ .space 0xF0

glabel CFire__3
/* 01E2AB30 */ .space 0x40

glabel Fuusya__2
/* 01E2AB70 */ .space 0x120

glabel Wind__2
/* 01E2AC90 */ .space 0x30

glabel TaimatsuFrame__2
/* 01E2ACC0 */ .space 0x30

glabel Taimatsu__2
/* 01E2ACF0 */ .space 0x6C0

glabel Water
/* 01E2B3B0 */ .space 0x320

glabel OP_NornMapObj3
/* 01E2B6D0 */ .space 0x3C0

glabel CBomb
/* 01E2BA90 */ .space 0x360

glabel CBeem
/* 01E2BDF0 */ .space 0x1440

glabel Shadow__2
/* 01E2D230 */ .space 0x40

glabel CharaF
/* 01E2D270 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01E2D27C_332A7C
/* 01E2D27C */ .space 0x04

glabel Wind__3
/* 01E2D280 */ .space 0x30

glabel Hamon
/* 01E2D2B0 */ .space 0x10

glabel HScale
/* 01E2D2C0 */ .space 0x14

/* Automatically generated and unreferenced pad */
glabel B_01E2D2D4_332AD4
/* 01E2D2D4 */ .space 0x0C

glabel Effect
/* 01E2D2E0 */ .space 0x11B0

glabel SeireiKing
/* 01E2E490 */ .space 0x1E0

glabel LIT_362__5
/* 01E2E670 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01E2E67C_333E7C
/* 01E2E67C */ .space 0x04

glabel MainCamera__3
/* 01E2E680 */ .space 0x2F0

glabel DispFade__2
/* 01E2E970 */ .space 0x10

glabel CFire__4
/* 01E2E980 */ .space 0x40

glabel CScript
/* 01E2E9C0 */ .space 0xE300

glabel Wind__4
/* 01E3CCC0 */ .space 0x30

glabel Water__2
/* 01E3CCF0 */ .space 0x320

glabel CharaTex
/* 01E3D010 */ .space 0x09

/* Automatically generated and unreferenced pad */
glabel B_01E3D019_342819
/* 01E3D019 */ .space 0x07

glabel CharaDataBuffer
/* 01E3D020 */ .space 0x10

glabel frame_info_cam__2
/* 01E3D030 */ .space 0xF3C0

glabel Cam
/* 01E4C3F0 */ .space 0x46C0

glabel MotionInfo
/* 01E50AB0 */ .space 0x10

glabel PathDataBuffer
/* 01E50AC0 */ .space 0x10

glabel WaterBuffer
/* 01E50AD0 */ .space 0x10

glabel DummyDataBuffer
/* 01E50AE0 */ .space 0x10

glabel TexAnimeData__3
/* 01E50AF0 */ .space 0xA50

glabel CRunFx
/* 01E51540 */ .space 0xD0

glabel LIT_339__4
/* 01E51610 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01E5161C_356E1C
/* 01E5161C */ .space 0x04

glabel Camera
/* 01E51620 */ .space 0x2C0

glabel LIT_340__3
/* 01E518E0 */ .space 0x0C

/* Automatically generated and unreferenced pad */
glabel B_01E518EC_3570EC
/* 01E518EC */ .space 0x04

glabel FCamera
/* 01E518F0 */ .space 0x2F0

glabel Cloud__2
/* 01E51BE0 */ .space 0x11B0

glabel Logo
/* 01E52D90 */ .space 0x11B0

glabel Spark
/* 01E53F40 */ .space 0x9F30

glabel CSprite
/* 01E5DE70 */ .space 0x68

/* Automatically generated and unreferenced pad */
glabel B_01E5DED8_3636D8
/* 01E5DED8 */ .space 0x08

glabel CLogo
/* 01E5DEE0 */ .space 0x60

glabel CCursol
/* 01E5DF40 */ .space 0x24

/* Automatically generated and unreferenced pad */
glabel B_01E5DF64_363764
/* 01E5DF64 */ .space 0x1C
