.include "macro.inc"

.set noat
.set noreorder

.section .rodata
.align 4
glabel LIT_1300
    /* 19F2D0 0029F1D0 8CF72200 */ .word .L0022F78C
    /* 19F2D4 0029F1D4 A0F72200 */ .word .L0022F7A0
    /* 19F2D8 0029F1D8 ACF72200 */ .word .L0022F7AC
    /* 19F2DC 0029F1DC B8F72200 */ .word .L0022F7B8
    /* 19F2E0 0029F1E0 B8F72200 */ .word .L0022F7B8
    /* 19F2E4 0029F1E4 B8F72200 */ .word .L0022F7B8
    /* 19F2E8 0029F1E8 B8F72200 */ .word .L0022F7B8
    /* 19F2EC 0029F1EC B8F72200 */ .word .L0022F7B8
    /* 19F2F0 0029F1F0 B8F72200 */ .word .L0022F7B8
    /* 19F2F4 0029F1F4 00000000 */ .word 0x00000000
    /* 19F2F8 0029F1F8 00000000 */ .word 0x00000000
    /* 19F2FC 0029F1FC 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.42.4 */

glabel PersonalRetMax__Fi
    /* 12F860 0022F760 28160070 */  paddub     $2, $0, $0
    /* 12F864 0022F764 0900812C */  sltiu      $1, $4, 0x9
    /* 12F868 0022F768 14002010 */  beqz       $1, .L0022F7BC
    /* 12F86C 0022F76C 00000000 */   nop
    /* 12F870 0022F770 2A00033C */  lui        $3, %hi(LIT_1300)
    /* 12F874 0022F774 D0F16524 */  addiu      $5, $3, %lo(LIT_1300)
    /* 12F878 0022F778 80180400 */  sll        $3, $4, 2
    /* 12F87C 0022F77C 21186500 */  addu       $3, $3, $5
    /* 12F880 0022F780 0000638C */  lw         $3, 0x0($3)
    /* 12F884 0022F784 08006000 */  jr         $3
    /* 12F888 0022F788 00000000 */   nop
  .L0022F78C:
    /* 12F88C 0022F78C A897828F */  lw         $2, -0x6858($28)
    /* 12F890 0022F790 2400428C */  lw         $2, 0x24($2)
    /* 12F894 0022F794 00004280 */  lb         $2, 0x0($2)
    /* 12F898 0022F798 08000010 */  b          .L0022F7BC
    /* 12F89C 0022F79C 00000000 */   nop
  .L0022F7A0:
    /* 12F8A0 0022F7A0 3C000224 */  addiu      $2, $0, 0x3C
    /* 12F8A4 0022F7A4 05000010 */  b          .L0022F7BC
    /* 12F8A8 0022F7A8 00000000 */   nop
  .L0022F7AC:
    /* 12F8AC 0022F7AC 28000224 */  addiu      $2, $0, 0x28
    /* 12F8B0 0022F7B0 02000010 */  b          .L0022F7BC
    /* 12F8B4 0022F7B4 00000000 */   nop
  .L0022F7B8:
    /* 12F8B8 0022F7B8 78000224 */  addiu      $2, $0, 0x78
  .L0022F7BC:
    /* 12F8BC 0022F7BC 0800E003 */  jr         $31
    /* 12F8C0 0022F7C0 00000000 */   nop
    /* 12F8C4 0022F7C4 00000000 */  nop
    /* 12F8C8 0022F7C8 00000000 */  nop
    /* 12F8CC 0022F7CC 00000000 */  nop
