.include "macro.inc"

.set noat
.set noreorder

.include "macro.inc"

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

glabel __malloc_lock
    /* 003728 00103628 0800E003 */  jr         $31
    /* 00372C 0010362C 00000000 */   nop

glabel __malloc_unlock
    /* 003730 00103630 0800E003 */  jr         $31
    /* 003734 00103634 00000000 */   nop
