#include "actionseq.hpp"

INCLUDE_ASM("main", Initialize__10CActionSeqFP7ACT_SEQi);
INCLUDE_ASM("main", __ct__10CActionSeqFv);
INCLUDE_ASM("main", ClearSeq__10CActionSeqFv);
INCLUDE_ASM("main", GetNextSeq__10CActionSeqFv);
INCLUDE_ASM("main", SyncChara__10CActionSeqFP10CCharacter);
INCLUDE_ASM("main", NextMoveSeq__10CActionSeqFv);
INCLUDE_ASM("main", NextMotionSeq__10CActionSeqFv);
INCLUDE_ASM("main", NextAnimeSeq__10CActionSeqFv);
INCLUDE_ASM("main", MoveSeq__10CActionSeqFPfi);
INCLUDE_ASM("main", MoveSeq__10CActionSeqFPff);
INCLUDE_ASM("main", MoveSeq__10CActionSeqFi);
INCLUDE_ASM("main", SetPos__10CActionSeqFPf);
INCLUDE_ASM("main", RotRefSeq__10CActionSeqFPff);
INCLUDE_ASM("main", RotAngleSeq__10CActionSeqFff);
INCLUDE_ASM("main", RotMoveSeq__10CActionSeqFf);
INCLUDE_ASM("main", ClearRotSeq__10CActionSeqFv);
INCLUDE_ASM("main", WaitRotSeq__10CActionSeqFv);
INCLUDE_ASM("main", SetRot__10CActionSeqFPf);
INCLUDE_ASM("main", SetDelayRot__10CActionSeqFi);
INCLUDE_ASM("main", MotionTrg__10CActionSeqFi);
INCLUDE_ASM("main", AnimeTrg__10CActionSeqFi);
INCLUDE_ASM("main", MotionSeq__10CActionSeqFiifi);
INCLUDE_ASM("main", AnimeSeq__10CActionSeqFiiii);
INCLUDE_ASM("main", CheckEnd__10CActionSeqFv);
INCLUDE_ASM("main", DeleteSeq__FP7ACT_SEQ);
INCLUDE_ASM("main", Play__10CActionSeqFv);
