#include "battle_globals.hpp"

INCLUDE_ASM("asm/nonmatchings/battle_globals", GlobalNameInit__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", InitNameRegist__FiiP1);
INCLUDE_ASM("asm/nonmatchings/battle_globals", ExitNameEnterFunc__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", GetNameTextureInfo__FPP8CTextureiRiRi);
INCLUDE_ASM("asm/nonmatchings/battle_globals", DrawCharaName__Fiiiii);
INCLUDE_ASM("asm/nonmatchings/battle_globals", DrawNameRegiWaku__Fiiiii);
INCLUDE_ASM("asm/nonmatchings/battle_globals", DrawCharaNameUp__Fiiii);
INCLUDE_ASM("asm/nonmatchings/battle_globals", DrawNameTemplete__Fiiii);
INCLUDE_ASM("asm/nonmatchings/battle_globals", NameCompare__FPsPs);
INCLUDE_ASM("asm/nonmatchings/battle_globals", CheckName__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", NameEnterDraw__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", NameEnterKey__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", NameDefaultSet__Fi);
INCLUDE_ASM("asm/nonmatchings/battle_globals", GetFontLRTumeW__Fiii);
INCLUDE_ASM("asm/nonmatchings/battle_globals", CharaSelectNameDraw2__FiiPsPP8CTexturei);
INCLUDE_ASM("asm/nonmatchings/battle_globals", DrawSaveBoardCharaName2__FiiPsPP8CTexture6spRGBA6spRGBA);
INCLUDE_ASM("asm/nonmatchings/battle_globals", GetMsgLengthCharaName__Fi);
INCLUDE_ASM("asm/nonmatchings/battle_globals", InitOpeningBook__FP1Pi);
INCLUDE_ASM("asm/nonmatchings/battle_globals", OpeningBookKey__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", OpeningBookDraw__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", runerror__FPCc);
INCLUDE_ASM("asm/nonmatchings/battle_globals", stkoverflow__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", chk_int__F12RS_STACKDATAP8funcdata);
INCLUDE_ASM("asm/nonmatchings/battle_globals", is_true__F12RS_STACKDATA);
INCLUDE_ASM("asm/nonmatchings/battle_globals", divby0error__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", modby0error__Fv);
INCLUDE_ASM("asm/nonmatchings/battle_globals", print__FP12RS_STACKDATAi);

