#include "common.h"

/* The data-file reader: header parsing, file lookup, and the background read
 * queue. */

INCLUDE_ASM("asm/nonmatchings/dataread", copy_data_head__FP11DATA_HEADERP16DATA_HEADER_READ);
INCLUDE_ASM("asm/nonmatchings/dataread", SearchFile__FPc);
INCLUDE_ASM("asm/nonmatchings/dataread", InitReadBG__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadFileBG__FPcP1Pi);
INCLUDE_ASM("asm/nonmatchings/dataread", GetReadBGFile__Fi);
INCLUDE_ASM("asm/nonmatchings/dataread", StartReadBG__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", ReadBG__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", ReadBGSync__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", BreakReadBG__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", search_tree__FP9NAME_TREEPc);
INCLUDE_ASM("asm/nonmatchings/dataread", add_tree__FP9NAME_TREEP9NAME_TREE);
INCLUDE_ASM("asm/nonmatchings/dataread", create_word_tree__FPciPc);
INCLUDE_ASM("asm/nonmatchings/dataread", InitCDFile__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", InitMemoryFile__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadFile__FPcPvPi);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadFile2__FPcPvPii);
INCLUDE_ASM("asm/nonmatchings/dataread", CDRead__FPcPUiPi);
INCLUDE_ASM("asm/nonmatchings/dataread", WriteFile__FPcPvi);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadPackFile__FPcPUiPi);
INCLUDE_ASM("asm/nonmatchings/dataread", GetPackFile__FPcPi);
INCLUDE_ASM("asm/nonmatchings/dataread", GetPackFile__FPUiPcPi);
INCLUDE_ASM("asm/nonmatchings/dataread", GetPackFile__FPUiiPPcPi);
INCLUDE_ASM("asm/nonmatchings/dataread", GetPackFileExt__FPUiPcPPUiiPiPPc);
INCLUDE_ASM("asm/nonmatchings/dataread", InitCloth__FP9CFrameVu1R9input_strP14CDataAlloc2_1_);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandSIZE__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandFRAME__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandNORMAL__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandFOLLOW__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandK__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandWINDEFFECT__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandGRAVITY__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandPOLYDIVE__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", CommandBOUND__FPPv);
INCLUDE_ASM("asm/nonmatchings/dataread", GetArg__FR9input_strPiPPv__2);
INCLUDE_ASM("asm/nonmatchings/dataread", SearchCommand__FR9input_strPi__2);
INCLUDE_ASM("asm/nonmatchings/dataread", SkipSpace__FR9input_str__2);
INCLUDE_ASM("asm/nonmatchings/dataread", CheckChar__Fc__2);
INCLUDE_ASM("asm/nonmatchings/dataread", keyCtrl__FffP11MOTION_INFO);
INCLUDE_ASM("asm/nonmatchings/dataread", MoveImageTest__FP13sceVif1PacketiiiRC8CRect_i_iiiiii);
INCLUDE_ASM("asm/nonmatchings/dataread", unitRotation__FP9CFrameVu1f);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadOverlay__Fi);
INCLUDE_ASM("asm/nonmatchings/dataread", init_all__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", SetEnv__FP13sceVif1Packet);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadSndTxt__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", PlayTimeCountFlag__Fi);
INCLUDE_ASM("asm/nonmatchings/dataread", PlayTimeCount__Fi);
INCLUDE_ASM("asm/nonmatchings/dataread", LoadSystemMessage__Fv);
INCLUDE_ASM("asm/nonmatchings/dataread", initialize_data__Fv);
