#include "common.h"

#include "ebattle.hpp"

/* The rest of the ebattle module: the intro, the main loop and the draw pass. */

INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBInitIntro__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBSetMotion__FP10CCharacterPi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBDebug__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBSetKey__Ffii);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBExit__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBIntroLoop__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBLoop__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EBDraw__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", DrawButton__Fiiifi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", DrawButtonSub__Fiiiif);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", init_draw_ok__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", set_draw_ok__Fii);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", draw_ok_loop__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", draw_ok__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", button_scale__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", check_key_mode__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdSetKeyMode__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdGetRXf__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdGetRYf__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdGetLXf__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdGetLYf__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdPadOn__Fii);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdPadDown__Fii);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", keylock__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", GetRXf__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", GetRYf__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", GetLXf__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", GetLYf__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", PadOn__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", PadDown__Fi);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", CameraAutoMove__FP13CCameraFollowP6CCPolyPfff);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdViewModeOff__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", InitEyeCamera__FP10CCharacter);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EyeCamera__FP7CCameraP10CCharacteri);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdInitCameraParam__FP13CCameraFollow);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdMoveCharaInit__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdEyeCamera__FP7CCameraP10CCharacter);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdCheckViewMode__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdAGetViewAngleH__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdAGetViewAngleV__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdASetViewAngle__Fff);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdMoveChara__Fv);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdInitHashigo__FP13ED_EVENT_INFOP14ED_EVENT_PARAM);
INCLUDE_ASM("asm/nonmatchings/ebattle_loop", EdInitGotoInterior__FP13ED_EVENT_INFOP14ED_EVENT_PARAM);
