#include "fish.hpp"

INCLUDE_ASM("asm/nonmatchings/fish", rand_check__Ff);
INCLUDE_ASM("asm/nonmatchings/fish", GetActCnt__Fv);
INCLUDE_ASM("asm/nonmatchings/fish", GetActCnt2__Fv);
INCLUDE_ASM("asm/nonmatchings/fish", FindFood__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", EatFood__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", BiteHook__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", LeaveFood__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", LeaveHook__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", SetCPoly__5CFishFP6CCPolyi);
INCLUDE_ASM("asm/nonmatchings/fish", Step__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", Draw__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", SetFoodPos__5CFishFiPff);
INCLUDE_ASM("asm/nonmatchings/fish", SetAngleMode__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", SetBattleMode__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", SetScale__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", GetFP__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", SetMotion__5CFishFii);
INCLUDE_ASM("asm/nonmatchings/fish", SetPosition__5CFishFPf);
INCLUDE_ASM("asm/nonmatchings/fish", GetPosition__5CFishFPf);
INCLUDE_ASM("asm/nonmatchings/fish", SetRotation__5CFishFPf);
INCLUDE_ASM("asm/nonmatchings/fish", GetRotation__5CFishFPf);
INCLUDE_ASM("asm/nonmatchings/fish", SetReference__5CFishFP6CFrame);
INCLUDE_ASM("asm/nonmatchings/fish", DeleteReference__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", Initialize__5CFishFv);
INCLUDE_ASM("asm/nonmatchings/fish", LoadFish__FP5CFishiiP14CDataAlloc2_1_i);
INCLUDE_ASM("asm/nonmatchings/fish", GetFishFileName__Fi);
