#include "mapparts.hpp"

INCLUDE_ASM("asm/nonmatchings/mapparts", GetPosition__9CMapPartsFPf);
INCLUDE_ASM("asm/nonmatchings/mapparts", SetPosition__9CMapPartsFPf);
INCLUDE_ASM("asm/nonmatchings/mapparts", SetPosition__9CMapPartsFfff);
INCLUDE_ASM("asm/nonmatchings/mapparts", SetRotation__9CMapPartsFfff);
INCLUDE_ASM("asm/nonmatchings/mapparts", SetRotY__9CMapPartsFi);
INCLUDE_ASM("asm/nonmatchings/mapparts", GetRotY__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", Initialize__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", __ct__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", FrameObjectOnOff__9CMapPartsFPci);
INCLUDE_ASM("asm/nonmatchings/mapparts", GetWidth__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", GetHeight__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", GetInfoData__9CMapPartsFii);
INCLUDE_ASM("asm/nonmatchings/mapparts", ChangeAltData__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", ChangeDigData__9CMapPartsFv);
INCLUDE_ASM("asm/nonmatchings/mapparts", CheckBox__9CMapPartsFP7CBoxVu0);
INCLUDE_ASM("asm/nonmatchings/mapparts", CheckBox2__9CMapPartsFP7CBoxVu0);
INCLUDE_ASM("asm/nonmatchings/mapparts", DrawLOD__9CMapPartsFPfiiPi);
INCLUDE_ASM("asm/nonmatchings/mapparts", DrawParts__9CMapPartsFfPfiiPi);
INCLUDE_ASM("asm/nonmatchings/mapparts", DrawEffect__9CMapPartsFP7CCamerafP12CEffectGroup);
