#include "npcharacter.hpp"

INCLUDE_ASM("asm/nonmatchings/npcharacter", Step__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", ShadowStep__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", PlaySeq__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", ClearSeq__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", SetSeq__12CNPCharacterFPff);
INCLUDE_ASM("asm/nonmatchings/npcharacter", SetWait__12CNPCharacterFi);
INCLUDE_ASM("asm/nonmatchings/npcharacter", CheckSeq__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", GetNextSeq__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", GetNowSeq__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", NextSeq__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", Draw__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", DrawShadow__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", CheckDraw__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", PickUpPoly__12CNPCharacterFPfP6CCPoly);
INCLUDE_ASM("asm/nonmatchings/npcharacter", PickUpPoly__10CCharacterFPfP6CCPoly);
INCLUDE_ASM("asm/nonmatchings/npcharacter", Initialize__12CNPCharacterFv);
INCLUDE_ASM("asm/nonmatchings/npcharacter", __ct__12CNPCharacterFv);
