#include "shot_freefuncs.hpp"

INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", WaterSplash_Init__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", CheckHealingWater__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", CheckHealZone__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", HealingWater__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", DrawWaterLing__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", StepWaterLing__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", SetBattleStyle__Fii);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", ValuePrint__FiiiiUc);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtStatusAlarmInit__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtStatusAlarmAnime__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtGetStatusPal__Fiff);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtGetStatusPal2__Fiff);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", topStatusInfo__Fiii);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", StatusErrCheck__Fi);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtStatusErrColorSet__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtStatusErrStep__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtSetStatusErr__Fi);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtStatusErrDraw__Fi);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", setItemToReserved__FPciiPcii);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtMapJumpCashClear__Fv);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtMapJumpLoad__FPc);
INCLUDE_ASM("asm/nonmatchings/shot_freefuncs", BtSet3DCellModel__FPfP8CTexturefiiiii);
