#include "common.h"

INCLUDE_ASM("asm/nonmatchings/sysmes", SkipSpace__FR9input_str__3);
INCLUDE_ASM("asm/nonmatchings/sysmes", CheckChar__Fc__3);
INCLUDE_ASM("asm/nonmatchings/sysmes", PreProcess__FR9input_str__2);
INCLUDE_ASM("asm/nonmatchings/sysmes", InitSystemMes__Fv);
INCLUDE_ASM("asm/nonmatchings/sysmes", ClearSystemMes__Fv);
INCLUDE_ASM("asm/nonmatchings/sysmes", SystemMesCheck__Fv);
INCLUDE_ASM("asm/nonmatchings/sysmes", SystemMesStep__Fv);
INCLUDE_ASM("asm/nonmatchings/sysmes", SystemMesDraw__Fv);
INCLUDE_ASM("asm/nonmatchings/sysmes", ItemGetMes__Fiiii);
INCLUDE_ASM("asm/nonmatchings/sysmes", AtraGetMes__Fiii);
INCLUDE_ASM("asm/nonmatchings/sysmes", TecGetMes__Fii);
INCLUDE_ASM("asm/nonmatchings/sysmes", MaxUpMes__Fii);
INCLUDE_ASM("asm/nonmatchings/sysmes", DeadMes__Fii);
INCLUDE_ASM("asm/nonmatchings/sysmes", AllDeadMes__Fi);
INCLUDE_ASM("asm/nonmatchings/sysmes", NotGetAtraMes__Fii);
INCLUDE_ASM("asm/nonmatchings/sysmes", DontGetItemMes__Fi);
INCLUDE_ASM("asm/nonmatchings/sysmes", SetSystemMes__FiiiiPiPi);
INCLUDE_ASM("asm/nonmatchings/sysmes", pretest__FPA4_fPf);
INCLUDE_ASM("asm/nonmatchings/sysmes", Trans_AddCell__FPfPf);
