#include "visualvu1.hpp"

INCLUDE_ASM("asm/nonmatchings/visualvu1", SetTextureInfo__FP8CTexturePcP8TM2_head);
INCLUDE_ASM("asm/nonmatchings/visualvu1", SetTextureInfo__FP8CTexturePcPUc);
INCLUDE_ASM("asm/nonmatchings/visualvu1", Initialize__7CVisualFv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", __ct__7CVisualFv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", RemakeData__10CVisualVu1FPUi);
INCLUDE_ASM("asm/nonmatchings/visualvu1", DrawVu1__10CVisualVu1FP13sceVif1PacketPA4_fP10RenderInfo11VU1_PROGRAMP1ii);
INCLUDE_ASM("asm/nonmatchings/visualvu1", SetShadowData__FPUiPA4_f);
INCLUDE_ASM("asm/nonmatchings/visualvu1", SetMaterial__FPUiP12MDT_MATERIAL);
INCLUDE_ASM("asm/nonmatchings/visualvu1", SetTEX0__FPUiUlUl);
INCLUDE_ASM("asm/nonmatchings/visualvu1", Initialize__10CVisualVu1Fv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", __ct__10CVisualVu1Fv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", SetMDTDataAddress__13CVisualMDTVu1FPUi);
INCLUDE_ASM("asm/nonmatchings/visualvu1", GetMDTDataAddress__13CVisualMDTVu1Fv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", Initialize__13CVisualMDTVu1Fv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", __ct__13CVisualMDTVu1Fv);
INCLUDE_ASM("asm/nonmatchings/visualvu1", DrawVu1__10CVisualVu1FPUiPA4_fP10RenderInfo11VU1_PROGRAMP1ii);
INCLUDE_ASM("asm/nonmatchings/visualvu1", SetVuData__FiP1PUiP1P1P1P1i);
INCLUDE_ASM("asm/nonmatchings/visualvu1", CreateVUdataFromMDT__10CVisualVu1FPUiPUiii);
INCLUDE_ASM("asm/nonmatchings/visualvu1", CreateVUdataFromMDTRemake__10CVisualVu1FPUiPUii);
INCLUDE_ASM("asm/nonmatchings/visualvu1", DrawVu1__13CVisualMDTVu1FPUiPA4_fP10RenderInfo11VU1_PROGRAMP1ii);
INCLUDE_ASM("asm/nonmatchings/visualvu1", DrawVu1__13CVisualMDTVu1FP13sceVif1PacketPA4_fP10RenderInfo11VU1_PROGRAMP1ii);
INCLUDE_ASM("asm/nonmatchings/visualvu1", RemakeData__13CVisualMDTVu1FPUi);
