#include "weaponelement.hpp"

INCLUDE_ASM("asm/nonmatchings/weaponelement", Initialize__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Set__14CWeaponElementFPA4_fPffif);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Step__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Draw__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Init_Holy__14CWeaponElementFPf);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Step_Holy__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Draw_Holy__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Init_Cold__14CWeaponElementFPf);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Step_Cold__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Draw_Cold__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Init_Wind__14CWeaponElementFPf);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Step_Wind__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Draw_Wind__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Init_Fire__14CWeaponElementFPf);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Step_Fire__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Draw_Fire__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Init_Thunder__14CWeaponElementFPf);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Step_Thunder__14CWeaponElementFv);
INCLUDE_ASM("asm/nonmatchings/weaponelement", Draw_Thunder__14CWeaponElementFv);
