# Object lists and the per-object build rules.
#
# The *_obj_files.mk lists are generated by scripts/disassemble.py and stay the
# single source of truth for link order, so they are parsed rather than copied.

# Read the $(BUILD_DIR)-relative object paths out of a .mk object list.
function(read_obj_list mk_file out_var)
    set(path ${CMAKE_SOURCE_DIR}/${mk_file})
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${path})

    file(READ ${path} content)
    string(REGEX REPLACE "#[^\n]*" "" content "${content}")
    string(REGEX MATCHALL "\\$\\(BUILD_DIR\\)/[^ \t\r\n\\\\]+" refs "${content}")

    set(objs "")
    foreach(ref IN LISTS refs)
        string(REPLACE "$(BUILD_DIR)/" "" ref ${ref})
        list(APPEND objs ${BUILD_DIR}/${ref})
    endforeach()
    set(${out_var} "${objs}" PARENT_SCOPE)
endfunction()

# Create every directory the object rules will write into.
function(make_object_dirs objs)
    set(dirs "")
    foreach(obj IN LISTS objs)
        get_filename_component(dir ${CMAKE_SOURCE_DIR}/${obj} DIRECTORY)
        list(APPEND dirs ${dir})
    endforeach()
    list(REMOVE_DUPLICATES dirs)
    foreach(dir IN LISTS dirs)
        file(MAKE_DIRECTORY ${dir})
    endforeach()
endfunction()

# Declare the rule that builds one object, picked from its source extension.
# `obj` is relative to the source root, e.g. build/src/main.cpp.o.
function(add_object obj)
    string(REGEX REPLACE "^${BUILD_DIR}/" "" rel ${obj})
    string(REGEX REPLACE "\\.o$" "" src ${rel})

    # Carved data sections are generated into the build tree.
    if(rel MATCHES "^generated/")
        set(src ${BUILD_DIR}/${src})
    endif()

    # Objects belonging to an overlay get their sections renamed onto that
    # overlay's private prefix, in the same pass that strips the empty ones.
    # Compiled objects only need the pass when they are in an overlay; the
    # main application has always linked them exactly as mwcc emits them.
    overlay_for_object(${obj} overlay)
    set(rename_flags "")
    set(overlay_fixup "")
    if(overlay)
        overlay_rename_flags(${overlay} rename_flags)
        set(overlay_fixup COMMAND sh ${SCRIPTS_DIR}/fixup_sections.sh ${obj} ${rename_flags})
    endif()

    if(src MATCHES "\\.s$")
        # MWLD rejects zero-sized input sections, but the assembler emits
        # .text/.data/.bss regardless, so strip the empty ones.
        add_custom_command(
            OUTPUT ${CMAKE_SOURCE_DIR}/${obj}
            COMMAND ${AS_PRODG} ${AS_FLAGS} -o ${obj} ${src}
            COMMAND sh ${SCRIPTS_DIR}/fixup_sections.sh ${obj} ${rename_flags}
            DEPENDS ${CMAKE_SOURCE_DIR}/${src}
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            COMMENT "AS ${src}"
            VERBATIM)
    elseif(src MATCHES "\\.(c|cpp)$")
        add_custom_command(
            OUTPUT ${CMAKE_SOURCE_DIR}/${obj}
            COMMAND ${CC_MW} ${CC_MW_FLAGS} -o ${obj} ${src}
            ${overlay_fixup}
            DEPENDS ${CMAKE_SOURCE_DIR}/${src}
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            COMMENT "CC ${src}"
            VERBATIM)
    elseif(src MATCHES "\\.bin$")
        add_custom_command(
            OUTPUT ${CMAKE_SOURCE_DIR}/${obj}
            COMMAND ${OBJCOPY} ${BIN_FLAGS} ${src} ${obj}
            DEPENDS ${CMAKE_SOURCE_DIR}/${src}
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            COMMENT "BIN ${src}"
            VERBATIM)
    else()
        message(FATAL_ERROR "No rule to build ${obj}")
    endif()
endfunction()
